/**
 * Ajedrez Integral — banco de líneas de apertura y celadas.
 *
 * Cada línea es una secuencia de jugadas que el alumno memoriza jugándola en el
 * tablero: el entrenador mueve por el rival y el alumno tiene que dar TODAS las
 * jugadas de su color, de memoria.
 *
 * Las jugadas van en notación inglesa (SAN de chess.js) porque es la que el
 * motor entiende. La página las traduce a la notación de acá (C, A, T, D, R)
 * antes de enseñarlas: nadie tiene que leer "Nf3" en pantalla.
 *
 * Campos de cada línea:
 *   id        identificador estable. NO se cambia nunca: es la clave con la que
 *             queda guardado el avance de cada alumno en su cuenta.
 *   nombre    cómo se llama, en español de acá.
 *   apertura  a qué apertura pertenece (para agrupar).
 *   tipo      "celada" (gana material o da mate si el rival se equivoca) o
 *             "apertura" (línea principal que conviene saber).
 *   color     "w" o "b": de qué lado juega el alumno.
 *   nivel     1 principiante, 2 intermedio, 3 avanzado.
 *   jugadas   la línea entera, empezando siempre por la jugada 1 de las blancas.
 *   idea      para qué sirve, en una frase.
 *   clave     qué es lo que hay que recordar de verdad.
 *
 * AL TOCAR ESTE ARCHIVO, CORRER herramientas/verificar-aperturas.js: comprueba
 * con chess.js que cada jugada exista de verdad en su posición, que el jaque
 * mate prometido sea mate, que los ids no se repitan y que el alumno tenga al
 * menos tres jugadas que dar. Una línea con una jugada mal escrita no da error
 * en pantalla: simplemente el alumno no puede terminarla nunca.
 */
(function () {
  "use strict";

  var LINEAS = [
    // ===================== CELADAS =====================
    {
      id: "pastor-mate",
      nombre: "Mate del pastor",
      apertura: "Apertura italiana",
      tipo: "celada", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Bc4", "Nc6", "Qh5", "Nf6", "Qxf7#"],
      idea: "La dama y el alfil apuntan juntos a f7, la casilla más débil del negro al empezar.",
      clave: "Son dos piezas contra una casilla: el alfil en c4 sostiene a la dama cuando come en f7.",
    },
    {
      id: "pastor-refutacion",
      nombre: "Cómo parar el mate del pastor",
      apertura: "Apertura italiana",
      tipo: "celada", color: "b", nivel: 1,
      jugadas: ["e4", "e5", "Bc4", "Nc6", "Qh5", "g6", "Qf3", "Nf6"],
      idea: "Con g6 se gana un tiempo echando a la dama, y con Cf6 se tapa f7 y se ataca.",
      clave: "No defiendas f7 con la dama: échale la dama al rival y desarrolla con ataque.",
    },
    {
      id: "damiano",
      nombre: "El castigo de la defensa Damiano",
      apertura: "Defensa Damiano",
      tipo: "celada", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "f6", "Nxe5", "fxe5", "Qh5+", "Ke7", "Qxe5+", "Kf7", "Bc4+", "Kg6", "Qf5+", "Kh6", "d4+", "g5", "h4"],
      idea: "Defender el peón de e5 con f6 es el error más caro que hay: cuesta la partida de una.",
      clave: "El caballo se entrega en e5 porque el peón de f6 ya no defiende nada: se llevó consigo la casa del rey.",
    },
    {
      id: "celada-legal",
      nombre: "Celada de Légal",
      apertura: "Defensa Philidor",
      tipo: "celada", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Bc4", "d6", "Nf3", "Bg4", "Nc3", "g6", "Nxe5", "Bxd1", "Bxf7+", "Ke7", "Nd5#"],
      idea: "Se entrega la dama para dar mate con tres piezas menores.",
      clave: "El caballo de f3 estaba clavado… pero la clavada no valía nada, porque tomar la dama pierde.",
    },
    {
      id: "blackburne",
      nombre: "Celada Blackburne",
      apertura: "Apertura italiana",
      tipo: "celada", color: "b", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nd4", "Nxe5", "Qg5", "Nxf7", "Qxg2", "Rf1", "Qxe4+", "Be2", "Nf3#"],
      idea: "El negro regala el peón de e5 y a cambio le cae encima al rey blanco.",
      clave: "Después de Cd4, comer en e5 es el error: la dama sale a g5 con dos amenazas a la vez.",
    },
    {
      id: "arca-de-noe",
      nombre: "Trampa del Arca de Noé",
      apertura: "Apertura española",
      tipo: "celada", color: "b", nivel: 3,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "d4", "b5", "Bb3", "Nxd4", "Nxd4", "exd4", "Qxd4", "c5", "Qd5", "Be6", "Qc6+", "Bd7", "Qd5", "c4"],
      idea: "Los peones negros van cerrando la jaula hasta que el alfil blanco se queda sin casillas.",
      clave: "Tres peones —a6, b5 y c4— le quitan al alfil todas las diagonales. Se llama arca porque no se escapa.",
    },
    {
      id: "fegatello",
      nombre: "Ataque Fegatello (hígado frito)",
      apertura: "Defensa de los dos caballos",
      tipo: "celada", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3"],
      idea: "Se entrega un caballo para sacar al rey negro a pasear a la mitad del tablero.",
      clave: "No es mate forzado: es un rey en e6 sin poder enrocar. Hay que seguir jugando con ideas, no de memoria.",
    },
    {
      id: "dos-caballos-bien",
      nombre: "Contra el hígado frito: la jugada de Polerio",
      apertura: "Defensa de los dos caballos",
      tipo: "celada", color: "b", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Na5"],
      idea: "En vez de comer en d5 con el caballo, se ataca el alfil de c4 y se sale del problema.",
      clave: "Ca5 entrega un peón pero salva la partida. Cxd5 es justo lo que el blanco quiere.",
    },
    {
      id: "cambridge-springs",
      nombre: "Trampa de Cambridge Springs",
      apertura: "Gambito de dama declinado",
      tipo: "celada", color: "b", nivel: 3,
      jugadas: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "cxd5", "exd5", "Nxd5", "Nxd5", "Bxd8", "Bb4+", "Qd2", "Bxd2+", "Kxd2", "Kxd8"],
      idea: "El caballo de d7 parece colgado, pero comerlo cuesta una pieza.",
      clave: "Tomar la dama no importa si el jaque intermedio recupera todo: Ab4+ es la jugada.",
    },
    {
      id: "albin-lasker",
      nombre: "Trampa de Lasker en la Albin",
      apertura: "Contragambito Albin",
      tipo: "celada", color: "b", nivel: 3,
      jugadas: ["d4", "d5", "c4", "e5", "dxe5", "d4", "e3", "Bb4+", "Bd2", "dxe3", "Bxb4", "exf2+", "Ke2", "fxg1=N+"],
      idea: "Termina con una coronación a caballo, no a dama, y por eso gana.",
      clave: "Coronar dama sería peor: el caballo da jaque y salva la torre. Coronar a algo que no es dama tiene nombre y sirve.",
    },
    {
      id: "gambito-dama-b5",
      nombre: "Aferrarse al peón del gambito",
      apertura: "Gambito de dama aceptado",
      tipo: "celada", color: "w", nivel: 2,
      jugadas: ["d4", "d5", "c4", "dxc4", "e3", "b5", "a4", "c6", "axb5", "cxb5", "Qf3"],
      idea: "El negro intenta guardarse el peón de c4 y pierde una torre por el camino.",
      clave: "La dama en f3 mira a la vez a a8 y a b7: el peón que defendía b5 ya no está.",
    },
    {
      id: "englund",
      nombre: "Trampa del gambito Englund",
      apertura: "Gambito Englund",
      tipo: "celada", color: "b", nivel: 2,
      jugadas: ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4"],
      idea: "La dama negra se mete por la puerta de atrás a cazar peones y clava lo que encuentra.",
      clave: "Ab4 clava el alfil de c3 contra el caballo de b1: no hay cómo salvar las dos cosas.",
    },

    // ===================== APERTURAS ABIERTAS (1.e4 e5) =====================
    {
      id: "espanola-cerrada",
      nombre: "Española, variante cerrada",
      apertura: "Apertura española",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Be7", "Re1", "b5", "Bb3", "d6", "c3", "O-O"],
      idea: "La apertura más jugada de la historia a alto nivel: presión lenta sobre e5 y el centro.",
      clave: "c3 no es una jugada perdida: prepara d4 y le da al alfil la casilla c2 para siempre.",
    },
    {
      id: "espanola-cambio",
      nombre: "Española, variante del cambio",
      apertura: "Apertura española",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Bxc6", "dxc6", "O-O"],
      idea: "Se cambia alfil por caballo y se juega a ganar el final con la mayoría de peones sana.",
      clave: "El negro queda con los dos alfiles; el blanco, con mejor estructura. Es un cambio de virtudes.",
    },
    {
      id: "italiana-giuoco",
      nombre: "Italiana, Giuoco Piano",
      apertura: "Apertura italiana",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4", "exd4", "cxd4", "Bb4+"],
      idea: "La apertura de toda la vida: salen las piezas hacia el centro y después se empuja d4.",
      clave: "Después de d4, el jaque en b4 es la respuesta correcta: sin él, el blanco arma un centro enorme.",
    },
    {
      id: "escocesa",
      nombre: "Apertura escocesa",
      apertura: "Apertura escocesa",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Nxd4", "Bc5", "Be3", "Qf6", "c3", "Nge7"],
      idea: "Se abre el centro de una vez, sin la maniobra lenta de la española.",
      clave: "El alfil en c5 ataca el caballo de d4: por eso Ae3 lo sostiene antes de que sea tarde.",
    },
    {
      id: "petrov",
      nombre: "Defensa rusa (Petrov)",
      apertura: "Defensa Petrov",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "d6", "Nf3", "Nxe4", "d4", "d5"],
      idea: "En vez de defender e5, el negro copia: si me comes un peón, te como el tuyo.",
      clave: "d6 antes de comer en e4 es obligatorio. Comer de una da Dе2 y el caballo negro está perdido.",
    },
    {
      id: "gambito-de-rey",
      nombre: "Gambito de rey aceptado",
      apertura: "Gambito de rey",
      tipo: "apertura", color: "w", nivel: 3,
      jugadas: ["e4", "e5", "f4", "exf4", "Nf3", "g5", "h4", "g4", "Ne5"],
      idea: "Se entrega un peón por el centro y por la columna f abierta contra el rey negro.",
      clave: "h4 no es un ataque: es romper la cadena de peones g5-f4 antes de que se haga fuerte.",
    },

    // ===================== SICILIANA =====================
    {
      id: "siciliana-najdorf",
      nombre: "Siciliana Najdorf",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"],
      idea: "La defensa favorita de Fischer y de Kaspárov: peón menos en el centro, iniciativa a cambio.",
      clave: "a6 parece una jugada de peón tonta y es la clave: le quita b5 al caballo y al alfil blancos.",
    },
    {
      id: "siciliana-dragon",
      nombre: "Siciliana, variante del dragón",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6", "Be3", "Bg7"],
      idea: "El alfil de g7 apunta a toda la diagonal larga y es la pieza de la que sale todo.",
      clave: "El nombre viene de la forma de los peones. Ese alfil no se cambia por nada.",
    },
    {
      id: "siciliana-cerrada",
      nombre: "Siciliana cerrada",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "d3", "d6"],
      idea: "Para quien no quiere estudiar la teoría enorme de la siciliana abierta: se juega con plan, no de memoria.",
      clave: "Sin d4 no hay cambio en el centro: la partida se decide en las alas y con maniobras.",
    },

    // ===================== FRANCESA Y CARO-KANN =====================
    {
      id: "francesa-avance",
      nombre: "Francesa, variante del avance",
      apertura: "Defensa francesa",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "e6", "d4", "d5", "e5", "c5", "c3", "Nc6", "Nf3", "Qb6"],
      idea: "El blanco cierra el centro y el negro le pega a la base de la cadena, que es d4.",
      clave: "Se ataca la base, no la punta: d4 está sostenido por c3, así que hay que sumar piezas a d4.",
    },
    {
      id: "francesa-tarrasch",
      nombre: "Francesa, variante Tarrasch",
      apertura: "Defensa francesa",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e6", "d4", "d5", "Nd2", "c5", "exd5", "exd5", "Ngf3", "Nc6"],
      idea: "El caballo va a d2 y no a c3 para no comerse la clavada con Ab4.",
      clave: "Cd2 tapa al alfil de c1 un rato: es el precio de evitar la clavada, y se resuelve con Cgf3 y Ad3.",
    },
    {
      id: "caro-kann-clasica",
      nombre: "Caro-Kann clásica",
      apertura: "Defensa Caro-Kann",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5", "Ng3", "Bg6", "h4", "h6"],
      idea: "Se juega c6 antes que d5 justamente para poder sacar el alfil de c8, que en la francesa queda encerrado.",
      clave: "h6 hay que jugarlo: sin eso viene h5 y el alfil de g6 se queda sin casillas.",
    },
    {
      id: "caro-kann-avance",
      nombre: "Caro-Kann, avance",
      apertura: "Defensa Caro-Kann",
      tipo: "apertura", color: "b", nivel: 1,
      jugadas: ["e4", "c6", "d4", "d5", "e5", "Bf5", "Nf3", "e6", "Be2", "c5"],
      idea: "El alfil sale ANTES de cerrar con e6: esa es toda la gracia de la Caro-Kann.",
      clave: "Primero Af5, después e6. Al revés, el alfil queda enterrado como en la francesa.",
    },
    {
      id: "escandinava",
      nombre: "Defensa escandinava",
      apertura: "Defensa escandinava",
      tipo: "apertura", color: "b", nivel: 1,
      jugadas: ["e4", "d5", "exd5", "Qxd5", "Nc3", "Qa5", "d4", "Nf6", "Nf3", "Bf5"],
      idea: "Se cambia el peón central de una vez; la dama sale temprano pero a una casilla donde no la echan.",
      clave: "Da5 y no Dd8: desde a5 la dama clava el caballo de c3 y el negro gana tiempo de desarrollo.",
    },
    {
      id: "pirc",
      nombre: "Defensa Pirc",
      apertura: "Defensa Pirc",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "d6", "d4", "Nf6", "Nc3", "g6", "Nf3", "Bg7", "Be2", "O-O"],
      idea: "Se le deja el centro al blanco a propósito, para atacarlo después con piezas.",
      clave: "Es una apertura hipermoderna: el centro se controla desde lejos, no se ocupa.",
    },
    {
      id: "alekhine",
      nombre: "Defensa Alekhine",
      apertura: "Defensa Alekhine",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "Nf6", "e5", "Nd5", "d4", "d6", "Nf3", "dxe5", "Nxe5", "c6"],
      idea: "El caballo se deja perseguir para que los peones blancos avancen demasiado y queden débiles.",
      clave: "Cada jugada de peón que hace el blanco persiguiendo el caballo es una debilidad para el final.",
    },

    // ===================== APERTURAS DE 1.d4 =====================
    {
      id: "gambito-dama-declinado",
      nombre: "Gambito de dama declinado",
      apertura: "Gambito de dama",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7", "e3", "O-O", "Nf3", "h6"],
      idea: "La forma más sólida de contestar al gambito de dama: no se toma el peón y se arma una fortaleza.",
      clave: "El problema del negro es siempre el alfil de c8. Todos los planes pasan por sacarlo.",
    },
    {
      id: "eslava",
      nombre: "Defensa eslava",
      apertura: "Defensa eslava",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "d5", "c4", "c6", "Nf3", "Nf6", "Nc3", "dxc4", "a4", "Bf5"],
      idea: "Se sostiene d5 con c6 en vez de con e6, y así el alfil de c8 sí puede salir.",
      clave: "a4 frena b5: sin ese peón, el negro no puede quedarse con el de c4.",
    },
    {
      id: "nimzoindia",
      nombre: "Defensa Nimzoindia",
      apertura: "Defensa india",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "e3", "O-O", "Bd3", "d5"],
      idea: "El alfil clava el caballo de c3 y con eso le quita al blanco el control de e4.",
      clave: "Cambiar alfil por caballo no es malo acá: a cambio, el blanco queda con peones doblados en c.",
    },
    {
      id: "india-de-rey",
      nombre: "India de rey",
      apertura: "Defensa india",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O", "Be2", "e5"],
      idea: "Se deja que el blanco arme un centro enorme para romperlo después con e5 o c5.",
      clave: "e5 es la jugada de toda la apertura: sin esa ruptura, el negro se queda sin espacio y sin juego.",
    },
    {
      id: "grunfeld",
      nombre: "Defensa Grünfeld",
      apertura: "Defensa india",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "g6", "Nc3", "d5", "cxd5", "Nxd5", "e4", "Nxc3", "bxc3", "Bg7"],
      idea: "Es la india de rey al revés: el negro cambia en el centro en vez de cerrarlo.",
      clave: "El centro blanco se ve imponente y es justo el objetivo: el alfil de g7 y c5 lo van a atacar.",
    },
    {
      id: "india-de-dama",
      nombre: "India de dama",
      apertura: "Defensa india",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "Nf6", "c4", "e6", "Nf3", "b6", "g3", "Bb7", "Bg2", "Be7"],
      idea: "Los dos bandos ponen su alfil en la diagonal larga y pelean por la casilla e4.",
      clave: "Toda la apertura es una pelea por e4. El alfil de b7 es quien la pelea.",
    },
    {
      id: "sistema-londres",
      nombre: "Sistema Londres",
      apertura: "Sistema Londres",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["d4", "d5", "Nf3", "Nf6", "Bf4", "e6", "e3", "c5", "c3", "Nc6", "Nbd2", "Bd6"],
      idea: "El mismo armado contra casi todo lo que juegue el negro: ideal para empezar sin estudiar teoría.",
      clave: "El alfil sale a f4 ANTES de jugar e3. Al revés se queda encerrado detrás de sus peones.",
    },
    {
      id: "holandesa",
      nombre: "Defensa holandesa",
      apertura: "Defensa holandesa",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "f5", "g3", "Nf6", "Bg2", "e6", "Nf3", "Be7", "O-O", "O-O"],
      idea: "Se pelea por e4 desde la primera jugada y se juega a atacar el enroque blanco.",
      clave: "f5 debilita la diagonal a2-g8 y el rey propio. Es una apertura de doble filo, no para jugar distraído.",
    },
    {
      id: "inglesa",
      nombre: "Apertura inglesa",
      apertura: "Apertura inglesa",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["c4", "e5", "Nc3", "Nf6", "Nf3", "Nc6", "g3", "d5", "cxd5", "Nxd5"],
      idea: "Es una siciliana con los colores cambiados, y con un tiempo de más.",
      clave: "Se juega el centro desde los flancos: el alfil de g2 va a mirar toda la diagonal larga.",
    },
    {
      id: "vienesa",
      nombre: "Apertura vienesa con f4",
      apertura: "Apertura vienesa",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "Nf3", "Be7", "d3"],
      idea: "Es el gambito de rey con el caballo ya puesto en c3: el mismo ataque con una pieza más lista.",
      clave: "d3 echa al caballo de e4; hasta que no salga de ahí, el centro no es de nadie.",
    },
    {
      id: "gambito-evans",
      nombre: "Gambito Evans",
      apertura: "Apertura italiana",
      tipo: "apertura", color: "w", nivel: 3,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4", "Bxb4", "c3", "Ba5", "d4"],
      idea: "Un peón de flanco a cambio de dos tiempos: c3 y d4 arman el centro grande de una.",
      clave: "No se juega por el peón: se juega por el tiempo. Si el ataque se apaga, el final está perdido.",
    },
    {
      id: "ataque-indio-de-rey",
      nombre: "Ataque indio de rey",
      apertura: "Ataque indio de rey",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["Nf3", "d5", "g3", "Nf6", "Bg2", "e6", "O-O", "Be7", "d3", "O-O", "Nbd2", "c5", "e4"],
      idea: "La misma formación contra casi cualquier respuesta: Cf3, g3, Ag2, enroque, d3, Cbd2 y e4.",
      clave: "Después de e4 viene e5, y todas las piezas van al rey. Es un plan, no una variante.",
    },

    // ============ MÁS SISTEMAS (las trajeron las fichas de Estudio) ============
    // Cada una es la línea de su ficha en js/fichas-estudio.js: la ficha la
    // dibuja y el botón «Practicarla» la abre acá.
    {
      id: "colle",
      nombre: "Sistema Colle",
      apertura: "Sistema Colle",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["d4", "d5", "Nf3", "Nf6", "e3", "e6", "Bd3", "c5", "c3", "Nc6", "Nbd2", "Bd6", "O-O", "O-O", "dxc5", "Bxc5", "e4"],
      idea: "Las mismas jugadas contra casi todo: d4, Cf3, e3, Ad3, c3, Cbd2, enroque y la ruptura e4.",
      clave: "Todo el sistema prepara e4: el alfil de d3 y el caballo de d2 la sostienen.",
    },
    {
      id: "alapin",
      nombre: "Ataque Alapin contra la siciliana",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "c5", "c3", "Nf6", "e5", "Nd5", "d4", "cxd4", "Nf3", "Nc6", "cxd4", "d6", "Bc4", "Nb6", "Bb5"],
      idea: "Con c3 se prepara d4 y se arma el centro de peones sin entrar en la teoría de la siciliana abierta.",
      clave: "El peón de e5 echa al caballo de f6; el alfil va a c4 a molestar al caballo de d5.",
    },
    {
      id: "trompowsky",
      nombre: "Ataque Trompowsky",
      apertura: "Ataque Trompowsky",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["d4", "Nf6", "Bg5", "Ne4", "Bf4", "c5", "f3", "Qa5+", "c3", "Nf6", "d5"],
      idea: "Ag5 en la segunda jugada amenaza doblarle los peones al negro y lo saca de la teoría que estudió.",
      clave: "Si el caballo salta a e4, f3 lo echa; con d5 el blanco gana espacio en el centro.",
    },
    {
      id: "reti",
      nombre: "Apertura Réti",
      apertura: "Apertura Réti",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["Nf3", "d5", "c4", "e6", "g3", "Nf6", "Bg2", "Be7", "O-O", "O-O", "b3", "c5", "Bb2", "Nc6"],
      idea: "El centro se controla de lejos: c4 golpea d5 y los dos alfiles van en fianchetto.",
      clave: "No hace falta ocupar el centro con peones: los alfiles de g2 y b2 lo miran desde los costados.",
    },
    {
      id: "catalana",
      nombre: "Apertura catalana",
      apertura: "Gambito de dama",
      tipo: "apertura", color: "w", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "e6", "g3", "d5", "Bg2", "Be7", "Nf3", "O-O", "O-O", "dxc4", "Qc2", "a6", "Qxc4", "b5", "Qc2", "Bb7"],
      idea: "Un gambito de dama con el alfil en g2: si el negro come en c4, la dama lo recupera.",
      clave: "El alfil de g2 apunta a la diagonal larga y a b7: todo el juego del blanco pasa por ahí.",
    },
    {
      id: "gambito-escoces",
      nombre: "Gambito escocés",
      apertura: "Apertura escocesa",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "d4", "exd4", "Bc4", "Bc5", "c3", "Nf6", "e5", "d5", "Bb5", "Ne4", "cxd4", "Bb4+", "Bd2", "Nxd2", "Nbxd2"],
      idea: "En vez de recuperar el peón de d4 en el acto, se desarrolla el alfil y se ataca primero.",
      clave: "e5 echa al caballo de f6: el blanco recupera el peón con el centro de su lado.",
    },
    {
      id: "philidor",
      nombre: "Defensa Philidor",
      apertura: "Defensa Philidor",
      tipo: "apertura", color: "b", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "d6", "d4", "Nf6", "Nc3", "Nbd7", "Bc4", "Be7", "O-O", "O-O", "Re1", "c6", "a4"],
      idea: "El negro sostiene su peón de e5 con d6 y Cbd7, y arma una posición sólida sin regalar nada.",
      clave: "El peón de e5 no se suelta: es lo que le da al negro su lugar en el centro.",
    },
    {
      id: "gambito-dama-aceptado",
      nombre: "Gambito de dama aceptado",
      apertura: "Gambito de dama",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "d5", "c4", "dxc4", "Nf3", "Nf6", "e3", "e6", "Bxc4", "c5", "O-O", "a6"],
      idea: "El negro toma el peón de c4 sin querer guardarlo: lo devuelve a cambio de jugar con c5 contra el centro.",
      clave: "No hay que aferrarse al peón: c5 y a6 son las jugadas que importan.",
    },
    {
      id: "semieslava",
      nombre: "Defensa semieslava, variante Merano",
      apertura: "Defensa eslava",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "d5", "c4", "c6", "Nf3", "Nf6", "Nc3", "e6", "e3", "Nbd7", "Bd3", "dxc4", "Bxc4", "b5", "Bd3", "Bb7"],
      idea: "Los peones de c6 y e6 arman una muralla, y el negro gana espacio en el flanco de dama con b5.",
      clave: "Después de b5 el alfil va a b7 y la ruptura que lo libera todo es c5.",
    },
    {
      id: "benoni-moderna",
      nombre: "Benoni moderna",
      apertura: "Defensa Benoni",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3", "exd5", "cxd5", "d6", "e4", "g6", "Nf3", "Bg7", "Be2", "O-O", "O-O", "Re8"],
      idea: "Se desequilibra desde la jugada dos: el blanco tiene el centro, el negro la mayoría en el flanco de dama.",
      clave: "El alfil de g7 y la torre de e8 presionan e4; el plan del negro es b5.",
    },
    {
      id: "siciliana-abierta",
      nombre: "Siciliana abierta, con Ae2",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6", "Be2", "e5", "Nb3", "Be7", "O-O", "O-O"],
      idea: "Con d4 el blanco abre el centro: cambia su peón de d por el de c y saca ventaja de desarrollo.",
      clave: "El caballo de d4 se retira a b3 cuando lo echan, y el blanco pelea por la casilla d5.",
    },
    {
      id: "smith-morra",
      nombre: "Gambito Smith-Morra",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "d6", "Bc4", "e6", "O-O", "Nf6", "Qe2", "Be7", "Rd1"],
      idea: "Se entrega un peón contra la siciliana a cambio de desarrollo rápido y columnas abiertas.",
      clave: "Las torres van a c1 y d1: la presión sobre el peón de d6 es el plan.",
    },
    {
      id: "cuatro-caballos",
      nombre: "Apertura de los cuatro caballos",
      apertura: "Apertura de los cuatro caballos",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6", "Bb5", "Bb4", "O-O", "O-O", "d3", "d6", "Bg5"],
      idea: "Los cuatro caballos salen primero, a sus mejores casillas, y después los alfiles.",
      clave: "Ag5 clava el caballo de f6: si el negro no lo cuida, el enroque queda débil.",
    },
    {
      id: "gambito-danes",
      nombre: "Gambito danés",
      apertura: "Apertura del centro",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "d4", "exd4", "c3", "dxc3", "Bc4", "cxb2", "Bxb2", "Nf6", "Nc3", "Bb4", "Ne2"],
      idea: "Dos peones entregados a cambio de dos alfiles que apuntan al enroque negro.",
      clave: "El alfil de c4 mira a f7 y el de b2 a g7: con desarrollo bien hecho, el negro devuelve los peones.",
    },
    {
      id: "berlin",
      nombre: "Defensa Berlín contra la española",
      apertura: "Apertura española",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Nxe4", "d4", "Nd6", "Bxc6", "dxc6", "dxe5", "Nf5", "Qxd8+", "Kxd8"],
      idea: "El negro cambia las damas temprano y llega a un final sólido con la pareja de alfiles.",
      clave: "El rey negro se queda en el centro sin miedo: sin damas, ahí está bien.",
    },
    {
      id: "inglesa-simetrica",
      nombre: "Inglesa simétrica",
      apertura: "Apertura inglesa",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["c4", "c5", "Nc3", "Nc6", "g3", "g6", "Bg2", "Bg7", "Nf3", "e6", "O-O", "Nge7"],
      idea: "El negro copia la estructura del blanco: c5 contra c4 y el alfil en fianchetto.",
      clave: "El caballo va a e7 para no tapar al alfil de g7; la ruptura del negro es d5.",
    },
    {
      id: "benko",
      nombre: "Gambito Benko",
      apertura: "Defensa Benoni",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "Nf6", "c4", "c5", "d5", "b5", "cxb5", "a6", "bxa6", "Bxa6", "Nc3", "d6", "e4", "Bxf1", "Kxf1", "g6"],
      idea: "El negro entrega un peón y a cambio abre las columnas a y b para sus torres.",
      clave: "El alfil de g7 y las torres en a8 y b8 presionan el flanco de dama durante toda la partida.",
    },
    {
      id: "francesa-winawer",
      nombre: "Francesa, variante Winawer",
      apertura: "Defensa francesa",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "e6", "d4", "d5", "Nc3", "Bb4", "e5", "c5", "a3", "Bxc3+", "bxc3", "Ne7", "Nf3", "Nbc6", "a4", "Qa5", "Bd2"],
      idea: "El negro clava el caballo de c3 y lo cambia: le deja al blanco los peones doblados a cambio del alfil.",
      clave: "El negro presiona c3 y d4 con la dama, los caballos y el peón de c5; el blanco tiene los dos alfiles y espacio.",
    },
    {
      id: "defensa-moderna",
      nombre: "Defensa moderna",
      apertura: "Defensa moderna",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "g6", "d4", "Bg7", "Nc3", "d6", "Be3", "a6", "Qd2", "b5", "f3", "Nd7"],
      idea: "El negro deja que el blanco arme el centro y lo ataca después, desde lejos, con el alfil de g7.",
      clave: "a6 y b5 ganan espacio en el flanco de dama; el caballo va a d7 para no tapar al alfil y preparar c5.",
    },
    {
      id: "stonewall",
      nombre: "Ataque Stonewall",
      apertura: "Peón de dama",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["d4", "d5", "e3", "Nf6", "Bd3", "c5", "c3", "Nc6", "f4", "e6", "Nf3", "Bd6", "Nbd2", "O-O", "O-O", "Qc7", "Ne5"],
      idea: "Los peones de c3, d4, e3 y f4 arman un muro, y el caballo se planta en e5 apoyado por ellos.",
      clave: "El caballo de e5 y el alfil de d3 apuntan al enroque negro; la torre puede subir por f3 hasta h3.",
    },
    {
      id: "gambito-budapest",
      nombre: "Gambito Budapest",
      apertura: "Peón de dama",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "Nf6", "c4", "e5", "dxe5", "Ng4", "Bf4", "Nc6", "Nf3", "Bb4+", "Nbd2", "Qe7", "e3", "Ngxe5", "Nxe5", "Nxe5"],
      idea: "El negro entrega el peón de e5 en la segunda jugada y casi siempre lo recupera con desarrollo rápido.",
      clave: "El caballo vuelve a e5 y el alfil de b4 clava al caballo de d2: el negro sale de la apertura sin peón de menos.",
    },
    {
      id: "ponziani",
      nombre: "Apertura Ponziani",
      apertura: "Apertura Ponziani",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "e5", "Nf3", "Nc6", "c3", "Nf6", "d4", "Nxe4", "d5", "Ne7", "Nxe5", "Ng6", "Qd4", "Qe7", "Qxe4", "Qxe5", "Qxe5", "Nxe5"],
      idea: "c3 prepara d4 para quedarse con el centro de peones, en vez de sacar el alfil.",
      clave: "Si el negro contraataca en e4, d5 echa al caballo de c6 y el blanco gana espacio.",
    },
    {
      id: "apertura-alfil",
      nombre: "Apertura del alfil",
      apertura: "Apertura del alfil",
      tipo: "apertura", color: "w", nivel: 1,
      jugadas: ["e4", "e5", "Bc4", "Nf6", "d3", "c6", "Nf3", "d5", "Bb3", "Bd6", "Nc3", "O-O", "O-O"],
      idea: "El alfil sale a c4 antes que el caballo: apunta a f7 y deja abierta la ruptura f4.",
      clave: "Con d3 el blanco sostiene e4 y no le da al negro un blanco fácil en el centro.",
    },
    {
      id: "bird",
      nombre: "Apertura Bird",
      apertura: "Apertura Bird",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["f4", "d5", "Nf3", "Nf6", "e3", "g6", "b3", "Bg7", "Bb2", "O-O", "Be2", "c5", "O-O", "Nc6"],
      idea: "f4 controla e5 desde la primera jugada y el alfil de b2 apunta a la diagonal larga.",
      clave: "La casilla e5 es del blanco: el caballo y el alfil de b2 la pelean juntos.",
    },
    {
      id: "grand-prix",
      nombre: "Ataque Grand Prix",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "w", nivel: 2,
      jugadas: ["e4", "c5", "Nc3", "Nc6", "f4", "g6", "Nf3", "Bg7", "Bb5", "Nd4", "O-O"],
      idea: "Contra la siciliana, el blanco juega f4 y ataca en el flanco de rey sin abrir el centro.",
      clave: "El plan es f5 y llevar la dama a e1 y h4, contra el enroque negro.",
    },
    {
      id: "siciliana-sveshnikov",
      nombre: "Siciliana Sveshnikov",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5", "Ndb5", "d6", "Bg5", "a6", "Na3", "b5", "Bxf6", "gxf6", "Nd5", "f5"],
      idea: "El negro juega e5 temprano: deja el hueco de d5 a cambio de tiempo, espacio y los dos alfiles.",
      clave: "Con f5 el negro ataca e4 y abre la columna g; el blanco tiene el caballo en d5.",
    },
    {
      id: "siciliana-kan",
      nombre: "Siciliana Kan",
      apertura: "Defensa siciliana",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["e4", "c5", "Nf3", "e6", "d4", "cxd4", "Nxd4", "a6", "Bd3", "Nf6", "O-O", "Qc7", "Qe2", "d6", "c4", "g6"],
      idea: "Con e6 y a6 el negro arma una posición flexible y espera para decidir dónde van sus piezas.",
      clave: "La dama en c7 y los peones en d6 y e6 forman un erizo: el negro espera el momento de b5 o d5.",
    },
    {
      id: "bogoindia",
      nombre: "Defensa Bogoindia",
      apertura: "Peón de dama",
      tipo: "apertura", color: "b", nivel: 2,
      jugadas: ["d4", "Nf6", "c4", "e6", "Nf3", "Bb4+", "Bd2", "Qe7", "g3", "Nc6", "Bg2", "Bxd2+", "Nbxd2", "d6", "O-O", "O-O"],
      idea: "El negro da jaque con el alfil en b4 y lo cambia: juega con los peones en casillas negras.",
      clave: "Después de cambiar el alfil, el plan negro es e5 para pelear por el centro.",
    },
    {
      id: "india-antigua",
      nombre: "Defensa india antigua",
      apertura: "Peón de dama",
      tipo: "apertura", color: "b", nivel: 1,
      jugadas: ["d4", "Nf6", "c4", "d6", "Nc3", "Nbd7", "e4", "e5", "Nf3", "Be7", "Be2", "O-O", "O-O", "c6"],
      idea: "Una defensa sólida: d6, Cbd7 y e5, con el alfil en e7 en vez del fianchetto.",
      clave: "El peón de e5 se sostiene con d6 y el caballo de d7; el negro rompe después con d5 o b5.",
    },
    {
      id: "holandesa-leningrado",
      nombre: "Holandesa Leningrado",
      apertura: "Defensa holandesa",
      tipo: "apertura", color: "b", nivel: 3,
      jugadas: ["d4", "f5", "g3", "Nf6", "Bg2", "g6", "Nf3", "Bg7", "O-O", "O-O", "c4", "d6", "Nc3", "Qe8"],
      idea: "La holandesa con el alfil en fianchetto: f5 controla e4 y el alfil de g7 apunta a la diagonal larga.",
      clave: "La dama va a e8 y después a h5 o f7, preparando e5 para abrir el juego.",
    },
  ];

  // Cuántas jugadas tiene que dar el alumno en una línea.
  function jugadasDelAlumno(linea) {
    var mias = 0;
    for (var i = 0; i < linea.jugadas.length; i++) {
      var deBlancas = i % 2 === 0;
      if ((linea.color === "w") === deBlancas) mias += 1;
    }
    return mias;
  }

  var api = { LINEAS: LINEAS, jugadasDelAlumno: jugadasDelAlumno };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (typeof window !== "undefined") window.AperturasLineas = api;
})();
