/* ===== Pareo Integral — los textos, en español y en inglés =====
 *
 * FIDE pide que un programa avalado se pueda usar en inglés; la página arranca
 * en español y cambia con el botón de arriba. Cada clave tiene las dos
 * versiones: herramientas/verificar-pareo-pagina.js falla si a una le falta
 * alguna o si la página usa una clave que no está acá. {x} se reemplaza.
 */
(function (raiz) {
  "use strict";

  const TEXTOS = {
    tituloPagina: ["Pareo Integral — emparejamientos de torneos de ajedrez (Sistema Holandés de FIDE)", "Pareo Integral — chess tournament pairings (FIDE Dutch System)"],
    lema: ["Emparejamientos de torneos de ajedrez con el Sistema Holandés de FIDE, resultados y desempates. Gratis, sin cuenta y en tu computadora.", "Chess tournament pairings with the FIDE Dutch System, results and tie-breaks. Free, no account, on your own computer."],
    misTorneos: ["Mis torneos", "My tournaments"],
    torneoAbierto: ["Torneo abierto", "Open tournament"],
    nuevoTorneo: ["Nuevo torneo", "New tournament"],
    privado: ["Lo que escribes queda guardado solo en este navegador. Para pasarlo a otra computadora o tener una copia, baja el archivo del torneo en «Archivos».", "Everything you type is saved only in this browser. To move it to another computer or keep a copy, download the tournament file under “Files”."],
    partes: ["Partes del torneo", "Tournament sections"],
    fTorneo: ["Torneo", "Tournament"],
    fJugadores: ["Jugadores", "Players"],
    fRondas: ["Rondas", "Rounds"],
    fClasificacion: ["Clasificación", "Standings"],
    fCruzada: ["Tabla cruzada", "Crosstable"],
    fArchivos: ["Archivos y comprobador", "Files and checker"],
    sinNombre: ["(sin nombre)", "(untitled)"],
    noGuarda: ["El navegador no dejó guardar el torneo (¿ventana privada?). Baja una copia en «Archivos» para no perderlo.", "The browser did not allow saving the tournament (private window?). Download a copy under “Files” so you don't lose it."],

    datosTorneo: ["Datos del torneo", "Tournament details"],
    nombreTorneo: ["Nombre del torneo", "Tournament name"],
    ciudad: ["Ciudad", "City"],
    federacion: ["Federación (código FIDE, p. ej. CRC)", "Federation (FIDE code, e.g. CRC)"],
    fechaInicio: ["Fecha de inicio", "Start date"],
    fechaFin: ["Fecha de cierre", "End date"],
    arbitro: ["Árbitro principal", "Chief arbiter"],
    arbitroAdjunto: ["Árbitro adjunto", "Deputy arbiter"],
    ritmo: ["Ritmo de juego (p. ej. 90 min + 30 s por jugada)", "Time control (e.g. 90 min + 30 s per move)"],
    sistema: ["Sistema", "System"],
    suizo: ["Suizo (Sistema Holandés de FIDE)", "Swiss (FIDE Dutch System)"],
    todos: ["Todos contra todos (tablas de Berger)", "Round robin (Berger tables)"],
    sistemaFijo: ["El sistema ya no se puede cambiar: hay rondas emparejadas.", "The system can no longer be changed: rounds have been paired."],
    rondasTotales: ["Número de rondas", "Number of rounds"],
    colorInicial: ["Color del n.º 1 en la ronda 1", "Colour of no. 1 in round 1"],
    blancas: ["Blancas", "White"],
    negras: ["Negras", "Black"],
    baku: ["Aceleración Baku", "Baku acceleration"],
    dobleVuelta: ["A doble vuelta", "Double round robin"],
    puntos: ["Puntos", "Points"],
    pVictoria: ["Victoria", "Win"],
    pTablas: ["Tablas", "Draw"],
    pDerrota: ["Derrota", "Loss"],
    pBye: ["Bye del pareo", "Pairing-allocated bye"],
    rondasInvalidas: ["El número de rondas va de {min} a 30.", "The number of rounds must be between {min} and 30."],
    desempates: ["Desempates, en orden", "Tie-breaks, in order"],
    desempatesAyuda: ["Se aplican uno detrás del otro, según el reglamento C.07 de FIDE (versión 2026). Los que usan el Elo necesitan el Elo de todos los jugadores.", "They are applied one after the other, following FIDE regulation C.07 (2026 version). Rating-based tie-breaks need every player's rating."],
    agregarDesempate: ["Agregar un desempate", "Add a tie-break"],
    agregar: ["Agregar", "Add"],
    sinDesempates: ["Sin desempates: los empatados comparten puesto.", "No tie-breaks: tied players share their place."],
    subir: ["Subir {n}", "Move {n} up"],
    bajar: ["Bajar {n}", "Move {n} down"],
    quitar: ["Quitar", "Remove"],
    quitarDesempate: ["Quitar {n}", "Remove {n}"],

    agregarJugador: ["Agregar un jugador", "Add a player"],
    nombreJugador: ["Apellidos, nombre", "Surname, first name"],
    titulo: ["Título", "Title"],
    fed: ["Fed.", "Fed."],
    fideId: ["ID FIDE", "FIDE ID"],
    sexo: ["Sexo", "Sex"],
    masculino: ["Masculino", "Male"],
    femenino: ["Femenino", "Female"],
    nacimiento: ["Fecha de nacimiento", "Date of birth"],
    nacimientoFormato: ["Fecha de nacimiento (AAAA-MM-DD)", "Date of birth (YYYY-MM-DD)"],
    pegarVarios: ["Pegar una lista de jugadores", "Paste a list of players"],
    pegarAyuda: ["Uno por línea: Nombre; Institución; Elo; Título; Federación; ID FIDE; Categoría. Sirve copiar las columnas de una hoja de cálculo (con tabuladores también); lo que no tengas, se deja en blanco.", "One per line: Name; Institution; Rating; Title; Federation; FIDE ID; Category. Columns copied from a spreadsheet (tab-separated) work too; leave out what you don't have."],
    listaJugadores: ["Lista de jugadores", "List of players"],
    agregarLista: ["Agregar la lista", "Add the list"],
    agregados: ["Se agregaron {n} jugadores.", "{n} players were added."],
    nadaQueAgregar: ["No hay ningún nombre que agregar.", "There is no name to add."],
    faltaNombre: ["Falta el nombre del jugador.", "The player's name is missing."],
    institucion: ["Institución", "Institution"],
    categoria: ["Categoría", "Category"],
    nombresRepetidos: ["Ya hay otro jugador con el mismo nombre: {n}. Revisa que no sea la misma persona anotada dos veces.", "There is already another player with the same name: {n}. Check that it isn't the same person entered twice."],
    subirLista: ["Subir una lista (Word o Excel)", "Upload a list (Word or Excel)"],
    subirListaAyuda: ["Un .xlsx, .csv o .docx con una fila o un párrafo por jugador. Si la primera fila dice «Nombre», «Institución», «Elo»… se usa esa columna; si no, se lee en el mismo orden de arriba.", "An .xlsx, .csv or .docx with one row or paragraph per player. If the first row says “Name”, “Institution”, “Rating”… that column is used; otherwise it's read in the same order as above."],
    subirListaBoton: ["Elegir el archivo", "Choose the file"],
    leyendoArchivo: ["Leyendo el archivo…", "Reading the file…"],
    archivoSinJugadores: ["No se encontró ningún nombre en ese archivo.", "No name was found in that file."],
    archivoDocAntiguo: ["Los .doc viejos no se pueden leer acá. Guárdalo como .docx.", "Old .doc files can't be read here. Save it as .docx."],
    bajarJugadores: ["Exportar jugadores (.csv)", "Export players (.csv)"],
    sinJugadoresQueExportar: ["No hay ningún jugador que exportar.", "There is no player to export."],
    buscarEloNacional: ["Buscar Elo Nacional de quien no tiene", "Look up National rating for those without one"],
    eloNacionalAyuda: ["Es lo único de Pareo Integral que sale de tu computadora: se manda el nombre de cada jugador a nuestro servidor para buscarlo en ajedrezcostarica.com. No se guarda nada.", "This is the one thing in Pareo Integral that leaves your computer: each player's name is sent to our server to look it up on ajedrezcostarica.com. Nothing is stored."],
    sinQuienBuscar: ["Ya todos los jugadores tienen Elo.", "Every player already has a rating."],
    buscandoElo: ["Buscando el Elo Nacional de {n} jugadores…", "Looking up the National rating of {n} players…"],
    eloNacionalResultado: ["Se encontró el Elo Nacional de {n} de {total}.", "Found the National rating for {n} of {total}."],
    eloNacionalError: ["No se pudo buscar el Elo Nacional. Intenta de nuevo.", "Could not look up the National rating. Try again."],
    eloNacionalTope: ["Se buscaron los primeros {tope}; vuelve a tocar el botón para seguir con el resto.", "Only the first {tope} were searched; click the button again for the rest."],
    eloAmbiguo: ["hay más de una persona con ese nombre en la lista nacional", "more than one person with that name is in the national list"],
    eloNoEncontrado: ["no aparece en la lista nacional", "not found in the national list"],
    inscritos: ["Inscritos", "Registered"],
    ordenAyuda: ["El número de cada uno sale del orden inicial de FIDE: Elo, título y nombre.", "Each number comes from the FIDE initial ranking: rating, title and name."],
    ordenFijo: ["Los números quedaron fijos al emparejar la ronda 1. Quien se inscribe tarde entra en el lugar que le toca por Elo.", "Numbers were fixed when round 1 was paired. Late entries are inserted where their rating places them."],
    sinJugadores: ["Todavía no hay nadie inscrito.", "Nobody has registered yet."],
    buscarJugador: ["Buscar un jugador", "Search for a player"],
    nadieCoincide: ["Nadie coincide con lo que buscas.", "Nobody matches what you're searching for."],
    nro: ["N.º", "No."],
    nombre: ["Nombre", "Name"],
    pts: ["Pts", "Pts"],
    estado: ["Estado", "Status"],
    acciones: ["Acciones", "Actions"],
    activo: ["Juega", "Active"],
    retiradoDesde: ["Retirado desde la ronda {r}", "Withdrawn from round {r}"],
    retirado: ["retirado", "withdrawn"],
    editar: ["Editar", "Edit"],
    editarA: ["Editar a {n}", "Edit {n}"],
    retirar: ["Retirar", "Withdraw"],
    retirarA: ["Retirar a {n}", "Withdraw {n}"],
    volver: ["Vuelve a jugar", "Rejoin"],
    volverA: ["{n} vuelve a jugar", "{n} rejoins"],
    vuelve: ["{n} vuelve a entrar en los emparejamientos.", "{n} is back in the pairings."],
    eliminar: ["Eliminar", "Delete"],
    eliminarA: ["Eliminar a {n}", "Delete {n}"],
    guardarCambios: ["Guardar los cambios", "Save changes"],
    confirmarRetiro: ["¿Retirar a {n}? No se le empareja desde la ronda {r}; lo que ya jugó sigue contando.", "Withdraw {n}? They will not be paired from round {r}; games already played still count."],
    confirmarEliminar: ["¿Eliminar a {n} del torneo?", "Delete {n} from the tournament?"],
    inscripcionTardia: ["Inscripción tardía: en las {r} rondas ya jugadas cuenta como ausente con 0 puntos. Si le corresponde un bye, cámbialo en cada ronda.", "Late entry: they count as absent with 0 points in the {r} rounds already played. If they are entitled to a bye, change it in each round."],

    ronda: ["Ronda", "Round"],
    rondaN: ["Ronda {r}", "Round {r}"],
    porEmparejar: ["por emparejar", "to be paired"],
    enJuego: ["en juego", "in progress"],
    primeroJugadores: ["Primero inscribe a los jugadores.", "Register the players first."],
    torneoTerminado: ["Ya se emparejaron todas las rondas del torneo.", "All rounds of the tournament have been paired."],
    emparejamientosRonda: ["Emparejamientos de la ronda {r}", "Pairings for round {r}"],
    imprimir: ["Imprimir", "Print"],
    plantillaMesas: ["Plantilla para la pared", "Wall sheet"],
    plantillaTitulo: ["Ronda {r} — Resultados por mesa", "Round {r} — Results by board"],
    planillasFirma: ["Planillas para firmar", "Signature sheets"],
    planillaFirmaTitulo: ["Ronda {r} — Mesa {m}", "Round {r} — Board {m}"],
    firmaDe: ["Firma de {n}", "Signature of {n}"],
    verDesdeElCelular: ["Ver desde el celular", "View from your phone"],
    verAyuda: ["Es una foto del momento: muestra esta ronda y la clasificación de ahora, pero no se actualiza sola. Si cambia un resultado o se empareja otra ronda, vuelve a mostrar el código.", "It's a snapshot: it shows this round and the standings as of now, but it doesn't update itself. If a result changes or another round is paired, show the code again."],
    copiarEnlace: ["Copiar el enlace", "Copy the link"],
    generandoQr: ["Generando…", "Generating…"],
    qrEtiqueta: ["Código QR para ver el torneo desde el celular", "QR code to view the tournament from your phone"],
    errorQr: ["No se pudo armar el código: {e}", "Couldn't build the code: {e}"],
    enlaceCopiado: ["Enlace copiado.", "Link copied."],
    noCopia: ["No se pudo copiar solo: selecciónalo y cópialo a mano.", "Couldn't copy it automatically: select it and copy it by hand."],
    cargandoVer: ["Cargando…", "Loading…"],
    errorVerEnlace: ["Este enlace no se pudo leer. Pide uno nuevo a quien organiza el torneo.", "This link couldn't be read. Ask the tournament organizer for a new one."],
    verFotoDelMomento: ["Esto es del momento en que se compartió: puede que ya haya cambiado.", "This is from when it was shared: it may have changed already."],
    actualizarSola: ["Actualizar sola (en vivo)", "Update itself (live)"],
    actualizarSolaAyuda: ["Mientras esta pestaña quede abierta, cada cambio que guardes llega solo a quien ya tenga el enlace o el código abiertos. Si la cierras, quien ya estaba mirando se queda con lo último que vio, y quien recién llega no ve nada hasta que la vuelvas a abrir.", "While this tab stays open, every change you save reaches only those who already have the link or code open. If you close it, whoever was already watching keeps the last thing they saw, and whoever just arrives sees nothing until you open it again."],
    conectandoEnVivo: ["Conectando…", "Connecting…"],
    enVivoActivo: ["En vivo.", "Live."],
    errorEnVivo: ["No se pudo conectar: {e}", "Couldn't connect: {e}"],
    nuevoCodigoBoton: ["Usar un código nuevo", "Use a new code"],
    verEnVivoLeyenda: ["Esto se actualiza solo mientras quien organiza tenga la pestaña abierta.", "This updates itself while the organizer keeps the tab open."],
    errorEnVivoVer: ["No se pudo conectar para ver el torneo en vivo. Pide un enlace nuevo a quien organiza.", "Couldn't connect to watch the tournament live. Ask the organizer for a new link."],
    esperandoVivo: ["Esperando a que quien organiza mande algo… Puede que no tenga esta pestaña abierta.", "Waiting for the organizer to send something… They may not have this tab open."],
    deshacerRonda: ["Deshacer el emparejamiento", "Undo the pairing"],
    faltanResultados: ["Faltan {n} resultados.", "{n} results are missing."],
    rondaCompleta: ["Están todos los resultados.", "All results are in."],
    avisoCorregir: ["Si corriges un resultado de esta ronda, las rondas siguientes no se vuelven a emparejar: ya están hechas con el resultado anterior.", "If you correct a result in this round, later rounds are not re-paired: they were made with the previous result."],
    mesa: ["Mesa", "Board"],
    resultado: ["Resultado", "Result"],
    resultadoMesa: ["Resultado de la mesa {m}: {b} contra {n}", "Result of board {m}: {b} vs {n}"],
    byePareo: ["Bye del pareo ({p})", "Pairing-allocated bye ({p})"],
    resSin: ["— sin resultado —", "— no result —"],
    res10: ["1-0", "1-0"],
    resTablas: ["½-½", "½-½"],
    res01: ["0-1", "0-1"],
    resMasMenos: ["+/− (no vino negras)", "+/− (black forfeits)"],
    resMenosMas: ["−/+ (no vino blancas)", "−/+ (white forfeits)"],
    resMenosMenos: ["−/− (no vino ninguno)", "−/− (both forfeit)"],
    "corto_1-0": ["1-0", "1-0"],
    "corto_=": ["½-½", "½-½"],
    "corto_0-1": ["0-1", "0-1"],
    "corto_+-": ["+/−", "+/−"],
    "corto_-+": ["−/+", "−/+"],
    "corto_--": ["−/−", "−/−"],
    noJuegan: ["No juegan esta ronda", "Not playing this round"],
    ausenciaDe: ["Lo que cuenta la ronda para {n}", "What this round counts for {n}"],
    byeMedio: ["Bye pedido ({p})", "Requested bye ({p})"],
    byeCero: ["Ausente (0)", "Absent (0)"],
    byeEntero: ["Bye de punto entero ({p})", "Full-point bye ({p})"],
    noViene: ["No viene", "Not coming"],
    noVieneA: ["Marcar que {n} no viene a esta ronda", "Mark {n} as not coming to this round"],
    deshacerNoViene: ["Deshacer", "Undo"],
    deshacerNoVieneA: ["Deshacer que {n} no viene a esta ronda", "Undo marking {n} as not coming to this round"],
    libre: ["Libre (0)", "Free round (0)"],
    primeroResultados: ["Para emparejar la ronda siguiente hacen falta todos los resultados de la ronda {r}.", "All results of round {r} are needed to pair the next round."],
    emparejarRonda: ["Emparejar la ronda {r}", "Pair round {r}"],
    todosAyuda: ["En un todos contra todos los emparejamientos salen de las tablas de Berger. Quien no se presenta pierde por incomparecencia: anótalo en el resultado.", "In a round robin the pairings come from the Berger tables. A player who does not show up loses by forfeit: record it as the result."],
    numerosSorteo: ["Números de sorteo", "Draw numbers"],
    sortear: ["Sortear los números", "Draw the numbers by lot"],
    sorteados: ["Números sorteados.", "Numbers drawn."],
    byesAyuda: ["Marca quién pidió bye o no viene a esta ronda; el resto se empareja con el Sistema Holandés.", "Mark who requested a bye or is not coming to this round; everyone else is paired with the Dutch System."],
    antesDeEmparejar: ["Antes de emparejar:", "Before pairing:"],
    sinCategoriaResumen: ["{n} sin categoría", "{n} without a category"],
    sinInstitucionResumen: ["{n} sin institución", "{n} without an institution"],
    sinEloResumen: ["{n} sin Elo (se ordenan al final)", "{n} without a rating (seeded last)"],
    juega: ["Juega", "Plays"],
    juegaRonda: ["{n} en la ronda {r}", "{n} in round {r}"],
    emparejando: ["Emparejando…", "Pairing…"],
    rondaLista: ["Ronda {r} emparejada.", "Round {r} paired."],
    sinPareoPosible: ["No hay forma de emparejar esta ronda con las reglas de FIDE (por ejemplo, ya no quedan rivales nuevos para alguien). Revisa el número de rondas o los byes.", "This round cannot be paired under the FIDE rules (for example, someone has no new opponents left). Check the number of rounds or the byes."],
    errorMotor: ["El motor no pudo terminar: {e}", "The engine could not finish: {e}"],
    yaEmparejada: ["La ronda ya estaba emparejada.", "The round was already paired."],
    pocosJugadores: ["Hacen falta al menos dos jugadores.", "At least two players are needed."],
    confirmarDeshacer: ["¿Deshacer el emparejamiento de la ronda {r}?", "Undo the pairing of round {r}?"],
    confirmarDeshacerConResultados: ["La ronda {r} ya tiene resultados anotados y se pierden. ¿Deshacer el emparejamiento?", "Round {r} already has results recorded and they will be lost. Undo the pairing?"],

    puesto: ["Puesto", "Rank"],
    clasificacionTras: ["Clasificación tras la ronda {r}", "Standings after round {r}"],
    clasSoloCompletas: ["Cuenta las rondas con todos sus resultados: hasta la ronda {r}.", "Only rounds with every result are counted: up to round {r}."],
    filtrarInstitucion: ["Institución", "Institution"],
    todasInstituciones: ["Todas las instituciones", "All institutions"],
    clasFiltroNota: [" · {n} de {total}, solo de «{inst}»", " · {n} of {total}, only from “{inst}”"],
    bajarPdf: ["Bajar PDF", "Download PDF"],
    generandoPdf: ["Armando el PDF…", "Building the PDF…"],
    errorPdf: ["No se pudo armar el PDF: {e}", "Could not build the PDF: {e}"],
    sinNadaQueExportar: ["No hay ningún jugador en esta lista para exportar.", "There is no player in this list to export."],
    cruzadaAyuda: ["En cada ronda: el número del rival, el color (b blancas, n negras) y el resultado. «+» y «−» son partidas no jugadas.", "For each round: the opponent's number, the colour (w white, b black) and the result. “+” and “−” are unplayed games."],
    rCorta: ["R{r}", "R{r}"],
    cBye: ["bye", "bye"],

    esteTorneo: ["Este torneo", "This tournament"],
    bajarTrf: ["Bajar el TRF para FIDE", "Download the FIDE TRF"],
    bajarCopia: ["Bajar una copia (.json)", "Download a copy (.json)"],
    borrarTorneo: ["Borrar este torneo", "Delete this tournament"],
    trfAyuda: ["El TRF es el archivo que FIDE pide para el informe de Elo, y el que leen los demás programas de emparejamiento.", "The TRF is the file FIDE requires for the rating report, and the one other pairing programs read."],
    trfSoloCompletas: ["El TRF lleva las rondas con todos sus resultados: hasta la ronda {r}.", "The TRF includes the rounds with every result: up to round {r}."],
    confirmarBorrar: ["¿Borrar «{n}» de este navegador? Si no bajaste una copia, no se puede recuperar.", "Delete “{n}” from this browser? Unless you downloaded a copy, it cannot be recovered."],
    borrado: ["Torneo borrado.", "Tournament deleted."],
    abrir: ["Abrir un torneo", "Open a tournament"],
    abrirArchivo: ["Abrir un TRF o una copia .json", "Open a TRF or a .json copy"],
    abrirAyuda: ["Sirve el TRF de Swiss-Manager, Vega u otro programa: se siguen emparejando las rondas que faltan.", "TRF files from Swiss-Manager, Vega or other programs work: the remaining rounds can be paired here."],
    abierto: ["Se abrió «{n}».", "“{n}” is open."],
    jsonNoEs: ["Ese archivo .json no es un torneo de Pareo Integral.", "That .json file is not a Pareo Integral tournament."],
    trfSinJugadores: ["El archivo no trae ninguna línea de jugador (001).", "The file has no player lines (001)."],
    noAbre: ["No se pudo abrir el archivo: {e}", "The file could not be opened: {e}"],
    archivoGrande: ["El archivo es demasiado grande para ser un torneo.", "The file is too large to be a tournament."],
    comprobador: ["Comprobador de emparejamientos", "Pairings checker"],
    comprobadorAyuda: ["Pega un TRF (de cualquier programa) y se vuelve a emparejar cada ronda con el Sistema Holandés para ver si coincide con la que se jugó.", "Paste a TRF (from any program) and every round is re-paired with the Dutch System to see whether it matches the one that was played."],
    trfComprobar: ["TRF a comprobar", "TRF to check"],
    comprobar: ["Comprobar", "Check"],
    comprobarEste: ["Comprobar este torneo", "Check this tournament"],
    desdeArchivo: ["Desde un archivo", "From a file"],
    comprobando: ["Comprobando…", "Checking…"],
    fpcBien: ["Correcto: las {r} rondas coinciden con el Sistema Holandés.", "Correct: all {r} rounds match the Dutch System."],
    fpcMal: ["Hay rondas que no coinciden con el Sistema Holandés:", "Some rounds do not match the Dutch System:"],
    fpcNoLee: ["No se pudo leer el TRF: {e}", "The TRF could not be read: {e}"],
    pegaTrf: ["Pega primero el TRF.", "Paste the TRF first."],
    soloSuizo: ["El comprobador es para torneos suizos.", "The checker is for Swiss tournaments."],
    generador: ["Generador de torneos al azar", "Random tournament generator"],
    generadorAyuda: ["Arma un torneo entero con resultados al azar, emparejado con el Sistema Holandés. Con la misma semilla sale siempre el mismo torneo: sirve para comparar programas.", "Builds a whole tournament with random results, paired with the Dutch System. The same seed always gives the same tournament, which is useful for comparing programs."],
    semilla: ["Semilla", "Seed"],
    generar: ["Generar y bajar el TRF", "Generate and download the TRF"],
    generarAbrir: ["Generar y abrirlo acá", "Generate and open it here"],
    torneoAzar: ["Torneo al azar (semilla {s})", "Random tournament (seed {s})"],
    creditos: ["Con qué está hecho", "What it is built on"],
    creditosMotor: ["Los emparejamientos los calcula bbpPairings (Jeremy Bierema, licencia Apache 2.0), el motor del Sistema Holandés que usan programas avalados por FIDE, compilado para correr en tu navegador.", "Pairings are computed by bbpPairings (Jeremy Bierema, Apache 2.0 licence), the Dutch System engine used by FIDE-endorsed programs, compiled to run in your browser."],
    creditosDesempates: ["Los desempates siguen el C.07 de FIDE (versión 2026) y están comparados con chesspairing (Gert Nutterts, licencia Apache 2.0).", "Tie-breaks follow FIDE C.07 (2026 version) and are cross-checked against chesspairing (Gert Nutterts, Apache 2.0 licence)."],
    creditosAval: ["Pareo Integral todavía no tiene el aval de FIDE.", "Pareo Integral is not yet endorsed by FIDE."],
    licencias: ["Licencias y versión del motor", "Engine licence and version"],
    manual: ["Manual de uso", "User manual"],
    bajarCli: ["Versión de línea de comandos (.zip)", "Command-line version (.zip)"],
  };

  function t(idioma, clave, vars) {
    const par = TEXTOS[clave];
    let s = par ? par[idioma === "en" ? 1 : 0] : clave;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split("{" + k + "}").join(String(v));
    return s;
  }

  const api = { TEXTOS, t };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else raiz.PareoTextos = api;
})(typeof self !== "undefined" ? self : this);
