/* ===== Las posiciones de «¿Cambio o no cambio?», de Oscar Angulo Cubero =====
 *
 * GENERADO por herramientas/cambio-o-no-cambio-generar.js — no se edita a mano.
 *
 * 87 posiciones de la base abierta de Lichess (CC0), comprobadas con
 * Stockfish: 23 ejemplos (uno por lección, los mismos del curso),
 * 40 ejercicios por capítulo y 24 mixtos. Lo usa el libro
 * (herramientas/cambio-o-no-cambio-pdf.js). Vive detrás del candado de
 * material/: trae las respuestas.
 */
window.CAMBIO_O_NO_CAMBIO = {
  TITULO: '¿Cambio o no cambio?',
  AUTOR: 'Oscar Angulo Cubero',
  POR_CAPITULO: 8,
  MIXTOS: 24,
  CAPITULOS: [{ n: 1, titulo: 'Qué se va y qué queda', temas: ['capturingDefender', 'quietMove', 'queenEndgame'] }, { n: 2, titulo: 'Alfiles y caballos', temas: ['knightEndgame', 'bishopEndgame', 'capturingDefender', 'zugzwang'] }, { n: 3, titulo: 'Damas y torres', temas: ['queenEndgame', 'rookEndgame', 'queenRookEndgame', 'capturingDefender'] }, { n: 4, titulo: 'Cambiar hacia el final', temas: ['pawnEndgame', 'rookEndgame', 'queenEndgame', 'knightEndgame', 'zugzwang'] }, { n: 5, titulo: 'Defenderse con los cambios', temas: ['defensiveMove'] }, { n: 6, titulo: 'Los cambios paradójicos', temas: [] }],
};
window.CAMBIO_O_NO_CAMBIO_ITEMS = [
  {
    n: 1,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 1,
    exige: 'cambio',
    id: 'cc_1v1IS',
    tema: 'capturingDefender',
    lichess: '1v1IS',
    rating: 1332,
    elo: 552,
    juegan: 'w',
    fen: 'r7/ppp2kb1/2n2np1/6B1/2pqp1bQ/2N5/PPP2PPP/R4RK1 w - - 4 14',
    ultima: 'Ag7',
    marca: ['f8', 'g7'],
    solucion: { from: 'g5', to: 'f6' },
    primera: 'Axf6',
    linea: '14.Axf6 Dxf6 15.Dxg4',
    gana: true,
    valor: '+3,7',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 1v1IS de la base abierta de Lichess (CC0), rating 1332. Stockfish 16 a profundidad 18: Axf6 es la mejor (+3,7) y la segunda queda en -0,7.',
  },
  {
    n: 2,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 2,
    exige: 'a-peones',
    id: 'cc_2yN82',
    tema: 'queenEndgame',
    lichess: '2yN82',
    rating: 1362,
    elo: 582,
    juegan: 'w',
    fen: '8/6pk/8/4p2p/3qP3/P1K1Q3/1P6/8 w - - 1 43',
    ultima: 'Dd4+',
    marca: ['d1', 'd4'],
    solucion: { from: 'e3', to: 'd4' },
    primera: 'Dxd4',
    linea: '43.Dxd4 exd4+ 44.Rxd4 h4 45.Re3',
    gana: true,
    valor: '+5,5',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2yN82 de la base abierta de Lichess (CC0), rating 1362. Stockfish 16 a profundidad 18: Dxd4 es la mejor (+5,5) y la segunda queda en -43,9.',
  },
  {
    n: 3,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 3,
    exige: 'cambio-m',
    id: 'cc_0R4YX',
    tema: 'capturingDefender',
    lichess: '0R4YX',
    rating: 1615,
    elo: 835,
    juegan: 'b',
    fen: 'rn2r2k/1p1b1ppB/2p5/q3n1B1/p1PR4/2P2N1P/P1Q3P1/2K4R b - - 1 22',
    ultima: 'Td4',
    marca: ['d1', 'd4'],
    solucion: { from: 'e5', to: 'f3' },
    primera: 'Cxf3',
    linea: '22…Cxf3 23.gxf3 Dxg5+',
    gana: true,
    valor: '+4,3',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 0R4YX de la base abierta de Lichess (CC0), rating 1615. Stockfish 16 a profundidad 18: Cxf3 es la mejor (+4,3) y la segunda queda en -2,0.',
  },
  {
    n: 4,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 4,
    exige: 'cambio-tranquila',
    id: 'cc_1QGUe',
    tema: 'quietMove',
    lichess: '1QGUe',
    rating: 1458,
    elo: 678,
    juegan: 'b',
    fen: 'r7/2P2ppk/4b2p/4p3/2B1P2P/5qP1/p1Q2P2/R5K1 b - - 5 38',
    ultima: 'Ac4',
    marca: ['f1', 'c4'],
    solucion: { from: 'e6', to: 'h3' },
    primera: 'Ah3',
    linea: '38…Ah3 39.Af1 Axf1 40.Rxf1 Dh1+ 41.Re2 Dxa1 42.c8=D Txc8',
    gana: true,
    valor: '+4,8',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'En la línea se cambian una pieza menor por otra. Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 1QGUe de la base abierta de Lichess (CC0), rating 1458. Stockfish 16 a profundidad 18: Ah3 es la mejor (+4,8) y la segunda queda en -0,1.',
  },
  {
    n: 5,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 5,
    exige: '',
    id: 'cc_1BALq',
    tema: 'bishopEndgame',
    lichess: '1BALq',
    rating: 1511,
    elo: 731,
    juegan: 'b',
    fen: '8/8/p1p3p1/5p1p/kBp2P1P/2P1KP2/8/8 b - - 7 46',
    ultima: 'Re3',
    marca: ['f2', 'e3'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'a5',
    linea: '46…a5 47.Af8 Rb3 48.Rd4 a4 49.Ae7 a3 50.Axa3 Rxa3',
    gana: true,
    valor: '+3,5',
    cambios: [],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1BALq de la base abierta de Lichess (CC0), rating 1511. Stockfish 16 a profundidad 18: a5 es la mejor (+3,5) y la segunda queda en -4,6.',
  },
  {
    n: 6,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 6,
    exige: 'cambio-m',
    id: 'cc_1hrAx',
    tema: 'knightEndgame',
    lichess: '1hrAx',
    rating: 1311,
    elo: 531,
    juegan: 'w',
    fen: '1n6/1P3kpp/2n1p3/N7/P3P3/2P1K2P/6P1/8 w - - 2 39',
    ultima: 'Cec6',
    marca: ['e5', 'c6'],
    solucion: { from: 'a5', to: 'c6' },
    primera: 'Cxc6',
    linea: '39.Cxc6 Cxc6 40.a5 Re8 41.a6',
    gana: true,
    valor: '+5,1',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra.',
    comprobado: 'Ejercicio 1hrAx de la base abierta de Lichess (CC0), rating 1311. Stockfish 16 a profundidad 18: Cxc6 es la mejor (+5,1) y la segunda queda en -0,6.',
  },
  {
    n: 7,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 7,
    exige: '',
    id: 'cc_3Ny4Q',
    tema: 'bishopEndgame',
    lichess: '3Ny4Q',
    rating: 1485,
    elo: 705,
    juegan: 'w',
    fen: '8/8/P3P1p1/2b5/6k1/3K4/5p2/8 w - - 0 42',
    ultima: 'f2',
    marca: ['f3', 'f2'],
    solucion: { from: 'd3', to: 'e2' },
    primera: 'Re2',
    linea: '42.Re2 Rg3 43.Rf1',
    gana: true,
    valor: '+3,6',
    cambios: [],
    finalDePeones: false,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: '',
    comprobado: 'Ejercicio 3Ny4Q de la base abierta de Lichess (CC0), rating 1485. Stockfish 16 a profundidad 18: Re2 es la mejor (+3,6) y la segunda queda en -36,5.',
  },
  {
    n: 8,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 8,
    exige: 'distinto-color',
    id: 'cc_2gmkP',
    tema: 'bishopEndgame',
    lichess: '2gmkP',
    rating: 1401,
    elo: 621,
    juegan: 'w',
    fen: '5b2/p3k2K/1p4Bp/1P2p2P/2Pp4/3P4/8/8 w - - 2 97',
    ultima: 'Re7',
    marca: ['f7', 'e7'],
    solucion: { from: 'h7', to: 'g8' },
    primera: 'Rg8',
    linea: '97.Rg8 a5 98.bxa6',
    gana: true,
    valor: '+6,1',
    cambios: [],
    finalDePeones: false,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: '',
    comprobado: 'Ejercicio 2gmkP de la base abierta de Lichess (CC0), rating 1401. Stockfish 16 a profundidad 18: Rg8 es la mejor (+6,1) y la segunda queda en +0,2.',
  },
  {
    n: 9,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 9,
    exige: 'cambio-q',
    id: 'cc_2IfUl',
    tema: 'queenEndgame',
    lichess: '2IfUl',
    rating: 1260,
    elo: 480,
    juegan: 'b',
    fen: '2k5/p1p5/2P4p/5Kp1/1P2Q3/2Pqp3/P5PP/8 b - - 1 34',
    ultima: 'De4',
    marca: ['e5', 'e4'],
    solucion: { from: 'd3', to: 'e4' },
    primera: 'Dxe4+',
    linea: '34…Dxe4+ 35.Rxe4 e2',
    gana: true,
    valor: '+5,3',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2IfUl de la base abierta de Lichess (CC0), rating 1260. Stockfish 16 a profundidad 18: Dxe4+ es la mejor (+5,3) y la segunda queda en -3,8.',
  },
  {
    n: 10,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 10,
    exige: 'sin-cambio-damas',
    id: 'cc_2TSGs',
    tema: 'quietMove',
    lichess: '2TSGs',
    rating: 1990,
    elo: 1210,
    juegan: 'w',
    fen: '2r3k1/1p2pp1p/r2p2p1/p1qP4/P1Q5/1P6/1P3PPP/2R2RK1 w - - 5 21',
    ultima: 'Tc8',
    marca: ['f8', 'c8'],
    solucion: { from: 'c4', to: 'f4' },
    primera: 'Df4',
    linea: '21.Df4 Dxc1 22.Txc1',
    gana: true,
    valor: '+4,6',
    cambios: [],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2TSGs de la base abierta de Lichess (CC0), rating 1990. Stockfish 16 a profundidad 18: Df4 es la mejor (+4,6) y la segunda queda en +0,1.',
  },
  {
    n: 11,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 11,
    exige: 'cambio-r',
    id: 'cc_33KTZ',
    tema: 'rookEndgame',
    lichess: '33KTZ',
    rating: 1406,
    elo: 626,
    juegan: 'b',
    fen: '3k4/3R2Rp/4p1p1/8/3P4/2P4P/1rr5/5K2 b - - 9 32',
    ultima: 'Td7+',
    marca: ['e7', 'd7'],
    solucion: { from: 'd8', to: 'c8' },
    primera: 'Rc8',
    linea: '32…Rc8 33.Tc7+ Rb8 34.Tb7+ Txb7 35.Txb7+ Rxb7',
    gana: true,
    valor: '+7,3',
    cambios: ['r', 'r'],
    finalDePeones: false,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres.',
    comprobado: 'Ejercicio 33KTZ de la base abierta de Lichess (CC0), rating 1406. Stockfish 16 a profundidad 18: Rc8 es la mejor (+7,3) y la segunda queda en 0,0.',
  },
  {
    n: 12,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 12,
    exige: 'sin-cambio',
    id: 'cc_1uVdA',
    tema: 'rookEndgame',
    lichess: '1uVdA',
    rating: 2202,
    elo: 1422,
    juegan: 'w',
    fen: '1R5r/2P5/8/8/8/3k4/1p6/3K4 w - - 3 59',
    ultima: 'Rd3',
    marca: ['c3', 'd3'],
    solucion: { from: 'b8', to: 'd8' },
    primera: 'Td8+',
    linea: '59.Td8+ Re3 60.Rc2 b1=D+ 61.Rxb1',
    gana: true,
    valor: '+35,4',
    cambios: [],
    finalDePeones: false,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: '',
    comprobado: 'Ejercicio 1uVdA de la base abierta de Lichess (CC0), rating 2202. Stockfish 16 a profundidad 18: Td8+ es la mejor (+35,4) y la segunda queda en 0,0.',
  },
  {
    n: 13,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 13,
    exige: '',
    id: 'cc_206zZ',
    tema: 'pawnEndgame',
    lichess: '206zZ',
    rating: 1451,
    elo: 671,
    juegan: 'b',
    fen: '8/8/8/p3pk1p/7P/P3KP2/8/8 b - - 0 48',
    ultima: 'a3',
    marca: ['a2', 'a3'],
    solucion: { from: 'a5', to: 'a4' },
    primera: 'a4',
    linea: '48…a4 49.Re2 Rf4 50.Rf2 e4 51.fxe4 Rxe4',
    gana: true,
    valor: '+4,5',
    cambios: [],
    finalDePeones: true,
    pista: 'Sin piezas, cada tiempo cuenta: calcula el final de peones hasta el final.',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 206zZ de la base abierta de Lichess (CC0), rating 1451. Stockfish 16 a profundidad 18: a4 es la mejor (+4,5) y la segunda queda en 0,0.',
  },
  {
    n: 14,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 14,
    exige: 'a-peones',
    id: 'cc_0MfrO',
    tema: 'rookEndgame',
    lichess: '0MfrO',
    rating: 1571,
    elo: 791,
    juegan: 'b',
    fen: '8/8/5R2/7P/6k1/2K5/P1P2pr1/8 b - - 0 54',
    ultima: 'h5',
    marca: ['h4', 'h5'],
    solucion: { from: 'g2', to: 'g3' },
    primera: 'Tg3+',
    linea: '54…Tg3+ 55.Rd4 Tf3 56.Txf3 Rxf3',
    gana: true,
    valor: '+4,8',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 0MfrO de la base abierta de Lichess (CC0), rating 1571. Stockfish 16 a profundidad 18: Tg3+ es la mejor (+4,8) y la segunda queda en +0,0.',
  },
  {
    n: 15,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 15,
    exige: 'cambio',
    id: 'cc_3MyjL',
    tema: 'advancedPawn',
    lichess: '3MyjL',
    rating: 1298,
    elo: 518,
    juegan: 'w',
    fen: '8/3p1RP1/p1b1p3/1pP5/6rk/P3K3/8/8 w - - 3 46',
    ultima: 'Rh4',
    marca: ['g3', 'h4'],
    solucion: { from: 'f7', to: 'f4' },
    primera: 'Tf4',
    linea: '46.Tf4 e5 47.Txg4+ Rxg4 48.g8=D+',
    gana: true,
    valor: '+4,8',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'El peón avanzado vale más que su punto: ¿qué pieza le estorba la coronación?',
    explica: 'En la línea se cambian las torres. Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 3MyjL de la base abierta de Lichess (CC0), rating 1298. Stockfish 16 a profundidad 18: Tf4 es la mejor (+4,8) y la segunda queda en -6,0.',
  },
  {
    n: 16,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 16,
    exige: 'a-peones',
    id: 'cc_1lEBF',
    tema: 'queenEndgame',
    lichess: '1lEBF',
    rating: 1489,
    elo: 709,
    juegan: 'b',
    fen: '8/6p1/1p3k1p/2q5/4QP1P/7K/6P1/8 b - - 3 51',
    ultima: 'De4',
    marca: ['b7', 'e4'],
    solucion: { from: 'c5', to: 'f5' },
    primera: 'Df5+',
    linea: '51…Df5+ 52.Dxf5+ Rxf5',
    gana: true,
    valor: '+5,7',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 1lEBF de la base abierta de Lichess (CC0), rating 1489. Stockfish 16 a profundidad 18: Df5+ es la mejor (+5,7) y la segunda queda en +0,3.',
  },
  {
    n: 17,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 17,
    exige: 'cambio',
    id: 'cc_35DZy',
    tema: 'defensiveMove',
    lichess: '35DZy',
    rating: 1554,
    elo: 774,
    juegan: 'b',
    fen: 'r3k2r/1pp1n1pp/p1p2p2/4p2Q/1b1qP3/1PNP4/PBP2PPP/R3R1K1 b kq - 2 12',
    ultima: 'Dh5+',
    marca: ['f3', 'h5'],
    solucion: { from: 'g7', to: 'g6' },
    primera: 'g6',
    linea: '12…g6 13.Dh6 Axc3 14.Axc3 Dxc3',
    gana: true,
    valor: '+3,8',
    cambios: ['m', 'm'],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'En la línea se cambian una pieza menor por otra. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 35DZy de la base abierta de Lichess (CC0), rating 1554. Stockfish 16 a profundidad 18: g6 es la mejor (+3,8) y la segunda queda en +0,2.',
  },
  {
    n: 18,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 18,
    exige: 'cambio-pesada',
    id: 'cc_0Twlj',
    tema: 'defensiveMove',
    lichess: '0Twlj',
    rating: 1307,
    elo: 527,
    juegan: 'b',
    fen: '5R2/8/p1p2kp1/3p4/3P1r2/P1P2p2/BP6/2K5 b - - 3 39',
    ultima: 'Tf8+',
    marca: ['b8', 'f8'],
    solucion: { from: 'f6', to: 'g5' },
    primera: 'Rg5',
    linea: '39…Rg5 40.Txf4 Rxf4 41.Rd2 Rg3',
    gana: true,
    valor: '+3,3',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'En la línea se cambian las torres. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0Twlj de la base abierta de Lichess (CC0), rating 1307. Stockfish 16 a profundidad 18: Rg5 es la mejor (+3,3) y la segunda queda en -6,6.',
  },
  {
    n: 19,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 19,
    exige: 'sin-cambio',
    id: 'cc_1hdjX',
    tema: 'defensiveMove',
    lichess: '1hdjX',
    rating: 1955,
    elo: 1175,
    juegan: 'b',
    fen: '5k2/7P/p3N1R1/5p2/2b2P2/3p2P1/7r/3K4 b - - 1 47',
    ultima: 'Ce6+',
    marca: ['g5', 'e6'],
    solucion: { from: 'f8', to: 'f7' },
    primera: 'Rf7',
    linea: '47…Rf7 48.h8=C+ Txh8',
    gana: true,
    valor: '+5,4',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1hdjX de la base abierta de Lichess (CC0), rating 1955. Stockfish 16 a profundidad 18: Rf7 es la mejor (+5,4) y la segunda queda en +0,1.',
  },
  {
    n: 20,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 20,
    exige: '',
    id: 'cc_0aIwq',
    tema: 'trappedPiece',
    lichess: '0aIwq',
    rating: 1493,
    elo: 713,
    juegan: 'w',
    fen: 'r4rk1/pp2npb1/3p1qp1/4pP1p/4P3/2PB2QP/PP4P1/RNB3K1 w - - 4 17',
    ultima: 'Ce7',
    marca: ['c6', 'e7'],
    solucion: { from: 'c1', to: 'g5' },
    primera: 'Ag5',
    linea: '17.Ag5 Dxg5 18.Dxg5',
    gana: true,
    valor: '+5,2',
    cambios: [],
    finalDePeones: false,
    pista: 'Una pieza sin casillas vale menos que su valor. ¿Cuál está atrapada?',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 0aIwq de la base abierta de Lichess (CC0), rating 1493. Stockfish 16 a profundidad 18: Ag5 es la mejor (+5,2) y la segunda queda en -1,7.',
  },
  {
    n: 21,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 21,
    exige: 'cambio',
    id: 'cc_2uMUi',
    tema: 'capturingDefender',
    lichess: '2uMUi',
    rating: 1473,
    elo: 693,
    juegan: 'w',
    fen: '5rk1/2Rr2p1/p5np/4pq2/8/5P2/2Q3PP/5RK1 w - - 0 31',
    ultima: 'Txd7',
    marca: ['d4', 'd7'],
    solucion: { from: 'c2', to: 'f5' },
    primera: 'Dxf5',
    linea: '31.Dxf5 Txf5 32.Txd7',
    gana: true,
    valor: '+3,0',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian las damas. Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2uMUi de la base abierta de Lichess (CC0), rating 1473. Stockfish 16 a profundidad 18: Dxf5 es la mejor (+3,0) y la segunda queda en -5,2.',
  },
  {
    n: 22,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 22,
    exige: 'sin-cambio',
    id: 'cc_0ZRCk',
    tema: 'quietMove',
    lichess: '0ZRCk',
    rating: 1853,
    elo: 1073,
    juegan: 'b',
    fen: '1r3rk1/5ppp/1RQ5/4p3/8/2P1B3/1P2qPPP/2K4R b - - 4 22',
    ultima: 'Tb6',
    marca: ['a6', 'b6'],
    solucion: { from: 'b8', to: 'a8' },
    primera: 'Ta8',
    linea: '22…Ta8 23.De4 Ta1+ 24.Db1 Txb1+',
    gana: true,
    valor: '+3,6',
    cambios: [],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0ZRCk de la base abierta de Lichess (CC0), rating 1853. Stockfish 16 a profundidad 18: Ta8 es la mejor (+3,6) y la segunda queda en -4,2.',
  },
  {
    n: 23,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 23,
    exige: 'cambio-pesada',
    id: 'cc_1K1Fv',
    tema: 'advancedPawn',
    lichess: '1K1Fv',
    rating: 1318,
    elo: 538,
    juegan: 'b',
    fen: '8/8/3R3p/p5p1/3R2P1/8/3rp1KP/3k4 b - - 7 59',
    ultima: 'Ted4',
    marca: ['e4', 'd4'],
    solucion: { from: 'e2', to: 'e1', promotion: 'q' },
    primera: 'e1=D+',
    linea: '59…e1=D+ 60.Txd2+ Dxd2+ 61.Txd2+ Rxd2',
    gana: true,
    valor: '+6,9',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'El peón avanzado vale más que su punto: ¿qué pieza le estorba la coronación?',
    explica: 'En la línea se cambian las torres, y queda un final de peones. Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1K1Fv de la base abierta de Lichess (CC0), rating 1318. Stockfish 16 a profundidad 18: e1=D+ es la mejor (+6,9) y la segunda queda en -0,8.',
  },
  {
    n: 24,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_1WbrB',
    tema: 'capturingDefender',
    lichess: '1WbrB',
    rating: 1371,
    elo: 591,
    juegan: 'b',
    fen: 'r2q1rk1/1p2ppbp/2p1b1p1/4N2n/p1BP4/P1P4P/1P1Q1PPB/R3R1K1 b - - 2 23',
    ultima: 'Ac4',
    marca: ['f1', 'c4'],
    solucion: { from: 'g7', to: 'e5' },
    primera: 'Axe5',
    linea: '23…Axe5 24.Txe5 Axc4',
    gana: true,
    valor: '+3,9',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 1WbrB de la base abierta de Lichess (CC0), rating 1371. Stockfish 16 a profundidad 18: Axe5 es la mejor (+3,9) y la segunda queda en -0,4.',
  },
  {
    n: 25,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_0bU2x',
    tema: 'queenEndgame',
    lichess: '0bU2x',
    rating: 1451,
    elo: 671,
    juegan: 'w',
    fen: '8/5pk1/5qp1/7p/3Q3P/5PK1/6P1/8 w - - 11 46',
    ultima: 'Df6',
    marca: ['e6', 'f6'],
    solucion: { from: 'd4', to: 'f6' },
    primera: 'Dxf6+',
    linea: '46.Dxf6+ Rxf6 47.Rf4 Re6 48.Rg5',
    gana: true,
    valor: '+4,8',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0bU2x de la base abierta de Lichess (CC0), rating 1451. Stockfish 16 a profundidad 18: Dxf6+ es la mejor (+4,8) y la segunda queda en 0,0.',
  },
  {
    n: 26,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_1RsiF',
    tema: 'quietMove',
    lichess: '1RsiF',
    rating: 1630,
    elo: 850,
    juegan: 'b',
    fen: 'r1r3k1/5ppp/p3p3/1p6/8/1R2B3/1P3PPP/2R3K1 b - - 2 21',
    ultima: 'Tc1',
    marca: ['f1', 'c1'],
    solucion: { from: 'c8', to: 'c1' },
    primera: 'Txc1+',
    linea: '21…Txc1+ 22.Axc1 Td8 23.h4 Td1+ 24.Rh2 Txc1',
    gana: true,
    valor: '+3,5',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'En la línea se cambian las torres. Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1RsiF de la base abierta de Lichess (CC0), rating 1630. Stockfish 16 a profundidad 18: Txc1+ es la mejor (+3,5) y la segunda queda en -3,4.',
  },
  {
    n: 27,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_2RaPd',
    tema: 'capturingDefender',
    lichess: '2RaPd',
    rating: 1698,
    elo: 918,
    juegan: 'b',
    fen: '5rk1/1b2q1pp/p2pp1r1/1p6/7R/P3QN2/1P2BPPP/5R1K b - - 9 27',
    ultima: 'Rh1',
    marca: ['g1', 'h1'],
    solucion: { from: 'b7', to: 'f3' },
    primera: 'Axf3',
    linea: '27…Axf3 28.Axf3 Dxh4',
    gana: true,
    valor: '+3,6',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 2RaPd de la base abierta de Lichess (CC0), rating 1698. Stockfish 16 a profundidad 18: Axf3 es la mejor (+3,6) y la segunda queda en -0,3.',
  },
  {
    n: 28,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_31r9u',
    tema: 'quietMove',
    lichess: '31r9u',
    rating: 1911,
    elo: 1131,
    juegan: 'w',
    fen: '2k5/bpp2rp1/p3p2p/1P2p3/P2P2nq/2P1B1nN/2N1Q1PP/5R1K w - - 4 25',
    ultima: 'Cg3+',
    marca: ['f5', 'g3'],
    solucion: { from: 'h2', to: 'g3' },
    primera: 'hxg3',
    linea: '25.hxg3 Dxg3 26.Ag1 Txf1 27.Dxf1',
    gana: true,
    valor: '+3,0',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'En la línea se cambian las torres.',
    comprobado: 'Ejercicio 31r9u de la base abierta de Lichess (CC0), rating 1911. Stockfish 16 a profundidad 18: hxg3 es la mejor (+3,0) y la segunda queda en recibe mate en 4.',
  },
  {
    n: 29,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_1eY42',
    tema: 'queenEndgame',
    lichess: '1eY42',
    rating: 2011,
    elo: 1231,
    juegan: 'b',
    fen: '6Q1/7p/5k2/6p1/1p2qP2/6PK/7P/8 b - - 2 42',
    ultima: 'Rh3',
    marca: ['g2', 'h3'],
    solucion: { from: 'e4', to: 'e6' },
    primera: 'De6+',
    linea: '42…De6+ 43.Dxe6+ Rxe6',
    gana: true,
    valor: '+4,9',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 1eY42 de la base abierta de Lichess (CC0), rating 2011. Stockfish 16 a profundidad 18: De6+ es la mejor (+4,9) y la segunda queda en +1,0.',
  },
  {
    n: 30,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_315pu',
    tema: 'capturingDefender',
    lichess: '315pu',
    rating: 2050,
    elo: 1270,
    juegan: 'b',
    fen: 'r2qk2r/ppp2ppp/5n2/4N3/1b1nP1b1/2N5/PPP1BPPP/R1BQ1RK1 b kq - 0 9',
    ultima: 'Cxe5',
    marca: ['f3', 'e5'],
    solucion: { from: 'd4', to: 'e2' },
    primera: 'Cxe2+',
    linea: '9…Cxe2+ 10.Cxe2 Dxd1 11.Txd1 Axe2',
    gana: true,
    valor: '+4,3',
    cambios: ['m', 'q'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra y las damas. Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 315pu de la base abierta de Lichess (CC0), rating 2050. Stockfish 16 a profundidad 18: Cxe2+ es la mejor (+4,3) y la segunda queda en -1,4.',
  },
  {
    n: 31,
    uso: 'ejercicio',
    capitulo: 1,
    exige: 'cambio',
    id: 'cc_2i6yb',
    tema: 'quietMove',
    lichess: '2i6yb',
    rating: 2265,
    elo: 1485,
    juegan: 'b',
    fen: '3r2k1/1p1q3p/6p1/3Q1p2/2P5/1P2P2P/P2p1PP1/5RK1 b - - 1 31',
    ultima: 'Dd5+',
    marca: ['e5', 'd5'],
    solucion: { from: 'd7', to: 'd5' },
    primera: 'Dxd5',
    linea: '31…Dxd5 32.cxd5 Tc8 33.Td1 Tc1 34.Rf1 Txd1+',
    gana: true,
    valor: '+5,0',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'En la línea se cambian las damas. Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 2i6yb de la base abierta de Lichess (CC0), rating 2265. Stockfish 16 a profundidad 18: Dxd5 es la mejor (+5,0) y la segunda queda en -4,5.',
  },
  {
    n: 32,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_2p2Sn',
    tema: 'bishopEndgame',
    lichess: '2p2Sn',
    rating: 1400,
    elo: 620,
    juegan: 'b',
    fen: '4b3/8/2B2kpp/1pK1pp2/1P6/2P2P2/6PP/8 b - - 3 36',
    ultima: 'Ac6',
    marca: ['d5', 'c6'],
    solucion: { from: 'e8', to: 'c6' },
    primera: 'Axc6',
    linea: '36…Axc6 37.Rxc6 e4 38.Rxb5 e3',
    gana: true,
    valor: '+4,0',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones.',
    comprobado: 'Ejercicio 2p2Sn de la base abierta de Lichess (CC0), rating 1400. Stockfish 16 a profundidad 18: Axc6 es la mejor (+4,0) y la segunda queda en -4,7.',
  },
  {
    n: 33,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_3RdkP',
    tema: 'capturingDefender',
    lichess: '3RdkP',
    rating: 1433,
    elo: 653,
    juegan: 'w',
    fen: '8/2p2k1p/4br2/2N5/3pR1nP/3P2P1/1PP5/6K1 w - - 5 33',
    ultima: 'Rf7',
    marca: ['e7', 'f7'],
    solucion: { from: 'c5', to: 'e6' },
    primera: 'Cxe6',
    linea: '33.Cxe6 Txe6 34.Txg4',
    gana: true,
    valor: '+3,4',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 3RdkP de la base abierta de Lichess (CC0), rating 1433. Stockfish 16 a profundidad 18: Cxe6 es la mejor (+3,4) y la segunda queda en -1,0.',
  },
  {
    n: 34,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_3H3ht',
    tema: 'knightEndgame',
    lichess: '3H3ht',
    rating: 1583,
    elo: 803,
    juegan: 'b',
    fen: '8/5p1p/5p2/1pN5/nP2kPP1/7P/3K4/8 b - - 2 44',
    ultima: 'Cc5+',
    marca: ['d3', 'c5'],
    solucion: { from: 'a4', to: 'c5' },
    primera: 'Cxc5',
    linea: '44…Cxc5 45.bxc5 Rd5 46.Rc3 Rxc5',
    gana: true,
    valor: '+4,5',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones.',
    comprobado: 'Ejercicio 3H3ht de la base abierta de Lichess (CC0), rating 1583. Stockfish 16 a profundidad 18: Cxc5 es la mejor (+4,5) y la segunda queda en 0,0.',
  },
  {
    n: 35,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_1LVSA',
    tema: 'bishopEndgame',
    lichess: '1LVSA',
    rating: 1656,
    elo: 876,
    juegan: 'b',
    fen: '8/3b1p2/3k4/pB1p4/P2K1P2/2P5/8/8 b - - 2 38',
    ultima: 'Ab5',
    marca: ['d3', 'b5'],
    solucion: { from: 'd7', to: 'b5' },
    primera: 'Axb5',
    linea: '38…Axb5 39.axb5 a4 40.c4 a3',
    gana: true,
    valor: '+4,0',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones.',
    comprobado: 'Ejercicio 1LVSA de la base abierta de Lichess (CC0), rating 1656. Stockfish 16 a profundidad 18: Axb5 es la mejor (+4,0) y la segunda queda en 0,0.',
  },
  {
    n: 36,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_35oOW',
    tema: 'capturingDefender',
    lichess: '35oOW',
    rating: 1807,
    elo: 1027,
    juegan: 'w',
    fen: 'r4rk1/pppb2pp/1q2pn2/5nB1/8/P1NB2QP/1PP5/2KR3R w - - 0 16',
    ultima: 'Cxf5',
    marca: ['d4', 'f5'],
    solucion: { from: 'd3', to: 'f5' },
    primera: 'Axf5',
    linea: '16.Axf5 exf5 17.Axf6 Dxf6 18.Txd7',
    gana: true,
    valor: '+3,4',
    cambios: ['m', 'm'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 35oOW de la base abierta de Lichess (CC0), rating 1807. Stockfish 16 a profundidad 18: Axf5 es la mejor (+3,4) y la segunda queda en -0,7.',
  },
  {
    n: 37,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_1yeYl',
    tema: 'knightEndgame',
    lichess: '1yeYl',
    rating: 2030,
    elo: 1250,
    juegan: 'w',
    fen: '8/4p3/3p4/2p1P2p/2P2Pp1/1nk1K1P1/3N4/8 w - - 0 58',
    ultima: 'Cxb3',
    marca: ['d4', 'b3'],
    solucion: { from: 'd2', to: 'b3' },
    primera: 'Cxb3',
    linea: '58.Cxb3 Rxb3 59.exd6 exd6 60.f5',
    gana: true,
    valor: '+3,9',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1yeYl de la base abierta de Lichess (CC0), rating 2030. Stockfish 16 a profundidad 18: Cxb3 es la mejor (+3,9) y la segunda queda en +0,1.',
  },
  {
    n: 38,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_2FGkN',
    tema: 'bishopEndgame',
    lichess: '2FGkN',
    rating: 2050,
    elo: 1270,
    juegan: 'w',
    fen: '8/2p5/p6p/1p2k1p1/1Pb1P3/2P1K1P1/4B2P/8 w - - 5 36',
    ultima: 'Ac4',
    marca: ['e6', 'c4'],
    solucion: { from: 'e2', to: 'c4' },
    primera: 'Axc4',
    linea: '36.Axc4 bxc4 37.g4 Rf6 38.Rd4',
    gana: true,
    valor: '+3,7',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2FGkN de la base abierta de Lichess (CC0), rating 2050. Stockfish 16 a profundidad 18: Axc4 es la mejor (+3,7) y la segunda queda en +0,1.',
  },
  {
    n: 39,
    uso: 'ejercicio',
    capitulo: 2,
    exige: 'cambio-m',
    id: 'cc_2GboY',
    tema: 'knightEndgame',
    lichess: '2GboY',
    rating: 2119,
    elo: 1339,
    juegan: 'b',
    fen: '8/8/4nkp1/6Np/5P1P/6K1/8/8 b - - 3 53',
    ultima: 'Cg5',
    marca: ['f3', 'g5'],
    solucion: { from: 'e6', to: 'g5' },
    primera: 'Cxg5',
    linea: '53…Cxg5 54.fxg5+ Re5 55.Rf3 Rf5',
    gana: true,
    valor: '+6,7',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2GboY de la base abierta de Lichess (CC0), rating 2119. Stockfish 16 a profundidad 18: Cxg5 es la mejor (+6,7) y la segunda queda en +0,1.',
  },
  {
    n: 40,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_18e8b',
    tema: 'queenEndgame',
    lichess: '18e8b',
    rating: 1444,
    elo: 664,
    juegan: 'b',
    fen: '8/8/6Q1/1p3p1p/1P1k3P/6PK/4q3/8 b - - 6 64',
    ultima: 'Rh3',
    marca: ['g2', 'h3'],
    solucion: { from: 'e2', to: 'g4' },
    primera: 'Dg4+',
    linea: '64…Dg4+ 65.Dxg4+ fxg4+',
    gana: true,
    valor: '+6,8',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 18e8b de la base abierta de Lichess (CC0), rating 1444. Stockfish 16 a profundidad 18: Dg4+ es la mejor (+6,8) y la segunda queda en +0,7.',
  },
  {
    n: 41,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_2BKxG',
    tema: 'rookEndgame',
    lichess: '2BKxG',
    rating: 1448,
    elo: 668,
    juegan: 'w',
    fen: '8/6P1/5K2/2k5/1p3R2/8/8/6r1 w - - 0 67',
    ultima: 'b4',
    marca: ['b5', 'b4'],
    solucion: { from: 'f4', to: 'f5' },
    primera: 'Tf5+',
    linea: '67.Tf5+ Rc4 68.Tg5 Txg5 69.Rxg5',
    gana: true,
    valor: '+7,0',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 2BKxG de la base abierta de Lichess (CC0), rating 1448. Stockfish 16 a profundidad 18: Tf5+ es la mejor (+7,0) y la segunda queda en 0,0.',
  },
  {
    n: 42,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_2TiYL',
    tema: 'queenRookEndgame',
    lichess: '2TiYL',
    rating: 1502,
    elo: 722,
    juegan: 'b',
    fen: '8/5pk1/6p1/2Q4p/2P1r3/1P1p3P/P5P1/6K1 b - - 0 33',
    ultima: 'Dxc5',
    marca: ['b6', 'c5'],
    solucion: { from: 'd3', to: 'd2' },
    primera: 'd2',
    linea: '33…d2 34.Dd5 Te1+ 35.Rf2 d1=D 36.Dxd1 Txd1',
    gana: true,
    valor: '+4,5',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Hay damas y torres: decide cuál de ellas te sobra y cuál te hace falta.',
    explica: 'En la línea se cambian las damas. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2TiYL de la base abierta de Lichess (CC0), rating 1502. Stockfish 16 a profundidad 18: d2 es la mejor (+4,5) y la segunda queda en -5,4.',
  },
  {
    n: 43,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_1l9zO',
    tema: 'rookEndgame',
    lichess: '1l9zO',
    rating: 1761,
    elo: 981,
    juegan: 'b',
    fen: '8/8/2r2R2/2k3P1/p7/8/6K1/8 b - - 0 45',
    ultima: 'Txf6',
    marca: ['f2', 'f6'],
    solucion: { from: 'c6', to: 'f6' },
    primera: 'Txf6',
    linea: '45…Txf6 46.gxf6 Rd6 47.f7 Re7 48.f8=T Rxf8',
    gana: true,
    valor: '+35,8',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 1l9zO de la base abierta de Lichess (CC0), rating 1761. Stockfish 16 a profundidad 18: Txf6 es la mejor (+35,8) y la segunda queda en +0,1.',
  },
  {
    n: 44,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_2uT1Z',
    tema: 'queenRookEndgame',
    lichess: '2uT1Z',
    rating: 1825,
    elo: 1045,
    juegan: 'w',
    fen: '7k/1p4p1/2p1P2p/8/2qP4/7P/6P1/5R1K w - - 1 46',
    ultima: 'Dc4',
    marca: ['c3', 'c4'],
    solucion: { from: 'f1', to: 'f8' },
    primera: 'Tf8+',
    linea: '46.Tf8+ Rh7 47.e7 De2 48.e8=D Dxe8 49.Txe8',
    gana: true,
    valor: '+4,3',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Hay damas y torres: decide cuál de ellas te sobra y cuál te hace falta.',
    explica: 'En la línea se cambian las damas. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2uT1Z de la base abierta de Lichess (CC0), rating 1825. Stockfish 16 a profundidad 18: Tf8+ es la mejor (+4,3) y la segunda queda en -4,5.',
  },
  {
    n: 45,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_2tTRW',
    tema: 'queenEndgame',
    lichess: '2tTRW',
    rating: 1831,
    elo: 1051,
    juegan: 'w',
    fen: '3Q4/pp6/2p4p/2kpP1p1/3q2P1/6KP/P7/8 w - - 7 56',
    ultima: 'Rc5',
    marca: ['b6', 'c5'],
    solucion: { from: 'd8', to: 'a5' },
    primera: 'Da5+',
    linea: '56.Da5+ Rc4 57.Da4+ Rc3 58.Dxd4+ Rxd4 59.e6',
    gana: true,
    valor: '+4,2',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 2tTRW de la base abierta de Lichess (CC0), rating 1831. Stockfish 16 a profundidad 18: Da5+ es la mejor (+4,2) y la segunda queda en -0,2.',
  },
  {
    n: 46,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_0q5Iq',
    tema: 'queenEndgame',
    lichess: '0q5Iq',
    rating: 2143,
    elo: 1363,
    juegan: 'b',
    fen: '8/4k1p1/1p3q2/p3Q3/P2P4/5P2/8/5K2 b - - 2 45',
    ultima: 'De5+',
    marca: ['d5', 'e5'],
    solucion: { from: 'f6', to: 'e5' },
    primera: 'Dxe5',
    linea: '45…Dxe5 46.dxe5 g5 47.Rf2 Re6',
    gana: true,
    valor: '+5,1',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 0q5Iq de la base abierta de Lichess (CC0), rating 2143. Stockfish 16 a profundidad 18: Dxe5 es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 47,
    uso: 'ejercicio',
    capitulo: 3,
    exige: 'cambio-pesada',
    id: 'cc_2grUm',
    tema: 'rookEndgame',
    lichess: '2grUm',
    rating: 2155,
    elo: 1375,
    juegan: 'w',
    fen: '8/5k2/1p3p2/1P2rR2/P1p5/2K5/8/8 w - - 2 45',
    ultima: 'Te5',
    marca: ['e4', 'e5'],
    solucion: { from: 'f5', to: 'e5' },
    primera: 'Txe5',
    linea: '45.Txe5 fxe5 46.a5 bxa5 47.b6',
    gana: true,
    valor: '+5,3',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 2grUm de la base abierta de Lichess (CC0), rating 2155. Stockfish 16 a profundidad 18: Txe5 es la mejor (+5,3) y la segunda queda en 0,0.',
  },
  {
    n: 48,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_2zDZZ',
    tema: 'queenEndgame',
    lichess: '2zDZZ',
    rating: 1388,
    elo: 608,
    juegan: 'b',
    fen: '8/8/8/1qk5/p6K/6P1/3Q4/8 b - - 25 74',
    ultima: 'Rh4',
    marca: ['g4', 'h4'],
    solucion: { from: 'b5', to: 'b4' },
    primera: 'Db4+',
    linea: '74…Db4+ 75.Dxb4+ Rxb4',
    gana: true,
    valor: '+7,4',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 2zDZZ de la base abierta de Lichess (CC0), rating 1388. Stockfish 16 a profundidad 18: Db4+ es la mejor (+7,4) y la segunda queda en 0,0.',
  },
  {
    n: 49,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_2Sd25',
    tema: 'rookEndgame',
    lichess: '2Sd25',
    rating: 1441,
    elo: 661,
    juegan: 'b',
    fen: '8/1p6/2p1k1r1/pPP5/P1P2KR1/8/8/8 b - - 0 41',
    ultima: 'Txg4',
    marca: ['g3', 'g4'],
    solucion: { from: 'g6', to: 'g4' },
    primera: 'Txg4+',
    linea: '41…Txg4+ 42.Rxg4 Re5 43.Rg5 Rd4',
    gana: true,
    valor: '+6,2',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 2Sd25 de la base abierta de Lichess (CC0), rating 1441. Stockfish 16 a profundidad 18: Txg4+ es la mejor (+6,2) y la segunda queda en -0,1.',
  },
  {
    n: 50,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_05n4L',
    tema: 'pawnEndgame',
    lichess: '05n4L',
    rating: 1629,
    elo: 849,
    juegan: 'b',
    fen: '8/8/5k1p/p3P2P/3K4/8/8/8 b - - 0 41',
    ultima: 'e5+',
    marca: ['e4', 'e5'],
    solucion: { from: 'f6', to: 'e6' },
    primera: 'Re6',
    linea: '41…Re6 42.Re4 a4 43.Rd4 a3 44.Rc3 Rxe5',
    gana: true,
    valor: '+7,4',
    cambios: [],
    finalDePeones: true,
    pista: 'Sin piezas, cada tiempo cuenta: calcula el final de peones hasta el final.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 05n4L de la base abierta de Lichess (CC0), rating 1629. Stockfish 16 a profundidad 18: Re6 es la mejor (+7,4) y la segunda queda en +0,1.',
  },
  {
    n: 51,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_1Ws47',
    tema: 'rookEndgame',
    lichess: '1Ws47',
    rating: 1859,
    elo: 1079,
    juegan: 'b',
    fen: '8/5p2/3k4/4r3/3p1PP1/8/5K2/4R3 b - - 0 49',
    ultima: 'f4',
    marca: ['f3', 'f4'],
    solucion: { from: 'e5', to: 'e1' },
    primera: 'Txe1',
    linea: '49…Txe1 50.Rxe1 Rd5 51.Re2 Re4 52.f5 Rf4 53.f6 Rxg4',
    gana: true,
    valor: '+6,9',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones.',
    comprobado: 'Ejercicio 1Ws47 de la base abierta de Lichess (CC0), rating 1859. Stockfish 16 a profundidad 18: Txe1 es la mejor (+6,9) y la segunda queda en 0,0.',
  },
  {
    n: 52,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_2lc0y',
    tema: 'queenEndgame',
    lichess: '2lc0y',
    rating: 1890,
    elo: 1110,
    juegan: 'w',
    fen: '5q2/p7/1pK3pk/2p1Q2p/P6P/2P3P1/8/8 w - - 3 50',
    ultima: 'Df8',
    marca: ['f7', 'f8'],
    solucion: { from: 'e5', to: 'f4' },
    primera: 'Df4+',
    linea: '50.Df4+ Dxf4 51.gxf4',
    gana: true,
    valor: '+4,1',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 2lc0y de la base abierta de Lichess (CC0), rating 1890. Stockfish 16 a profundidad 18: Df4+ es la mejor (+4,1) y la segunda queda en +0,3.',
  },
  {
    n: 53,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_3A4dt',
    tema: 'pawnEndgame',
    lichess: '3A4dt',
    rating: 1969,
    elo: 1189,
    juegan: 'w',
    fen: '8/8/8/2kPp1pp/1p2Pp2/5P1P/1K3P2/8 w - - 4 46',
    ultima: 'Rc5',
    marca: ['b5', 'c5'],
    solucion: { from: 'b2', to: 'b3' },
    primera: 'Rb3',
    linea: '46.Rb3 Rb5 47.d6 Rc6 48.Rxb4 Rxd6 49.Rb5',
    gana: true,
    valor: '+4,1',
    cambios: [],
    finalDePeones: true,
    pista: 'Sin piezas, cada tiempo cuenta: calcula el final de peones hasta el final.',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 3A4dt de la base abierta de Lichess (CC0), rating 1969. Stockfish 16 a profundidad 18: Rb3 es la mejor (+4,1) y la segunda queda en +0,4.',
  },
  {
    n: 54,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_1FblW',
    tema: 'rookEndgame',
    lichess: '1FblW',
    rating: 2056,
    elo: 1276,
    juegan: 'w',
    fen: '4R3/8/rk2p3/3p4/8/2P1P3/3K4/8 w - - 0 43',
    ultima: 'Txa6',
    marca: ['a1', 'a6'],
    solucion: { from: 'e8', to: 'e6' },
    primera: 'Txe6+',
    linea: '43.Txe6+ Rb5 44.Txa6 Rxa6 45.Rd3 Rb7 46.Rd4 Rc6 47.c4 dxc4 48.Rxc4 Rd6 49.Rd4 Re6 50.Re4',
    gana: true,
    valor: '+6,8',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1FblW de la base abierta de Lichess (CC0), rating 2056. Stockfish 16 a profundidad 18: Txe6+ es la mejor (+6,8) y la segunda queda en 0,0.',
  },
  {
    n: 55,
    uso: 'ejercicio',
    capitulo: 4,
    exige: 'final',
    id: 'cc_35ZSi',
    tema: 'pawnEndgame',
    lichess: '35ZSi',
    rating: 2071,
    elo: 1291,
    juegan: 'b',
    fen: '8/6pp/p3k3/1p3P2/2p1K1P1/P1P5/1P6/8 b - - 0 42',
    ultima: 'f5+',
    marca: ['f4', 'f5'],
    solucion: { from: 'e6', to: 'f6' },
    primera: 'Rf6',
    linea: '42…Rf6 43.Rf4 h6',
    gana: true,
    valor: '+3,2',
    cambios: [],
    finalDePeones: true,
    pista: 'Sin piezas, cada tiempo cuenta: calcula el final de peones hasta el final.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 35ZSi de la base abierta de Lichess (CC0), rating 2071. Stockfish 16 a profundidad 18: Rf6 es la mejor (+3,2) y la segunda queda en +0,0.',
  },
  {
    n: 56,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_2TCPk',
    tema: 'defensiveMove',
    lichess: '2TCPk',
    rating: 1501,
    elo: 721,
    juegan: 'b',
    fen: 'rnqk1b1r/ppp4p/3pNn2/4p3/4P1Q1/8/PPP2PPP/RNB1K2R b KQ - 2 10',
    ultima: 'Ce6+',
    marca: ['g7', 'e6'],
    solucion: { from: 'd8', to: 'e7' },
    primera: 'Re7',
    linea: '10…Re7 11.Ag5 Dxe6',
    gana: true,
    valor: '+3,2',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2TCPk de la base abierta de Lichess (CC0), rating 1501. Stockfish 16 a profundidad 18: Re7 es la mejor (+3,2) y la segunda queda en -2,6.',
  },
  {
    n: 57,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_2Apo2',
    tema: 'defensiveMove',
    lichess: '2Apo2',
    rating: 1586,
    elo: 806,
    juegan: 'w',
    fen: '2kr4/pp2p2Q/2n2p1b/1BP5/4p1b1/2q5/PPP2PPP/1K4NR w - - 0 14',
    ultima: 'Dxc3',
    marca: ['a5', 'c3'],
    solucion: { from: 'b2', to: 'c3' },
    primera: 'bxc3',
    linea: '14.bxc3 Td1+ 15.Rb2 Ac1+ 16.Rb3',
    gana: true,
    valor: '+4,4',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 2Apo2 de la base abierta de Lichess (CC0), rating 1586. Stockfish 16 a profundidad 18: bxc3 es la mejor (+4,4) y la segunda queda en -3,6.',
  },
  {
    n: 58,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_39mSw',
    tema: 'defensiveMove',
    lichess: '39mSw',
    rating: 1632,
    elo: 852,
    juegan: 'b',
    fen: 'r4rk1/1bp1q2p/p3pbNP/1p6/2pP1BQ1/P1P1P3/2P2P2/R3K1R1 b Q - 0 20',
    ultima: 'Cxg6',
    marca: ['e5', 'g6'],
    solucion: { from: 'h7', to: 'g6' },
    primera: 'hxg6',
    linea: '20…hxg6 21.Dxg6+ Rh8',
    gana: false,
    valor: '+1,1',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 39mSw de la base abierta de Lichess (CC0), rating 1632. Stockfish 16 a profundidad 18: hxg6 es la mejor (+1,1) y la segunda queda en -6,2.',
  },
  {
    n: 59,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_0yX3W',
    tema: 'defensiveMove',
    lichess: '0yX3W',
    rating: 1805,
    elo: 1025,
    juegan: 'w',
    fen: '2qr4/p2k4/p1p1pRp1/N2p4/Q2P4/2P1P1b1/PP6/1R1K3r w - - 2 24',
    ultima: 'Th1+',
    marca: ['h2', 'h1'],
    solucion: { from: 'd1', to: 'c2' },
    primera: 'Rc2',
    linea: '24.Rc2 Th2+ 25.Rd3',
    gana: false,
    valor: '+2,7',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0yX3W de la base abierta de Lichess (CC0), rating 1805. Stockfish 16 a profundidad 18: Rc2 es la mejor (+2,7) y la segunda queda en -2,6.',
  },
  {
    n: 60,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_3PoFx',
    tema: 'defensiveMove',
    lichess: '3PoFx',
    rating: 1815,
    elo: 1035,
    juegan: 'w',
    fen: 'r4rk1/p4ppp/b1n2n2/2b5/4pq2/2N3N1/PPPP1PPP/R1BQR1K1 w - - 12 13',
    ultima: 'Df4',
    marca: ['d6', 'f4'],
    solucion: { from: 'd2', to: 'd4' },
    primera: 'd4',
    linea: '13.d4 Dc7 14.dxc5 Tad8 15.Ad2',
    gana: false,
    valor: '+1,9',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 3PoFx de la base abierta de Lichess (CC0), rating 1815. Stockfish 16 a profundidad 18: d4 es la mejor (+1,9) y la segunda queda en -2,2.',
  },
  {
    n: 61,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_2ePct',
    tema: 'defensiveMove',
    lichess: '2ePct',
    rating: 1901,
    elo: 1121,
    juegan: 'w',
    fen: '8/7p/1pb2kp1/1P3p2/8/3P2P1/4PK1P/8 w - - 0 42',
    ultima: 'Axc6',
    marca: ['d5', 'c6'],
    solucion: { from: 'b5', to: 'c6' },
    primera: 'bxc6',
    linea: '42.bxc6 Re6 43.d4 Rd6 44.d5',
    gana: true,
    valor: '+3,4',
    cambios: [],
    finalDePeones: true,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2ePct de la base abierta de Lichess (CC0), rating 1901. Stockfish 16 a profundidad 18: bxc6 es la mejor (+3,4) y la segunda queda en -4,9.',
  },
  {
    n: 62,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_3AzN4',
    tema: 'defensiveMove',
    lichess: '3AzN4',
    rating: 2223,
    elo: 1443,
    juegan: 'b',
    fen: '2r3r1/3k3p/Q1p2p1n/3p4/3N1q2/2P5/PP3P1P/4RR1K b - - 1 23',
    ultima: 'Tae1',
    marca: ['a1', 'e1'],
    solucion: { from: 'h6', to: 'g4' },
    primera: 'Cg4',
    linea: '23…Cg4 24.Db7+ Tc7 25.Dxc7+ Dxc7',
    gana: true,
    valor: '+4,8',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 3AzN4 de la base abierta de Lichess (CC0), rating 2223. Stockfish 16 a profundidad 18: Cg4 es la mejor (+4,8) y la segunda queda en -2,8.',
  },
  {
    n: 63,
    uso: 'ejercicio',
    capitulo: 5,
    exige: '',
    id: 'cc_1FspE',
    tema: 'defensiveMove',
    lichess: '1FspE',
    rating: 2241,
    elo: 1461,
    juegan: 'b',
    fen: '3r1rk1/ppqb2pp/2pb4/5pN1/2P1n3/1P1QB1P1/P1B2P1P/2KR3R b - - 8 19',
    ultima: 'Cg5',
    marca: ['f3', 'g5'],
    solucion: { from: 'd6', to: 'a3' },
    primera: 'Aa3+',
    linea: '19…Aa3+ 20.Rb1 Ac8',
    gana: true,
    valor: '+4,3',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1FspE de la base abierta de Lichess (CC0), rating 2241. Stockfish 16 a profundidad 18: Aa3+ es la mejor (+4,3) y la segunda queda en +0,4.',
  },
  {
    n: 64,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2I24a',
    tema: 'capturingDefender',
    lichess: '2I24a',
    rating: 1296,
    elo: 516,
    juegan: 'w',
    fen: 'r4rk1/ppp1bppp/2n5/2q5/2b2P2/4QN1P/PP1B2P1/2KR1B1R w - - 0 14',
    ultima: 'Axc4',
    marca: ['e6', 'c4'],
    solucion: { from: 'e3', to: 'c5' },
    primera: 'Dxc5',
    linea: '14.Dxc5 Axc5 15.Axc4',
    gana: true,
    valor: '+5,0',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian las damas. Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2I24a de la base abierta de Lichess (CC0), rating 1296. Stockfish 16 a profundidad 18: Dxc5 es la mejor (+5,0) y la segunda queda en -1,5.',
  },
  {
    n: 65,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_3B5Ca',
    tema: 'rookEndgame',
    lichess: '3B5Ca',
    rating: 1328,
    elo: 548,
    juegan: 'b',
    fen: '8/2R5/3p2P1/3k2K1/1r6/7P/2p5/8 b - - 3 55',
    ultima: 'Rg5',
    marca: ['g4', 'g5'],
    solucion: { from: 'b4', to: 'c4' },
    primera: 'Tc4',
    linea: '55…Tc4 56.Txc4 Rxc4 57.g7 c1=D+',
    gana: true,
    valor: '+6,3',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3B5Ca de la base abierta de Lichess (CC0), rating 1328. Stockfish 16 a profundidad 18: Tc4 es la mejor (+6,3) y la segunda queda en -5,0.',
  },
  {
    n: 66,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_3Pmm9',
    tema: 'defensiveMove',
    lichess: '3Pmm9',
    rating: 1395,
    elo: 615,
    juegan: 'w',
    fen: '8/5k1p/2p3p1/3p4/P1p2P2/2NnK1P1/1r2R2P/8 w - - 0 39',
    ultima: 'Txb2',
    marca: ['b8', 'b2'],
    solucion: { from: 'e2', to: 'b2' },
    primera: 'Txb2',
    linea: '39.Txb2 Cxb2 40.a5',
    gana: true,
    valor: '+4,5',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'En la línea se cambian las torres. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 3Pmm9 de la base abierta de Lichess (CC0), rating 1395. Stockfish 16 a profundidad 18: Txb2 es la mejor (+4,5) y la segunda queda en -2,9.',
  },
  {
    n: 67,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_1Us6Z',
    tema: 'queenRookEndgame',
    lichess: '1Us6Z',
    rating: 1413,
    elo: 633,
    juegan: 'w',
    fen: '4Rrk1/1p1P2p1/2pq3p/8/P7/6P1/1P5P/4R2K w - - 3 33',
    ultima: 'Dd6',
    marca: ['g6', 'd6'],
    solucion: { from: 'e8', to: 'f8' },
    primera: 'Txf8+',
    linea: '33.Txf8+ Rxf8 34.Te8+ Rf7 35.d8=D Dxd8 36.Txd8',
    gana: true,
    valor: '+5,8',
    cambios: ['r', 'q'],
    finalDePeones: false,
    pista: 'Hay damas y torres: decide cuál de ellas te sobra y cuál te hace falta.',
    explica: 'En la línea se cambian las torres y las damas. Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1Us6Z de la base abierta de Lichess (CC0), rating 1413. Stockfish 16 a profundidad 18: Txf8+ es la mejor (+5,8) y la segunda queda en 0,0.',
  },
  {
    n: 68,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0kVhB',
    tema: 'knightEndgame',
    lichess: '0kVhB',
    rating: 1430,
    elo: 650,
    juegan: 'b',
    fen: '8/1PK5/2N5/4n3/5k2/8/7p/8 b - - 0 76',
    ultima: 'b7',
    marca: ['b6', 'b7'],
    solucion: { from: 'e5', to: 'c6' },
    primera: 'Cxc6',
    linea: '76…Cxc6 77.Rxc6 h1=D+',
    gana: true,
    valor: '+6,5',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra. Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 0kVhB de la base abierta de Lichess (CC0), rating 1430. Stockfish 16 a profundidad 18: Cxc6 es la mejor (+6,5) y la segunda queda en +0,6.',
  },
  {
    n: 69,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2cpBz',
    tema: 'queenEndgame',
    lichess: '2cpBz',
    rating: 1476,
    elo: 696,
    juegan: 'w',
    fen: '7k/6p1/4q2p/8/P4QPK/8/8/8 w - - 3 57',
    ultima: 'De6',
    marca: ['b3', 'e6'],
    solucion: { from: 'f4', to: 'f8' },
    primera: 'Df8+',
    linea: '57.Df8+ Rh7 58.Df5+ Dxf5 59.gxf5',
    gana: true,
    valor: '+6,7',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones.',
    comprobado: 'Ejercicio 2cpBz de la base abierta de Lichess (CC0), rating 1476. Stockfish 16 a profundidad 18: Df8+ es la mejor (+6,7) y la segunda queda en 0,0.',
  },
  {
    n: 70,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_22hTe',
    tema: 'bishopEndgame',
    lichess: '22hTe',
    rating: 1570,
    elo: 790,
    juegan: 'b',
    fen: '8/8/1pB5/1Pk5/2b1K3/8/8/8 b - - 6 40',
    ultima: 'Re4',
    marca: ['f5', 'e4'],
    solucion: { from: 'c4', to: 'b5' },
    primera: 'Axb5',
    linea: '40…Axb5 41.Ab7 Ac6+ 42.Axc6 Rxc6 43.Rd4 Rb5',
    gana: true,
    valor: '+9,7',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 22hTe de la base abierta de Lichess (CC0), rating 1570. Stockfish 16 a profundidad 18: Axb5 es la mejor (+9,7) y la segunda queda en +0,1.',
  },
  {
    n: 71,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2l9qX',
    tema: 'zugzwang',
    lichess: '2l9qX',
    rating: 1583,
    elo: 803,
    juegan: 'w',
    fen: '8/2B2p2/p2n2p1/1p1k2P1/1P5P/P2K4/8/8 w - - 6 49',
    ultima: 'Cd6',
    marca: ['e4', 'd6'],
    solucion: { from: 'c7', to: 'd6' },
    primera: 'Axd6',
    linea: '49.Axd6 Rxd6 50.Rd4 Re6 51.Rc5 f5 52.gxf6',
    gana: true,
    valor: '+3,8',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Después de los cambios, el que tiene que mover pierde. ¿A quién le toca?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2l9qX de la base abierta de Lichess (CC0), rating 1583. Stockfish 16 a profundidad 18: Axd6 es la mejor (+3,8) y la segunda queda en -2,4.',
  },
  {
    n: 72,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_3FSc7',
    tema: 'zugzwang',
    lichess: '3FSc7',
    rating: 1672,
    elo: 892,
    juegan: 'b',
    fen: '8/p2b4/1p1p2p1/1PpPp2k/P1P1PnN1/5PK1/8/5B2 b - - 11 41',
    ultima: 'Cg4',
    marca: ['e3', 'g4'],
    solucion: { from: 'd7', to: 'g4' },
    primera: 'Axg4',
    linea: '41…Axg4 42.fxg4+ Rg5 43.Rf3 Rh4',
    gana: true,
    valor: '+4,3',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Después de los cambios, el que tiene que mover pierde. ¿A quién le toca?',
    explica: 'En la línea se cambian una pieza menor por otra. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 3FSc7 de la base abierta de Lichess (CC0), rating 1672. Stockfish 16 a profundidad 18: Axg4 es la mejor (+4,3) y la segunda queda en +0,7.',
  },
  {
    n: 73,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_1AGmg',
    tema: 'rookEndgame',
    lichess: '1AGmg',
    rating: 1688,
    elo: 908,
    juegan: 'b',
    fen: '8/8/r1p3k1/8/8/P2K1R2/8/8 b - - 2 42',
    ultima: 'Rd3',
    marca: ['e2', 'd3'],
    solucion: { from: 'a6', to: 'a3' },
    primera: 'Txa3+',
    linea: '42…Txa3+ 43.Re2 Txf3 44.Rxf3 Rf5 45.Re3 Re5 46.Rd3 Rd5 47.Rc3 Rc5',
    gana: true,
    valor: '+7,2',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1AGmg de la base abierta de Lichess (CC0), rating 1688. Stockfish 16 a profundidad 18: Txa3+ es la mejor (+7,2) y la segunda queda en -0,0.',
  },
  {
    n: 74,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_1crNx',
    tema: 'queenEndgame',
    lichess: '1crNx',
    rating: 1698,
    elo: 918,
    juegan: 'w',
    fen: '8/8/1K2k3/1PQ5/5p2/5q2/8/8 w - - 0 56',
    ultima: 'Dxf3',
    marca: ['e3', 'f3'],
    solucion: { from: 'c5', to: 'c6' },
    primera: 'Dc6+',
    linea: '56.Dc6+ Dxc6+ 57.bxc6 f3 58.c7 Rd5 59.c8=D',
    gana: true,
    valor: '+35,2',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1crNx de la base abierta de Lichess (CC0), rating 1698. Stockfish 16 a profundidad 18: Dc6+ es la mejor (+35,2) y la segunda queda en +0,0.',
  },
  {
    n: 75,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0QMZY',
    tema: 'quietMove',
    lichess: '0QMZY',
    rating: 1736,
    elo: 956,
    juegan: 'b',
    fen: '8/1B1b2pp/3k4/pN3p2/Pb6/3P2P1/2P2PKP/8 b - - 2 36',
    ultima: 'Cb5+',
    marca: ['d4', 'b5'],
    solucion: { from: 'd7', to: 'b5' },
    primera: 'Axb5',
    linea: '36…Axb5 37.axb5 a4 38.b6 a3',
    gana: true,
    valor: '+3,9',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'No hay captura que gane ya: busca la jugada tranquila que obliga al cambio que te sirve.',
    explica: 'En la línea se cambian una pieza menor por otra.',
    comprobado: 'Ejercicio 0QMZY de la base abierta de Lichess (CC0), rating 1736. Stockfish 16 a profundidad 18: Axb5 es la mejor (+3,9) y la segunda queda en -0,2.',
  },
  {
    n: 76,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0F6J3',
    tema: 'knightEndgame',
    lichess: '0F6J3',
    rating: 1787,
    elo: 1007,
    juegan: 'w',
    fen: '8/8/2K1nk2/2N2p2/1P6/8/8/8 w - - 2 53',
    ultima: 'Ce6',
    marca: ['f4', 'e6'],
    solucion: { from: 'c5', to: 'e6' },
    primera: 'Cxe6',
    linea: '53.Cxe6 Rxe6 54.b5 f4 55.b6 f3 56.b7 f2 57.b8=D f1=D 58.De8+ Rf6 59.Df8+ Re5 60.Dxf1',
    gana: true,
    valor: '+35,8',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra. Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 0F6J3 de la base abierta de Lichess (CC0), rating 1787. Stockfish 16 a profundidad 18: Cxe6 es la mejor (+35,8) y la segunda queda en +0,0.',
  },
  {
    n: 77,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2koy7',
    tema: 'capturingDefender',
    lichess: '2koy7',
    rating: 1872,
    elo: 1092,
    juegan: 'b',
    fen: '5k2/1b3p2/4pPp1/4P3/1PpPNr1r/5PRp/1P5P/R6K b - - 2 35',
    ultima: 'Ta1',
    marca: ['e1', 'a1'],
    solucion: { from: 'f4', to: 'f3' },
    primera: 'Txf3',
    linea: '35…Txf3 36.Rg1 Axe4 37.Txf3 Axf3',
    gana: true,
    valor: '+3,0',
    cambios: ['r'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian las torres. Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 2koy7 de la base abierta de Lichess (CC0), rating 1872. Stockfish 16 a profundidad 18: Txf3 es la mejor (+3,0) y la segunda queda en -1,8.',
  },
  {
    n: 78,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2HZRa',
    tema: 'advancedPawn',
    lichess: '2HZRa',
    rating: 1914,
    elo: 1134,
    juegan: 'w',
    fen: '2kr2nr/ppp4p/3p2P1/3Pp1q1/3n2p1/3P2Q1/PPP1B1PP/2R2RK1 w - - 1 17',
    ultima: 'Cd4',
    marca: ['c6', 'd4'],
    solucion: { from: 'g3', to: 'g4' },
    primera: 'Dxg4+',
    linea: '17.Dxg4+ Dxg4 18.Axg4+ Rb8 19.g7',
    gana: true,
    valor: '+5,0',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'El peón avanzado vale más que su punto: ¿qué pieza le estorba la coronación?',
    explica: 'En la línea se cambian las damas. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2HZRa de la base abierta de Lichess (CC0), rating 1914. Stockfish 16 a profundidad 18: Dxg4+ es la mejor (+5,0) y la segunda queda en -1,8.',
  },
  {
    n: 79,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0kkd0',
    tema: 'defensiveMove',
    lichess: '0kkd0',
    rating: 2021,
    elo: 1241,
    juegan: 'b',
    fen: '4r1k1/5ppp/R3n1r1/1pB4q/2pPQ2P/2P1pPP1/4P2K/2R5 b - - 0 30',
    ultima: 'Txa6',
    marca: ['a1', 'a6'],
    solucion: { from: 'e6', to: 'c7' },
    primera: 'Cc7',
    linea: '30…Cc7 31.Dxe8+ Cxe8 32.Ta8 Te6',
    gana: false,
    valor: '+2,7',
    cambios: [],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0kkd0 de la base abierta de Lichess (CC0), rating 2021. Stockfish 16 a profundidad 18: Cc7 es la mejor (+2,7) y la segunda queda en 0,0.',
  },
  {
    n: 80,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_3ENFC',
    tema: 'capturingDefender',
    lichess: '3ENFC',
    rating: 2086,
    elo: 1306,
    juegan: 'b',
    fen: '2r3k1/4pp1p/bq1p1bp1/pNrP4/P1PN4/3Q2P1/5PKP/2R2R2 b - - 10 24',
    ultima: 'Cfd4',
    marca: ['f3', 'd4'],
    solucion: { from: 'f6', to: 'd4' },
    primera: 'Axd4',
    linea: '24…Axd4 25.Dxd4 Txb5 26.cxb5 Dxd4',
    gana: true,
    valor: '+4,6',
    cambios: ['m'],
    finalDePeones: false,
    pista: 'Una pieza rival defiende todo. ¿Qué pasa si la cambias?',
    explica: 'En la línea se cambian una pieza menor por otra. Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 3ENFC de la base abierta de Lichess (CC0), rating 2086. Stockfish 16 a profundidad 18: Axd4 es la mejor (+4,6) y la segunda queda en 0,0.',
  },
  {
    n: 81,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0Tru5',
    tema: 'bishopEndgame',
    lichess: '0Tru5',
    rating: 2122,
    elo: 1342,
    juegan: 'w',
    fen: '4B3/8/2b5/pkp5/8/1PK5/P7/8 w - - 10 55',
    ultima: 'Ac6',
    marca: ['d5', 'c6'],
    solucion: { from: 'a2', to: 'a4' },
    primera: 'a4+',
    linea: '55.a4+ Rb6 56.Axc6 Rxc6 57.Rc4 Rd6 58.Rb5 Rd5 59.Rxa5 c4 60.bxc4+',
    gana: true,
    valor: '+6,9',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Mira de qué color son las casillas de los peones y de los alfiles antes de mover.',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0Tru5 de la base abierta de Lichess (CC0), rating 2122. Stockfish 16 a profundidad 18: a4+ es la mejor (+6,9) y la segunda queda en +0,1.',
  },
  {
    n: 82,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0dyJ5',
    tema: 'rookEndgame',
    lichess: '0dyJ5',
    rating: 2133,
    elo: 1353,
    juegan: 'b',
    fen: '6k1/5p2/8/2P3p1/3P4/1KP5/R7/r7 b - - 0 39',
    ultima: 'Txa2',
    marca: ['a6', 'a2'],
    solucion: { from: 'a1', to: 'a2' },
    primera: 'Txa2',
    linea: '39…Txa2 40.Rxa2 Rf8 41.Rb3 g4',
    gana: true,
    valor: '+3,8',
    cambios: ['r'],
    finalDePeones: true,
    pista: 'Antes de cambiar las torres, cuenta el final de peones que queda.',
    explica: 'En la línea se cambian las torres, y queda un final de peones. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0dyJ5 de la base abierta de Lichess (CC0), rating 2133. Stockfish 16 a profundidad 18: Txa2 es la mejor (+3,8) y la segunda queda en -5,2.',
  },
  {
    n: 83,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_0Q03I',
    tema: 'defensiveMove',
    lichess: '0Q03I',
    rating: 2165,
    elo: 1385,
    juegan: 'w',
    fen: '3r1r1k/p1q1n1bp/6p1/1p2pPB1/2pp2P1/2P3NP/PP6/R2Q1R1K w - - 0 25',
    ultima: 'd4',
    marca: ['d5', 'd4'],
    solucion: { from: 'f5', to: 'f6' },
    primera: 'f6',
    linea: '25.f6 Dc6+ 26.Df3 Dxf3+ 27.Txf3',
    gana: false,
    valor: '+1,7',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'En la línea se cambian las damas. Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0Q03I de la base abierta de Lichess (CC0), rating 2165. Stockfish 16 a profundidad 18: f6 es la mejor (+1,7) y la segunda queda en -1,4.',
  },
  {
    n: 84,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_3OKQ7',
    tema: 'queenRookEndgame',
    lichess: '3OKQ7',
    rating: 2213,
    elo: 1433,
    juegan: 'w',
    fen: '8/p2P2kp/1p4p1/8/8/PP1R4/K1P4q/8 w - - 0 49',
    ultima: 'Dxh2',
    marca: ['e5', 'h2'],
    solucion: { from: 'a2', to: 'b1' },
    primera: 'Rb1',
    linea: '49.Rb1 Db8 50.d8=D Dxd8 51.Txd8',
    gana: true,
    valor: '+4,7',
    cambios: ['q'],
    finalDePeones: false,
    pista: 'Hay damas y torres: decide cuál de ellas te sobra y cuál te hace falta.',
    explica: 'En la línea se cambian las damas. El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3OKQ7 de la base abierta de Lichess (CC0), rating 2213. Stockfish 16 a profundidad 18: Rb1 es la mejor (+4,7) y la segunda queda en 0,0.',
  },
  {
    n: 85,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2N28j',
    tema: 'knightEndgame',
    lichess: '2N28j',
    rating: 2257,
    elo: 1477,
    juegan: 'w',
    fen: '8/1k5p/1p2Np2/2p2Pp1/5nP1/P1PK4/8/8 w - - 2 45',
    ultima: 'Cf4+',
    marca: ['d5', 'f4'],
    solucion: { from: 'e6', to: 'f4' },
    primera: 'Cxf4',
    linea: '45.Cxf4 gxf4 46.g5 Rc7 47.g6',
    gana: true,
    valor: '+3,9',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Un caballo menos cambia todo el final: ¿quién gana si se van los caballos?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones.',
    comprobado: 'Ejercicio 2N28j de la base abierta de Lichess (CC0), rating 2257. Stockfish 16 a profundidad 18: Cxf4 es la mejor (+3,9) y la segunda queda en 0,0.',
  },
  {
    n: 86,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_28Cp8',
    tema: 'queenEndgame',
    lichess: '28Cp8',
    rating: 2275,
    elo: 1495,
    juegan: 'w',
    fen: '8/8/8/4pkPK/5q2/8/5Q2/8 w - - 9 68',
    ultima: 'Df4',
    marca: ['c4', 'f4'],
    solucion: { from: 'f2', to: 'f4' },
    primera: 'Dxf4+',
    linea: '68.Dxf4+ exf4 69.g6 Re6 70.Rh6 Re7 71.g7 Rf7 72.Rh7',
    gana: true,
    valor: '+35,4',
    cambios: ['q'],
    finalDePeones: true,
    pista: 'Con damas, el rey nunca está tranquilo. ¿Te conviene que se vayan?',
    explica: 'En la línea se cambian las damas, y queda un final de peones. Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 28Cp8 de la base abierta de Lichess (CC0), rating 2275. Stockfish 16 a profundidad 18: Dxf4+ es la mejor (+35,4) y la segunda queda en +0,1.',
  },
  {
    n: 87,
    uso: 'mixto',
    capitulo: 0,
    exige: '',
    id: 'cc_2BVjz',
    tema: 'zugzwang',
    lichess: '2BVjz',
    rating: 2302,
    elo: 1522,
    juegan: 'b',
    fen: '8/8/8/4nkPp/4p2B/4P1K1/8/8 b - - 3 51',
    ultima: 'Rg3',
    marca: ['f2', 'g3'],
    solucion: { from: 'e5', to: 'g6' },
    primera: 'Cg6',
    linea: '51…Cg6 52.Rh3 Cxh4 53.Rxh4 Rg6',
    gana: true,
    valor: '+7,2',
    cambios: ['m'],
    finalDePeones: true,
    pista: 'Después de los cambios, el que tiene que mover pierde. ¿A quién le toca?',
    explica: 'En la línea se cambian una pieza menor por otra, y queda un final de peones. Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2BVjz de la base abierta de Lichess (CC0), rating 2302. Stockfish 16 a profundidad 18: Cg6 es la mejor (+7,2) y la segunda queda en +0,1.',
  },
];
