#!/usr/bin/env node
/* Los cuestionarios listos de la Academia: 30, diez por nivel (inicial,
   intermedio y avanzado), de al menos 15 preguntas cada uno. Los ven quienes
   dan clase (cuestionarios.html y la clase en vivo), nunca los alumnos: traen
   las respuestas. Ver «Los cuestionarios listos» en
   docs/decisiones/clase-en-vivo.md.

   Esto es la fuente: lo que está acá es lo que se siembra. Cada pregunta se
   escribe con la CORRECTA PRIMERO —así se revisa de un vistazo— y el script
   reparte su lugar entre A, B, C y D (siempre igual para la misma pregunta,
   para que sembrar dos veces dé lo mismo). «Verdadero / Falso» queda en ese
   orden.

   Ninguna trae posición: una posición no se inventa (ver CLAUDE.md), y las
   que se nombran por sus jugadas (las aperturas) se comprueban con chess.js
   en verificar-cuestionarios-listos.js.

       node herramientas/cuestionarios-listos.js
   escribe herramientas/cuestionarios/semilla.sql (no se commitea), que se
   corre en la base (SQL editor o execute_sql). Borra los listos y los vuelve
   a sembrar: se puede correr las veces que haga falta, y no toca los que
   armaron los profes. */

const fs = require("fs");
const path = require("path");

// [texto, correcta, ...distractores]
const Q = (texto, correcta, ...otras) => ({ texto, correcta, otras });

const LISTOS = [
  // ============================== INICIAL ==============================
  { titulo: "El tablero y las casillas", nivel: "inicial", preguntas: [
    Q("¿Cuántas casillas tiene el tablero de ajedrez?", "64", "48", "81", "100"),
    Q("¿Cuántas filas tiene el tablero?", "8", "6", "10", "12"),
    Q("La casilla de la esquina derecha de cada jugador, ¿de qué color es?", "Clara", "Oscura", "Depende de quién juega", "Da igual cómo se ponga"),
    Q("Las columnas se nombran con…", "Letras de la a a la h", "Números del 1 al 8", "Letras de la a a la z", "Colores"),
    Q("Las filas se nombran con…", "Números del 1 al 8", "Letras de la a a la h", "Números del 0 al 7", "Nombres de piezas"),
    Q("Vista desde las blancas, ¿cómo se llama la esquina de abajo a la izquierda?", "a1", "h1", "a8", "h8"),
    Q("¿En qué casilla empieza el rey blanco?", "e1", "d1", "e8", "f1"),
    Q("¿En qué casilla empieza la dama blanca?", "d1", "e1", "d8", "c1"),
    Q("¿En qué casilla empieza la dama negra?", "d8", "e8", "d1", "c8"),
    Q("¿Qué es una diagonal?", "Una línea inclinada de casillas del mismo color", "Una fila completa", "Una columna completa", "El centro del tablero"),
    Q("¿Cuántas casillas tiene cada columna?", "8", "6", "7", "10"),
    Q("¿Cuáles son las cuatro casillas del centro?", "d4, e4, d5 y e5", "c3, f3, c6 y f6", "a1, h1, a8 y h8", "d1, e1, d8 y e8"),
    Q("¿En qué fila empiezan los peones blancos?", "En la 2", "En la 1", "En la 3", "En la 7"),
    Q("¿En qué fila empiezan los peones negros?", "En la 7", "En la 8", "En la 2", "En la 6"),
    Q("¿Cuántas casillas claras tiene el tablero?", "32", "64", "16", "30"),
    Q("¿Quién mueve primero en una partida?", "Las blancas", "Las negras", "Quien gane el sorteo", "El más joven"),
  ] },
  { titulo: "Cómo se mueven las piezas", nivel: "inicial", preguntas: [
    Q("¿Qué pieza se mueve en forma de L?", "El caballo", "El alfil", "La torre", "El rey"),
    Q("¿Qué pieza puede saltar por encima de las demás?", "El caballo", "La dama", "La torre", "El alfil"),
    Q("¿Cómo se mueve la torre?", "En línea recta, por filas y columnas", "Solo en diagonal", "En forma de L", "Una casilla a la vez"),
    Q("¿Cómo se mueve el alfil?", "En diagonal, las casillas que quiera", "En línea recta", "En forma de L", "Solo hacia adelante"),
    Q("En su primera jugada, ¿cuántas casillas puede avanzar un peón?", "Una o dos", "Solo una", "Hasta tres", "Las que quiera"),
    Q("¿Cómo captura el peón?", "En diagonal, una casilla hacia adelante", "Hacia adelante, en línea recta", "Hacia atrás", "Como el caballo"),
    Q("¿Puede un peón moverse hacia atrás?", "No, nunca", "Sí, siempre", "Solo al capturar", "Solo en su primera jugada"),
    Q("¿Qué pieza combina los movimientos de la torre y el alfil?", "La dama", "El rey", "El caballo", "El peón"),
    Q("En una jugada normal (sin enrocar), ¿cuántas casillas se mueve el rey?", "Una", "Dos", "Las que quiera", "Tres"),
    Q("Un alfil que empieza en una casilla clara…", "Siempre se queda en casillas claras", "Puede pasar a casillas oscuras", "Cambia de color en cada jugada", "Solo va a casillas oscuras"),
    Q("¿Qué pieza se mueve en cualquier dirección, tantas casillas como quiera?", "La dama", "La torre", "El rey", "El alfil"),
    Q("Cuando un caballo salta desde una casilla clara, ¿a qué color llega?", "A una oscura", "A una clara", "Depende de la dirección", "Depende de la pieza que salte"),
    Q("¿Qué pieza NO puede capturar hacia adelante en línea recta?", "El peón", "La torre", "La dama", "El rey"),
    Q("¿Cuántos caballos tiene cada jugador al empezar?", "2", "1", "3", "4"),
    Q("¿Cuántos peones tiene cada jugador al empezar?", "8", "6", "10", "16"),
    Q("¿Qué piezas empiezan en las esquinas?", "Las torres", "Los alfiles", "Los caballos", "Los reyes"),
  ] },
  { titulo: "El valor de las piezas", nivel: "inicial", preguntas: [
    Q("¿Cuántos puntos vale un peón?", "1", "3", "5", "9"),
    Q("¿Cuánto vale aproximadamente un caballo?", "3 puntos", "1 punto", "5 puntos", "9 puntos"),
    Q("¿Cuánto vale aproximadamente un alfil?", "3 puntos", "5 puntos", "1 punto", "9 puntos"),
    Q("¿Cuánto vale aproximadamente una torre?", "5 puntos", "3 puntos", "9 puntos", "7 puntos"),
    Q("¿Cuánto vale aproximadamente la dama?", "9 puntos", "5 puntos", "12 puntos", "3 puntos"),
    Q("¿Por qué el rey no tiene un valor en puntos?", "Porque si lo pierdes, pierdes la partida", "Porque vale 0", "Porque es la pieza más débil", "Porque casi no se mueve"),
    Q("¿Qué vale más: una torre o un alfil?", "La torre", "El alfil", "Valen igual", "Depende del color"),
    Q("Cambiar tu alfil por la torre del rival es…", "Ganar material", "Perder material", "Un cambio parejo", "Siempre un error"),
    Q("¿Cuánto suman aproximadamente dos torres?", "10 puntos", "9 puntos", "6 puntos", "18 puntos"),
    Q("Si cambias tu caballo por un alfil del rival, ¿cómo quedas en material?", "Parejo", "Ganas 2 puntos", "Pierdes 2 puntos", "Ganas 1 punto"),
    Q("¿Qué es «ganar la calidad»?", "Cambiar una pieza menor por una torre", "Ganar un peón", "Cambiar las damas", "Coronar un peón"),
    Q("¿Cuáles son las «piezas menores»?", "El alfil y el caballo", "La torre y la dama", "El rey y la dama", "Los peones"),
    Q("¿Cuáles son las «piezas mayores»?", "La dama y las torres", "Los alfiles y los caballos", "El rey y los peones", "Los caballos y las torres"),
    Q("Tres peones valen aproximadamente lo mismo que…", "Un alfil o un caballo", "Una torre", "La dama", "Dos torres"),
    Q("Después del rey, ¿cuál es la pieza más valiosa?", "La dama", "La torre", "El caballo", "El alfil"),
    Q("Tienes una torre; tu rival, un alfil y un peón. ¿Quién tiene más material?", "Tú, por un punto", "Tu rival", "Están iguales", "No se puede saber"),
  ] },
  { titulo: "Jaque, jaque mate y ahogado", nivel: "inicial", preguntas: [
    Q("¿Qué es el jaque?", "Un ataque al rey", "Capturar la dama", "Un empate", "Mover el rey dos casillas"),
    Q("¿Qué es el jaque mate?", "Un jaque del que el rey no se puede librar", "Cualquier jaque", "Capturar el rey", "Quedarse sin piezas"),
    Q("¿Cuáles son las tres formas de salir de un jaque?", "Mover el rey, tapar o capturar a quien da jaque", "Enrocar, tapar o capturar", "Mover cualquier pieza", "Pasar el turno, tapar o capturar"),
    Q("¿Se puede enrocar para salir de un jaque?", "No", "Sí, siempre", "Solo el enroque corto", "Solo si la torre no se movió"),
    Q("¿Qué es el ahogado?", "Al que le toca no está en jaque y no tiene jugadas legales", "El rey está en jaque y no puede escapar", "La misma posición se repite", "Solo quedan los dos reyes"),
    Q("¿Cómo termina una partida con ahogado?", "En tablas", "Gana el que ahogó", "Gana el ahogado", "Se vuelve a jugar"),
    Q("¿Puede un rey dar jaque al otro rey?", "No: los reyes nunca pueden quedar pegados", "Sí, si está protegido", "Sí, en el final", "Solo en diagonal"),
    Q("¿Puede un rey moverse a una casilla atacada por el rival?", "No", "Sí", "Solo si captura", "Solo en el enroque"),
    Q("¿Qué es un jaque doble?", "Un jaque que dan dos piezas a la vez", "Dar jaque dos veces seguidas", "Un jaque con la dama", "Un jaque que se tapa dos veces"),
    Q("Ante un jaque doble, ¿cuál es la única forma de salir?", "Mover el rey", "Tapar", "Capturar una de las piezas", "Enrocar"),
    Q("¿Qué es un jaque descubierto?", "Se mueve una pieza y deja a otra dando jaque", "Un jaque que nadie ve", "Un jaque del rey", "Un jaque que se tapa"),
    Q("Con rey y caballo contra el rey solo, ¿se puede dar mate?", "No: no hay forma de dar mate", "Sí, fácilmente", "Sí, en diez jugadas", "Solo en la esquina"),
    Q("Contra el rey solo, ¿con qué pieza y tu rey se puede dar mate?", "Con una torre", "Con un caballo", "Con un alfil", "Con el rey solo"),
    Q("Tu rey está en jaque y no tienes ninguna jugada legal. ¿Qué es?", "Jaque mate: pierdes", "Ahogado: tablas", "Pasas el turno", "Se repite la jugada"),
    Q("¿Qué es tapar un jaque?", "Poner una pieza entre el rey y la que da jaque", "Capturar a la que da jaque", "Enrocar", "Llevar el rey a una esquina"),
    Q("¿Qué pieza no puede dar jaque nunca?", "El rey", "El peón", "El caballo", "La dama"),
  ] },
  { titulo: "Enroque, coronación y captura al paso", nivel: "inicial", preguntas: [
    Q("¿Qué es el enroque?", "Una jugada del rey y una torre a la vez", "Cambiar dos piezas", "Una jugada del peón", "Capturar dos piezas"),
    Q("Al enrocar, ¿cuántas casillas se mueve el rey?", "Dos", "Una", "Tres", "Las que quiera"),
    Q("En el enroque corto de las blancas, ¿a qué casilla va el rey?", "g1", "c1", "h1", "f1"),
    Q("En el enroque largo de las blancas, ¿a qué casilla va el rey?", "c1", "b1", "g1", "d1"),
    Q("En el enroque corto de las blancas, ¿a qué casilla va la torre?", "f1", "g1", "e1", "d1"),
    Q("Si el rey ya se movió antes (aunque haya vuelto), ¿se puede enrocar?", "No", "Sí", "Solo el corto", "Solo si no hay jaque"),
    Q("¿Se puede enrocar si el rey tiene que pasar por una casilla atacada?", "No", "Sí", "Solo el largo", "Solo si la torre está protegida"),
    Q("¿Se puede enrocar si la torre está atacada?", "Sí", "No", "Solo el corto", "Solo si el rey no se movió"),
    Q("¿Qué es la coronación?", "Un peón llega a la última fila y se cambia por otra pieza", "El rey llega al centro", "Se da jaque mate", "Se captura la dama"),
    Q("Al coronar, ¿por qué pieza se puede cambiar el peón?", "Por dama, torre, alfil o caballo", "Solo por dama", "Por cualquiera, incluso el rey", "Solo por una pieza que se haya perdido"),
    Q("¿Se puede tener dos damas en el tablero?", "Sí, coronando un peón", "No, nunca", "Solo en partidas amistosas", "Solo si no quedan torres"),
    Q("¿Qué es la captura al paso?", "Un peón captura a otro que avanzó dos casillas a su lado", "Capturar al rey", "Una captura del caballo", "Capturar dos piezas a la vez"),
    Q("¿Cuándo se puede capturar al paso?", "Solo en la jugada siguiente", "En cualquier momento", "Solo en el final", "Dos jugadas después"),
    Q("¿En qué fila tiene que estar un peón blanco para capturar al paso?", "En la 5", "En la 4", "En la 6", "En la 2"),
    Q("¿Qué piezas participan en el enroque?", "El rey y una torre", "La dama y una torre", "El rey y la dama", "El rey y un caballo"),
    Q("¿Se puede enrocar estando en jaque?", "No", "Sí", "Solo el largo", "Solo si el jaque es de caballo"),
  ] },
  { titulo: "La notación del ajedrez", nivel: "inicial", preguntas: [
    Q("En la notación en español, ¿qué letra es el caballo?", "C", "K", "N", "A"),
    Q("¿Qué letra es el alfil?", "A", "B", "L", "F"),
    Q("¿Qué letra es la dama?", "D", "Q", "R", "M"),
    Q("¿Qué letra es el rey?", "R", "K", "Y", "E"),
    Q("¿Qué letra es la torre?", "T", "R", "O", "K"),
    Q("¿Cómo se anota una jugada de peón?", "Solo con la casilla de llegada, como e4", "Con la letra P, como Pe4", "Con un número", "Con la casilla de salida"),
    Q("¿Qué significa el símbolo «x»?", "Captura", "Jaque", "Mate", "Enroque"),
    Q("¿Qué significa el símbolo «+»?", "Jaque", "Captura", "Buena jugada", "Tablas"),
    Q("¿Cómo se anota el enroque corto?", "O-O", "O-O-O", "R-g1", "E-C"),
    Q("¿Cómo se anota el enroque largo?", "O-O-O", "O-O", "0-1", "E-L"),
    Q("¿Qué significa «Cf3»?", "El caballo va a f3", "El caballo captura en f3", "La dama va a f3", "El peón va a f3"),
    Q("¿Qué significa «Axe5»?", "Un alfil captura en e5", "Un alfil va a x5", "Un alfil da jaque en e5", "La dama captura en e5"),
    Q("¿Qué significa «1-0» al final de una partida?", "Ganaron las blancas", "Ganaron las negras", "Tablas", "Se suspendió"),
    Q("¿Qué significa «½-½»?", "Tablas", "Ganaron las blancas", "Ganaron las negras", "Se suspendió"),
    Q("¿Qué significa «!!» junto a una jugada?", "Una jugada brillante", "Un error grave", "Una jugada dudosa", "Un jaque doble"),
    Q("¿Qué significa «?» junto a una jugada?", "Un error", "Una buena jugada", "Un jaque", "Una pregunta al árbitro"),
  ] },
  { titulo: "Principios de la apertura", nivel: "inicial", preguntas: [
    Q("¿Qué es lo más importante en la apertura?", "Desarrollar las piezas y controlar el centro", "Mover solo peones", "Sacar la dama rápido", "Pasear el rey"),
    Q("¿Por qué conviene enrocar temprano?", "Pone el rey a salvo y conecta las torres", "Gana material", "Es obligatorio", "Para atacar con el rey"),
    Q("¿Qué piezas conviene desarrollar primero?", "Los caballos y los alfiles", "Las torres", "La dama", "El rey"),
    Q("¿Por qué no conviene sacar la dama muy temprano?", "El rival la ataca y gana tiempos", "Porque no se puede", "Porque vale poco", "Porque tapa al rey"),
    Q("¿Conviene mover la misma pieza muchas veces en la apertura?", "No: se pierde tiempo de desarrollo", "Sí, siempre", "Solo el caballo", "Solo la dama"),
    Q("¿Qué primera jugada de las blancas ocupa el centro con un peón?", "1.e4", "1.a4", "1.h4", "1.Ch3"),
    Q("Un caballo en el borde del tablero…", "Controla menos casillas", "Es más fuerte", "Protege mejor al rey", "Vale más puntos"),
    Q("¿Qué significa «conectar las torres»?", "Que no haya piezas entre ellas en la primera fila", "Ponerlas en la columna del rival", "Cambiarlas", "Enrocar dos veces"),
    Q("¿Cuál es una mala costumbre en la apertura?", "Mover muchos peones del costado sin desarrollar", "Enrocar", "Sacar los caballos", "Ocupar el centro"),
    Q("¿Qué es un gambito?", "Entregar material (casi siempre un peón) a cambio de desarrollo o ataque", "Un tipo de mate", "Una forma de enrocar", "Una apertura sin peones"),
    Q("¿Conviene mover el peón de f2 sin un buen motivo?", "No: debilita al rey", "Sí, siempre", "Solo para enrocar", "Da lo mismo"),
    Q("Al comienzo, ¿qué casilla negra está defendida solo por el rey?", "f7", "e5", "d5", "a7"),
    Q("¿Qué busca el «mate del pastor»?", "Atacar f7 con la dama y el alfil", "Atacar con los caballos", "Enrocar rápido", "Cambiar las damas"),
    Q("¿Cómo se defiende bien contra un ataque temprano a f7?", "Desarrollando y protegiendo f7", "Paseando el rey", "Sacando la torre", "Moviendo el peón de h"),
    Q("¿Cuándo termina, más o menos, la apertura?", "Con las piezas desarrolladas y el rey enrocado", "En la jugada 3", "Con la primera captura", "Con el primer jaque"),
    Q("Tras 1.e4 e5 2.Cf3, ¿qué ataca el caballo?", "El peón de e5", "Al rey", "A la dama", "El peón de f7"),
  ] },
  { titulo: "Mates básicos", nivel: "inicial", preguntas: [
    Q("¿Qué es el mate del pasillo?", "Un mate en la última fila, con el rey encerrado por sus peones", "Un mate con dos caballos", "Un mate en el centro", "Un mate con el rey"),
    Q("¿Qué pieza suele dar el mate del pasillo?", "Una torre o la dama", "Un caballo", "Un peón", "El rey"),
    Q("¿Cómo se evita el mate del pasillo?", "Abriéndole una «ventana» al rey con un peón", "Enrocando largo", "Cambiando las damas", "Poniendo el rey en el centro"),
    Q("Con rey y dama contra el rey solo, ¿se puede dar mate?", "Sí, siempre, jugando bien", "No", "Solo si el rival se equivoca", "Solo en el centro"),
    Q("Con rey y dos alfiles contra el rey solo, ¿se puede dar mate?", "Sí", "No", "Solo si los alfiles son del mismo color", "Nunca en la práctica"),
    Q("Con rey y dos caballos contra el rey solo, ¿se puede forzar el mate?", "No, no se puede forzar", "Sí, siempre", "Sí, en cinco jugadas", "Solo en el centro"),
    Q("Para dar mate con rey y torre, ¿a dónde hay que llevar al rey rival?", "Al borde del tablero", "Al centro", "Cerca de tus peones", "A la columna e"),
    Q("Al dar mate con rey y dama, ¿qué error hay que evitar?", "El ahogado", "El jaque", "El enroque", "La coronación"),
    Q("¿Qué es el mate del pastor?", "Un mate en f7 en las primeras jugadas, con dama y alfil", "Un mate con torre", "Un mate con dos torres", "Un mate en la esquina con caballo"),
    Q("¿En cuántas jugadas se da el mate más rápido posible (el mate del loco)?", "En dos", "En una", "En cuatro", "En diez"),
    Q("¿Quién da el mate del loco?", "Las negras", "Las blancas", "Cualquiera de los dos", "Nadie, son tablas"),
    Q("En el mate del loco, ¿con qué pieza se da el mate?", "Con la dama", "Con el alfil", "Con el caballo", "Con la torre"),
    Q("¿Qué es el mate de la escalera (con dos torres)?", "Las torres se turnan para empujar al rey al borde", "Un mate con el rey", "Un mate con dos alfiles", "Un mate con peones"),
    Q("Para dar mate, ¿hace falta capturar al rey?", "No: basta con que no tenga salida", "Sí", "Solo en el final", "Solo con la dama"),
    Q("Rey y alfil contra el rey solo: ¿qué resultado es?", "Tablas: no alcanza para dar mate", "Gana el del alfil", "Gana si el alfil es de casillas claras", "Depende de quién mueva"),
    Q("Rey y torre contra el rey solo: ¿quién gana?", "El de la torre, si juega bien", "Tablas", "Depende de quién mueva", "El rey solo"),
  ] },
  { titulo: "Tablas y el final de la partida", nivel: "inicial", preguntas: [
    Q("¿Cómo puede terminar una partida?", "Gana uno, gana el otro o hay tablas", "Solo con un ganador", "Solo en tablas", "Solo con mate"),
    Q("¿Qué es la triple repetición?", "La misma posición aparece tres veces y se pueden pedir tablas", "Dar jaque tres veces", "Mover una pieza tres veces", "Perder tres peones"),
    Q("¿Qué dice la regla de las 50 jugadas?", "50 jugadas de cada uno sin capturas ni jugadas de peón: tablas", "Una partida dura 50 jugadas", "Hay que dar mate en 50 jugadas", "A las 50 jugadas se cambia de color"),
    Q("¿Qué pasa si solo quedan los dos reyes?", "Tablas", "Gana el que mueve", "Gana el que tenía más piezas", "Se sigue jugando"),
    Q("¿Pueden los dos jugadores acordar tablas?", "Sí, si los dos están de acuerdo", "No, nunca", "Solo el árbitro", "Solo después de la jugada 100"),
    Q("¿Qué significa abandonar?", "Rendirse: se reconoce la derrota", "Pedir tablas", "Salir un rato", "Cambiar de color"),
    Q("Rey y caballo contra el rey solo: ¿qué resultado es?", "Tablas", "Gana el del caballo", "Depende de quién mueva", "Gana el que mueve"),
    Q("Si se te acaba el tiempo, ¿qué pasa en general?", "Pierdes, salvo que el rival no pueda dar mate de ninguna forma", "Tablas siempre", "Te dan más tiempo", "Sigue la partida"),
    Q("¿Qué es ahogar al rival?", "Dejarlo sin jugadas legales sin estar en jaque: tablas", "Darle mate", "Ganarle la dama", "Encerrarle un caballo"),
    Q("Cuando vas ganando por mucho, ¿qué hay que cuidar?", "No ahogar al rival", "Cambiar todo", "No dar jaque", "Jugar rápido"),
    Q("¿Qué es el jaque perpetuo?", "Jaques sin parar que el rival no puede evitar: tablas", "Un jaque mate", "Un jaque de la dama", "Un jaque que dura una jugada"),
    Q("¿Qué se dice antes de acomodar una pieza sin querer moverla?", "«Compongo»", "«Jaque»", "«Tablas»", "«Toco»"),
    Q("Si tocas a propósito una pieza tuya, ¿qué tienes que hacer?", "Moverla, si tiene alguna jugada legal", "Nada", "Pedir perdón y seguir", "Moverla solo si quieres"),
    Q("Si tocas a propósito una pieza del rival, ¿qué tienes que hacer?", "Capturarla, si se puede", "Nada", "Moverla a otra casilla", "Devolvérsela"),
    Q("Rey y dama contra el rey solo, jugando bien: ¿quién gana?", "El de la dama", "Tablas", "El rey solo", "Depende del reloj"),
    Q("En un torneo, ¿qué suma cada jugador con unas tablas?", "Medio punto", "Nada", "Un punto", "Se juega otra partida"),
  ] },
  { titulo: "Historia y curiosidades del ajedrez", nivel: "inicial", preguntas: [
    Q("Según la mayoría de los historiadores, ¿de dónde viene el ajedrez?", "De la India", "De Francia", "De Inglaterra", "De México"),
    Q("¿Cómo se llamaba el juego antiguo del que viene el ajedrez?", "Chaturanga", "Damas", "Go", "Mancala"),
    Q("¿Quién fue el primer campeón mundial oficial?", "Wilhelm Steinitz", "Bobby Fischer", "Garry Kaspárov", "Magnus Carlsen"),
    Q("¿De qué país es Magnus Carlsen?", "Noruega", "Rusia", "Estados Unidos", "India"),
    Q("¿Qué computadora le ganó un match a Garry Kaspárov en 1997?", "Deep Blue", "Stockfish", "AlphaZero", "Watson"),
    Q("¿De qué país era Bobby Fischer?", "Estados Unidos", "Rusia", "Canadá", "Cuba"),
    Q("¿Qué campeón mundial era cubano?", "José Raúl Capablanca", "Anatoli Kárpov", "Mijaíl Tal", "Emanuel Lasker"),
    Q("¿Qué es un Gran Maestro?", "El título más alto que da la FIDE a un jugador", "Un árbitro", "Un entrenador de club", "Un campeón nacional"),
    Q("¿Qué es la FIDE?", "La Federación Internacional de Ajedrez", "Una fundación de deportes", "Un torneo en Francia", "Un programa de ajedrez"),
    Q("¿Qué número mide la fuerza de un jugador?", "El Elo", "El PGN", "El FEN", "El ECO"),
    Q("¿Qué es una simultánea?", "Un jugador juega contra muchos a la vez", "Dos partidas en un tablero", "Una partida muy rápida", "Un torneo por equipos"),
    Q("¿Qué es una partida a ciegas?", "Se juega sin ver el tablero", "Se juega a oscuras", "Solo el árbitro tiene los ojos vendados", "Se juega sin reloj"),
    Q("¿Qué es el blitz?", "Partidas rápidas, de pocos minutos por jugador", "Ajedrez para cuatro", "Ajedrez sin reglas", "Ajedrez por correo"),
    Q("¿Qué reloj se usa en el ajedrez?", "Un reloj doble, uno para cada jugador", "Un reloj de arena", "Un cronómetro del árbitro", "Ninguno"),
    Q("¿Cómo se llama la gran competencia de ajedrez entre países?", "La Olimpiada de Ajedrez", "La Copa América", "El Mundial de Clubes", "El Grand Slam"),
    Q("¿En qué año se jugó el famoso match Fischer–Spassky en Reikiavik?", "1972", "1985", "1997", "1960"),
  ] },

  // ============================== INTERMEDIO ==============================
  { titulo: "La clavada y la enfilada", nivel: "intermedio", preguntas: [
    Q("¿Qué es una clavada?", "No puede o no le conviene moverse: destaparía otra más valiosa", "Un jaque doble", "Capturar dos piezas", "Encerrar una pieza en el borde"),
    Q("¿Qué es una clavada absoluta?", "Detrás está el rey: la pieza clavada no puede moverse", "Detrás está la dama", "La pieza clavada es un peón", "Dura toda la partida"),
    Q("¿Qué piezas pueden clavar?", "El alfil, la torre y la dama", "Solo el caballo", "Solo el rey", "Todas, también el caballo"),
    Q("¿Puede un caballo clavar a otra pieza?", "No: salta y no actúa en línea", "Sí, siempre", "Solo en diagonal", "Solo contra el rey"),
    Q("¿Qué es una clavada relativa?", "Detrás hay una pieza valiosa que no es el rey", "Una clavada que no existe", "Una clavada con el rey detrás", "Una clavada del peón"),
    Q("¿Qué es la enfilada (o pincho)?", "Atacar una pieza valiosa que, al moverse, destapa otra detrás", "Una clavada con el rey", "Un jaque doble", "Un sacrificio de dama"),
    Q("¿En qué se diferencia la enfilada de la clavada?", "En la enfilada, la pieza más valiosa está adelante", "Son lo mismo", "En la enfilada no hay una línea", "En la clavada, la de adelante vale más"),
    Q("¿Cuál es una buena forma de aprovechar una pieza clavada?", "Atacarla otra vez, mejor con un peón", "Cambiar la pieza que clava", "Olvidarse de ella", "Mover el propio rey"),
    Q("¿Cómo se sale de una clavada?", "Tapando, moviendo la pieza de atrás o atacando a la que clava", "Moviendo siempre la clavada", "Enrocando", "No hay forma"),
    Q("Tras 1.e4 e5 2.Cf3 Cc6 3.Ab5, ¿qué pieza presiona el alfil?", "Al caballo de c6, que defiende e5", "Al rey, directamente", "A la dama", "Al peón de f7"),
    Q("Tras 1.d4 Cf6 2.c4 e6 3.Cc3 Ab4, ¿qué hace Ab4?", "Clava el caballo de c3 contra el rey", "Da jaque", "Amenaza la dama", "Ataca d4"),
    Q("Una torre en la columna del rey rival, con un caballo rival en medio: el caballo está…", "Clavado", "Libre", "En jaque", "Colgando"),
    Q("¿Qué es romper una clavada?", "Quitar la línea: mover el rey o tapar", "Capturar el rey", "Enrocar largo", "Mover la pieza clavada sin más"),
    Q("¿Qué es un ataque a la descubierta?", "Se mueve una pieza y otra ataca desde atrás", "Un ataque con el rey", "Una clavada", "Una horquilla"),
    Q("Una pieza clavada contra su rey, ¿sigue dando jaque al rey rival?", "Sí: sigue atacando aunque no pueda moverse", "No, pierde su ataque", "Solo si es la dama", "Solo si el rey está en la esquina"),
    Q("¿Qué piezas clavan a lo largo de una fila?", "La torre o la dama", "El alfil", "El caballo", "El peón"),
  ] },
  { titulo: "Horquillas y dobles ataques", nivel: "intermedio", preguntas: [
    Q("¿Qué es una horquilla?", "Una pieza ataca a dos o más a la vez", "Una clavada", "Un enroque", "Un jaque perpetuo"),
    Q("¿Qué pieza es famosa por sus horquillas?", "El caballo", "El alfil", "La torre", "El rey"),
    Q("¿Puede un peón hacer una horquilla?", "Sí, atacando dos piezas en diagonal", "No", "Solo al coronar", "Solo al paso"),
    Q("¿Qué es la «horquilla familiar» del caballo?", "Ataca al rey, a la dama y a más piezas", "Un caballo que da mate", "Dos caballos juntos", "Un caballo en la esquina"),
    Q("¿Por qué el doble ataque es tan fuerte?", "El rival solo puede salvar una cosa por jugada", "Porque es jaque mate", "Porque no se puede defender nunca", "Porque se gana tiempo en el reloj"),
    Q("¿Qué es un doble ataque con jaque?", "Dar jaque y, a la vez, atacar otra pieza", "Dar dos jaques", "Atacar dos peones", "Una clavada con jaque"),
    Q("¿Puede la dama hacer dobles ataques?", "Sí: es la pieza que más los hace", "No", "Solo en diagonal", "Solo en el final"),
    Q("¿Qué conviene revisar para no caer en una horquilla de caballo?", "Las casillas adonde puede saltar el caballo rival", "Solo las diagonales", "Solo las columnas abiertas", "El reloj"),
    Q("«Piezas sueltas caen»: ¿qué significa?", "Las piezas sin defensa son blanco de dobles ataques", "Hay que soltar las piezas", "Las piezas del borde se pierden", "Hay que cambiarlo todo"),
    Q("Una torre ataca a una pieza a su izquierda y a otra a su derecha. ¿Qué es?", "Un doble ataque", "Una clavada", "Una enfilada", "Un ahogado"),
    Q("En 1.e4 e5 2.Cf3 Cc6 3.Ac4 Cf6 4.Cg5 d5 5.exd5 Cxd5 6.Cxf7, ¿qué dos piezas ataca el caballo?", "La dama de d8 y la torre de h8", "El rey y el alfil", "Solo un peón", "La dama y el rey"),
    Q("¿Cómo se escapa a veces de una horquilla?", "Con una jugada intermedia que dé jaque o amenace más", "No hay forma nunca", "Enrocando siempre", "Moviendo siempre el rey"),
    Q("¿Qué es un doble ataque del alfil?", "Ataca dos piezas en diagonales distintas", "Un alfil que da mate", "Dos alfiles juntos", "Un alfil clavado"),
    Q("Un peón ataca a la vez un caballo y un alfil. ¿Qué conviene?", "Salvar una pieza o contraatacar con algo mayor", "Salvar las dos", "Ignorar el peón", "Abandonar"),
    Q("¿Qué es un doble ataque a la descubierta?", "Una pieza ataca al moverse y destapa otro ataque detrás", "Una clavada", "Dos jaques seguidos", "Mover dos piezas"),
    Q("¿Qué pieza no puede hacer una horquilla?", "Ninguna: todas pueden atacar dos cosas a la vez", "El rey", "El peón", "La torre"),
  ] },
  { titulo: "Temas tácticos", nivel: "intermedio", preguntas: [
    Q("¿Qué es la desviación?", "Obligar a una pieza a alejarse de lo que defiende", "Mover el rey al costado", "Cambiar las damas", "Un tipo de enroque"),
    Q("¿Qué es la atracción?", "Llevar con un sacrificio a una pieza (a menudo el rey) a una mala casilla", "Cambiar piezas", "Defender una pieza", "Avanzar un peón"),
    Q("¿Qué es la sobrecarga?", "Una pieza tiene demasiadas tareas de defensa a la vez", "Tener muchas piezas", "Un rey muy protegido", "Una torre doblada"),
    Q("¿Qué es eliminar al defensor?", "Capturar o desviar la pieza que protege algo importante", "Enrocar", "Defender con el rey", "Cambiar los alfiles"),
    Q("¿Qué es una interferencia?", "Meter una pieza entre una pieza rival y lo que defiende", "Tapar un jaque", "Enrocar", "Un ahogado"),
    Q("¿Qué es un ataque de rayos X?", "Una pieza actúa a través de otra que está en su línea", "Un jaque de caballo", "Un ataque a un peón", "Una clavada con el rey"),
    Q("¿Qué es un sacrificio?", "Entregar material a propósito para lograr algo mejor", "Perder una pieza sin querer", "Cambiar dos piezas iguales", "Coronar"),
    Q("¿Qué es una pieza colgada?", "Una pieza atacada y sin defensa suficiente", "Una pieza en el borde", "Una pieza clavada", "Una pieza que no se ha movido"),
    Q("¿Qué es un molino?", "Jaques a la descubierta que se repiten ganando material", "Un mate con torre", "Un enroque doble", "Una apertura"),
    Q("¿Qué es una pieza atrapada?", "Una pieza sin casillas seguras adonde ir", "Una pieza clavada al rey", "Una pieza en el centro", "Una pieza coronada"),
    Q("¿Qué es despejar una casilla o una línea?", "Mover una pieza propia para que otra use esa casilla o línea", "Capturarlo todo", "Cambiar las damas", "Defender al rey"),
    Q("En táctica, ¿qué busca un sacrificio de bloqueo?", "Que una pieza rival tape una salida de su propio rey", "Poner un peón delante de un pasado", "Clavar un caballo", "Cambiar las torres"),
    Q("¿Qué es una amenaza de mate?", "Una jugada que, si no se atiende, da mate en la siguiente", "Cualquier jaque", "Un sacrificio", "Una jugada de tablas"),
    Q("¿Qué conviene revisar antes de cada jugada?", "Los jaques, las capturas y las amenazas", "Solo tus planes", "Cuánto tiempo queda", "Qué jugó tu rival la semana pasada"),
    Q("¿Qué es una jugada intermedia?", "Una que se mete antes de la esperada, como un jaque antes de recapturar", "Una jugada del centro", "La jugada 20", "Un enroque"),
    Q("¿Qué es una combinación?", "Una serie forzada de jugadas, a menudo con sacrificio, que logra ventaja", "Una apertura", "Un final de peones", "Mover dos piezas a la vez"),
  ] },
  { titulo: "Aperturas abiertas (1.e4 e5)", nivel: "intermedio", preguntas: [
    Q("1.e4 e5 2.Cf3 Cc6 3.Ab5: ¿qué apertura es?", "La española (Ruy López)", "La italiana", "La escocesa", "La Petrov"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ac4: ¿qué apertura es?", "La italiana", "La española", "La escocesa", "La vienesa"),
    Q("1.e4 e5 2.Cf3 Cc6 3.d4: ¿qué apertura es?", "La escocesa", "La italiana", "La española", "El gambito de rey"),
    Q("1.e4 e5 2.f4: ¿qué apertura es?", "El gambito de rey", "El gambito de dama", "El gambito Evans", "La vienesa"),
    Q("1.e4 e5 2.Cf3 Cf6: ¿qué defensa es?", "La Petrov (o rusa)", "La Philidor", "La de los dos caballos", "La siciliana"),
    Q("1.e4 e5 2.Cf3 d6: ¿qué defensa es?", "La Philidor", "La Petrov", "La francesa", "La Pirc"),
    Q("1.e4 e5 2.Cc3: ¿qué apertura es?", "La vienesa", "La escocesa", "La italiana", "La Ponziani"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ac4 Ac5 4.b4: ¿qué gambito es?", "El gambito Evans", "El gambito de rey", "El gambito escocés", "El gambito danés"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ac4 Cf6: ¿qué defensa es?", "La de los dos caballos", "La Petrov", "La Philidor", "La berlinesa"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ac4 Ac5: ¿qué variante es?", "El Giuoco piano (italiana)", "Los dos caballos", "La española", "La escocesa"),
    Q("En la española, 3...a6 4.Axc6 dxc6: ¿qué variante es?", "La del cambio", "La cerrada", "La berlinesa", "El ataque Marshall"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ab5 Cf6: ¿qué defensa es?", "La berlinesa", "La del cambio", "La Steinitz", "La Schliemann"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Cc3 Cf6: ¿qué apertura es?", "La de los cuatro caballos", "La de los tres caballos", "La vienesa", "La escocesa"),
    Q("1.e4 e5 2.Cf3 Cc6 3.c3: ¿qué apertura es?", "La Ponziani", "La escocesa", "La italiana", "La vienesa"),
    Q("1.e4 e5 2.d4 exd4 3.c3: ¿qué gambito es?", "El gambito danés", "El gambito de rey", "El gambito escocés", "El gambito Evans"),
    Q("1.e4 e5 2.Cf3 Cc6 3.Ab5 f5: ¿qué defensa es?", "La Schliemann (o Jaenisch)", "La berlinesa", "El ataque Marshall", "La Steinitz"),
  ] },
  { titulo: "Aperturas semiabiertas y cerradas", nivel: "intermedio", preguntas: [
    Q("1.e4 c5: ¿qué defensa es?", "La siciliana", "La francesa", "La Caro-Kann", "La escandinava"),
    Q("1.e4 e6: ¿qué defensa es?", "La francesa", "La siciliana", "La Caro-Kann", "La Alekhine"),
    Q("1.e4 c6: ¿qué defensa es?", "La Caro-Kann", "La francesa", "La siciliana", "La Pirc"),
    Q("1.e4 d5: ¿qué defensa es?", "La escandinava", "La Alekhine", "La francesa", "La holandesa"),
    Q("1.e4 Cf6: ¿qué defensa es?", "La Alekhine", "La Petrov", "La Pirc", "La india de rey"),
    Q("1.e4 d6 2.d4 Cf6 3.Cc3 g6: ¿qué defensa es?", "La Pirc", "La moderna", "La india de rey", "La Alekhine"),
    Q("1.d4 d5 2.c4: ¿qué apertura es?", "El gambito de dama", "El gambito de rey", "El gambito Benko", "La inglesa"),
    Q("1.d4 d5 2.c4 dxc4: ¿qué variante es?", "El gambito de dama aceptado", "El gambito de dama rehusado", "La eslava", "La Tarrasch"),
    Q("1.d4 d5 2.c4 c6: ¿qué defensa es?", "La eslava", "La semieslava", "La ortodoxa", "La Tarrasch"),
    Q("1.d4 d5 2.c4 e6: ¿qué variante es?", "El gambito de dama rehusado", "El gambito de dama aceptado", "La eslava", "La holandesa"),
    Q("1.d4 f5: ¿qué defensa es?", "La holandesa", "La Benoni", "La india antigua", "La Budapest"),
    Q("1.c4: ¿qué apertura es?", "La inglesa", "La Réti", "La Bird", "La catalana"),
    Q("1.Cf3 d5 2.c4: ¿qué apertura es?", "La Réti", "La inglesa", "La catalana", "La Larsen"),
    Q("1.f4: ¿qué apertura es?", "La Bird", "La holandesa", "El gambito de rey", "La Larsen"),
    Q("1.d4 Cf6 2.c4 g6 3.Cc3 Ag7 4.e4 d6: ¿qué defensa es?", "La india de rey", "La Grünfeld", "La Nimzo-india", "La moderna"),
    Q("1.d4 Cf6 2.c4 g6 3.Cc3 d5: ¿qué defensa es?", "La Grünfeld", "La india de rey", "La Benoni", "La eslava"),
    Q("1.d4 Cf6 2.c4 e6 3.Cc3 Ab4: ¿qué defensa es?", "La Nimzo-india", "La india de dama", "La Bogo-india", "La catalana"),
  ] },
  { titulo: "Estructuras de peones", nivel: "intermedio", preguntas: [
    Q("¿Qué es un peón pasado?", "Uno sin peones rivales delante ni en las columnas vecinas", "Uno que ya se movió", "Uno que está en la séptima", "Uno que capturó"),
    Q("¿Qué es un peón aislado?", "Uno sin peones propios en las columnas vecinas", "Uno que no defiende ninguna pieza", "Uno en el borde", "Uno bloqueado"),
    Q("¿Qué son los peones doblados?", "Dos peones del mismo color en la misma columna", "Dos peones juntos en una fila", "Dos peones pasados", "Dos peones que se defienden"),
    Q("¿Qué es un peón retrasado?", "Quedó atrás de los vecinos y ellos ya no pueden defenderlo", "Uno que no se ha movido", "Uno en la segunda fila", "Uno que perdió tiempo"),
    Q("¿Qué es una cadena de peones?", "Peones en diagonal que se defienden uno a otro", "Peones en la misma fila", "Peones doblados", "Peones pasados"),
    Q("¿Dónde conviene atacar una cadena de peones?", "En su base", "En su punta", "En el medio", "No se puede atacar"),
    Q("¿Qué es un peón pasado protegido?", "Un pasado defendido por otro peón", "Un pasado en la séptima", "Un pasado bloqueado", "Un pasado en el borde"),
    Q("¿Qué es tener mayoría de peones en un flanco?", "Tener ahí más peones que el rival", "Tener más piezas", "Tener peones doblados", "Tener pasados en los dos flancos"),
    Q("¿Para qué sirve una mayoría de peones en el flanco de dama?", "Para crear un peón pasado", "Para atacar al rey", "Para enrocar", "Para defender el centro"),
    Q("¿Qué pieza es ideal para bloquear un peón pasado rival?", "El caballo", "La dama", "La torre", "El rey, siempre"),
    Q("¿Qué son los peones colgantes?", "Dos peones juntos, sin peones propios a los lados, en columnas semiabiertas", "Un peón atacado", "Un peón en el borde", "Peones doblados"),
    Q("¿Qué es una columna semiabierta?", "Una columna con peones de un solo bando", "Una columna sin peones", "Una columna con torres", "Una columna del borde"),
    Q("¿Qué es una columna abierta?", "Una columna sin peones", "Una columna con un solo peón", "Una columna con la dama", "La columna del rey"),
    Q("Contra un peón aislado, ¿qué casilla es buena?", "La que está justo delante de él, para bloquearlo", "La que está detrás", "Cualquiera del borde", "La del rey"),
    Q("¿Los peones doblados son siempre malos?", "No: a veces abren columnas o controlan casillas clave", "Sí, siempre", "Solo en el final", "Solo si son centrales"),
    Q("¿Qué es un agujero?", "Una casilla que ya no pueden defender los propios peones", "Una columna abierta", "Una casilla vacía del centro", "Un peón perdido"),
  ] },
  { titulo: "Finales de rey y peón", nivel: "intermedio", preguntas: [
    Q("¿Qué es la oposición?", "Reyes frente a frente con una casilla en medio; la tiene quien no mueve", "Que los reyes se toquen", "Un tipo de enroque", "Que el rey proteja al peón"),
    Q("¿Qué dice la regla del cuadrado?", "Si el rey rival entra en el cuadrado del peón, lo alcanza", "El peón corona en cuatro jugadas", "El rey debe ir a la esquina", "Los peones valen cuatro"),
    Q("Peón de torre contra rey que llega a la esquina de coronación: ¿qué suele ser?", "Tablas", "Gana siempre el del peón", "Depende del color de la casilla", "Gana el rey solo"),
    Q("En un final de rey y peón, ¿dónde conviene tener el rey?", "Delante de su peón", "Detrás del peón", "En el borde", "Lejos del peón"),
    Q("¿Qué es el zugzwang?", "Estar obligado a mover cuando cualquier jugada empeora", "Un tipo de jaque", "Una apertura alemana", "Tablas por repetición"),
    Q("¿Qué son las casillas clave de un peón?", "Las que, si las ocupa el rey atacante, el peón corona", "Las del centro", "Las esquinas", "Las casillas donde el peón captura"),
    Q("Rey y peón (no de torre) contra rey: el rey atacante llega a la sexta, delante del peón. ¿Qué pasa?", "Gana, le toque a quien le toque", "Tablas siempre", "Depende del reloj", "Gana solo si le toca mover"),
    Q("¿Qué es un peón pasado alejado?", "Un pasado lejos de los demás peones, que desvía al rey rival", "Un pasado en la segunda fila", "Un pasado doblado", "Un peón que no se movió"),
    Q("En los finales de peones, el rey…", "Es una pieza de ataque muy fuerte", "No debe moverse", "Debe quedarse en la esquina", "Vale un punto"),
    Q("¿Qué es la triangulación?", "Mover el rey en triángulo para pasarle el turno al rival", "Un mate con tres piezas", "Un tipo de apertura", "Una cadena de peones"),
    Q("Reyes frente a frente, tu rey delante de tu peón: ¿a quién quieres que le toque mover?", "Al rival: así tienes la oposición", "A ti", "Da igual", "Al árbitro"),
    Q("En rey y peón contra rey, ¿cuál es el error típico que regala las tablas?", "Ahogar al rey rival", "Dar jaque", "Avanzar el rey", "Coronar dama"),
    Q("¿Qué es un rompimiento de peones?", "Un avance, a veces con sacrificio, que crea un peón pasado", "Un peón que se cae", "Un cambio de reyes", "Un jaque de peón"),
    Q("Blancas: a5, b5, c5; negras: a7, b7, c7 (y los reyes lejos). ¿Con qué rompe el blanco?", "b6", "a6", "c6", "No hay rompimiento"),
    Q("Con un peón de más, ¿conviene cambiar piezas?", "Casi siempre: simplificar ayuda a quien tiene ventaja", "Nunca", "Todas menos las damas", "Da igual"),
    Q("¿Qué es un rey activo?", "Un rey centralizado que ataca y apoya a sus peones", "Un rey enrocado", "Un rey en jaque", "Un rey que se mueve sin plan"),
  ] },
  { titulo: "Estrategia del medio juego", nivel: "intermedio", preguntas: [
    Q("¿Qué es un puesto avanzado?", "Una casilla rival, protegida por un peón, que los peones rivales no atacan", "Una casilla de tu primera fila", "Una columna abierta", "El centro"),
    Q("¿Qué pieza es ideal para un puesto avanzado?", "El caballo", "La dama", "El rey", "La torre"),
    Q("¿Qué es un alfil malo?", "Uno trabado por sus peones, puestos en casillas de su color", "Un alfil perdido", "Un alfil en el borde", "Un alfil clavado"),
    Q("¿Dónde conviene poner las torres?", "En columnas abiertas o semiabiertas", "Detrás de peones sin mover", "Siempre en las esquinas", "Delante del rey"),
    Q("¿Qué es doblar las torres?", "Ponerlas en la misma columna o fila", "Coronar otra torre", "Cambiarlas", "Enrocar"),
    Q("¿Qué es la séptima fila para una torre?", "Una fila muy fuerte: ataca peones y encierra al rey", "Una fila mala", "La fila de coronación", "Una fila prohibida"),
    Q("¿Qué es la pareja de alfiles?", "Tener los dos alfiles cuando el rival no los tiene", "Dos alfiles del mismo color", "Un alfil y un caballo", "Dos alfiles clavados"),
    Q("En posiciones abiertas, ¿qué pieza menor suele ser mejor?", "El alfil", "El caballo", "Siempre valen igual", "El peón"),
    Q("En posiciones cerradas, ¿qué pieza menor suele ser mejor?", "El caballo", "El alfil", "La torre", "Ninguna"),
    Q("¿Qué es la iniciativa?", "Poder hacer amenazas que obligan al rival a responder", "Tener más material", "Enrocar primero", "Mover rápido"),
    Q("¿Qué es un plan?", "Una idea de varias jugadas para mejorar la posición", "Una jugada suelta", "Una apertura", "Un sacrificio"),
    Q("¿Qué suele ser un buen plan cuando no sabes qué hacer?", "Mejorar tu pieza peor ubicada", "Mover el rey", "Cambiar la dama", "Avanzar un peón de torre"),
    Q("Uno enrocó corto y el otro largo: ¿qué suele pasar?", "Ataques de peones contra los reyes, en flancos opuestos", "Tablas", "Nadie ataca", "Se cambian las damas"),
    Q("¿Qué es un centro de peones?", "Peones en las columnas d y e que dominan el centro", "Un peón solo en e4", "Los peones del flanco", "Peones doblados"),
    Q("¿Qué es ganar espacio?", "Tener peones avanzados que dan más casillas a tus piezas", "Cambiar piezas", "Enrocar", "Mover el rey"),
    Q("¿Cuándo suele convenir cambiar piezas?", "Con ventaja de material, o para quitar una pieza activa del rival", "Nunca", "Siempre", "Solo al principio"),
  ] },
  { titulo: "El reglamento y el reloj", nivel: "intermedio", preguntas: [
    Q("En una partida oficial tocas a propósito una pieza tuya. ¿Qué haces?", "La mueves, si tiene jugada legal", "Nada", "Avisas al árbitro", "La mueves solo si quieres"),
    Q("¿Con qué mano se aprieta el reloj?", "Con la misma con que se movió la pieza", "Con cualquiera", "Siempre con la izquierda", "Siempre con la derecha"),
    Q("Soltaste la pieza en una casilla legal. ¿Puedes llevarla a otra?", "No", "Sí, mientras no aprietes el reloj", "Sí, si el rival no se dio cuenta", "Solo si es un peón"),
    Q("Se te cae la bandera y tu rival solo tiene el rey. ¿Qué pasa?", "Tablas", "Pierdes", "Ganas", "Se juega otra"),
    Q("¿Quién pide las tablas por triple repetición?", "El jugador, al árbitro", "Solo el árbitro, por su cuenta", "El público", "Nadie: son automáticas desde la tercera"),
    Q("¿Qué pasa si la misma posición se repite cinco veces?", "El árbitro declara tablas aunque nadie las pida", "Nada", "Pierde el que repitió", "Se agrega tiempo"),
    Q("¿Qué dice la regla de las 75 jugadas?", "75 jugadas de cada uno sin capturas ni jugadas de peón: tablas automáticas", "Una partida dura 75 jugadas", "A la 75 se agrega tiempo", "Se pierde por lentitud"),
    Q("¿Puedes tener el celular encendido en la sala durante una partida oficial?", "No: puedes perder la partida", "Sí, para ver la hora", "Sí, si no miras ajedrez", "Solo en tu turno"),
    Q("¿Qué significa decir «compongo»?", "Que vas a acomodar una pieza sin intención de moverla", "Que ofreces tablas", "Que abandonas", "Que llamas al árbitro"),
    Q("Según el reglamento, ¿cuándo se ofrecen tablas?", "Después de hacer tu jugada y antes de apretar el reloj", "En cualquier momento", "Antes de mover, en tu tiempo", "Solo por escrito"),
    Q("¿Qué es el incremento en el reloj?", "Segundos que se suman después de cada jugada", "Tiempo extra al final", "Tiempo que se resta", "El tiempo del árbitro"),
    Q("En «90 minutos + 30 segundos», ¿qué son los 30 segundos?", "Lo que se le suma a cada jugador por jugada", "Tiempo para el final", "Tiempo del árbitro", "Un descanso"),
    Q("En una partida clásica, primera jugada ilegal de un jugador. ¿Qué pasa?", "Se corrige y el rival recibe dos minutos más", "Pierde la partida", "No pasa nada", "Pierde un peón"),
    Q("¿Y si hace una segunda jugada ilegal en esa partida clásica?", "Pierde la partida (salvo que el rival no pueda dar mate)", "El rival recibe otros dos minutos", "Nada", "Se repite la partida"),
    Q("En una partida clásica, ¿quién anota las jugadas?", "Cada jugador anota las suyas y las del rival", "Solo el árbitro", "Solo las blancas", "Nadie"),
    Q("¿Se puede anotar una jugada antes de hacerla?", "No: primero se juega y después se anota", "Sí, es lo recomendado", "Solo en blitz", "Solo si es jaque"),
  ] },
  { titulo: "Mates con nombre", nivel: "intermedio", preguntas: [
    Q("¿Qué es el mate de la coz?", "Un caballo da mate a un rey encerrado por sus propias piezas", "Un mate de torre en la última fila", "Un mate con dos alfiles", "Un mate con peón"),
    Q("¿Qué pieza se sacrifica en la jugada anterior al mate de la coz clásico (el de Philidor)?", "La dama", "La torre", "El alfil", "El caballo"),
    Q("¿Qué aprovecha el mate del pasillo?", "Que el rey está encerrado por sus peones en su primera fila", "Una clavada de la dama", "Un caballo en el centro", "Un alfil malo"),
    Q("¿Qué piezas dan el mate de Anastasia?", "Un caballo y una torre (o la dama)", "Dos alfiles", "La dama y un peón", "Dos caballos"),
    Q("¿Qué piezas dan el mate de Boden?", "Dos alfiles en diagonales cruzadas", "Dos torres", "Caballo y dama", "Torre y alfil"),
    Q("¿Qué es el mate de Legal?", "En la apertura: se entrega la dama y las piezas menores dan mate", "Un mate con dos torres", "Un mate del pasillo", "Un mate con peón"),
    Q("¿Qué es el sacrificio griego?", "Entregar el alfil en h7 (o h2) para abrir al rey enrocado", "Entregar la dama en f7", "Un mate con torre", "Un gambito de apertura"),
    Q("¿Qué es el mate del beso?", "La dama da mate pegada al rey, protegida por otra pieza", "Un mate con el rey", "Un mate de caballo", "Un mate con peones"),
    Q("¿Qué piezas dan el mate árabe?", "Torre y caballo, con el rey en la esquina", "Dos alfiles", "Dama y rey", "Dos caballos"),
    Q("¿Qué es el mate de la escalera?", "Dos piezas mayores empujan al rey al borde, turnándose", "Un mate con un alfil", "Un mate de caballo", "Un mate en el centro"),
    Q("¿Qué piezas dan el mate de Damiano?", "La dama, apoyada por un peón", "Dos torres", "Alfil y caballo", "Dos caballos"),
    Q("¿Con qué otro nombre se conoce el mate de la coz?", "Mate ahogado", "Mate del pasillo", "Mate de Legal", "Mate del pastor"),
    Q("¿Qué es el mate de la charretera?", "El rey queda entre dos piezas propias y la dama da mate de frente", "Un mate con dos caballos", "Un mate en la esquina con alfil", "Un mate de peón"),
    Q("¿Puede un peón dar jaque mate?", "Sí", "No", "Solo al coronar", "Solo al paso"),
    Q("¿Cómo termina la partida de la ópera de Morphy (1858)?", "Con mate de torre en la última fila, apoyada por un alfil", "Con mate de caballo", "Con mate de peón", "En tablas"),
    Q("¿Qué es el «legado de Philidor»?", "Jaques de dama y caballo que terminan en el mate de la coz", "Un final de torres", "Una defensa de apertura", "Un mate con dos alfiles"),
  ] },

  // ============================== AVANZADO ==============================
  { titulo: "Finales de torre", nivel: "avanzado", preguntas: [
    Q("¿Qué es la posición de Lucena?", "Torre y peón contra torre, que se gana «construyendo un puente»", "Una posición de tablas", "Un final de alfiles", "Una apertura"),
    Q("¿Qué es la posición de Philidor en los finales de torre?", "Un método de defensa para hacer tablas contra torre y peón", "Un método para ganar", "Un mate", "Una defensa de apertura"),
    Q("En la defensa de Philidor, ¿dónde pone primero su torre el defensor?", "En su tercera fila, para cortar al rey", "En su primera fila", "Detrás del peón", "Pegada a su rey"),
    Q("En Philidor, cuando el peón llega a esa fila, ¿qué hace el defensor?", "Lleva la torre atrás y da jaques desde lejos", "Cambia torres", "Se queda quieto", "Ataca el peón con el rey"),
    Q("¿Qué es «construir un puente»?", "Usar la torre para tapar los jaques y sacar al rey", "Doblar torres", "Un jaque perpetuo", "Cambiar torres"),
    Q("En la posición de Lucena, ¿a qué fila lleva la torre el atacante?", "A la cuarta", "A la primera", "A la séptima", "A la octava"),
    Q("¿Dónde conviene la torre respecto de un peón pasado?", "Detrás del peón, propio o rival", "Delante del peón", "Siempre al costado", "En la esquina"),
    Q("¿A quién se atribuye esa regla de las torres detrás de los pasados?", "Siegbert Tarrasch", "Philidor", "Capablanca", "Botvínnik"),
    Q("Un final de torre con un peón de más, ¿se gana siempre?", "No: muchos son tablas", "Sí, siempre", "Solo si el peón es central", "Nunca"),
    Q("¿Qué quiere decir «todos los finales de torre son tablas»?", "Que defenderlos es más fácil de lo que parece", "Que nunca se ganan", "Que la torre vale poco", "Que hay que cambiar las torres"),
    Q("¿Qué es cortar al rey en un final de torre?", "Impedir con la torre que el rey rival cruce una fila o columna", "Dar jaque", "Capturar el rey", "Encerrar a la torre"),
    Q("¿Qué es la posición de Vancura?", "Una defensa de tablas contra peón de torre, atacándolo de costado", "Un final de alfiles", "Una forma de ganar con dos peones", "Una apertura"),
    Q("Torre y peón de torre en la séptima, con la torre delante del peón, contra torre: ¿qué suele ser?", "Tablas: la torre atacante no tiene buenas casillas", "Gana siempre", "Pierde el del peón", "Depende del reloj"),
    Q("En un final de torres, ¿torre activa o pasiva?", "Activa, aunque cueste un peón", "Pasiva", "Da igual", "Pasiva si hay peones"),
    Q("Torre contra alfil, sin peones: ¿qué suele ser?", "Tablas, si el rey defensor va a la esquina correcta", "Gana siempre la torre", "Gana el alfil", "Depende del reloj"),
    Q("Torre contra caballo, sin peones: ¿qué suele ser?", "Tablas, si el caballo se queda cerca de su rey", "Gana siempre la torre", "Gana el caballo", "Pierde siempre el caballo"),
  ] },
  { titulo: "Finales teóricos", nivel: "avanzado", preguntas: [
    Q("Dama contra torre, sin peones: ¿qué dice la teoría?", "Gana la dama, aunque cuesta", "Tablas", "Gana la torre", "Depende del color"),
    Q("Rey, alfil y caballo contra rey: ¿en qué esquina se da el mate?", "En una del color del alfil", "En cualquiera", "En el centro", "En una del color contrario"),
    Q("Bien jugado, ¿cuántas jugadas lleva como máximo el mate de alfil y caballo?", "Unas 33", "Unas 10", "Unas 60", "Unas 5"),
    Q("Alfiles de distinto color con un peón de más: ¿qué suele ser?", "Tablas", "Gana siempre", "Pierde", "Depende del rey"),
    Q("Dama contra peón en séptima apoyado por su rey: ¿cuándo suelen ser tablas?", "Si es peón de alfil o de torre", "Nunca", "Siempre", "Si es peón central"),
    Q("¿Por qué dos caballos a veces ganan contra rey y peón, pero no contra el rey solo?", "El peón le da jugadas al rival y evita el ahogado", "El peón da jaque", "Es una regla especial", "El peón corona"),
    Q("¿Quién estudió cuándo ganan dos caballos contra peón (la «línea de Troitzky»)?", "Alexéi Troitzky", "Capablanca", "Morphy", "Philidor"),
    Q("Alfil y peón de torre «del color equivocado» contra rey en la esquina: ¿qué pasa?", "Tablas: el alfil no controla la casilla de coronación", "Gana siempre", "Pierde", "Depende de quién mueva"),
    Q("Torre y alfil contra torre, sin peones: ¿qué suele ser?", "Tablas, aunque hay posiciones ganadas", "Gana siempre", "Pierde", "No se puede defender"),
    Q("¿Qué es una fortaleza?", "Una posición donde el bando con menos material no puede ser vencido", "Un rey enrocado", "Una apertura cerrada", "Un peón pasado"),
    Q("Dos alfiles contra el rey solo: ¿se puede forzar el mate?", "Sí", "No", "Solo si el rival se equivoca", "Solo en cien jugadas"),
    Q("Con dos alfiles contra el rey solo, ¿a dónde hay que llevar al rey rival?", "A una esquina, cualquiera", "Al centro", "A la columna e", "A un costado, lejos de las esquinas"),
    Q("Dama contra dama, sin peones: ¿qué suele ser?", "Tablas", "Gana el que mueve", "Gana el blanco", "Pierde siempre uno"),
    Q("Rey y peón contra rey: ¿qué peón hace tablas si el rey defensor llega a la esquina?", "El de torre", "Los centrales", "El de caballo", "Ninguno"),
    Q("¿Qué es la oposición a distancia?", "Reyes en la misma línea, con un número impar de casillas entre ellos", "Reyes pegados", "Reyes en cualquier diagonal", "Una forma de ahogado"),
    Q("¿Qué enseña el famoso estudio de Réti (1921)?", "Que el rey puede perseguir dos objetivos a la vez, en diagonal", "Que la torre es mejor que el alfil", "Un mate con caballo", "Que el peón de torre siempre gana"),
  ] },
  { titulo: "Variantes de apertura con nombre", nivel: "avanzado", preguntas: [
    Q("1.e4 c5 2.Cf3 d6 3.d4 cxd4 4.Cxd4 Cf6 5.Cc3 a6: ¿qué variante es?", "La Najdorf", "La Dragón", "La Scheveningen", "La Sveshnikov"),
    Q("1.e4 c5 2.Cf3 d6 3.d4 cxd4 4.Cxd4 Cf6 5.Cc3 g6: ¿qué variante es?", "La Dragón", "La Najdorf", "La Scheveningen", "La Taimanov"),
    Q("1.e4 c5 2.Cf3 Cc6 3.d4 cxd4 4.Cxd4 Cf6 5.Cc3 e5: ¿qué variante es?", "La Sveshnikov", "La Najdorf", "La Kalashnikov", "La Taimanov"),
    Q("1.e4 c5 2.c3: ¿qué variante es?", "La Alapin", "El gambito Morra", "La Rossolimo", "La cerrada"),
    Q("1.e4 c5 2.d4 cxd4 3.c3: ¿qué es?", "El gambito Smith-Morra", "La Alapin", "La variante Moscú", "El gambito Wing"),
    Q("1.e4 c5 2.Cf3 Cc6 3.Ab5: ¿qué variante es?", "La Rossolimo", "La Moscú", "La Alapin", "La Grand Prix"),
    Q("1.e4 c5 2.Cf3 d6 3.Ab5+: ¿qué variante es?", "La Moscú", "La Rossolimo", "La Najdorf", "La Richter-Rauzer"),
    Q("En la española cerrada, 7.Ab3 O-O 8.c3 d5: ¿qué es?", "El ataque Marshall", "La berlinesa", "La Zaitsev", "La Breyer"),
    Q("1.e4 e6 2.d4 d5 3.Cc3 Ab4: ¿qué variante es?", "La Winawer", "La Tarrasch", "La Rubinstein", "La clásica"),
    Q("1.e4 e6 2.d4 d5 3.Cd2: ¿qué variante es?", "La Tarrasch", "La Winawer", "La del avance", "La del cambio"),
    Q("1.e4 e6 2.d4 d5 3.e5: ¿qué variante es?", "La del avance", "La Winawer", "La Tarrasch", "La del cambio"),
    Q("1.e4 c6 2.d4 d5 3.e5: ¿qué variante de la Caro-Kann es?", "La del avance", "El ataque Panov", "La clásica", "La del cambio"),
    Q("1.d4 Cf6 2.c4 c5 3.d5 b5: ¿qué es?", "El gambito Benko (o del Volga)", "La Benoni", "El gambito Budapest", "El gambito Blumenfeld"),
    Q("1.d4 Cf6 2.c4 e5: ¿qué es?", "El gambito Budapest", "El gambito Benko", "El contragambito Albin", "El gambito Blackmar"),
    Q("1.d4 d5 2.c4 e5: ¿qué es?", "El contragambito Albin", "El gambito Budapest", "El gambito Benko", "La defensa Chigorin"),
    Q("1.d4 d5 2.e4: ¿qué es?", "El gambito Blackmar-Diemer", "El contragambito Albin", "El gambito Staunton", "El gambito Budapest"),
    Q("1.d4 Cf6 2.c4 e6 3.g3: ¿qué apertura es?", "La catalana", "La Bogo-india", "La india de dama", "La Nimzo-india"),
    Q("1.d4 Cf6 2.c4 e6 3.Cf3 b6: ¿qué defensa es?", "La india de dama", "La Nimzo-india", "La Bogo-india", "La catalana"),
    Q("1.d4 Cf6 2.c4 e6 3.Cf3 Ab4+: ¿qué defensa es?", "La Bogo-india", "La Nimzo-india", "La india de dama", "La catalana"),
  ] },
  { titulo: "Estrategia avanzada", nivel: "avanzado", preguntas: [
    Q("¿Qué es la profilaxis?", "Jugadas que impiden los planes del rival antes de que ocurran", "Un ataque directo", "Un tipo de apertura", "Cambiar las damas"),
    Q("¿Quiénes hicieron de la profilaxis un método?", "Nimzowitsch y, después, Petrosián", "Tal y Morphy", "Anderssen y Morphy", "Steinitz y Tal"),
    Q("¿Qué es el ataque de minorías?", "Avanzar menos peones contra una mayoría rival para crearle debilidades", "Atacar con pocas piezas", "Atacar con el rey", "Un sacrificio de calidad"),
    Q("¿En qué estructura es típico el ataque de minorías?", "En la Carlsbad (gambito de dama, variante del cambio)", "En la siciliana Dragón", "En la india de rey", "En el gambito de rey"),
    Q("¿Qué es un sacrificio de calidad posicional?", "Dar una torre por una pieza menor a cambio de ventajas duraderas", "Perder una torre sin querer", "Cambiar dama por torre", "Dar un peón en la apertura"),
    Q("¿Qué campeón era famoso por sus sacrificios de calidad posicionales?", "Tigrán Petrosián", "Bobby Fischer", "Emanuel Lasker", "Vasili Smyslov"),
    Q("¿Qué es el bloqueo, según Nimzowitsch?", "Poner una pieza delante de un peón pasado rival para frenarlo", "Encerrar al rey", "Tapar un jaque", "Cerrar el centro con peones"),
    Q("¿Qué libro escribió Nimzowitsch?", "«Mi sistema»", "«Mis 60 partidas memorables»", "«Piense como un gran maestro»", "«Manual de finales»"),
    Q("¿Qué es el principio de las dos debilidades?", "Para ganar, suele hacer falta una segunda debilidad lejos de la primera", "Tener dos peones doblados", "Tener los dos alfiles", "Atacar dos veces una pieza"),
    Q("Con tus peones fijos en casillas claras, ¿qué alfil tuyo es el malo?", "El de casillas claras", "El de casillas oscuras", "Ninguno", "Los dos"),
    Q("¿Qué es el juego posicional?", "Mejorar poco a poco la posición según sus rasgos, sin atacar ya", "Jugar solo aperturas", "Jugar rápido", "Atacar siempre al rey"),
    Q("Tu rival tiene el peón aislado de dama. ¿Qué buscas en general?", "Cambiar piezas y bloquear el peón", "Atacar a su rey de inmediato", "Ofrecer tablas", "Cambiar tu caballo bloqueador"),
    Q("¿Qué es una ruptura en una estructura cerrada?", "Un avance de peón que abre líneas para tus piezas", "Un cambio de damas", "Un sacrificio de dama", "Un enroque"),
    Q("India de rey clásica, centro cerrado (blancas d5, negras e5): ¿dónde atacan las negras?", "En el flanco de rey, con ...f5", "En el flanco de dama, con ...c5", "En el centro, con ...d5", "No atacan"),
    Q("En esa misma estructura, ¿dónde atacan las blancas?", "En el flanco de dama, con c5", "En el flanco de rey", "Siempre con f4", "No atacan"),
    Q("¿Qué es la ventaja de desarrollo?", "Tener más piezas en juego que el rival", "Tener más material", "Tener el rey enrocado", "Tener más tiempo en el reloj"),
  ] },
  { titulo: "Los campeones del mundo", nivel: "avanzado", preguntas: [
    Q("¿Quién fue el primer campeón mundial oficial, en 1886?", "Wilhelm Steinitz", "Emanuel Lasker", "Paul Morphy", "José Raúl Capablanca"),
    Q("¿Quién tuvo el título más tiempo, 27 años?", "Emanuel Lasker", "Garry Kaspárov", "Anatoli Kárpov", "Magnus Carlsen"),
    Q("¿A quién le ganó Capablanca el título en 1921?", "A Emanuel Lasker", "A Alexander Alekhine", "A Wilhelm Steinitz", "A Max Euwe"),
    Q("¿Quién le ganó el título a Capablanca en 1927?", "Alexander Alekhine", "Max Euwe", "Emanuel Lasker", "Mijaíl Botvínnik"),
    Q("¿Qué campeón murió con el título, en 1946?", "Alexander Alekhine", "José Raúl Capablanca", "Mijaíl Tal", "Tigrán Petrosián"),
    Q("¿Quién ganó el torneo-match de 1948 y fue campeón?", "Mijaíl Botvínnik", "Vasili Smyslov", "Paul Keres", "Max Euwe"),
    Q("¿De qué país era Max Euwe, campeón en 1935?", "Países Bajos", "Alemania", "Bélgica", "Suiza"),
    Q("¿Qué campeón era llamado «el mago de Riga»?", "Mijaíl Tal", "Tigrán Petrosián", "Borís Spassky", "Vasili Smyslov"),
    Q("¿A quién le ganó Fischer el título en 1972?", "A Borís Spassky", "A Tigrán Petrosián", "A Anatoli Kárpov", "A Mijaíl Tal"),
    Q("¿Cómo llegó Kárpov al título en 1975?", "Fischer no defendió el título", "Le ganó a Fischer un match", "Le ganó a Spassky el match por el título", "Ganó un torneo"),
    Q("¿En qué año se coronó Garry Kaspárov?", "1985", "1984", "1990", "1978"),
    Q("¿Quién le ganó a Kaspárov el match de Londres 2000?", "Vladímir Krámnik", "Viswanathan Anand", "Veselin Topálov", "Anatoli Kárpov"),
    Q("¿De qué país es Viswanathan Anand?", "India", "Sri Lanka", "Pakistán", "Bangladés"),
    Q("¿A quién le ganó Magnus Carlsen el título en 2013?", "A Viswanathan Anand", "A Serguéi Kariakin", "A Fabiano Caruana", "A Vladímir Krámnik"),
    Q("¿Quién fue campeón en 2023, cuando Carlsen no defendió el título?", "Ding Liren", "Ian Nepómniashchi", "Fabiano Caruana", "Hikaru Nakamura"),
    Q("¿Quién ganó el título mundial en 2024?", "Gukesh Dommaraju", "Ding Liren", "Ian Nepómniashchi", "Alireza Firouzja"),
    Q("¿Quién es considerada la mejor jugadora de la historia, aunque nunca jugó el mundial femenino?", "Judit Polgár", "Hou Yifan", "Maia Chiburdanidze", "Vera Ménchik"),
  ] },
  { titulo: "Partidas célebres", nivel: "avanzado", preguntas: [
    Q("¿Quiénes jugaron «la Inmortal» (Londres, 1851)?", "Anderssen y Kieseritzky", "Morphy y el duque de Brunswick", "Fischer y Spassky", "Kaspárov y Topálov"),
    Q("¿Qué entregó Anderssen en la Inmortal?", "Las dos torres, la dama y un alfil", "Solo la dama", "Solo un caballo", "Nada: ganó con material"),
    Q("¿Contra quién jugó Anderssen «la Siempreviva» (1852)?", "Jean Dufresne", "Lionel Kieseritzky", "Paul Morphy", "Howard Staunton"),
    Q("¿Dónde jugó Morphy «la partida de la ópera» (1858)?", "En un palco de la Ópera de París", "En Nueva Orleans", "En Londres", "En Viena"),
    Q("¿Contra quiénes jugó Morphy esa partida?", "El duque de Brunswick y el conde Isouard, en consulta", "Adolf Anderssen", "Howard Staunton", "Johann Löwenthal"),
    Q("¿Cómo se conoce la partida de Fischer contra Donald Byrne (1956)?", "«La partida del siglo»", "«La Inmortal»", "«La Siempreviva»", "«La del milenio»"),
    Q("¿Cuántos años tenía Fischer en «la partida del siglo»?", "13", "17", "21", "10"),
    Q("¿Qué entregó Fischer en esa partida?", "Su dama", "Las dos torres", "Solo un caballo", "Nada"),
    Q("¿Contra quién jugó Kaspárov su famosa partida de Wijk aan Zee 1999?", "Veselin Topálov", "Anatoli Kárpov", "Vladímir Krámnik", "Viswanathan Anand"),
    Q("¿Qué computadora le ganó el match a Kaspárov en 1997?", "Deep Blue", "Deep Fritz", "Stockfish", "Deep Junior"),
    Q("¿Qué pasó en la partida 6 del match Fischer–Spassky (1972)?", "Fischer abrió 1.c4, rarísimo en él, y Spassky aplaudió su victoria", "Fischer no se presentó", "Spassky ganó en 20 jugadas", "Terminó en tablas"),
    Q("¿Por qué perdió Fischer la partida 2 de ese match?", "No se presentó", "Por tiempo", "Por una jugada ilegal", "Abandonó en la jugada 5"),
    Q("¿En qué ciudad se jugó el match Fischer–Spassky?", "Reikiavik", "Moscú", "Nueva York", "Buenos Aires"),
    Q("¿Cuánto duró el primer match Kárpov–Kaspárov (1984-85) antes de suspenderse?", "Unos cinco meses, 48 partidas", "Un año", "Una semana", "Dos años"),
    Q("¿Qué pasó en la primera partida Deep Blue–Kaspárov (1996)?", "Ganó Deep Blue: la primera victoria de una máquina ante el campeón", "Ganó Kaspárov", "Tablas", "No se jugó"),
    Q("¿Qué programa sorprendió en 2017 al aprender ajedrez jugando solo contra sí mismo?", "AlphaZero", "Deep Blue", "Fritz", "Rybka"),
  ] },
  { titulo: "Cálculo y conceptos finos", nivel: "avanzado", preguntas: [
    Q("¿Qué es un zugzwang mutuo?", "A quien le toque mover, empeora su posición", "Un jaque doble", "Un zugzwang de dos jugadas", "Tablas por repetición"),
    Q("¿Qué es una jugada candidata?", "Una de las jugadas que vale la pena calcular", "La mejor jugada", "La jugada del rival", "Una jugada de apertura"),
    Q("¿Quién popularizó las jugadas candidatas y el «árbol de variantes»?", "Alexander Kotov", "Aarón Nimzowitsch", "François-André Philidor", "Wilhelm Steinitz"),
    Q("¿Qué es el efecto horizonte?", "No ver lo que pasa justo después de donde terminó el cálculo", "Mirar solo el borde del tablero", "Un error de apertura", "Un tipo de ahogado"),
    Q("¿Qué es una jugada tranquila dentro de una combinación?", "Una sin jaque ni captura que crea una amenaza decisiva", "Una jugada de defensa", "Tablas", "Un enroque"),
    Q("¿Qué es ganar un tempo?", "Obligar al rival a gastar una jugada, por ejemplo atacando una pieza", "Ganar tiempo en el reloj", "Ganar un final", "Jugar la italiana"),
    Q("¿Qué es una posición crítica?", "Un momento en que la decisión cambia el rumbo y conviene pensar más", "Una posición perdida", "La posición inicial", "Un jaque"),
    Q("¿Qué es calcular por eliminación?", "Descartar las jugadas que no sirven hasta quedarse con la mejor", "Cambiar todas las piezas", "Jugar la primera que se ve", "Calcular solo jugadas de peón"),
    Q("En una posición táctica, ¿qué jugadas se miran primero?", "Jaques, capturas y amenazas", "Jugadas de peón", "Jugadas de rey", "Jugadas lentas"),
    Q("¿Qué es la visualización?", "Ver en la cabeza cómo queda la posición tras varias jugadas", "Mirar el tablero", "Ver partidas en video", "Jugar siempre a ciegas"),
    Q("¿Qué es un recurso defensivo?", "Una jugada que salva una posición que parecía perdida", "Un enroque", "Una apertura defensiva", "Abandonar a tiempo"),
    Q("¿Qué es un estudio de ajedrez?", "Una posición compuesta, con una solución única y artística", "Una partida de torneo", "Un libro de aperturas", "Una clase"),
    Q("¿Qué es un problema como «mate en 2»?", "Una posición compuesta con una tarea: dar mate en esas jugadas", "Un final real", "Un error de apertura", "Una partida perdida"),
    Q("¿Qué es un sacrificio de despeje?", "Entregar una pieza para que otra use su casilla o su línea", "Cambiar piezas", "Siempre un sacrificio de dama", "Enrocar"),
    Q("¿Qué es una celada?", "Una trampa: una jugada que tienta al rival a equivocarse", "Un mate", "Un final", "Un gambito aceptado"),
    Q("¿Hasta dónde conviene calcular una variante forzada?", "Hasta que no quedan jaques ni capturas pendientes, y ahí evaluar", "Siempre diez jugadas", "Hasta el primer jaque", "Solo la respuesta del rival"),
  ] },
  { titulo: "Finales de piezas menores", nivel: "avanzado", preguntas: [
    Q("Alfil contra caballo, con peones en los dos flancos: ¿quién suele estar mejor?", "El alfil", "El caballo", "Da igual", "El que tenga el rey en la esquina"),
    Q("Con peones en un solo flanco y posición cerrada, ¿qué pieza suele rendir bien?", "El caballo", "El alfil", "Ninguna", "Da igual"),
    Q("¿Qué es el alfil bueno en un final?", "El que no está trabado por sus propios peones", "El que va por casillas claras", "El del flanco de rey", "El que se movió primero"),
    Q("Si tienes alfil, ¿dónde conviene poner tus peones?", "En casillas del color contrario al de tu alfil", "En casillas del mismo color", "En el borde", "No importa"),
    Q("¿Por qué al caballo le cuestan los peones de torre?", "En el borde tiene menos casillas para frenarlos", "No puede capturar peones", "Salta demasiado lejos", "Vale poco"),
    Q("Alfiles del mismo color e igualdad de peones: ¿cómo se busca ganar?", "Con el rey más activo, el mejor alfil y creando debilidades", "No se puede", "Cambiando alfiles siempre", "Con jaques"),
    Q("Alfiles de distinto color con dos peones de más: ¿qué suele pasar?", "Muchas veces se gana, si los peones están bien separados", "Siempre tablas", "Siempre se gana", "Pierde el que tiene más"),
    Q("¿Qué pieza no puede perder un tiempo (volver a su casilla en un número impar de jugadas)?", "El caballo", "El alfil", "La torre", "El rey"),
    Q("¿Qué dijo Botvínnik de los finales de caballo?", "Que son finales de peones", "Que siempre se ganan", "Que el caballo vale como una torre", "Que hay que cambiar el caballo"),
    Q("Rey, alfil y peón de torre contra rey, con el alfil del color de la casilla de coronación: ¿qué es?", "Gana", "Tablas", "Pierde", "Depende del reloj"),
    Q("Un caballo solo, ¿puede frenar un peón pasado?", "Sí, muchas veces, si llega a tiempo delante del peón", "Nunca", "Solo en la séptima", "Solo con ayuda del rey"),
    Q("¿Qué ventaja tiene el alfil contra los peones?", "Puede frenarlos a distancia", "Ninguna", "Salta", "Da mate solo"),
    Q("Final de alfiles del mismo color: ¿qué peones rivales son blanco fácil?", "Los que están en casillas del color de tu alfil", "Los otros", "Ninguno", "Siempre los pasados"),
    Q("¿Por qué el rey se vuelve una pieza fuerte en el final?", "Ya no hay peligro de mate y puede atacar y defender", "Porque vale cuatro puntos", "Porque no recibe jaques", "Porque salta"),
    Q("Caballo y peón contra el rey solo: ¿se gana en general?", "Sí, casi siempre, salvo algunas posiciones con peón de torre", "No, nunca", "Solo con peón central", "Solo con el caballo en el centro"),
    Q("Alfil contra caballo, peones bloqueados en casillas del color del alfil: ¿quién está mejor?", "El caballo", "El alfil", "Igual", "Nadie"),
  ] },
  { titulo: "Torneos y reglamento FIDE", nivel: "avanzado", preguntas: [
    Q("¿Qué es el sistema suizo?", "Se empareja a quienes tienen puntajes parecidos, sin eliminar a nadie", "Todos contra todos", "Eliminación directa", "Un sistema por equipos"),
    Q("¿Qué es un todos contra todos (round robin)?", "Cada jugador juega contra todos los demás", "Se elimina al que pierde", "Se juega por equipos", "Se juega solo blitz"),
    Q("¿Para qué sirven los desempates (Buchholz, Sonneborn-Berger…)?", "Para ordenar a quienes terminaron con los mismos puntos", "Para dar más tiempo", "Para sortear colores", "Para descalificar"),
    Q("¿Qué mide el Buchholz?", "La suma de los puntos de los rivales de un jugador", "Los puntos del jugador", "Las partidas con blancas", "Las victorias con negras"),
    Q("¿Qué es un bye en un torneo suizo?", "Una ronda sin rival, que suma lo que diga el reglamento", "Una partida perdida", "Unas tablas", "Una descalificación"),
    Q("Si el reglamento del torneo no dice otra cosa, ¿cuánto tiempo de espera hay?", "Cero: hay que estar en el tablero al empezar", "15 minutos", "30 minutos", "Una hora"),
    Q("Llegas al tablero después del tiempo de espera fijado. ¿Qué pasa?", "Pierdes por incomparecencia", "Se te resta la mitad del tiempo", "Juegas igual", "Tablas"),
    Q("¿Quién puede hacer valer que a un jugador se le cayó la bandera?", "El árbitro o cualquiera de los jugadores", "Solo el rival", "Los espectadores", "Nadie"),
    Q("Para la FIDE, ¿qué es una partida rápida?", "Más de 10 y menos de 60 minutos por jugador (con el incremento)", "Menos de 10 minutos", "Más de 90 minutos", "Exactamente 25 minutos"),
    Q("Para la FIDE, ¿qué es una partida blitz?", "10 minutos o menos por jugador (con el incremento)", "Menos de 3 minutos", "Entre 15 y 30 minutos", "Un minuto exacto"),
    Q("Un peón llega a la octava, aprietas el reloj y el peón sigue ahí sin cambiar. ¿Qué es?", "Una jugada ilegal", "Se toma como dama y sigue", "Tablas", "Nada"),
    Q("¿Cómo se llama la hoja donde se anotan las jugadas?", "La planilla", "El acta", "El FEN", "El Elo"),
    Q("En plena partida, ¿puedes salir de la sala de juego sin permiso del árbitro?", "No", "Sí, cuando quieras", "Solo en tu turno", "Solo si abandonas"),
    Q("Suena tu celular en la sala durante la partida. ¿Qué pasa?", "Pierdes la partida, salvo que el reglamento diga otra cosa", "Nada", "Pierdes 5 minutos", "Te advierten"),
    Q("Se te cae la bandera; tú solo tienes el rey y tu rival, rey y caballo. ¿Qué pasa?", "Tablas: nadie puede dar mate", "Pierdes", "Ganas", "Se sigue jugando"),
    Q("¿Cuándo se pueden reclamar tablas por la regla de las 50 jugadas?", "Tras 50 jugadas de cada bando sin capturas ni jugadas de peón", "Tras 50 jugadas en total", "Con 50 segundos en el reloj", "Nunca"),
  ] },
  { titulo: "Grandes jugadores y sus estilos", nivel: "avanzado", preguntas: [
    Q("¿Qué jugador del siglo XIX arrasó en Europa en 1858 con su desarrollo rápido y sus ataques?", "Paul Morphy", "Wilhelm Steinitz", "Adolf Anderssen", "Mijaíl Chigorin"),
    Q("¿A quién se considera el padre del juego posicional moderno?", "Wilhelm Steinitz", "Paul Morphy", "Mijaíl Tal", "Adolf Anderssen"),
    Q("¿Qué campeón cubano era famoso por su técnica en los finales y su juego natural?", "José Raúl Capablanca", "Alexander Alekhine", "Max Euwe", "Emanuel Lasker"),
    Q("¿Qué campeón era famoso por sus sacrificios intuitivos y ataques salvajes?", "Mijaíl Tal", "Tigrán Petrosián", "Anatoli Kárpov", "Vladímir Krámnik"),
    Q("¿A qué campeón llamaban «Tigrán de hierro» por su defensa?", "Tigrán Petrosián", "Mijaíl Tal", "Borís Spassky", "Mijaíl Botvínnik"),
    Q("¿Quién escribió «Mis 60 partidas memorables»?", "Bobby Fischer", "Garry Kaspárov", "Mijaíl Tal", "Anatoli Kárpov"),
    Q("¿Qué campeón era famoso por su estilo de «boa constrictor», asfixiando poco a poco al rival?", "Anatoli Kárpov", "Mijaíl Tal", "Paul Morphy", "Adolf Anderssen"),
    Q("¿Qué defensa usó Krámnik para frenar a Kaspárov en el match de 2000?", "La berlinesa", "La Najdorf", "La Grünfeld", "La francesa"),
    Q("¿Qué país dominó el ajedrez mundial en la segunda mitad del siglo XX?", "La Unión Soviética", "Estados Unidos", "Alemania", "Argentina"),
    Q("¿Quién fue el primer campeón mundial nacido en la India?", "Viswanathan Anand", "Gukesh Dommaraju", "Pentala Harikrishna", "Vidit Gujrathi"),
    Q("¿Quién alcanzó el Elo más alto de la historia, 2882?", "Magnus Carlsen", "Garry Kaspárov", "Fabiano Caruana", "Bobby Fischer"),
    Q("¿Qué gran maestro nacido en Polonia se quedó a vivir en Argentina desde 1939?", "Miguel Najdorf", "Oscar Panno", "Hermann Pilnik", "Erich Eliskases"),
    Q("¿Qué jugadora húngara llegó a estar entre los diez mejores del mundo en la categoría absoluta?", "Judit Polgár", "Susan Polgár", "Hou Yifan", "Ju Wenjun"),
    Q("¿Qué campeón mundial era además doctor en ingeniería eléctrica?", "Mijaíl Botvínnik", "Mijaíl Tal", "Borís Spassky", "Vasili Smyslov"),
    Q("¿Qué campeón mundial era doctor en matemáticas?", "Emanuel Lasker", "José Raúl Capablanca", "Mijaíl Tal", "Anatoli Kárpov"),
    Q("¿Qué campeón mundial fue profesor de matemáticas?", "Max Euwe", "Alexander Alekhine", "Bobby Fischer", "Magnus Carlsen"),
  ] },
];

// Siempre el mismo lugar para la misma pregunta: sembrar dos veces da lo mismo.
function hash(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
const VF = ["Verdadero", "Falso"];

// El tiempo: 30 s, y 60 s si hay mucho que leer.
function tiempoDe(p) {
  const largo = p.texto.length + p.correcta.length + p.otras.reduce((a, o) => a + o.length, 0);
  return largo > 200 ? 60 : 30;
}

function armar(p) {
  const todas = [p.correcta, ...p.otras];
  let opciones, correcta;
  if (todas.length === 2 && VF.includes(todas[0]) && VF.includes(todas[1])) {
    opciones = VF.slice();
    correcta = VF.indexOf(p.correcta);
  } else {
    // El lugar de la correcta sale del texto; las demás, en el orden escrito.
    correcta = hash(p.texto) % todas.length;
    opciones = p.otras.slice();
    opciones.splice(correcta, 0, p.correcta);
  }
  return { texto: p.texto, opciones, correcta, tiempo: tiempoDe(p), fen: null };
}

const cuestionarios = () => LISTOS.map((c) => ({ titulo: c.titulo, nivel: c.nivel, preguntas: c.preguntas.map(armar) }));

/* Una sentencia por nivel, con cada pregunta como [texto, opciones, correcta,
   tiempo]: la base arma el objeto. Así el SQL pesa un cuarto menos y cabe en
   el editor de Supabase de a un nivel por vez (cada sentencia es completa). */
function sql() {
  const partes = [
    "-- Generado por herramientas/cuestionarios-listos.js: no se edita a mano.",
    "delete from public.cuestionarios where listo;",
  ];
  ["inicial", "intermedio", "avanzado"].forEach((nivel) => {
    const filas = cuestionarios().filter((c) => c.nivel === nivel).map((c) => "($q$" + c.titulo + "$q$, $q$"
      + JSON.stringify(c.preguntas.map((p) => [p.texto, p.opciones, p.correcta, p.tiempo])) + "$q$::jsonb)");
    partes.push("with d(titulo, p) as (values\n" + filas.join(",\n") + ")\n"
      + "insert into public.cuestionarios (titulo, nivel, listo, profesor_id, preguntas)\n"
      + "select titulo, '" + nivel + "', true, null, (select jsonb_agg(jsonb_build_object('texto', e->>0, 'opciones', e->1, "
      + "'correcta', (e->>2)::int, 'tiempo', (e->>3)::int, 'fen', null) order by o) from jsonb_array_elements(p) with ordinality x(e, o)) from d;");
  });
  return partes.join("\n") + "\n";
}

module.exports = { LISTOS, armar, cuestionarios, sql };

if (require.main === module) {
  const dir = path.join(__dirname, "cuestionarios");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "semilla.sql"), sql());
  const n = LISTOS.reduce((a, c) => a + c.preguntas.length, 0);
  console.log("herramientas/cuestionarios/semilla.sql: " + LISTOS.length + " cuestionarios, " + n + " preguntas.");
}
