/* ===== Las posiciones de «Rompe el estancamiento», de Oscar Angulo Cubero =====
 *
 * GENERADO por herramientas/rompe-el-estancamiento-generar.js — no se edita a mano.
 *
 * 115 posiciones de la base abierta de Lichess (CC0), comprobadas con
 * Stockfish: 35 ejemplos (uno por lección, los mismos del curso),
 * 56 ejercicios por capítulo y 24 mixtos. Lo usa el libro
 * (herramientas/rompe-el-estancamiento-pdf.js). Vive detrás del candado de
 * material/: trae las respuestas.
 */
window.ROMPE_EL_ESTANCAMIENTO = {
  TITULO: 'Rompe el estancamiento',
  AUTOR: 'Oscar Angulo Cubero',
  POR_CAPITULO: 8,
  MIXTOS: 24,
  CAPITULOS: [{ n: 1, titulo: 'Jugar con un plan', temas: ['quietMove', 'pawnEndgame', 'clearance'] }, { n: 2, titulo: 'Los conceptos que sí sirven', temas: ['exposedKing', 'sacrifice', 'deflection'] }, { n: 3, titulo: 'Leer la posición más allá de las jugadas', temas: ['pawnEndgame', 'intermezzo', 'defensiveMove', 'veryLong'] }, { n: 4, titulo: 'Cambios y transformaciones', temas: ['pawnEndgame', 'zugzwang', 'clearance'] }, { n: 5, titulo: 'Cálculo y visualización', temas: ['veryLong', 'intermezzo', 'attraction'] }, { n: 6, titulo: 'Pensar también por el rival', temas: ['defensiveMove', 'zugzwang'] }, { n: 7, titulo: 'La cabeza en la partida', temas: ['sacrifice', 'defensiveMove', 'exposedKing'] }, { n: 8, titulo: 'Tu propio método', temas: [] }],
};
window.ROMPE_EL_ESTANCAMIENTO_ITEMS = [
  {
    n: 1,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 1,
    id: 're_0jVsL',
    tema: 'quietMove',
    lichess: '0jVsL',
    rating: 1263,
    elo: 483,
    juegan: 'b',
    fen: '8/8/8/p5Rp/1r5P/1k3PK1/8/8 b - - 2 46',
    ultima: 'Tg5',
    marca: ['g6', 'g5'],
    solucion: { from: 'a5', to: 'a4' },
    primera: 'a4',
    linea: '46…a4 47.Txh5 a3 48.Te5 a2',
    gana: true,
    valor: '+3,4',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0jVsL de la base abierta de Lichess (CC0), rating 1263. Stockfish 16 a profundidad 18: a4 es la mejor (+3,4) y la segunda queda en 0,0.',
  },
  {
    n: 2,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 2,
    id: 're_2T8eM',
    tema: 'quietMove',
    lichess: '2T8eM',
    rating: 1480,
    elo: 700,
    juegan: 'w',
    fen: '1r3rk1/1p3pp1/1q6/p2p2PQ/8/P7/1bP1R3/4R2K w - - 0 28',
    ultima: 'cxd5',
    marca: ['c6', 'd5'],
    solucion: { from: 'e2', to: 'h2' },
    primera: 'Th2',
    linea: '28.Th2 Dh6 29.gxh6',
    gana: true,
    valor: '+5,8',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2T8eM de la base abierta de Lichess (CC0), rating 1480. Stockfish 16 a profundidad 18: Th2 es la mejor (+5,8) y la segunda queda en -4,5.',
  },
  {
    n: 3,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 3,
    id: 're_10hcN',
    tema: 'pawnEndgame',
    lichess: '10hcN',
    rating: 1578,
    elo: 798,
    juegan: 'b',
    fen: '4k3/p7/4Kp2/2P1p1p1/P7/5P2/7P/8 b - - 6 46',
    ultima: 'Re6',
    marca: ['d6', 'e6'],
    solucion: { from: 'g5', to: 'g4' },
    primera: 'g4',
    linea: '46…g4 47.fxg4 e4 48.Rxf6 e3',
    gana: true,
    valor: '+3,2',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 10hcN de la base abierta de Lichess (CC0), rating 1578. Stockfish 16 a profundidad 18: g4 es la mejor (+3,2) y la segunda queda en -6,2.',
  },
  {
    n: 4,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 4,
    id: 're_1xOmS',
    tema: 'clearance',
    lichess: '1xOmS',
    rating: 1391,
    elo: 611,
    juegan: 'b',
    fen: '2kr1r2/p1pn1R2/1p1pQ2p/8/2PP3N/2q3P1/P5PP/5R1K b - - 0 23',
    ultima: 'Dxe6',
    marca: ['g4', 'e6'],
    solucion: { from: 'f8', to: 'f7' },
    primera: 'Txf7',
    linea: '23…Txf7 24.Dxf7 Tf8 25.Dxf8+ Cxf8',
    gana: true,
    valor: '+4,3',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 1xOmS de la base abierta de Lichess (CC0), rating 1391. Stockfish 16 a profundidad 18: Txf7 es la mejor (+4,3) y la segunda queda en -0,7.',
  },
  {
    n: 5,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 5,
    id: 're_283ff',
    tema: 'exposedKing',
    lichess: '283ff',
    rating: 1567,
    elo: 787,
    juegan: 'w',
    fen: '4k3/1p2r1b1/p1p3pp/2q5/4P3/1Q4P1/PPP2P1P/3R2K1 w - - 9 23',
    ultima: 'Re8',
    marca: ['f7', 'e8'],
    solucion: { from: 'b3', to: 'g8' },
    primera: 'Dg8+',
    linea: '23.Dg8+ Af8 24.Dxg6+ Tf7 25.De6+',
    gana: true,
    valor: '+3,6',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 283ff de la base abierta de Lichess (CC0), rating 1567. Stockfish 16 a profundidad 18: Dg8+ es la mejor (+3,6) y la segunda queda en -1,8.',
  },
  {
    n: 6,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 6,
    id: 're_3P7FK',
    tema: 'sacrifice',
    lichess: '3P7FK',
    rating: 1422,
    elo: 642,
    juegan: 'b',
    fen: '3rr1k1/1pp2pp1/5q1p/8/1QPp4/3P2Pb/PP2BP2/R3R1K1 b - - 0 22',
    ultima: 'Dxb4',
    marca: ['c5', 'b4'],
    solucion: { from: 'e8', to: 'e2' },
    primera: 'Txe2',
    linea: '22…Txe2 23.Txe2 Df3',
    gana: true,
    valor: '+6,1',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 3P7FK de la base abierta de Lichess (CC0), rating 1422. Stockfish 16 a profundidad 18: Txe2 es la mejor (+6,1) y la segunda queda en +1,1.',
  },
  {
    n: 7,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 7,
    id: 're_0N87n',
    tema: 'exposedKing',
    lichess: '0N87n',
    rating: 1325,
    elo: 545,
    juegan: 'w',
    fen: 'r7/2p2r1k/1p1pR2b/5q2/1B3Q2/P6P/5P2/4K3 w - - 0 41',
    ultima: 'Axh6',
    marca: ['g7', 'h6'],
    solucion: { from: 'f4', to: 'h6' },
    primera: 'Dxh6+',
    linea: '41.Dxh6+ Rg8 42.Tg6+ Dxg6 43.Dxg6+',
    gana: true,
    valor: '+4,9',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: '',
    comprobado: 'Ejercicio 0N87n de la base abierta de Lichess (CC0), rating 1325. Stockfish 16 a profundidad 18: Dxh6+ es la mejor (+4,9) y la segunda queda en -3,8.',
  },
  {
    n: 8,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 8,
    id: 're_2UQNN',
    tema: 'deflection',
    lichess: '2UQNN',
    rating: 1407,
    elo: 627,
    juegan: 'b',
    fen: '2k3r1/pp2pn2/2np4/2p5/5PN1/P2P1K2/1PP5/R4R2 b - - 2 26',
    ultima: 'Rf3',
    marca: ['g2', 'f3'],
    solucion: { from: 'c6', to: 'd4' },
    primera: 'Cd4+',
    linea: '26…Cd4+ 27.Rf2 Txg4',
    gana: true,
    valor: '+3,7',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2UQNN de la base abierta de Lichess (CC0), rating 1407. Stockfish 16 a profundidad 18: Cd4+ es la mejor (+3,7) y la segunda queda en -1,8.',
  },
  {
    n: 9,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 9,
    id: 're_17Hf8',
    tema: 'pawnEndgame',
    lichess: '17Hf8',
    rating: 1535,
    elo: 755,
    juegan: 'w',
    fen: '8/2p3K1/p1p4p/8/1k6/7P/5P2/8 w - - 0 35',
    ultima: 'Rxb4',
    marca: ['a3', 'b4'],
    solucion: { from: 'f2', to: 'f4' },
    primera: 'f4',
    linea: '35.f4 a5 36.f5 c5 37.f6',
    gana: true,
    valor: '+3,3',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 17Hf8 de la base abierta de Lichess (CC0), rating 1535. Stockfish 16 a profundidad 18: f4 es la mejor (+3,3) y la segunda queda en -1,7.',
  },
  {
    n: 10,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 10,
    id: 're_34QhP',
    tema: 'sacrifice',
    lichess: '34QhP',
    rating: 1458,
    elo: 678,
    juegan: 'w',
    fen: 'r1b2rk1/pp3p1p/1n2p1p1/8/4N1n1/4B1Pq/PPB1QP2/R4RK1 w - - 2 20',
    ultima: 'Cg4',
    marca: ['e5', 'g4'],
    solucion: { from: 'e2', to: 'g4' },
    primera: 'Dxg4',
    linea: '20.Dxg4 Dxg4 21.Cf6+ Rh8 22.Cxg4',
    gana: true,
    valor: '+4,7',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 34QhP de la base abierta de Lichess (CC0), rating 1458. Stockfish 16 a profundidad 18: Dxg4 es la mejor (+4,7) y la segunda queda en -3,9.',
  },
  {
    n: 11,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 11,
    id: 're_30JV8',
    tema: 'intermezzo',
    lichess: '30JV8',
    rating: 1356,
    elo: 576,
    juegan: 'b',
    fen: '2r3k1/1p4pp/2br1p2/1N6/8/P2PKP2/1P4PP/2R4R b - - 0 27',
    ultima: 'Cxb5',
    marca: ['d4', 'b5'],
    solucion: { from: 'c8', to: 'e8' },
    primera: 'Te8+',
    linea: '27…Te8+ 28.Rf2 Axb5',
    gana: true,
    valor: '+4,1',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 30JV8 de la base abierta de Lichess (CC0), rating 1356. Stockfish 16 a profundidad 18: Te8+ es la mejor (+4,1) y la segunda queda en -2,1.',
  },
  {
    n: 12,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 12,
    id: 're_30ZBU',
    tema: 'defensiveMove',
    lichess: '30ZBU',
    rating: 1301,
    elo: 521,
    juegan: 'b',
    fen: '8/3R1N2/p1p5/2k5/4pq2/5p2/PP1R4/5K2 b - - 3 43',
    ultima: 'Cf7',
    marca: ['e5', 'f7'],
    solucion: { from: 'e4', to: 'e3' },
    primera: 'e3',
    linea: '43…e3 44.Tc2+ Rb6 45.Cd6 e2+',
    gana: true,
    valor: '+4,1',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 30ZBU de la base abierta de Lichess (CC0), rating 1301. Stockfish 16 a profundidad 18: e3 es la mejor (+4,1) y la segunda queda en 0,0.',
  },
  {
    n: 13,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 13,
    id: 're_0hXbD',
    tema: 'veryLong',
    lichess: '0hXbD',
    rating: 1442,
    elo: 662,
    juegan: 'b',
    fen: 'r2kr3/p1p1BQ1p/1p1q2p1/3b4/8/2P5/PPP2PPP/R3R1K1 b - - 0 18',
    ultima: 'Axe7+',
    marca: ['g5', 'e7'],
    solucion: { from: 'e8', to: 'e7' },
    primera: 'Txe7',
    linea: '18…Txe7 19.Df8+ Rd7 20.Dxe7+ Dxe7 21.Txe7+ Rxe7',
    gana: true,
    valor: '+3,9',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: '',
    comprobado: 'Ejercicio 0hXbD de la base abierta de Lichess (CC0), rating 1442. Stockfish 16 a profundidad 18: Txe7 es la mejor (+3,9) y la segunda queda en -5,7.',
  },
  {
    n: 14,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 14,
    id: 're_0KYr1',
    tema: 'pawnEndgame',
    lichess: '0KYr1',
    rating: 1638,
    elo: 858,
    juegan: 'w',
    fen: '8/4pp2/1p4p1/1k6/4K1P1/4P2P/8/8 w - - 0 43',
    ultima: 'Rxb5',
    marca: ['b4', 'b5'],
    solucion: { from: 'h3', to: 'h4' },
    primera: 'h4',
    linea: '43.h4 Rc4 44.h5',
    gana: true,
    valor: '+3,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0KYr1 de la base abierta de Lichess (CC0), rating 1638. Stockfish 16 a profundidad 18: h4 es la mejor (+3,8) y la segunda queda en -2,3.',
  },
  {
    n: 15,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 15,
    id: 're_2vlyU',
    tema: 'zugzwang',
    lichess: '2vlyU',
    rating: 1580,
    elo: 800,
    juegan: 'b',
    fen: '8/1p6/1P1k2p1/P1pb1p1p/2B2P1P/2K3P1/8/8 b - - 1 46',
    ultima: 'Ac4',
    marca: ['d3', 'c4'],
    solucion: { from: 'd5', to: 'c4' },
    primera: 'Axc4',
    linea: '46…Axc4 47.Rxc4 Rc6 48.a6 bxa6',
    gana: true,
    valor: '+4,7',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2vlyU de la base abierta de Lichess (CC0), rating 1580. Stockfish 16 a profundidad 18: Axc4 es la mejor (+4,7) y la segunda queda en -4,0.',
  },
  {
    n: 16,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 16,
    id: 're_0bBpO',
    tema: 'clearance',
    lichess: '0bBpO',
    rating: 1453,
    elo: 673,
    juegan: 'w',
    fen: '1br3k1/p4pp1/1p5p/8/1Pq5/P4NP1/4QP1P/4R1K1 w - - 2 31',
    ultima: 'Dc4',
    marca: ['d4', 'c4'],
    solucion: { from: 'e2', to: 'c4' },
    primera: 'Dxc4',
    linea: '31.Dxc4 Txc4 32.Te8+ Rh7 33.Txb8',
    gana: true,
    valor: '+4,5',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0bBpO de la base abierta de Lichess (CC0), rating 1453. Stockfish 16 a profundidad 18: Dxc4 es la mejor (+4,5) y la segunda queda en +0,1.',
  },
  {
    n: 17,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 17,
    id: 're_0yaFE',
    tema: 'sacrifice',
    lichess: '0yaFE',
    rating: 1401,
    elo: 621,
    juegan: 'b',
    fen: 'r4qk1/1b1p2p1/1p2p3/p2nP1p1/3P4/P2B4/1PQ1N1PP/5RK1 b - - 1 20',
    ultima: 'Tf1',
    marca: ['a1', 'f1'],
    solucion: { from: 'f8', to: 'f1' },
    primera: 'Dxf1+',
    linea: '20…Dxf1+ 21.Rxf1 Ce3+ 22.Rg1 Cxc2',
    gana: true,
    valor: '+4,2',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0yaFE de la base abierta de Lichess (CC0), rating 1401. Stockfish 16 a profundidad 18: Dxf1+ es la mejor (+4,2) y la segunda queda en -2,4.',
  },
  {
    n: 18,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 18,
    id: 're_2Gudr',
    tema: 'defensiveMove',
    lichess: '2Gudr',
    rating: 1379,
    elo: 599,
    juegan: 'w',
    fen: '8/8/4pk2/7r/2p2PpK/2P5/P6P/8 w - - 0 51',
    ultima: 'Txh5+',
    marca: ['h8', 'h5'],
    solucion: { from: 'h4', to: 'h5' },
    primera: 'Rxh5',
    linea: '51.Rxh5 Rf5 52.a4',
    gana: true,
    valor: '+4,2',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2Gudr de la base abierta de Lichess (CC0), rating 1379. Stockfish 16 a profundidad 18: Rxh5 es la mejor (+4,2) y la segunda queda en -7,0.',
  },
  {
    n: 19,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 19,
    id: 're_1Ome1',
    tema: 'veryLong',
    lichess: '1Ome1',
    rating: 1593,
    elo: 813,
    juegan: 'w',
    fen: '8/8/p2PQp2/1p4p1/2p4q/P1k5/6PK/8 w - - 1 61',
    ultima: 'Dh4+',
    marca: ['f2', 'h4'],
    solucion: { from: 'e6', to: 'h3' },
    primera: 'Dh3+',
    linea: '61.Dh3+ Rb2 62.Dxh4 gxh4 63.d7 c3 64.d8=D',
    gana: true,
    valor: '+3,4',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1Ome1 de la base abierta de Lichess (CC0), rating 1593. Stockfish 16 a profundidad 18: Dh3+ es la mejor (+3,4) y la segunda queda en -2,6.',
  },
  {
    n: 20,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 20,
    id: 're_0dTpN',
    tema: 'quietMove',
    lichess: '0dTpN',
    rating: 1509,
    elo: 729,
    juegan: 'w',
    fen: 'rn1q1rk1/p1p2p2/1p1p2pQ/8/2Pp4/3b2P1/PP3PP1/2KR4 w - - 0 18',
    ultima: 'Axd3',
    marca: ['e4', 'd3'],
    solucion: { from: 'd1', to: 'h1' },
    primera: 'Th1',
    linea: '18.Th1 Dg5+ 19.Dxg5',
    gana: true,
    valor: '+3,8',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0dTpN de la base abierta de Lichess (CC0), rating 1509. Stockfish 16 a profundidad 18: Th1 es la mejor (+3,8) y la segunda queda en -8,2.',
  },
  {
    n: 21,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 21,
    id: 're_0NgNm',
    tema: 'intermezzo',
    lichess: '0NgNm',
    rating: 1285,
    elo: 505,
    juegan: 'b',
    fen: '5rk1/1qRn1ppp/p2pbb2/1p6/1P1BPP2/P6P/3N2P1/1B1Q1RK1 b - - 0 22',
    ultima: 'Txc7',
    marca: ['c1', 'c7'],
    solucion: { from: 'f6', to: 'd4' },
    primera: 'Axd4+',
    linea: '22…Axd4+ 23.Rh1 Dxc7',
    gana: true,
    valor: '+4,4',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 0NgNm de la base abierta de Lichess (CC0), rating 1285. Stockfish 16 a profundidad 18: Axd4+ es la mejor (+4,4) y la segunda queda en -0,3.',
  },
  {
    n: 22,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 22,
    id: 're_2up56',
    tema: 'attraction',
    lichess: '2up56',
    rating: 1505,
    elo: 725,
    juegan: 'b',
    fen: '8/5p1k/1R2p1pp/5q2/3p4/1n3QPP/1r3PK1/4R3 b - - 1 36',
    ultima: 'Df3',
    marca: ['e3', 'f3'],
    solucion: { from: 'f5', to: 'f3' },
    primera: 'Dxf3+',
    linea: '36…Dxf3+ 37.Rxf3 Cd2+',
    gana: true,
    valor: '+4,8',
    pista: 'Piensa en qué casilla te convendría tener una pieza rival, y cómo llevarla ahí.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2up56 de la base abierta de Lichess (CC0), rating 1505. Stockfish 16 a profundidad 18: Dxf3+ es la mejor (+4,8) y la segunda queda en -0,1.',
  },
  {
    n: 23,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 23,
    id: 're_1tcof',
    tema: 'defensiveMove',
    lichess: '1tcof',
    rating: 1640,
    elo: 860,
    juegan: 'w',
    fen: 'r1b1k1r1/ppppqp2/1bn2n2/4P1B1/2BP4/8/PP3PPP/RN1QK2R w KQq - 1 12',
    ultima: 'Tg8',
    marca: ['h8', 'g8'],
    solucion: { from: 'g5', to: 'f6' },
    primera: 'Axf6',
    linea: '12.Axf6 Db4+ 13.Cd2',
    gana: false,
    valor: '+2,3',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1tcof de la base abierta de Lichess (CC0), rating 1640. Stockfish 16 a profundidad 18: Axf6 es la mejor (+2,3) y la segunda queda en -2,3.',
  },
  {
    n: 24,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 24,
    id: 're_0Y04I',
    tema: 'veryLong',
    lichess: '0Y04I',
    rating: 1486,
    elo: 706,
    juegan: 'b',
    fen: '3rr2k/ppp3pp/2n2p2/2b5/5Q1N/1BP4P/PP3PP1/3R2K1 b - - 0 24',
    ultima: 'Txd1',
    marca: ['f1', 'd1'],
    solucion: { from: 'd8', to: 'd1' },
    primera: 'Txd1+',
    linea: '24…Txd1+ 25.Axd1 Te1+ 26.Rh2 Ad6 27.Dxd6 cxd6',
    gana: true,
    valor: '+4,7',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0Y04I de la base abierta de Lichess (CC0), rating 1486. Stockfish 16 a profundidad 18: Txd1+ es la mejor (+4,7) y la segunda queda en -5,3.',
  },
  {
    n: 25,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 25,
    id: 're_0IqIt',
    tema: 'defensiveMove',
    lichess: '0IqIt',
    rating: 1306,
    elo: 526,
    juegan: 'w',
    fen: '8/5p2/p4pp1/1pR2p2/5P1k/r1P4P/6K1/8 w - - 1 38',
    ultima: 'Rh4',
    marca: ['h5', 'h4'],
    solucion: { from: 'c5', to: 'c8' },
    primera: 'Tc8',
    linea: '38.Tc8 Ta2+ 39.Rf3 Tf2+ 40.Rxf2',
    gana: true,
    valor: '+5,2',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0IqIt de la base abierta de Lichess (CC0), rating 1306. Stockfish 16 a profundidad 18: Tc8 es la mejor (+5,2) y la segunda queda en -4,7.',
  },
  {
    n: 26,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 26,
    id: 're_15BTp',
    tema: 'defensiveMove',
    lichess: '15BTp',
    rating: 1338,
    elo: 558,
    juegan: 'w',
    fen: '8/2k5/1p3KP1/5B2/8/8/1r6/8 w - - 1 57',
    ultima: 'Tb2',
    marca: ['b5', 'b2'],
    solucion: { from: 'g6', to: 'g7' },
    primera: 'g7',
    linea: '57.g7 Tg2 58.Ag6',
    gana: true,
    valor: '+5,1',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 15BTp de la base abierta de Lichess (CC0), rating 1338. Stockfish 16 a profundidad 18: g7 es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 27,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 27,
    id: 're_2pZcV',
    tema: 'defensiveMove',
    lichess: '2pZcV',
    rating: 1556,
    elo: 776,
    juegan: 'w',
    fen: 'r4rk1/1pp2ppp/1n6/p1b1p3/3nP3/PPNP1BPq/5P2/R1BQ1RK1 w - - 0 16',
    ultima: 'Dxh3',
    marca: ['d7', 'h3'],
    solucion: { from: 'f3', to: 'g4' },
    primera: 'Ag4',
    linea: '16.Ag4 Ce2+ 17.Dxe2 Dxg3+ 18.Rh1 Dh4+ 19.Rg2',
    gana: false,
    valor: '+2,6',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2pZcV de la base abierta de Lichess (CC0), rating 1556. Stockfish 16 a profundidad 18: Ag4 es la mejor (+2,6) y la segunda queda en -1,6.',
  },
  {
    n: 28,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 28,
    id: 're_1qs2e',
    tema: 'zugzwang',
    lichess: '1qs2e',
    rating: 1562,
    elo: 782,
    juegan: 'w',
    fen: '8/8/8/3n4/B3k3/3p4/1P1K4/8 w - - 0 50',
    ultima: 'd3',
    marca: ['d4', 'd3'],
    solucion: { from: 'a4', to: 'c6' },
    primera: 'Ac6',
    linea: '50.Ac6 Rd4 51.Axd5 Rxd5 52.Rxd3 Rc5 53.Rc3 Rb5 54.Rb3',
    gana: true,
    valor: '+6,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1qs2e de la base abierta de Lichess (CC0), rating 1562. Stockfish 16 a profundidad 18: Ac6 es la mejor (+6,8) y la segunda queda en 0,0.',
  },
  {
    n: 29,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 29,
    id: 're_30fX7',
    tema: 'sacrifice',
    lichess: '30fX7',
    rating: 1558,
    elo: 778,
    juegan: 'w',
    fen: '1b6/8/P7/2B5/8/6kp/8/7K w - - 3 53',
    ultima: 'Rg3',
    marca: ['g4', 'g3'],
    solucion: { from: 'c5', to: 'd6' },
    primera: 'Ad6+',
    linea: '53.Ad6+ Axd6 54.a7',
    gana: true,
    valor: '+5,1',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 30fX7 de la base abierta de Lichess (CC0), rating 1558. Stockfish 16 a profundidad 18: Ad6+ es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 30,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 30,
    id: 're_1PA8f',
    tema: 'defensiveMove',
    lichess: '1PA8f',
    rating: 1632,
    elo: 852,
    juegan: 'w',
    fen: 'r3k2r/2p1bppp/pq6/1p2Q3/8/2NP1bN1/PPP3PP/R1B3K1 w kq - 2 19',
    ultima: 'Db6+',
    marca: ['g6', 'b6'],
    solucion: { from: 'c1', to: 'e3' },
    primera: 'Ae3',
    linea: '19.Ae3 Df6 20.Dxf6 Axf6 21.gxf3',
    gana: false,
    valor: '+2,4',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1PA8f de la base abierta de Lichess (CC0), rating 1632. Stockfish 16 a profundidad 18: Ae3 es la mejor (+2,4) y la segunda queda en -1,3.',
  },
  {
    n: 31,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 31,
    id: 're_2Rsrp',
    tema: 'sacrifice',
    lichess: '2Rsrp',
    rating: 1300,
    elo: 520,
    juegan: 'b',
    fen: '6rk/5b1p/1pp2p2/1N1np3/p7/P3PB2/1Br2P1P/Q2R1K2 b - - 2 35',
    ultima: 'Rf1',
    marca: ['g1', 'f1'],
    solucion: { from: 'd5', to: 'e3' },
    primera: 'Cxe3+',
    linea: '35…Cxe3+ 36.fxe3 Ac4+ 37.Ae2 Axe2+',
    gana: true,
    valor: '+6,2',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2Rsrp de la base abierta de Lichess (CC0), rating 1300. Stockfish 16 a profundidad 18: Cxe3+ es la mejor (+6,2) y la segunda queda en -1,9.',
  },
  {
    n: 32,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 32,
    id: 're_0NLXb',
    tema: 'exposedKing',
    lichess: '0NLXb',
    rating: 1468,
    elo: 688,
    juegan: 'w',
    fen: '2r4k/R7/8/4N2p/3P4/2P1p2P/1r4P1/5K2 w - - 0 37',
    ultima: 'Txb2',
    marca: ['b6', 'b2'],
    solucion: { from: 'e5', to: 'g6' },
    primera: 'Cg6+',
    linea: '37.Cg6+ Rg8 38.Ce7+ Rf8 39.Cxc8',
    gana: true,
    valor: '+5,0',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0NLXb de la base abierta de Lichess (CC0), rating 1468. Stockfish 16 a profundidad 18: Cg6+ es la mejor (+5,0) y la segunda queda en -1,6.',
  },
  {
    n: 33,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 33,
    id: 're_2PCQF',
    tema: 'quietMove',
    lichess: '2PCQF',
    rating: 1377,
    elo: 597,
    juegan: 'w',
    fen: '8/8/2B3r1/3Pk1p1/P5K1/6P1/8/8 w - - 3 52',
    ultima: 'Tg6',
    marca: ['d6', 'g6'],
    solucion: { from: 'a4', to: 'a5' },
    primera: 'a5',
    linea: '52.a5 Tg7 53.a6',
    gana: true,
    valor: '+3,1',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2PCQF de la base abierta de Lichess (CC0), rating 1377. Stockfish 16 a profundidad 18: a5 es la mejor (+3,1) y la segunda queda en +0,0.',
  },
  {
    n: 34,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 34,
    id: 're_17stN',
    tema: 'defensiveMove',
    lichess: '17stN',
    rating: 1405,
    elo: 625,
    juegan: 'b',
    fen: '4r1k1/ppp1br1p/n2pQ1p1/3P4/PPP1Pq2/4R3/1B3PBP/1R4K1 b - - 5 27',
    ultima: 'Te3',
    marca: ['e2', 'e3'],
    solucion: { from: 'f4', to: 'f2' },
    primera: 'Dxf2+',
    linea: '27…Dxf2+ 28.Rh1 Dxe3 29.Tf1 Tf8',
    gana: true,
    valor: '+3,5',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 17stN de la base abierta de Lichess (CC0), rating 1405. Stockfish 16 a profundidad 18: Dxf2+ es la mejor (+3,5) y la segunda queda en -0,1.',
  },
  {
    n: 35,
    uso: 'ejemplo',
    capitulo: 7,
    leccion: 35,
    id: 're_33vTh',
    tema: 'deflection',
    lichess: '33vTh',
    rating: 1397,
    elo: 617,
    juegan: 'b',
    fen: '8/2RQ2bk/p1p3rp/q4p1n/P4P2/7P/2P1NRP1/6K1 b - - 3 37',
    ultima: 'Dd7',
    marca: ['d4', 'd7'],
    solucion: { from: 'a5', to: 'e1' },
    primera: 'De1+',
    linea: '37…De1+ 38.Tf1 Dxe2',
    gana: true,
    valor: '+5,2',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 33vTh de la base abierta de Lichess (CC0), rating 1397. Stockfish 16 a profundidad 18: De1+ es la mejor (+5,2) y la segunda queda en +0,4.',
  },
  {
    n: 36,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_0rUS2',
    tema: 'quietMove',
    lichess: '0rUS2',
    rating: 1395,
    elo: 615,
    juegan: 'b',
    fen: '8/8/q7/Q4p2/K7/P1P3k1/1P6/8 b - - 2 53',
    ultima: 'Da5',
    marca: ['d8', 'a5'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'Dxa5+',
    linea: '53…Dxa5+ 54.Rxa5 f4 55.b4 f3 56.b5 f2 57.b6 f1=D',
    gana: true,
    valor: '+3,3',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0rUS2 de la base abierta de Lichess (CC0), rating 1395. Stockfish 16 a profundidad 18: Dxa5+ es la mejor (+3,3) y la segunda queda en +0,1.',
  },
  {
    n: 37,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_0qUV5',
    tema: 'clearance',
    lichess: '0qUV5',
    rating: 1408,
    elo: 628,
    juegan: 'b',
    fen: '3rr1k1/2pq1ppp/Q7/1p2p3/1P2R3/P5P1/2P2P1P/4R1K1 b - - 0 25',
    ultima: 'Dxa6',
    marca: ['c6', 'a6'],
    solucion: { from: 'd8', to: 'a8' },
    primera: 'Ta8',
    linea: '25…Ta8 26.Db7 Teb8 27.Dxa8 Txa8',
    gana: true,
    valor: '+3,8',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 0qUV5 de la base abierta de Lichess (CC0), rating 1408. Stockfish 16 a profundidad 18: Ta8 es la mejor (+3,8) y la segunda queda en +0,1.',
  },
  {
    n: 38,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_1nWAz',
    tema: 'pawnEndgame',
    lichess: '1nWAz',
    rating: 1608,
    elo: 828,
    juegan: 'w',
    fen: '8/8/6p1/P3k3/1P5p/3p4/5K2/8 w - - 0 50',
    ultima: 'd3',
    marca: ['d4', 'd3'],
    solucion: { from: 'a5', to: 'a6' },
    primera: 'a6',
    linea: '50.a6 h3 51.a7',
    gana: true,
    valor: '+4,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1nWAz de la base abierta de Lichess (CC0), rating 1608. Stockfish 16 a profundidad 18: a6 es la mejor (+4,8) y la segunda queda en -5,5.',
  },
  {
    n: 39,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_3KiG7',
    tema: 'clearance',
    lichess: '3KiG7',
    rating: 1733,
    elo: 953,
    juegan: 'b',
    fen: '1rb3k1/2pp2p1/1p5p/p3P3/8/PPBP2q1/1QP3B1/5RK1 b - - 1 23',
    ultima: 'Ag2',
    marca: ['f3', 'g2'],
    solucion: { from: 'c8', to: 'b7' },
    primera: 'Ab7',
    linea: '23…Ab7 24.Tf2 Tf8 25.Txf8+ Rxf8',
    gana: true,
    valor: '+5,2',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 3KiG7 de la base abierta de Lichess (CC0), rating 1733. Stockfish 16 a profundidad 18: Ab7 es la mejor (+5,2) y la segunda queda en -2,9.',
  },
  {
    n: 40,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_2bg5c',
    tema: 'quietMove',
    lichess: '2bg5c',
    rating: 1819,
    elo: 1039,
    juegan: 'b',
    fen: '4r1k1/3Q3p/4n1p1/P4p2/4q3/4P3/2P2PpP/R3R1K1 b - - 2 25',
    ultima: 'Dd7',
    marca: ['c7', 'd7'],
    solucion: { from: 'e6', to: 'g5' },
    primera: 'Cg5',
    linea: '25…Cg5 26.Dxe8+ Dxe8',
    gana: true,
    valor: '+4,0',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2bg5c de la base abierta de Lichess (CC0), rating 1819. Stockfish 16 a profundidad 18: Cg5 es la mejor (+4,0) y la segunda queda en -4,3.',
  },
  {
    n: 41,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_0qlSa',
    tema: 'pawnEndgame',
    lichess: '0qlSa',
    rating: 1955,
    elo: 1175,
    juegan: 'b',
    fen: '8/8/p6p/3k2p1/P2p2P1/1P1K4/5P2/8 b - a3 0 41',
    ultima: 'a4',
    marca: ['a2', 'a4'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'a5',
    linea: '41…a5 42.f3 Rc5 43.Re4 Rb4 44.Rxd4 Rxb3',
    gana: true,
    valor: '+4,5',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0qlSa de la base abierta de Lichess (CC0), rating 1955. Stockfish 16 a profundidad 18: a5 es la mejor (+4,5) y la segunda queda en -4,1.',
  },
  {
    n: 42,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_1dc2v',
    tema: 'pawnEndgame',
    lichess: '1dc2v',
    rating: 2139,
    elo: 1359,
    juegan: 'b',
    fen: '8/5p2/pk2p3/2p1P1Pp/2K5/1PP3P1/8/8 b - - 0 45',
    ultima: 'c3',
    marca: ['c2', 'c3'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'a5',
    linea: '45…a5 46.b4 cxb4 47.cxb4 a4',
    gana: true,
    valor: '+4,9',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1dc2v de la base abierta de Lichess (CC0), rating 2139. Stockfish 16 a profundidad 18: a5 es la mejor (+4,9) y la segunda queda en 0,0.',
  },
  {
    n: 43,
    uso: 'ejercicio',
    capitulo: 1,
    id: 're_3APfy',
    tema: 'quietMove',
    lichess: '3APfy',
    rating: 2169,
    elo: 1389,
    juegan: 'b',
    fen: '5k2/5pp1/2bq3p/1p2r3/2p2QP1/2P2BPP/1P5K/4R3 b - - 1 37',
    ultima: 'Af3',
    marca: ['e2', 'f3'],
    solucion: { from: 'c6', to: 'f3' },
    primera: 'Axf3',
    linea: '37…Axf3 38.Txe5 Dd1 39.Dxf3 Dxf3',
    gana: true,
    valor: '+4,5',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3APfy de la base abierta de Lichess (CC0), rating 2169. Stockfish 16 a profundidad 18: Axf3 es la mejor (+4,5) y la segunda queda en +0,1.',
  },
  {
    n: 44,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_1LCoW',
    tema: 'exposedKing',
    lichess: '1LCoW',
    rating: 1314,
    elo: 534,
    juegan: 'w',
    fen: '4k1nr/1p2q2p/4Q1p1/3pP3/2pP4/r1P5/7P/1N3R1K w k - 1 25',
    ultima: 'De7',
    marca: ['g5', 'e7'],
    solucion: { from: 'e6', to: 'c8' },
    primera: 'Dc8+',
    linea: '25.Dc8+ Dd8 26.Tf8+ Rxf8 27.Dxd8+',
    gana: true,
    valor: '+6,1',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1LCoW de la base abierta de Lichess (CC0), rating 1314. Stockfish 16 a profundidad 18: Dc8+ es la mejor (+6,1) y la segunda queda en -0,4.',
  },
  {
    n: 45,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_1Qlru',
    tema: 'deflection',
    lichess: '1Qlru',
    rating: 1466,
    elo: 686,
    juegan: 'w',
    fen: 'rn2r3/pp1k2pp/2p2p2/4B3/3PR3/5PP1/PPP2K2/5B2 w - - 0 18',
    ultima: 'f6',
    marca: ['f7', 'f6'],
    solucion: { from: 'f1', to: 'h3' },
    primera: 'Ah3+',
    linea: '18.Ah3+ Rd8 19.Ac7+ Rxc7 20.Txe8',
    gana: true,
    valor: '+3,6',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1Qlru de la base abierta de Lichess (CC0), rating 1466. Stockfish 16 a profundidad 18: Ah3+ es la mejor (+3,6) y la segunda queda en -2,3.',
  },
  {
    n: 46,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_1JqSK',
    tema: 'sacrifice',
    lichess: '1JqSK',
    rating: 1594,
    elo: 814,
    juegan: 'w',
    fen: '8/1p4pk/2p5/r1PnNpq1/3Pp3/1Q2P1P1/6K1/4R3 w - - 1 36',
    ultima: 'Ta5',
    marca: ['a7', 'a5'],
    solucion: { from: 'e1', to: 'h1' },
    primera: 'Th1+',
    linea: '36.Th1+ Rg8 37.Th8+ Rxh8 38.Cf7+ Rh7 39.Cxg5+',
    gana: true,
    valor: '+4,0',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1JqSK de la base abierta de Lichess (CC0), rating 1594. Stockfish 16 a profundidad 18: Th1+ es la mejor (+4,0) y la segunda queda en -2,8.',
  },
  {
    n: 47,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_0d30b',
    tema: 'deflection',
    lichess: '0d30b',
    rating: 1720,
    elo: 940,
    juegan: 'b',
    fen: '8/p7/3k4/2R5/PK1p4/1P3r2/8/8 b - - 2 55',
    ultima: 'Rb4',
    marca: ['c4', 'b4'],
    solucion: { from: 'f3', to: 'b3' },
    primera: 'Txb3+',
    linea: '55…Txb3+ 56.Rxb3 Rxc5',
    gana: true,
    valor: '+7,8',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0d30b de la base abierta de Lichess (CC0), rating 1720. Stockfish 16 a profundidad 18: Txb3+ es la mejor (+7,8) y la segunda queda en 0,0.',
  },
  {
    n: 48,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_1YXu9',
    tema: 'exposedKing',
    lichess: '1YXu9',
    rating: 1762,
    elo: 982,
    juegan: 'w',
    fen: 'r2rbkn1/pp6/8/3q1p2/8/4RQ1P/2P2PP1/4R2K w - - 2 32',
    ultima: 'Dd5',
    marca: ['a2', 'd5'],
    solucion: { from: 'e3', to: 'e8' },
    primera: 'Txe8+',
    linea: '32.Txe8+ Txe8 33.Txe8+ Txe8 34.Dxd5',
    gana: true,
    valor: '+4,8',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: '',
    comprobado: 'Ejercicio 1YXu9 de la base abierta de Lichess (CC0), rating 1762. Stockfish 16 a profundidad 18: Txe8+ es la mejor (+4,8) y la segunda queda en -4,5.',
  },
  {
    n: 49,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_1Cf29',
    tema: 'sacrifice',
    lichess: '1Cf29',
    rating: 1862,
    elo: 1082,
    juegan: 'w',
    fen: '4r1k1/pppn3p/5p2/3P1R1N/2PP4/1N5P/PP2r1P1/7K w - - 0 25',
    ultima: 'f6',
    marca: ['f7', 'f6'],
    solucion: { from: 'b3', to: 'c5' },
    primera: 'Cc5',
    linea: '25.Cc5 Cxc5 26.Cxf6+ Rf7 27.Cxe8+ Rxe8 28.dxc5',
    gana: true,
    valor: '+4,1',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1Cf29 de la base abierta de Lichess (CC0), rating 1862. Stockfish 16 a profundidad 18: Cc5 es la mejor (+4,1) y la segunda queda en -0,8.',
  },
  {
    n: 50,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_0jgYf',
    tema: 'exposedKing',
    lichess: '0jgYf',
    rating: 2059,
    elo: 1279,
    juegan: 'b',
    fen: 'rnbqnrk1/pp4pp/3p4/3Pppb1/2B5/2N1BP2/PPPQN1PP/R3K2R b KQ - 3 11',
    ultima: 'Dd2',
    marca: ['d1', 'd2'],
    solucion: { from: 'g5', to: 'e3' },
    primera: 'Axe3',
    linea: '11…Axe3 12.Dxe3 Dh4+ 13.g3 Dxc4',
    gana: true,
    valor: '+5,0',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0jgYf de la base abierta de Lichess (CC0), rating 2059. Stockfish 16 a profundidad 18: Axe3 es la mejor (+5,0) y la segunda queda en -0,1.',
  },
  {
    n: 51,
    uso: 'ejercicio',
    capitulo: 2,
    id: 're_0xrbL',
    tema: 'sacrifice',
    lichess: '0xrbL',
    rating: 2334,
    elo: 1554,
    juegan: 'w',
    fen: 'r7/5p2/p2q2nk/1p1b1r1p/5P1P/1B4Q1/PPP3PK/3R1R2 w - - 3 27',
    ultima: 'Dd6',
    marca: ['d8', 'd6'],
    solucion: { from: 'b3', to: 'd5' },
    primera: 'Axd5',
    linea: '27.Axd5 Txd5 28.Dg5+ Txg5 29.hxg5+ Rg7 30.Txd6',
    gana: true,
    valor: '+5,2',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 0xrbL de la base abierta de Lichess (CC0), rating 2334. Stockfish 16 a profundidad 18: Axd5 es la mejor (+5,2) y la segunda queda en +0,1.',
  },
  {
    n: 52,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_0Qg9E',
    tema: 'pawnEndgame',
    lichess: '0Qg9E',
    rating: 1261,
    elo: 481,
    juegan: 'b',
    fen: '8/8/p3k1p1/1p5P/1P2K3/P4P2/8/8 b - - 0 44',
    ultima: 'gxh5',
    marca: ['g4', 'h5'],
    solucion: { from: 'g6', to: 'h5' },
    primera: 'gxh5',
    linea: '44…gxh5 45.Rf4 Rf6',
    gana: true,
    valor: '+5,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0Qg9E de la base abierta de Lichess (CC0), rating 1261. Stockfish 16 a profundidad 18: gxh5 es la mejor (+5,0) y la segunda queda en -6,1.',
  },
  {
    n: 53,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_1PRRh',
    tema: 'defensiveMove',
    lichess: '1PRRh',
    rating: 1307,
    elo: 527,
    juegan: 'w',
    fen: 'r7/pp1n2kp/2p3p1/3p2q1/8/2P2B2/PP2NrPP/1K1Q3R w - - 2 22',
    ultima: 'Cd7',
    marca: ['b8', 'd7'],
    solucion: { from: 'd1', to: 'd4' },
    primera: 'Dd4+',
    linea: '22.Dd4+ Ce5 23.Dxf2 Df5+ 24.Ra1',
    gana: true,
    valor: '+3,6',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1PRRh de la base abierta de Lichess (CC0), rating 1307. Stockfish 16 a profundidad 18: Dd4+ es la mejor (+3,6) y la segunda queda en -3,8.',
  },
  {
    n: 54,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_06Asm',
    tema: 'intermezzo',
    lichess: '06Asm',
    rating: 1383,
    elo: 603,
    juegan: 'w',
    fen: '6k1/4b1pp/p1N1p3/2n5/r7/4B1PK/7P/3R1r2 w - - 0 27',
    ultima: 'Txf1',
    marca: ['f8', 'f1'],
    solucion: { from: 'c6', to: 'e7' },
    primera: 'Cxe7+',
    linea: '27.Cxe7+ Rf7 28.Txf1+ Rxe7 29.Axc5+',
    gana: true,
    valor: '+4,2',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 06Asm de la base abierta de Lichess (CC0), rating 1383. Stockfish 16 a profundidad 18: Cxe7+ es la mejor (+4,2) y la segunda queda en -0,7.',
  },
  {
    n: 55,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_10NPD',
    tema: 'intermezzo',
    lichess: '10NPD',
    rating: 1653,
    elo: 873,
    juegan: 'b',
    fen: '8/pQ4pk/3b3p/3p1P2/3Pn3/8/4q1PP/1R4BK b - - 4 28',
    ultima: 'Ag1',
    marca: ['e3', 'g1'],
    solucion: { from: 'e4', to: 'g3' },
    primera: 'Cg3+',
    linea: '28…Cg3+ 29.hxg3 Dh5+ 30.Ah2 Axg3',
    gana: true,
    valor: '+3,0',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 10NPD de la base abierta de Lichess (CC0), rating 1653. Stockfish 16 a profundidad 18: Cg3+ es la mejor (+3,0) y la segunda queda en +0,2.',
  },
  {
    n: 56,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_364jA',
    tema: 'pawnEndgame',
    lichess: '364jA',
    rating: 1704,
    elo: 924,
    juegan: 'w',
    fen: '8/8/8/1pk3K1/5P2/8/8/8 w - b6 0 55',
    ultima: 'b5',
    marca: ['b7', 'b5'],
    solucion: { from: 'f4', to: 'f5' },
    primera: 'f5',
    linea: '55.f5 b4 56.f6 Rd6 57.Rg6 b3 58.f7 Re7 59.Rg7 b2 60.f8=D+',
    gana: true,
    valor: '+7,1',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 364jA de la base abierta de Lichess (CC0), rating 1704. Stockfish 16 a profundidad 18: f5 es la mejor (+7,1) y la segunda queda en +0,0.',
  },
  {
    n: 57,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_13uDm',
    tema: 'defensiveMove',
    lichess: '13uDm',
    rating: 1909,
    elo: 1129,
    juegan: 'w',
    fen: '3B2k1/5p1p/6p1/p2p4/PpnP4/1Pr3RP/5PP1/6K1 w - - 4 35',
    ultima: 'Cc4',
    marca: ['a3', 'c4'],
    solucion: { from: 'g3', to: 'c3' },
    primera: 'Txc3',
    linea: '35.Txc3 bxc3 36.bxc4 c2 37.Ag5',
    gana: true,
    valor: '+4,9',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 13uDm de la base abierta de Lichess (CC0), rating 1909. Stockfish 16 a profundidad 18: Txc3 es la mejor (+4,9) y la segunda queda en -0,1.',
  },
  {
    n: 58,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_0Ql7G',
    tema: 'intermezzo',
    lichess: '0Ql7G',
    rating: 2073,
    elo: 1293,
    juegan: 'w',
    fen: 'r3k2r/1p2ppbp/1qnp2p1/p7/2PN4/1P4PP/PB2PnB1/1R1Q1RK1 w kq - 0 14',
    ultima: 'Cxf2',
    marca: ['e4', 'f2'],
    solucion: { from: 'g2', to: 'c6' },
    primera: 'Axc6+',
    linea: '14.Axc6+ bxc6 15.Txf2',
    gana: true,
    valor: '+3,1',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 0Ql7G de la base abierta de Lichess (CC0), rating 2073. Stockfish 16 a profundidad 18: Axc6+ es la mejor (+3,1) y la segunda queda en -0,3.',
  },
  {
    n: 59,
    uso: 'ejercicio',
    capitulo: 3,
    id: 're_2jPCu',
    tema: 'pawnEndgame',
    lichess: '2jPCu',
    rating: 2299,
    elo: 1519,
    juegan: 'w',
    fen: '8/p7/1p2k3/2p5/PP4K1/6P1/8/8 w - - 0 40',
    ultima: 'c5',
    marca: ['c6', 'c5'],
    solucion: { from: 'b4', to: 'c5' },
    primera: 'bxc5',
    linea: '40.bxc5 bxc5 41.Rf4 Rd5 42.Re3',
    gana: true,
    valor: '+3,9',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2jPCu de la base abierta de Lichess (CC0), rating 2299. Stockfish 16 a profundidad 18: bxc5 es la mejor (+3,9) y la segunda queda en -0,0.',
  },
  {
    n: 60,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2raAo',
    tema: 'clearance',
    lichess: '2raAo',
    rating: 1334,
    elo: 554,
    juegan: 'b',
    fen: '3r1rk1/Q1pqbpp1/3p1n1p/8/3PP3/2N1B2P/PPP3P1/R4RK1 b - - 0 16',
    ultima: 'Dxa7',
    marca: ['b7', 'a7'],
    solucion: { from: 'd8', to: 'a8' },
    primera: 'Ta8',
    linea: '16…Ta8 17.Db7 Tfb8 18.Dxa8 Txa8',
    gana: true,
    valor: '+4,0',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 2raAo de la base abierta de Lichess (CC0), rating 1334. Stockfish 16 a profundidad 18: Ta8 es la mejor (+4,0) y la segunda queda en -1,4.',
  },
  {
    n: 61,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2MyjR',
    tema: 'pawnEndgame',
    lichess: '2MyjR',
    rating: 1514,
    elo: 734,
    juegan: 'b',
    fen: '8/p4kp1/1p2p2p/1P2P3/1P5P/4K1P1/8/8 b - h3 0 37',
    ultima: 'h4',
    marca: ['h2', 'h4'],
    solucion: { from: 'f7', to: 'g6' },
    primera: 'Rg6',
    linea: '37…Rg6 38.g4 h5 39.Rf4 hxg4 40.Rxg4 Rh6',
    gana: true,
    valor: '+4,5',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2MyjR de la base abierta de Lichess (CC0), rating 1514. Stockfish 16 a profundidad 18: Rg6 es la mejor (+4,5) y la segunda queda en +0,1.',
  },
  {
    n: 62,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_1k7xG',
    tema: 'zugzwang',
    lichess: '1k7xG',
    rating: 1535,
    elo: 755,
    juegan: 'w',
    fen: '8/5p2/1p4p1/p5Pp/P2kP2P/1P3K2/8/8 w - - 1 39',
    ultima: 'Rd4',
    marca: ['e5', 'd4'],
    solucion: { from: 'f3', to: 'f4' },
    primera: 'Rf4',
    linea: '39.Rf4 Rc3 40.Re5',
    gana: true,
    valor: '+3,6',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1k7xG de la base abierta de Lichess (CC0), rating 1535. Stockfish 16 a profundidad 18: Rf4 es la mejor (+3,6) y la segunda queda en -4,4.',
  },
  {
    n: 63,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2Xfv6',
    tema: 'pawnEndgame',
    lichess: '2Xfv6',
    rating: 1656,
    elo: 876,
    juegan: 'b',
    fen: '8/6p1/2K4p/3pk2P/6P1/2P5/8/8 b - - 6 38',
    ultima: 'Rc6',
    marca: ['c5', 'c6'],
    solucion: { from: 'd5', to: 'd4' },
    primera: 'd4',
    linea: '38…d4 39.cxd4+ Rxd4 40.Rd6 Re4',
    gana: true,
    valor: '+6,6',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2Xfv6 de la base abierta de Lichess (CC0), rating 1656. Stockfish 16 a profundidad 18: d4 es la mejor (+6,6) y la segunda queda en 0,0.',
  },
  {
    n: 64,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2NPXT',
    tema: 'clearance',
    lichess: '2NPXT',
    rating: 1931,
    elo: 1151,
    juegan: 'b',
    fen: '2r5/5ppk/p2R2qp/8/4p1P1/7P/PP1Q1P2/6K1 b - - 1 30',
    ultima: 'Td6',
    marca: ['d5', 'd6'],
    solucion: { from: 'e4', to: 'e3' },
    primera: 'e3',
    linea: '30…e3 31.fxe3 Db1+',
    gana: true,
    valor: '+4,6',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 2NPXT de la base abierta de Lichess (CC0), rating 1931. Stockfish 16 a profundidad 18: e3 es la mejor (+4,6) y la segunda queda en -0,1.',
  },
  {
    n: 65,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2sLF2',
    tema: 'zugzwang',
    lichess: '2sLF2',
    rating: 2039,
    elo: 1259,
    juegan: 'b',
    fen: '8/8/5p2/4r1Pk/6R1/6K1/8/8 b - - 0 43',
    ultima: 'hxg5',
    marca: ['h4', 'g5'],
    solucion: { from: 'e5', to: 'g5' },
    primera: 'Txg5',
    linea: '43…Txg5 44.Txg5+ Rxg5 45.Rf3 Rf5',
    gana: true,
    valor: '+8,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2sLF2 de la base abierta de Lichess (CC0), rating 2039. Stockfish 16 a profundidad 18: Txg5 es la mejor (+8,8) y la segunda queda en 0,0.',
  },
  {
    n: 66,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_2Nydl',
    tema: 'pawnEndgame',
    lichess: '2Nydl',
    rating: 2083,
    elo: 1303,
    juegan: 'b',
    fen: '8/3k4/p2P4/2P1K3/1p6/8/8/8 b - - 1 52',
    ultima: 'Re5',
    marca: ['f5', 'e5'],
    solucion: { from: 'b4', to: 'b3' },
    primera: 'b3',
    linea: '52…b3 53.c6+ Rxc6 54.Re6 b2 55.d7 b1=D 56.d8=D De4+',
    gana: true,
    valor: '+6,4',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2Nydl de la base abierta de Lichess (CC0), rating 2083. Stockfish 16 a profundidad 18: b3 es la mejor (+6,4) y la segunda queda en -0,0.',
  },
  {
    n: 67,
    uso: 'ejercicio',
    capitulo: 4,
    id: 're_30VQx',
    tema: 'zugzwang',
    lichess: '30VQx',
    rating: 2112,
    elo: 1332,
    juegan: 'b',
    fen: '8/8/4p1p1/3kPp1p/pK3P1P/Pp4P1/1P6/8 b - - 4 44',
    ultima: 'Rb4',
    marca: ['c3', 'b4'],
    solucion: { from: 'd5', to: 'd4' },
    primera: 'Rd4',
    linea: '44…Rd4 45.Rxa4 Rc4 46.Ra5 Rd3 47.Rb6 Rc2',
    gana: true,
    valor: '+3,1',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 30VQx de la base abierta de Lichess (CC0), rating 2112. Stockfish 16 a profundidad 18: Rd4 es la mejor (+3,1) y la segunda queda en -3,3.',
  },
  {
    n: 68,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_2cX9N',
    tema: 'veryLong',
    lichess: '2cX9N',
    rating: 1367,
    elo: 587,
    juegan: 'w',
    fen: '3r4/p3kppp/1p2pn2/2qpNP2/3Q4/1P6/P5PP/4R1K1 w - - 1 24',
    ultima: 'Dc5',
    marca: ['c7', 'c5'],
    solucion: { from: 'd4', to: 'c5' },
    primera: 'Dxc5+',
    linea: '24.Dxc5+ bxc5 25.Cc6+ Rd7 26.Cxd8 Rxd8 27.fxe6',
    gana: true,
    valor: '+3,1',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2cX9N de la base abierta de Lichess (CC0), rating 1367. Stockfish 16 a profundidad 18: Dxc5+ es la mejor (+3,1) y la segunda queda en -3,9.',
  },
  {
    n: 69,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_3Hyta',
    tema: 'intermezzo',
    lichess: '3Hyta',
    rating: 1387,
    elo: 607,
    juegan: 'w',
    fen: '3r1rk1/p1p1npp1/1pN1p2p/1BP5/q3P1b1/P7/3B1PPP/R3R1K1 w - - 0 20',
    ultima: 'Dxa4',
    marca: ['d4', 'a4'],
    solucion: { from: 'c6', to: 'e7' },
    primera: 'Cxe7+',
    linea: '20.Cxe7+ Rh7 21.Axa4',
    gana: true,
    valor: '+4,3',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 3Hyta de la base abierta de Lichess (CC0), rating 1387. Stockfish 16 a profundidad 18: Cxe7+ es la mejor (+4,3) y la segunda queda en +0,1.',
  },
  {
    n: 70,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_1YcjC',
    tema: 'attraction',
    lichess: '1YcjC',
    rating: 1538,
    elo: 758,
    juegan: 'b',
    fen: '1r4k1/p4ppp/5q2/2pB1b2/2P4P/Q2P2P1/PP1RrP2/2K4R b - - 2 21',
    ultima: 'Td2',
    marca: ['d1', 'd2'],
    solucion: { from: 'e2', to: 'd2' },
    primera: 'Txd2',
    linea: '21…Txd2 22.Rxd2 Txb2+ 23.Dxb2 Dxb2+',
    gana: true,
    valor: '+5,3',
    pista: 'Piensa en qué casilla te convendría tener una pieza rival, y cómo llevarla ahí.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1YcjC de la base abierta de Lichess (CC0), rating 1538. Stockfish 16 a profundidad 18: Txd2 es la mejor (+5,3) y la segunda queda en -2,2.',
  },
  {
    n: 71,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_3MiV4',
    tema: 'attraction',
    lichess: '3MiV4',
    rating: 1658,
    elo: 878,
    juegan: 'b',
    fen: 'r4rk1/1pp3pp/p7/3pB2Q/1P5b/P2P2Nq/2P2P2/R3R1K1 b - - 3 18',
    ultima: 'Tfe1',
    marca: ['f1', 'e1'],
    solucion: { from: 'f8', to: 'f2' },
    primera: 'Txf2',
    linea: '18…Txf2 19.Rxf2 Axg3+ 20.Axg3 Dxh5',
    gana: true,
    valor: '+5,3',
    pista: 'Piensa en qué casilla te convendría tener una pieza rival, y cómo llevarla ahí.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 3MiV4 de la base abierta de Lichess (CC0), rating 1658. Stockfish 16 a profundidad 18: Txf2 es la mejor (+5,3) y la segunda queda en -3,1.',
  },
  {
    n: 72,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_33vYs',
    tema: 'intermezzo',
    lichess: '33vYs',
    rating: 1782,
    elo: 1002,
    juegan: 'w',
    fen: '3k1br1/4r3/p3qp1p/1pp1PQ2/3p1PP1/3P3P/PPP5/2K1RR2 w - - 7 27',
    ultima: 'De6',
    marca: ['d5', 'e6'],
    solucion: { from: 'e5', to: 'f6' },
    primera: 'exf6',
    linea: '27.exf6 Dxf5 28.fxe7+ Axe7 29.gxf5',
    gana: true,
    valor: '+4,8',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 33vYs de la base abierta de Lichess (CC0), rating 1782. Stockfish 16 a profundidad 18: exf6 es la mejor (+4,8) y la segunda queda en -0,6.',
  },
  {
    n: 73,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_1bZaa',
    tema: 'veryLong',
    lichess: '1bZaa',
    rating: 1824,
    elo: 1044,
    juegan: 'b',
    fen: '7k/5Qp1/4P2p/3p4/3Pp3/pqP1P2P/6PK/8 b - - 0 35',
    ultima: 'e6',
    marca: ['e5', 'e6'],
    solucion: { from: 'b3', to: 'b8' },
    primera: 'Db8+',
    linea: '35…Db8+ 36.Rg1 a2 37.Df1 Db1 38.e7 Dxf1+',
    gana: true,
    valor: '+4,5',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1bZaa de la base abierta de Lichess (CC0), rating 1824. Stockfish 16 a profundidad 18: Db8+ es la mejor (+4,5) y la segunda queda en -3,6.',
  },
  {
    n: 74,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_1jXr1',
    tema: 'intermezzo',
    lichess: '1jXr1',
    rating: 2188,
    elo: 1408,
    juegan: 'b',
    fen: '2r5/5pk1/4b1p1/4p3/4P3/pB1K1P2/PrP5/1R5R b - - 5 29',
    ultima: 'Rd3',
    marca: ['c3', 'd3'],
    solucion: { from: 'e6', to: 'b3' },
    primera: 'Axb3',
    linea: '29…Axb3 30.Txb2 Ac4+ 31.Rd2 axb2',
    gana: true,
    valor: '+5,7',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 1jXr1 de la base abierta de Lichess (CC0), rating 2188. Stockfish 16 a profundidad 18: Axb3 es la mejor (+5,7) y la segunda queda en 0,0.',
  },
  {
    n: 75,
    uso: 'ejercicio',
    capitulo: 5,
    id: 're_28nbR',
    tema: 'veryLong',
    lichess: '28nbR',
    rating: 2272,
    elo: 1492,
    juegan: 'b',
    fen: '8/p6p/kp1QP3/2p5/3p2q1/3PR3/PPP3PP/6K1 b - - 0 32',
    ultima: 'Txe3',
    marca: ['e2', 'e3'],
    solucion: { from: 'd4', to: 'e3' },
    primera: 'dxe3',
    linea: '32…dxe3 33.h3 Dd1+ 34.Rh2 e2 35.Df4 e1=D',
    gana: true,
    valor: '+4,1',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 28nbR de la base abierta de Lichess (CC0), rating 2272. Stockfish 16 a profundidad 18: dxe3 es la mejor (+4,1) y la segunda queda en -5,0.',
  },
  {
    n: 76,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_2hxsn',
    tema: 'zugzwang',
    lichess: '2hxsn',
    rating: 1346,
    elo: 566,
    juegan: 'w',
    fen: '8/5k2/5p1p/6pP/4K1P1/5P2/8/8 w - - 4 51',
    ultima: 'Rf7',
    marca: ['e6', 'f7'],
    solucion: { from: 'e4', to: 'f5' },
    primera: 'Rf5',
    linea: '51.Rf5 Rg7 52.Re6 Rf8 53.Rxf6',
    gana: true,
    valor: '+6,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2hxsn de la base abierta de Lichess (CC0), rating 1346. Stockfish 16 a profundidad 18: Rf5 es la mejor (+6,8) y la segunda queda en 0,0.',
  },
  {
    n: 77,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_2NZMZ',
    tema: 'defensiveMove',
    lichess: '2NZMZ',
    rating: 1362,
    elo: 582,
    juegan: 'b',
    fen: '8/8/1B6/pK5p/1P6/P4k2/8/4b3 b - b3 0 43',
    ultima: 'b4',
    marca: ['b2', 'b4'],
    solucion: { from: 'a5', to: 'b4' },
    primera: 'axb4',
    linea: '43…axb4 44.axb4 h4',
    gana: true,
    valor: '+4,8',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2NZMZ de la base abierta de Lichess (CC0), rating 1362. Stockfish 16 a profundidad 18: axb4 es la mejor (+4,8) y la segunda queda en +0,4.',
  },
  {
    n: 78,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_0nBHN',
    tema: 'defensiveMove',
    lichess: '0nBHN',
    rating: 1414,
    elo: 634,
    juegan: 'w',
    fen: '8/1p3k2/7p/p2Npp1P/PbP5/1P1K1P2/8/8 w - - 5 42',
    ultima: 'Rf7',
    marca: ['e6', 'f7'],
    solucion: { from: 'd5', to: 'b4' },
    primera: 'Cxb4',
    linea: '42.Cxb4 axb4 43.c5',
    gana: false,
    valor: '+2,9',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0nBHN de la base abierta de Lichess (CC0), rating 1414. Stockfish 16 a profundidad 18: Cxb4 es la mejor (+2,9) y la segunda queda en -0,6.',
  },
  {
    n: 79,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_1KiYC',
    tema: 'defensiveMove',
    lichess: '1KiYC',
    rating: 1682,
    elo: 902,
    juegan: 'b',
    fen: '8/1p2N3/2p1R3/7Q/3pk3/4p3/1P5K/q4r2 b - - 6 49',
    ultima: 'Te6+',
    marca: ['g6', 'e6'],
    solucion: { from: 'e4', to: 'd3' },
    primera: 'Rd3',
    linea: '49…Rd3 50.Dg6+ Rd2',
    gana: true,
    valor: '+6,8',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1KiYC de la base abierta de Lichess (CC0), rating 1682. Stockfish 16 a profundidad 18: Rd3 es la mejor (+6,8) y la segunda queda en recibe mate en 1.',
  },
  {
    n: 80,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_0gjXA',
    tema: 'defensiveMove',
    lichess: '0gjXA',
    rating: 1731,
    elo: 951,
    juegan: 'w',
    fen: 'r2q1rk1/pp3ppp/1np1pb2/8/3P1B2/2PBRQ2/PP3PPP/R5K1 w - - 6 14',
    ultima: 'Cb6',
    marca: ['d7', 'b6'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '14.Axh7+ Rxh7 15.Dh5+ Rg8 16.Th3',
    gana: true,
    valor: '+3,9',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 0gjXA de la base abierta de Lichess (CC0), rating 1731. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+3,9) y la segunda queda en +0,5.',
  },
  {
    n: 81,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_36anG',
    tema: 'zugzwang',
    lichess: '36anG',
    rating: 2003,
    elo: 1223,
    juegan: 'b',
    fen: '8/8/6pp/2kp1p2/4rP1P/2PKR1P1/8/8 b - - 8 44',
    ultima: 'Rd3',
    marca: ['d2', 'd3'],
    solucion: { from: 'e4', to: 'e3' },
    primera: 'Txe3+',
    linea: '44…Txe3+ 45.Rxe3 Rc4 46.Rd2 d4 47.cxd4 Rxd4',
    gana: true,
    valor: '+4,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 36anG de la base abierta de Lichess (CC0), rating 2003. Stockfish 16 a profundidad 18: Txe3+ es la mejor (+4,8) y la segunda queda en 0,0.',
  },
  {
    n: 82,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_0YlAi',
    tema: 'defensiveMove',
    lichess: '0YlAi',
    rating: 2092,
    elo: 1312,
    juegan: 'w',
    fen: '5k1r/1p4p1/p2r2Bp/2P5/1P6/P6P/5PP1/6K1 w - - 0 29',
    ultima: 'Txd6',
    marca: ['d8', 'd6'],
    solucion: { from: 'c5', to: 'd6' },
    primera: 'cxd6',
    linea: '29.cxd6 h5 30.f4',
    gana: true,
    valor: '+3,5',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0YlAi de la base abierta de Lichess (CC0), rating 2092. Stockfish 16 a profundidad 18: cxd6 es la mejor (+3,5) y la segunda queda en -5,1.',
  },
  {
    n: 83,
    uso: 'ejercicio',
    capitulo: 6,
    id: 're_1iEla',
    tema: 'zugzwang',
    lichess: '1iEla',
    rating: 2144,
    elo: 1364,
    juegan: 'b',
    fen: '8/8/2p5/4k3/2Pp2P1/5K2/8/8 b - - 0 53',
    ultima: 'g4',
    marca: ['g3', 'g4'],
    solucion: { from: 'c6', to: 'c5' },
    primera: 'c5',
    linea: '53…c5 54.Rg3 Re4',
    gana: true,
    valor: '+5,3',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1iEla de la base abierta de Lichess (CC0), rating 2144. Stockfish 16 a profundidad 18: c5 es la mejor (+5,3) y la segunda queda en +0,0.',
  },
  {
    n: 84,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_1bTEt',
    tema: 'defensiveMove',
    lichess: '1bTEt',
    rating: 1329,
    elo: 549,
    juegan: 'w',
    fen: '8/5pk1/6p1/pRp5/2B1b2p/PP5P/3r1KP1/8 w - - 8 37',
    ultima: 'Td2+',
    marca: ['d4', 'd2'],
    solucion: { from: 'f2', to: 'e3' },
    primera: 'Re3',
    linea: '37.Re3 Txg2 38.Rxe4',
    gana: true,
    valor: '+3,0',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1bTEt de la base abierta de Lichess (CC0), rating 1329. Stockfish 16 a profundidad 18: Re3 es la mejor (+3,0) y la segunda queda en -2,8.',
  },
  {
    n: 85,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_1lAH1',
    tema: 'exposedKing',
    lichess: '1lAH1',
    rating: 1524,
    elo: 744,
    juegan: 'w',
    fen: '4k3/7R/2r2K2/3r4/6B1/5P2/8/8 w - - 5 58',
    ultima: 'Tc6+',
    marca: ['c1', 'c6'],
    solucion: { from: 'g4', to: 'e6' },
    primera: 'Ae6',
    linea: '58.Ae6 Rd8 59.Th8+ Rc7 60.Tc8+',
    gana: true,
    valor: '+4,8',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: '',
    comprobado: 'Ejercicio 1lAH1 de la base abierta de Lichess (CC0), rating 1524. Stockfish 16 a profundidad 18: Ae6 es la mejor (+4,8) y la segunda queda en recibe mate en 8.',
  },
  {
    n: 86,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_0RDbf',
    tema: 'sacrifice',
    lichess: '0RDbf',
    rating: 1648,
    elo: 868,
    juegan: 'w',
    fen: '1r3rk1/pbp3pp/1p2pp2/3n4/2NP1q2/P1P2B2/3Q1PPP/R4RK1 w - - 0 18',
    ultima: 'Dxf4',
    marca: ['d6', 'f4'],
    solucion: { from: 'f3', to: 'd5' },
    primera: 'Axd5',
    linea: '18.Axd5 Dxd2 19.Axe6+ Rh8 20.Cxd2',
    gana: true,
    valor: '+4,8',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 0RDbf de la base abierta de Lichess (CC0), rating 1648. Stockfish 16 a profundidad 18: Axd5 es la mejor (+4,8) y la segunda queda en -1,1.',
  },
  {
    n: 87,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_0u8Jf',
    tema: 'sacrifice',
    lichess: '0u8Jf',
    rating: 1655,
    elo: 875,
    juegan: 'b',
    fen: '8/1N5k/7p/p2p4/Ppp5/8/1P3K2/8 b - - 1 54',
    ultima: 'Cb7',
    marca: ['d6', 'b7'],
    solucion: { from: 'c4', to: 'c3' },
    primera: 'c3',
    linea: '54…c3 55.bxc3 b3 56.Cxa5 b2',
    gana: true,
    valor: '+5,2',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0u8Jf de la base abierta de Lichess (CC0), rating 1655. Stockfish 16 a profundidad 18: c3 es la mejor (+5,2) y la segunda queda en -0,2.',
  },
  {
    n: 88,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_2EURS',
    tema: 'exposedKing',
    lichess: '2EURS',
    rating: 1672,
    elo: 892,
    juegan: 'w',
    fen: '2r5/ppr1ppbk/7q/3pP2Q/3Pp1R1/1P6/P5PP/5RK1 w - - 0 23',
    ultima: 'Dxh6',
    marca: ['e6', 'h6'],
    solucion: { from: 'g4', to: 'g7' },
    primera: 'Txg7+',
    linea: '23.Txg7+ Rxg7 24.Txf7+ Rg8 25.Dxh6',
    gana: true,
    valor: '+4,0',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 2EURS de la base abierta de Lichess (CC0), rating 1672. Stockfish 16 a profundidad 18: Txg7+ es la mejor (+4,0) y la segunda queda en -3,3.',
  },
  {
    n: 89,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_2gSoe',
    tema: 'defensiveMove',
    lichess: '2gSoe',
    rating: 1848,
    elo: 1068,
    juegan: 'w',
    fen: '8/5p2/5Pkp/4P1r1/2R2K2/8/8/8 w - - 1 44',
    ultima: 'Rg6',
    marca: ['h7', 'g6'],
    solucion: { from: 'c4', to: 'c8' },
    primera: 'Tc8',
    linea: '44.Tc8 Tf5+ 45.Re4 Tf1 46.Tg8+ Rh7 47.Tg7+ Rh8 48.Txf7',
    gana: true,
    valor: '+3,9',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2gSoe de la base abierta de Lichess (CC0), rating 1848. Stockfish 16 a profundidad 18: Tc8 es la mejor (+3,9) y la segunda queda en 0,0.',
  },
  {
    n: 90,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_2XaTT',
    tema: 'sacrifice',
    lichess: '2XaTT',
    rating: 2199,
    elo: 1419,
    juegan: 'w',
    fen: 'r2k3r/1pp2ppp/2n1b3/4p3/1b6/P4NP1/4PPBP/R1B2RK1 w - - 0 13',
    ultima: 'Axb4',
    marca: ['c5', 'b4'],
    solucion: { from: 'a3', to: 'b4' },
    primera: 'axb4',
    linea: '13.axb4 Txa1 14.Ag5+ f6 15.Txa1',
    gana: true,
    valor: '+3,1',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2XaTT de la base abierta de Lichess (CC0), rating 2199. Stockfish 16 a profundidad 18: axb4 es la mejor (+3,1) y la segunda queda en -0,2.',
  },
  {
    n: 91,
    uso: 'ejercicio',
    capitulo: 7,
    id: 're_1mLmi',
    tema: 'defensiveMove',
    lichess: '1mLmi',
    rating: 2332,
    elo: 1552,
    juegan: 'w',
    fen: '8/8/1r3K1k/4P3/5P2/7P/8/8 w - - 3 55',
    ultima: 'Tb6+',
    marca: ['b1', 'b6'],
    solucion: { from: 'e5', to: 'e6' },
    primera: 'e6',
    linea: '55.e6 Rh7 56.Rf7 Tb5 57.e7 Tf5+ 58.Re6 Txf4 59.Rd5',
    gana: true,
    valor: '+4,3',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1mLmi de la base abierta de Lichess (CC0), rating 2332. Stockfish 16 a profundidad 18: e6 es la mejor (+4,3) y la segunda queda en -0,2.',
  },
  {
    n: 92,
    uso: 'mixto',
    capitulo: 0,
    id: 're_3CDlj',
    tema: 'exposedKing',
    lichess: '3CDlj',
    rating: 1283,
    elo: 503,
    juegan: 'b',
    fen: '8/r7/3P4/8/4k3/3R4/3K4/8 b - - 0 60',
    ultima: 'd6',
    marca: ['d5', 'd6'],
    solucion: { from: 'a7', to: 'a2' },
    primera: 'Ta2+',
    linea: '60…Ta2+ 61.Rc3 Ta3+ 62.Rb4 Txd3',
    gana: true,
    valor: '+5,2',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 3CDlj de la base abierta de Lichess (CC0), rating 1283. Stockfish 16 a profundidad 18: Ta2+ es la mejor (+5,2) y la segunda queda en 0,0.',
  },
  {
    n: 93,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1s0he',
    tema: 'zugzwang',
    lichess: '1s0he',
    rating: 1303,
    elo: 523,
    juegan: 'w',
    fen: '8/6k1/5p1p/3p4/p1pP2P1/PpP2K1P/1P6/8 w - - 4 36',
    ultima: 'Rg7',
    marca: ['f7', 'g7'],
    solucion: { from: 'f3', to: 'f4' },
    primera: 'Rf4',
    linea: '36.Rf4 Rg6 37.h4 Rg7 38.Rf5',
    gana: true,
    valor: '+3,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 1s0he de la base abierta de Lichess (CC0), rating 1303. Stockfish 16 a profundidad 18: Rf4 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 94,
    uso: 'mixto',
    capitulo: 0,
    id: 're_36DnU',
    tema: 'intermezzo',
    lichess: '36DnU',
    rating: 1465,
    elo: 685,
    juegan: 'w',
    fen: '3r2k1/1p3ppp/1q2p3/p2pP1N1/1n1P1Q2/1P6/P4PPP/2rR2K1 w - - 0 20',
    ultima: 'Txc1',
    marca: ['c8', 'c1'],
    solucion: { from: 'f4', to: 'f7' },
    primera: 'Dxf7+',
    linea: '20.Dxf7+ Rh8 21.Txc1',
    gana: true,
    valor: '+5,4',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 36DnU de la base abierta de Lichess (CC0), rating 1465. Stockfish 16 a profundidad 18: Dxf7+ es la mejor (+5,4) y la segunda queda en -0,3.',
  },
  {
    n: 95,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1fzmf',
    tema: 'defensiveMove',
    lichess: '1fzmf',
    rating: 1495,
    elo: 715,
    juegan: 'b',
    fen: 'r1b1k1nr/ppN2ppp/3p4/2b1q3/3pP1Q1/3B4/PPPP1PPP/R1B1K2R b KQkq - 0 9',
    ultima: 'Cxc7+',
    marca: ['d5', 'c7'],
    solucion: { from: 'e8', to: 'd8' },
    primera: 'Rd8',
    linea: '9…Rd8 10.Df3 Rxc7',
    gana: true,
    valor: '+3,1',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1fzmf de la base abierta de Lichess (CC0), rating 1495. Stockfish 16 a profundidad 18: Rd8 es la mejor (+3,1) y la segunda queda en -2,3.',
  },
  {
    n: 96,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1Y2Qh',
    tema: 'sacrifice',
    lichess: '1Y2Qh',
    rating: 1510,
    elo: 730,
    juegan: 'w',
    fen: '8/3k4/4p3/3pP1NP/7b/3K4/8/8 w - - 1 41',
    ultima: 'Ah4',
    marca: ['f2', 'h4'],
    solucion: { from: 'h5', to: 'h6' },
    primera: 'h6',
    linea: '41.h6 Axg5 42.h7',
    gana: true,
    valor: '+6,2',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1Y2Qh de la base abierta de Lichess (CC0), rating 1510. Stockfish 16 a profundidad 18: h6 es la mejor (+6,2) y la segunda queda en +0,0.',
  },
  {
    n: 97,
    uso: 'mixto',
    capitulo: 0,
    id: 're_3MXZP',
    tema: 'quietMove',
    lichess: '3MXZP',
    rating: 1573,
    elo: 793,
    juegan: 'b',
    fen: '3r2k1/5p1p/p1b1p1p1/8/2N3Q1/6RP/PPPq1PP1/6K1 b - - 0 27',
    ultima: 'Cxc4',
    marca: ['e3', 'c4'],
    solucion: { from: 'd2', to: 'e1' },
    primera: 'De1+',
    linea: '27…De1+ 28.Rh2 Td1 29.Dxd1 Dxd1',
    gana: true,
    valor: '+4,2',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 3MXZP de la base abierta de Lichess (CC0), rating 1573. Stockfish 16 a profundidad 18: De1+ es la mejor (+4,2) y la segunda queda en +0,8.',
  },
  {
    n: 98,
    uso: 'mixto',
    capitulo: 0,
    id: 're_0SRBP',
    tema: 'veryLong',
    lichess: '0SRBP',
    rating: 1582,
    elo: 802,
    juegan: 'b',
    fen: '8/2k5/1p2P3/7p/p1P1R3/3P1K2/6PP/4r3 b - - 8 43',
    ultima: 'Te4',
    marca: ['d4', 'e4'],
    solucion: { from: 'e1', to: 'e4' },
    primera: 'Txe4',
    linea: '43…Txe4 44.Rxe4 a3 45.e7 Rd7 46.e8=T Rxe8',
    gana: true,
    valor: '+4,5',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: '',
    comprobado: 'Ejercicio 0SRBP de la base abierta de Lichess (CC0), rating 1582. Stockfish 16 a profundidad 18: Txe4 es la mejor (+4,5) y la segunda queda en -4,7.',
  },
  {
    n: 99,
    uso: 'mixto',
    capitulo: 0,
    id: 're_09KGH',
    tema: 'pawnEndgame',
    lichess: '09KGH',
    rating: 1610,
    elo: 830,
    juegan: 'b',
    fen: '8/8/P1k1K3/3p3p/7P/6P1/8/8 b - - 0 40',
    ultima: 'a6',
    marca: ['a5', 'a6'],
    solucion: { from: 'd5', to: 'd4' },
    primera: 'd4',
    linea: '40…d4 41.g4 d3 42.a7 Rb7 43.a8=A+ Rxa8',
    gana: true,
    valor: '+3,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 09KGH de la base abierta de Lichess (CC0), rating 1610. Stockfish 16 a profundidad 18: d4 es la mejor (+3,0) y la segunda queda en -8,2.',
  },
  {
    n: 100,
    uso: 'mixto',
    capitulo: 0,
    id: 're_0Q1GF',
    tema: 'pawnEndgame',
    lichess: '0Q1GF',
    rating: 1662,
    elo: 882,
    juegan: 'w',
    fen: '8/8/8/1p6/4K1Pp/2k5/2P5/8 w - - 0 53',
    ultima: 'gxh4',
    marca: ['g5', 'h4'],
    solucion: { from: 'g4', to: 'g5' },
    primera: 'g5',
    linea: '53.g5 h3 54.Rf3 b4 55.g6 Rxc2 56.g7 h2 57.Rg2 b3 58.g8=D',
    gana: true,
    valor: '+5,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0Q1GF de la base abierta de Lichess (CC0), rating 1662. Stockfish 16 a profundidad 18: g5 es la mejor (+5,0) y la segunda queda en 0,0.',
  },
  {
    n: 101,
    uso: 'mixto',
    capitulo: 0,
    id: 're_2Nt4N',
    tema: 'veryLong',
    lichess: '2Nt4N',
    rating: 1715,
    elo: 935,
    juegan: 'w',
    fen: '8/p4k2/1pN1p2R/5p2/2b5/P1Pq1P2/6PK/8 w - - 3 36',
    ultima: 'Rf7',
    marca: ['f6', 'f7'],
    solucion: { from: 'c6', to: 'e5' },
    primera: 'Ce5+',
    linea: '36.Ce5+ Rg7 37.Tg6+ Rh7 38.Cxd3 Rxg6 39.Ce5+ Rf6 40.Cxc4',
    gana: true,
    valor: '+4,3',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2Nt4N de la base abierta de Lichess (CC0), rating 1715. Stockfish 16 a profundidad 18: Ce5+ es la mejor (+4,3) y la segunda queda en -5,0.',
  },
  {
    n: 102,
    uso: 'mixto',
    capitulo: 0,
    id: 're_26kgi',
    tema: 'exposedKing',
    lichess: '26kgi',
    rating: 1734,
    elo: 954,
    juegan: 'w',
    fen: '3rk1r1/1R6/p2R4/P2p4/3Pb3/2P5/1P3K2/8 w - - 1 35',
    ultima: 'Td8',
    marca: ['c8', 'd8'],
    solucion: { from: 'd6', to: 'd8' },
    primera: 'Txd8+',
    linea: '35.Txd8+ Rxd8 36.Tb8+ Rd7 37.Txg8',
    gana: true,
    valor: '+6,4',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 26kgi de la base abierta de Lichess (CC0), rating 1734. Stockfish 16 a profundidad 18: Txd8+ es la mejor (+6,4) y la segunda queda en +0,6.',
  },
  {
    n: 103,
    uso: 'mixto',
    capitulo: 0,
    id: 're_3RqUC',
    tema: 'zugzwang',
    lichess: '3RqUC',
    rating: 1736,
    elo: 956,
    juegan: 'w',
    fen: '8/8/2p5/1k1pK3/p2P4/1PP5/8/8 w - - 0 47',
    ultima: 'a4',
    marca: ['a5', 'a4'],
    solucion: { from: 'b3', to: 'a4' },
    primera: 'bxa4+',
    linea: '47.bxa4+ Rxa4 48.Rd6 Rb5 49.Rc7 c5 50.Rd6 cxd4 51.cxd4 Rc4 52.Re5 Rc3 53.Rxd5',
    gana: true,
    valor: '+7,2',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 3RqUC de la base abierta de Lichess (CC0), rating 1736. Stockfish 16 a profundidad 18: bxa4+ es la mejor (+7,2) y la segunda queda en -7,0.',
  },
  {
    n: 104,
    uso: 'mixto',
    capitulo: 0,
    id: 're_0YH7Q',
    tema: 'sacrifice',
    lichess: '0YH7Q',
    rating: 1746,
    elo: 966,
    juegan: 'b',
    fen: 'r1b2rk1/pp1p2pp/2p2n2/4b3/1q6/2NBP3/PPPQ1PPP/R1B2RK1 b - - 1 12',
    ultima: 'O-O',
    marca: ['e1', 'g1'],
    solucion: { from: 'e5', to: 'h2' },
    primera: 'Axh2+',
    linea: '12…Axh2+ 13.Rxh2 Dh4+ 14.Rg1 Cg4',
    gana: true,
    valor: '+6,1',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 0YH7Q de la base abierta de Lichess (CC0), rating 1746. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+6,1) y la segunda queda en -0,7.',
  },
  {
    n: 105,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1uUY3',
    tema: 'defensiveMove',
    lichess: '1uUY3',
    rating: 1856,
    elo: 1076,
    juegan: 'w',
    fen: '6R1/8/1P2pk2/3p3p/P7/2K5/r5p1/8 w - - 2 51',
    ultima: 'Ta2',
    marca: ['e2', 'a2'],
    solucion: { from: 'b6', to: 'b7' },
    primera: 'b7',
    linea: '51.b7 d4+ 52.Rb3',
    gana: true,
    valor: '+5,2',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1uUY3 de la base abierta de Lichess (CC0), rating 1856. Stockfish 16 a profundidad 18: b7 es la mejor (+5,2) y la segunda queda en +1,1.',
  },
  {
    n: 106,
    uso: 'mixto',
    capitulo: 0,
    id: 're_3N9mT',
    tema: 'quietMove',
    lichess: '3N9mT',
    rating: 1934,
    elo: 1154,
    juegan: 'b',
    fen: '2r5/R3B3/p4p2/5k2/5Pn1/2P1p1P1/PP2K3/8 b - - 2 28',
    ultima: 'Ae7',
    marca: ['f8', 'e7'],
    solucion: { from: 'c8', to: 'h8' },
    primera: 'Th8',
    linea: '28…Th8 29.Ac5 Th2+',
    gana: true,
    valor: '+3,6',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3N9mT de la base abierta de Lichess (CC0), rating 1934. Stockfish 16 a profundidad 18: Th8 es la mejor (+3,6) y la segunda queda en -0,6.',
  },
  {
    n: 107,
    uso: 'mixto',
    capitulo: 0,
    id: 're_240UX',
    tema: 'intermezzo',
    lichess: '240UX',
    rating: 2049,
    elo: 1269,
    juegan: 'w',
    fen: '1k1r1b1r/1pq1pppp/8/pb1P4/Pn1Q4/1PN1BP2/5P1P/R3K2R w KQ - 0 17',
    ultima: 'Axb5',
    marca: ['d7', 'b5'],
    solucion: { from: 'd4', to: 'a7' },
    primera: 'Da7+',
    linea: '17.Da7+ Rc8 18.Cxb5',
    gana: true,
    valor: '+5,1',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 240UX de la base abierta de Lichess (CC0), rating 2049. Stockfish 16 a profundidad 18: Da7+ es la mejor (+5,1) y la segunda queda en -0,6.',
  },
  {
    n: 108,
    uso: 'mixto',
    capitulo: 0,
    id: 're_0Lthg',
    tema: 'intermezzo',
    lichess: '0Lthg',
    rating: 2091,
    elo: 1311,
    juegan: 'w',
    fen: '2r5/5pkp/3R1pp1/4P3/2q4P/1n4P1/4Q2K/8 w - - 0 38',
    ultima: 'Dxc4',
    marca: ['b4', 'c4'],
    solucion: { from: 'e5', to: 'f6' },
    primera: 'exf6+',
    linea: '38.exf6+ Rg8 39.Dxc4',
    gana: true,
    valor: '+37,3',
    pista: 'Antes de la jugada obvia, ¿hay un jaque o una amenaza más fuerte?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 0Lthg de la base abierta de Lichess (CC0), rating 2091. Stockfish 16 a profundidad 18: exf6+ es la mejor (+37,3) y la segunda queda en -3,9.',
  },
  {
    n: 109,
    uso: 'mixto',
    capitulo: 0,
    id: 're_2neKj',
    tema: 'exposedKing',
    lichess: '2neKj',
    rating: 2131,
    elo: 1351,
    juegan: 'w',
    fen: 'r1b1q1k1/2p1p1b1/pn3rp1/6Q1/N7/3B3P/1PP2PP1/3RR1K1 w - - 3 19',
    ultima: 'De8',
    marca: ['d8', 'e8'],
    solucion: { from: 'a4', to: 'b6' },
    primera: 'Cxb6',
    linea: '19.Cxb6 cxb6 20.Dd5+ Ae6 21.Txe6',
    gana: true,
    valor: '+4,4',
    pista: 'El factor que manda es el rey rival: ¿qué le falta para defenderse?',
    explica: 'Es un tenedor: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2neKj de la base abierta de Lichess (CC0), rating 2131. Stockfish 16 a profundidad 18: Cxb6 es la mejor (+4,4) y la segunda queda en -1,0.',
  },
  {
    n: 110,
    uso: 'mixto',
    capitulo: 0,
    id: 're_0q8KX',
    tema: 'pawnEndgame',
    lichess: '0q8KX',
    rating: 2194,
    elo: 1414,
    juegan: 'w',
    fen: '8/6p1/7p/k7/P4K1P/8/8/8 w - - 0 41',
    ultima: 'Rxa5',
    marca: ['b4', 'a5'],
    solucion: { from: 'h4', to: 'h5' },
    primera: 'h5',
    linea: '41.h5 Rxa4 42.Rf5 Rb5 43.Rg6 Rc6 44.Rxg7 Rd7 45.Rxh6 Re7 46.Rg7',
    gana: true,
    valor: '+35,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0q8KX de la base abierta de Lichess (CC0), rating 2194. Stockfish 16 a profundidad 18: h5 es la mejor (+35,8) y la segunda queda en 0,0.',
  },
  {
    n: 111,
    uso: 'mixto',
    capitulo: 0,
    id: 're_2Lyss',
    tema: 'quietMove',
    lichess: '2Lyss',
    rating: 2323,
    elo: 1543,
    juegan: 'w',
    fen: 'r6k/1bq3p1/p2pQbp1/5N2/1p1NP3/8/PP3r1P/1K1R3R w - - 0 25',
    ultima: 'hxg6',
    marca: ['h7', 'g6'],
    solucion: { from: 'd1', to: 'd3' },
    primera: 'Td3',
    linea: '25.Td3 Df7 26.Dxf7',
    gana: true,
    valor: '+3,1',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que deja una amenaza sin defensa.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2Lyss de la base abierta de Lichess (CC0), rating 2323. Stockfish 16 a profundidad 18: Td3 es la mejor (+3,1) y la segunda queda en -0,3.',
  },
  {
    n: 112,
    uso: 'mixto',
    capitulo: 0,
    id: 're_2a3it',
    tema: 'zugzwang',
    lichess: '2a3it',
    rating: 2352,
    elo: 1572,
    juegan: 'w',
    fen: '8/1p4pp/1pp1k1b1/8/5KP1/P7/1PB3P1/8 w - - 1 36',
    ultima: 'Ag6',
    marca: ['h5', 'g6'],
    solucion: { from: 'c2', to: 'g6' },
    primera: 'Axg6',
    linea: '36.Axg6 hxg6 37.Rg5 Rf7 38.a4 c5 39.b3 Re6 40.Rxg6',
    gana: true,
    valor: '+3,0',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2a3it de la base abierta de Lichess (CC0), rating 2352. Stockfish 16 a profundidad 18: Axg6 es la mejor (+3,0) y la segunda queda en -2,2.',
  },
  {
    n: 113,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1Z8fW',
    tema: 'defensiveMove',
    lichess: '1Z8fW',
    rating: 2368,
    elo: 1588,
    juegan: 'b',
    fen: '5R2/6pp/2pkr3/8/1P1p4/6P1/P4PP1/5K2 b - - 1 28',
    ultima: 'Tf8',
    marca: ['f7', 'f8'],
    solucion: { from: 'd6', to: 'd5' },
    primera: 'Rd5',
    linea: '28…Rd5 29.Td8+ Rc4',
    gana: false,
    valor: '+2,6',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1Z8fW de la base abierta de Lichess (CC0), rating 2368. Stockfish 16 a profundidad 18: Rd5 es la mejor (+2,6) y la segunda queda en 0,0.',
  },
  {
    n: 114,
    uso: 'mixto',
    capitulo: 0,
    id: 're_2CqeR',
    tema: 'sacrifice',
    lichess: '2CqeR',
    rating: 2383,
    elo: 1603,
    juegan: 'b',
    fen: '3r2k1/6pp/p3pp2/1p2P3/2qNKP2/8/1Q4PP/2R5 b - - 1 36',
    ultima: 'Tc1',
    marca: ['b1', 'c1'],
    solucion: { from: 'd8', to: 'd4' },
    primera: 'Txd4+',
    linea: '36…Txd4+ 37.Dxd4 f5+ 38.Re3 Dxc1+',
    gana: true,
    valor: '+3,6',
    pista: 'Lo que cuenta no es el material que entregas, sino lo que queda en el tablero después.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 2CqeR de la base abierta de Lichess (CC0), rating 2383. Stockfish 16 a profundidad 18: Txd4+ es la mejor (+3,6) y la segunda queda en -0,2.',
  },
  {
    n: 115,
    uso: 'mixto',
    capitulo: 0,
    id: 're_1GDHY',
    tema: 'veryLong',
    lichess: '1GDHY',
    rating: 2402,
    elo: 1622,
    juegan: 'b',
    fen: '8/bp4k1/p3p2p/3p4/1r1P1P2/6P1/3Q3P/6K1 b - f3 0 34',
    ultima: 'f4',
    marca: ['f2', 'f4'],
    solucion: { from: 'a7', to: 'd4' },
    primera: 'Axd4+',
    linea: '34…Axd4+ 35.Rf1 Tb1+ 36.Re2 Tb2 37.Dxb2 Axb2',
    gana: true,
    valor: '+6,0',
    pista: 'La línea es larga: calcúlala hasta el final antes de tocar una pieza.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 1GDHY de la base abierta de Lichess (CC0), rating 2402. Stockfish 16 a profundidad 18: Axd4+ es la mejor (+6,0) y la segunda queda en -0,9.',
  },
];
