/* ===== Las posiciones de «Ideas que ganan partidas», de Oscar Angulo Cubero =====
 *
 * GENERADO por herramientas/ideas-que-ganan-partidas-generar.js — no se edita a mano.
 *
 * 107 posiciones de la base abierta de Lichess (CC0), comprobadas con
 * Stockfish: 35 ejemplos (uno por lección, los mismos del curso),
 * 48 ejercicios por capítulo y 24 mixtos. Lo usa el libro
 * (herramientas/ideas-que-ganan-partidas-pdf.js). Vive detrás del candado de
 * material/: trae las respuestas.
 */
window.IDEAS_QUE_GANAN = {
  TITULO: 'Ideas que ganan partidas',
  AUTOR: 'Oscar Angulo Cubero',
  POR_CAPITULO: 8,
  MIXTOS: 24,
  CAPITULOS: [{ n: 1, titulo: 'El ataque al rey enrocado', ideas: ['concentracion', 'h7', 'demolicion', 'mayores', 'octava', 'patrones'] }, { n: 2, titulo: 'El rey en el centro y los enroques opuestos', ideas: ['reycentro', 'f7', 'desarrollo', 'extraccion', 'opuestos', 'defensa'] }, { n: 3, titulo: 'Las piezas en su sitio', ideas: ['septima', 'caballo', 'alfil', 'dama', 'atrapada', 'calidad'] }, { n: 4, titulo: 'Los peones deciden', ideas: ['pasado', 'coronar', 'ruptura', 'peonsac', 'peones', 'detener'] }, { n: 5, titulo: 'La táctica que sostiene el plan', ideas: ['desviacion', 'defensor', 'interferencia', 'clavada', 'despeje', 'rayosx'] }, { n: 6, titulo: 'Los finales que hay que saber', ideas: ['torres', 'alfiles', 'alfilcaballo', 'damas', 'zugzwang'] }],
};
window.IDEAS_QUE_GANAN_ITEMS = [
  {
    n: 1,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 1,
    id: 'ig_0eUUp',
    tema: 'concentracion',
    lichess: '0eUUp',
    rating: 1312,
    elo: 532,
    juegan: 'w',
    fen: 'r2b2k1/ppp2rpp/3pR3/3P4/2P2B2/8/PP4PP/5RK1 w - - 2 21',
    ultima: 'Tf7',
    marca: ['f5', 'f7'],
    solucion: { from: 'e6', to: 'e8' },
    primera: 'Te8+',
    linea: '21.Te8+ Tf8 22.Txf8+ Rxf8 23.Axd6+',
    gana: true,
    valor: '+4,0',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 0eUUp de la base abierta de Lichess (CC0), rating 1312. Stockfish 16 a profundidad 18: Te8+ es la mejor (+4,0) y la segunda queda en +0,2.',
  },
  {
    n: 2,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 2,
    id: 'ig_1tJp9',
    tema: 'h7',
    lichess: '1tJp9',
    rating: 1585,
    elo: 805,
    juegan: 'w',
    fen: 'r1bq1rk1/pp2nppp/1bn1p3/3pP3/3P4/2PB1N2/P4PPP/RNBQK2R w KQ - 1 9',
    ultima: 'Cbc6',
    marca: ['b8', 'c6'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '9.Axh7+ Rxh7 10.Cg5+',
    gana: true,
    valor: '+5,1',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1tJp9 de la base abierta de Lichess (CC0), rating 1585. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+5,1) y la segunda queda en +0,6.',
  },
  {
    n: 3,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 3,
    id: 'ig_0yjuV',
    tema: 'demolicion',
    lichess: '0yjuV',
    rating: 1355,
    elo: 575,
    juegan: 'w',
    fen: '1b5k/1p3qp1/p1npR2p/P1pQp3/2P5/8/5PPP/6K1 w - - 7 39',
    ultima: 'Df7',
    marca: ['e7', 'f7'],
    solucion: { from: 'e6', to: 'h6' },
    primera: 'Txh6+',
    linea: '39.Txh6+ Rg8 40.Th8+ Rxh8 41.Dxf7',
    gana: true,
    valor: '+5,5',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0yjuV de la base abierta de Lichess (CC0), rating 1355. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+5,5) y la segunda queda en -3,0.',
  },
  {
    n: 4,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 4,
    id: 'ig_2vk7U',
    tema: 'mayores',
    lichess: '2vk7U',
    rating: 1493,
    elo: 713,
    juegan: 'w',
    fen: '3r1rk1/pp3pp1/1n2q2p/2p1P3/7P/5N2/PP1Q1PP1/1K1R3R w - - 2 19',
    ultima: 'Tad8',
    marca: ['a8', 'd8'],
    solucion: { from: 'd2', to: 'd8' },
    primera: 'Dxd8',
    linea: '19.Dxd8 Txd8 20.Txd8+ Rh7 21.Cg5+ hxg5 22.hxg5+ Rg6 23.Td6',
    gana: true,
    valor: '+4,8',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2vk7U de la base abierta de Lichess (CC0), rating 1493. Stockfish 16 a profundidad 18: Dxd8 es la mejor (+4,8) y la segunda queda en -1,1.',
  },
  {
    n: 5,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 5,
    id: 'ig_12rIE',
    tema: 'octava',
    lichess: '12rIE',
    rating: 1388,
    elo: 608,
    juegan: 'b',
    fen: '4rk2/pQ6/7R/4q1p1/2p5/2Pb4/PP4PP/R5K1 b - - 0 31',
    ultima: 'Dxb7',
    marca: ['d5', 'b7'],
    solucion: { from: 'e5', to: 'e3' },
    primera: 'De3+',
    linea: '31…De3+ 32.Rh1 De1+ 33.Txe1 Txe1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 12rIE de la base abierta de Lichess (CC0), rating 1388. Stockfish 16 a profundidad 18: De3+ es la mejor (mate en 3) y la segunda queda en -4,0.',
  },
  {
    n: 6,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 6,
    id: 'ig_35JUo',
    tema: 'patrones',
    lichess: '35JUo',
    rating: 1484,
    elo: 704,
    juegan: 'b',
    fen: '1k4r1/1pp5/8/p1qQp3/2Pn4/P7/5RP1/5RK1 b - - 2 38',
    ultima: 'Dd5',
    marca: ['f3', 'd5'],
    solucion: { from: 'd4', to: 'e2' },
    primera: 'Ce2+',
    linea: '38…Ce2+ 39.Rh2 Th8#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 35JUo de la base abierta de Lichess (CC0), rating 1484. Stockfish 16 a profundidad 18: Ce2+ es la mejor (mate en 2) y la segunda queda en -1,2.',
  },
  {
    n: 7,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 7,
    id: 'ig_2XhlY',
    tema: 'reycentro',
    lichess: '2XhlY',
    rating: 1609,
    elo: 829,
    juegan: 'w',
    fen: '2Qqk2r/1p4pp/5p2/1p1pbp2/5r2/8/PP3P1P/2R1R1K1 w k - 2 24',
    ultima: 'Dd8',
    marca: ['d7', 'd8'],
    solucion: { from: 'c8', to: 'e6' },
    primera: 'De6+',
    linea: '24.De6+ Rf8 25.Tc8 Dxc8 26.Dxc8+ Rf7 27.Dxh8',
    gana: true,
    valor: '+5,0',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 2XhlY de la base abierta de Lichess (CC0), rating 1609. Stockfish 16 a profundidad 18: De6+ es la mejor (+5,0) y la segunda queda en 0,0.',
  },
  {
    n: 8,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 8,
    id: 'ig_1yuqX',
    tema: 'f7',
    lichess: '1yuqX',
    rating: 1479,
    elo: 699,
    juegan: 'b',
    fen: 'r1bqk2r/ppp1Pppp/2n5/2b5/5B2/2P5/PP2PPPP/RN1QKBNR b KQkq - 0 6',
    ultima: 'dxe7',
    marca: ['d6', 'e7'],
    solucion: { from: 'c5', to: 'f2' },
    primera: 'Axf2+',
    linea: '6…Axf2+ 7.Rxf2 Dxd1',
    gana: true,
    valor: '+4,3',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1yuqX de la base abierta de Lichess (CC0), rating 1479. Stockfish 16 a profundidad 18: Axf2+ es la mejor (+4,3) y la segunda queda en -4,1.',
  },
  {
    n: 9,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 9,
    id: 'ig_1ghMX',
    tema: 'desarrollo',
    lichess: '1ghMX',
    rating: 1373,
    elo: 593,
    juegan: 'w',
    fen: 'rnbqkb1r/ppp2ppp/4pn2/4N3/8/3Q4/PPP2PPP/RNB1KB1R w KQkq - 1 6',
    ultima: 'Cf6',
    marca: ['g8', 'f6'],
    solucion: { from: 'd3', to: 'd8' },
    primera: 'Dxd8+',
    linea: '6.Dxd8+ Rxd8 7.Cxf7+ Re8 8.Cxh8',
    gana: true,
    valor: '+3,7',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1ghMX de la base abierta de Lichess (CC0), rating 1373. Stockfish 16 a profundidad 18: Dxd8+ es la mejor (+3,7) y la segunda queda en -0,8.',
  },
  {
    n: 10,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 10,
    id: 'ig_1bOdm',
    tema: 'extraccion',
    lichess: '1bOdm',
    rating: 1602,
    elo: 822,
    juegan: 'w',
    fen: '4R3/1p3p1k/p1n3pp/2Qp3N/1P1r4/5qP1/5P1P/6K1 w - - 4 37',
    ultima: 'Df3',
    marca: ['d3', 'f3'],
    solucion: { from: 'e8', to: 'h8' },
    primera: 'Th8+',
    linea: '37.Th8+ Rxh8 38.Df8+ Rh7 39.Dg7#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Un jaque con sacrificio puede sacar al rey de su casa. Afuera está solo.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1bOdm de la base abierta de Lichess (CC0), rating 1602. Stockfish 16 a profundidad 18: Th8+ es la mejor (mate en 3) y la segunda queda en -5,1.',
  },
  {
    n: 11,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 11,
    id: 'ig_2jpNp',
    tema: 'opuestos',
    lichess: '2jpNp',
    rating: 1615,
    elo: 835,
    juegan: 'b',
    fen: '3r2k1/pppb1p1p/6p1/q4P2/2P1P3/1KQ5/P2N3P/R5R1 b - - 2 28',
    ultima: 'Dc3',
    marca: ['e3', 'c3'],
    solucion: { from: 'd7', to: 'a4' },
    primera: 'Aa4+',
    linea: '28…Aa4+ 29.Rb2 Txd2+ 30.Dxd2 Dxd2+',
    gana: true,
    valor: '+6,3',
    pista: 'Con los reyes en flancos distintos, gana quien llegue primero.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2jpNp de la base abierta de Lichess (CC0), rating 1615. Stockfish 16 a profundidad 18: Aa4+ es la mejor (+6,3) y la segunda queda en -3,8.',
  },
  {
    n: 12,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 12,
    id: 'ig_2HqSP',
    tema: 'defensa',
    lichess: '2HqSP',
    rating: 1429,
    elo: 649,
    juegan: 'w',
    fen: 'r4rk1/3b1p2/3p1R2/2pPp3/1pP1n2N/8/4BR2/6K1 w - - 4 36',
    ultima: 'Ce4',
    marca: ['d2', 'e4'],
    solucion: { from: 'f2', to: 'g2' },
    primera: 'Tg2+',
    linea: '36.Tg2+ Rh7 37.Ad3 Ta1+ 38.Rh2',
    gana: true,
    valor: '+3,7',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 2HqSP de la base abierta de Lichess (CC0), rating 1429. Stockfish 16 a profundidad 18: Tg2+ es la mejor (+3,7) y la segunda queda en -5,1.',
  },
  {
    n: 13,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 13,
    id: 'ig_2K2IX',
    tema: 'septima',
    lichess: '2K2IX',
    rating: 1279,
    elo: 499,
    juegan: 'b',
    fen: '2r2k2/2R3pp/1ppp4/8/8/P1P2P2/1P1rRKPP/8 b - - 0 26',
    ultima: 'Txc7',
    marca: ['e7', 'c7'],
    solucion: { from: 'd2', to: 'e2' },
    primera: 'Txe2+',
    linea: '26…Txe2+ 27.Rxe2 Txc7',
    gana: true,
    valor: '+5,3',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2K2IX de la base abierta de Lichess (CC0), rating 1279. Stockfish 16 a profundidad 18: Txe2+ es la mejor (+5,3) y la segunda queda en -1,8.',
  },
  {
    n: 14,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 14,
    id: 'ig_25UOh',
    tema: 'caballo',
    lichess: '25UOh',
    rating: 1645,
    elo: 865,
    juegan: 'w',
    fen: '2qr2k1/p4p1p/1b3Pp1/5N2/2P5/7P/P4rQ1/3RR1K1 w - - 0 26',
    ultima: 'Txf2',
    marca: ['b2', 'f2'],
    solucion: { from: 'f5', to: 'e7' },
    primera: 'Ce7+',
    linea: '26.Ce7+ Rf8 27.Cxc8 Txg2+ 28.Rxg2',
    gana: true,
    valor: '+4,5',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 25UOh de la base abierta de Lichess (CC0), rating 1645. Stockfish 16 a profundidad 18: Ce7+ es la mejor (+4,5) y la segunda queda en -4,8.',
  },
  {
    n: 15,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 15,
    id: 'ig_2tT48',
    tema: 'alfil',
    lichess: '2tT48',
    rating: 1590,
    elo: 810,
    juegan: 'w',
    fen: 'r3q1kr/2pbB1p1/p1N2bQp/1p2p3/7P/1P3PP1/1PP5/3RK2R w K - 6 24',
    ultima: 'De8',
    marca: ['c8', 'e8'],
    solucion: { from: 'e7', to: 'f6' },
    primera: 'Axf6',
    linea: '24.Axf6 Dxg6 25.Ce7+ Rh7 26.Cxg6',
    gana: true,
    valor: '+3,4',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2tT48 de la base abierta de Lichess (CC0), rating 1590. Stockfish 16 a profundidad 18: Axf6 es la mejor (+3,4) y la segunda queda en -3,7.',
  },
  {
    n: 16,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 16,
    id: 'ig_2QnPY',
    tema: 'dama',
    lichess: '2QnPY',
    rating: 1567,
    elo: 787,
    juegan: 'b',
    fen: '5rk1/pp3rpp/1q6/3Q4/3p4/1P4P1/PB1N1RKP/8 b - - 0 26',
    ultima: 'Txf2',
    marca: ['e2', 'f2'],
    solucion: { from: 'b6', to: 'c6' },
    primera: 'Dc6',
    linea: '26…Dc6 27.Tf5 Dxd5+ 28.Txd5 Tf2+ 29.Rh3 Txd2',
    gana: true,
    valor: '+4,2',
    pista: 'No hay jaque ni captura que sirva: la dama gana con una jugada tranquila.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2QnPY de la base abierta de Lichess (CC0), rating 1567. Stockfish 16 a profundidad 18: Dc6 es la mejor (+4,2) y la segunda queda en 0,0.',
  },
  {
    n: 17,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 17,
    id: 'ig_1r5Zh',
    tema: 'atrapada',
    lichess: '1r5Zh',
    rating: 1431,
    elo: 651,
    juegan: 'w',
    fen: 'r3kb1r/pp3ppp/2npp1b1/2p5/4N1Pq/3P3P/PPP2PB1/R1BQK2R w KQkq - 0 11',
    ultima: 'Dxh4',
    marca: ['d8', 'h4'],
    solucion: { from: 'c1', to: 'g5' },
    primera: 'Ag5',
    linea: '11.Ag5 Axe4 12.Axh4',
    gana: true,
    valor: '+4,2',
    pista: 'Una pieza rival se quedó sin casillas. ¿Cómo la atacas?',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 1r5Zh de la base abierta de Lichess (CC0), rating 1431. Stockfish 16 a profundidad 18: Ag5 es la mejor (+4,2) y la segunda queda en -1,2.',
  },
  {
    n: 18,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 18,
    id: 'ig_11MuH',
    tema: 'calidad',
    lichess: '11MuH',
    rating: 1583,
    elo: 803,
    juegan: 'w',
    fen: 'r4r1k/2p1b1p1/p3bp1p/1p2n2q/7N/P1N4P/1PQB1PP1/3RR1K1 w - - 2 21',
    ultima: 'Dh5',
    marca: ['e8', 'h5'],
    solucion: { from: 'e1', to: 'e5' },
    primera: 'Txe5',
    linea: '21.Txe5 fxe5 22.Cg6+ Rg8 23.Cxe7+',
    gana: true,
    valor: '+3,9',
    pista: 'Entregar la torre por una pieza menor está bien si lo que queda vale más.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 11MuH de la base abierta de Lichess (CC0), rating 1583. Stockfish 16 a profundidad 18: Txe5 es la mejor (+3,9) y la segunda queda en -0,3.',
  },
  {
    n: 19,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 19,
    id: 'ig_0lARS',
    tema: 'pasado',
    lichess: '0lARS',
    rating: 1321,
    elo: 541,
    juegan: 'b',
    fen: '8/8/6K1/7P/8/p7/1p6/k4Q2 b - - 7 56',
    ultima: 'Df1+',
    marca: ['c4', 'f1'],
    solucion: { from: 'b2', to: 'b1', promotion: 'q' },
    primera: 'b1=D+',
    linea: '56…b1=D+ 57.Dxb1+ Rxb1 58.h6 a2 59.Rg7 a1=D+',
    gana: true,
    valor: '+34,9',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0lARS de la base abierta de Lichess (CC0), rating 1321. Stockfish 16 a profundidad 18: b1=D+ es la mejor (+34,9) y la segunda queda en -0,0.',
  },
  {
    n: 20,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 20,
    id: 'ig_26Lkb',
    tema: 'coronar',
    lichess: '26Lkb',
    rating: 1295,
    elo: 515,
    juegan: 'b',
    fen: '7Q/8/4bpk1/8/4PK2/P7/6pp/1R6 b - - 1 50',
    ultima: 'Dh8',
    marca: ['b8', 'h8'],
    solucion: { from: 'g2', to: 'g1', promotion: 'q' },
    primera: 'g1=D',
    linea: '50…g1=D 51.Txg1+ hxg1=D 52.De8+ Af7',
    gana: true,
    valor: '+3,5',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 26Lkb de la base abierta de Lichess (CC0), rating 1295. Stockfish 16 a profundidad 18: g1=D es la mejor (+3,5) y la segunda queda en -6,6.',
  },
  {
    n: 21,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 21,
    id: 'ig_3RUBS',
    tema: 'ruptura',
    lichess: '3RUBS',
    rating: 1371,
    elo: 591,
    juegan: 'w',
    fen: 'r7/p3kppp/1q6/4PP2/B2rQ3/2b5/P5PP/5R1K w - - 1 24',
    ultima: 'Td4',
    marca: ['d8', 'd4'],
    solucion: { from: 'f5', to: 'f6' },
    primera: 'f6+',
    linea: '24.f6+ gxf6 25.exf6+',
    gana: true,
    valor: '+5,0',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 3RUBS de la base abierta de Lichess (CC0), rating 1371. Stockfish 16 a profundidad 18: f6+ es la mejor (+5,0) y la segunda queda en 0,0.',
  },
  {
    n: 22,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 22,
    id: 'ig_3P3ul',
    tema: 'peonsac',
    lichess: '3P3ul',
    rating: 1604,
    elo: 824,
    juegan: 'w',
    fen: 'r3r1k1/4qppp/p7/2p2P2/3p2RQ/1P2p3/P1P3PP/3R2K1 w - - 1 30',
    ultima: 'De7',
    marca: ['b7', 'e7'],
    solucion: { from: 'f5', to: 'f6' },
    primera: 'f6',
    linea: '30.f6 Df8 31.Txg7+ Dxg7 32.fxg7',
    gana: true,
    valor: '+3,8',
    pista: 'El peón se entrega a propósito: lo que importa es lo que abre.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3P3ul de la base abierta de Lichess (CC0), rating 1604. Stockfish 16 a profundidad 18: f6 es la mejor (+3,8) y la segunda queda en -0,6.',
  },
  {
    n: 23,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 23,
    id: 'ig_2M12b',
    tema: 'peones',
    lichess: '2M12b',
    rating: 1365,
    elo: 585,
    juegan: 'b',
    fen: '8/8/2pp1k1p/1p2P3/p2P1KP1/2P5/1P4P1/8 b - - 0 37',
    ultima: 'e5+',
    marca: ['e4', 'e5'],
    solucion: { from: 'd6', to: 'e5' },
    primera: 'dxe5+',
    linea: '37…dxe5+ 38.dxe5+ Re6 39.Re4 c5 40.g3 b4',
    gana: true,
    valor: '+4,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2M12b de la base abierta de Lichess (CC0), rating 1365. Stockfish 16 a profundidad 18: dxe5+ es la mejor (+4,0) y la segunda queda en 0,0.',
  },
  {
    n: 24,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 24,
    id: 'ig_2SZAc',
    tema: 'detener',
    lichess: '2SZAc',
    rating: 1580,
    elo: 800,
    juegan: 'b',
    fen: 'r7/8/PK6/2R2ppp/3k4/7P/5PP1/8 b - - 4 51',
    ultima: 'Rb6',
    marca: ['b5', 'b6'],
    solucion: { from: 'a8', to: 'a6' },
    primera: 'Txa6+',
    linea: '51…Txa6+ 52.Rb5 Ta5+ 53.Rxa5 Rxc5',
    gana: true,
    valor: '+4,6',
    pista: 'El peón rival está muy avanzado. Lo primero es frenarlo.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2SZAc de la base abierta de Lichess (CC0), rating 1580. Stockfish 16 a profundidad 18: Txa6+ es la mejor (+4,6) y la segunda queda en -4,9.',
  },
  {
    n: 25,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 25,
    id: 'ig_0RHWa',
    tema: 'desviacion',
    lichess: '0RHWa',
    rating: 1472,
    elo: 692,
    juegan: 'b',
    fen: '5rk1/pb1Q3p/1p6/2ppN3/4nr1q/2P5/PP2B1PP/R4RK1 b - - 1 27',
    ultima: 'Dd7',
    marca: ['b5', 'd7'],
    solucion: { from: 'f4', to: 'f1' },
    primera: 'Txf1+',
    linea: '27…Txf1+ 28.Axf1 Df2+ 29.Rh1 Dxf1+ 30.Txf1 Txf1#',
    gana: true,
    valor: 'mate en 4',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 0RHWa de la base abierta de Lichess (CC0), rating 1472. Stockfish 16 a profundidad 18: Txf1+ es la mejor (mate en 4) y la segunda queda en -0,2.',
  },
  {
    n: 26,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 26,
    id: 'ig_2Eueb',
    tema: 'defensor',
    lichess: '2Eueb',
    rating: 1337,
    elo: 557,
    juegan: 'b',
    fen: '6k1/4nppp/B2qp3/2Np4/1P1Pn3/1Q2P3/5PPP/6K1 b - - 0 22',
    ultima: 'Axa6',
    marca: ['e2', 'a6'],
    solucion: { from: 'e4', to: 'c5' },
    primera: 'Cxc5',
    linea: '22…Cxc5 23.bxc5 Dxa6',
    gana: true,
    valor: '+3,2',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2Eueb de la base abierta de Lichess (CC0), rating 1337. Stockfish 16 a profundidad 18: Cxc5 es la mejor (+3,2) y la segunda queda en -2,1.',
  },
  {
    n: 27,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 27,
    id: 'ig_32oY9',
    tema: 'interferencia',
    lichess: '32oY9',
    rating: 1493,
    elo: 713,
    juegan: 'w',
    fen: 'r6r/p2q1kbp/3p2p1/1p6/3Q4/2N2PP1/PPP4P/4R1K1 w - - 4 25',
    ultima: 'Ag7',
    marca: ['f8', 'g7'],
    solucion: { from: 'd4', to: 'd5' },
    primera: 'Dd5+',
    linea: '25.Dd5+ Rf8 26.Dxa8+',
    gana: true,
    valor: '+5,1',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 32oY9 de la base abierta de Lichess (CC0), rating 1493. Stockfish 16 a profundidad 18: Dd5+ es la mejor (+5,1) y la segunda queda en -4,4.',
  },
  {
    n: 28,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 28,
    id: 'ig_16rjh',
    tema: 'clavada',
    lichess: '16rjh',
    rating: 1309,
    elo: 529,
    juegan: 'w',
    fen: 'r3kb1r/1p1qpp1p/p4np1/1N1P4/Q7/8/P4PPP/R1B1K2R w KQkq - 0 15',
    ultima: 'Dxd7',
    marca: ['d8', 'd7'],
    solucion: { from: 'b5', to: 'c7' },
    primera: 'Cc7+',
    linea: '15.Cc7+ Rd8 16.Dxd7+ Rxd7 17.Cxa8',
    gana: true,
    valor: '+4,6',
    pista: 'Una pieza rival no se puede mover sin dejar algo peor detrás.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 16rjh de la base abierta de Lichess (CC0), rating 1309. Stockfish 16 a profundidad 18: Cc7+ es la mejor (+4,6) y la segunda queda en -2,7.',
  },
  {
    n: 29,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 29,
    id: 'ig_1srCZ',
    tema: 'despeje',
    lichess: '1srCZ',
    rating: 1637,
    elo: 857,
    juegan: 'w',
    fen: '4r3/p4pk1/2p3p1/8/7Q/2P2q2/PP3P1R/5nK1 w - - 2 31',
    ultima: 'Rg7',
    marca: ['f6', 'g7'],
    solucion: { from: 'h4', to: 'd4' },
    primera: 'Dd4+',
    linea: '31.Dd4+ Df6 32.Th7+ Rxh7 33.Dxf6',
    gana: true,
    valor: '+4,6',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1srCZ de la base abierta de Lichess (CC0), rating 1637. Stockfish 16 a profundidad 18: Dd4+ es la mejor (+4,6) y la segunda queda en 0,0.',
  },
  {
    n: 30,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 30,
    id: 'ig_00coU',
    tema: 'rayosx',
    lichess: '00coU',
    rating: 1472,
    elo: 692,
    juegan: 'b',
    fen: '6k1/R3K3/8/1r6/5r2/p4N2/8/5R2 b - - 4 50',
    ultima: 'Re7',
    marca: ['f6', 'e7'],
    solucion: { from: 'f4', to: 'f7' },
    primera: 'Tf7+',
    linea: '50…Tf7+ 51.Rd6 Txa7',
    gana: true,
    valor: '+4,7',
    pista: 'Dos piezas rivales en la misma línea: ataca la de adelante.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 00coU de la base abierta de Lichess (CC0), rating 1472. Stockfish 16 a profundidad 18: Tf7+ es la mejor (+4,7) y la segunda queda en +0,2.',
  },
  {
    n: 31,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 31,
    id: 'ig_2msgm',
    tema: 'torres',
    lichess: '2msgm',
    rating: 1620,
    elo: 840,
    juegan: 'w',
    fen: '5k2/R5p1/p2P1p1p/1p6/8/4P1PP/5P1K/r7 w - - 1 40',
    ultima: 'Rf8',
    marca: ['g8', 'f8'],
    solucion: { from: 'a7', to: 'a8' },
    primera: 'Ta8+',
    linea: '40.Ta8+ Rf7 41.d7',
    gana: true,
    valor: '+4,7',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2msgm de la base abierta de Lichess (CC0), rating 1620. Stockfish 16 a profundidad 18: Ta8+ es la mejor (+4,7) y la segunda queda en +0,3.',
  },
  {
    n: 32,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 32,
    id: 'ig_14y0L',
    tema: 'alfiles',
    lichess: '14y0L',
    rating: 1486,
    elo: 706,
    juegan: 'b',
    fen: '8/p3b2p/1k4p1/1p1p4/P2P4/1P1K1PB1/5P1P/8 b - - 0 45',
    ultima: 'a4',
    marca: ['a3', 'a4'],
    solucion: { from: 'b5', to: 'a4' },
    primera: 'bxa4',
    linea: '45…bxa4 46.bxa4 Ra5 47.Ab8 a6 48.Rc3 Rxa4',
    gana: true,
    valor: '+3,9',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 14y0L de la base abierta de Lichess (CC0), rating 1486. Stockfish 16 a profundidad 18: bxa4 es la mejor (+3,9) y la segunda queda en +0,2.',
  },
  {
    n: 33,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 33,
    id: 'ig_1ABiI',
    tema: 'alfilcaballo',
    lichess: '1ABiI',
    rating: 1528,
    elo: 748,
    juegan: 'w',
    fen: '8/8/4pkp1/p1P1N3/P3K2b/8/8/8 w - - 0 47',
    ultima: 'Axh4',
    marca: ['e1', 'h4'],
    solucion: { from: 'c5', to: 'c6' },
    primera: 'c6',
    linea: '47.c6 Ag3 48.c7 Axe5 49.c8=D',
    gana: true,
    valor: '+5,5',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1ABiI de la base abierta de Lichess (CC0), rating 1528. Stockfish 16 a profundidad 18: c6 es la mejor (+5,5) y la segunda queda en 0,0.',
  },
  {
    n: 34,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 34,
    id: 'ig_0XUee',
    tema: 'damas',
    lichess: '0XUee',
    rating: 1549,
    elo: 769,
    juegan: 'b',
    fen: '8/8/6k1/3q1pp1/7P/5Q2/5PK1/8 b - - 4 50',
    ultima: 'Df3',
    marca: ['e3', 'f3'],
    solucion: { from: 'd5', to: 'f3' },
    primera: 'Dxf3+',
    linea: '50…Dxf3+ 51.Rxf3 gxh4',
    gana: true,
    valor: '+7,1',
    pista: 'Con damas, cada jaque cuenta: busca el que gana algo o corona.',
    explica: '',
    comprobado: 'Ejercicio 0XUee de la base abierta de Lichess (CC0), rating 1549. Stockfish 16 a profundidad 18: Dxf3+ es la mejor (+7,1) y la segunda queda en 0,0.',
  },
  {
    n: 35,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 35,
    id: 'ig_3FN1D',
    tema: 'zugzwang',
    lichess: '3FN1D',
    rating: 1392,
    elo: 612,
    juegan: 'w',
    fen: '8/8/p2k4/5p2/1PK2Pp1/6P1/8/8 w - - 7 63',
    ultima: 'Rd6',
    marca: ['c6', 'd6'],
    solucion: { from: 'c4', to: 'd4' },
    primera: 'Rd4',
    linea: '63.Rd4 Rc6 64.Re5',
    gana: true,
    valor: '+5,2',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 3FN1D de la base abierta de Lichess (CC0), rating 1392. Stockfish 16 a profundidad 18: Rd4 es la mejor (+5,2) y la segunda queda en 0,0.',
  },
  {
    n: 36,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_13M4a',
    tema: 'concentracion',
    lichess: '13M4a',
    rating: 1450,
    elo: 670,
    juegan: 'w',
    fen: '2rq1rk1/5p2/2n1p2Q/pp1p4/3Pn3/2P2NPP/PP4P1/R3R1K1 w - - 1 19',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'e1', to: 'e4' },
    primera: 'Txe4',
    linea: '19.Txe4 dxe4 20.Cg5 Dxg5 21.Dxg5+',
    gana: true,
    valor: '+5,9',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 13M4a de la base abierta de Lichess (CC0), rating 1450. Stockfish 16 a profundidad 18: Txe4 es la mejor (+5,9) y la segunda queda en -0,8.',
  },
  {
    n: 37,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_1v2LH',
    tema: 'h7',
    lichess: '1v2LH',
    rating: 1551,
    elo: 771,
    juegan: 'b',
    fen: 'r4rk1/1Qb1qpp1/p3p2p/8/1n6/1PN2N2/PB1P1PPP/2R1R1K1 b - - 0 20',
    ultima: 'Dxb7',
    marca: ['e4', 'b7'],
    solucion: { from: 'c7', to: 'h2' },
    primera: 'Axh2+',
    linea: '20…Axh2+ 21.Rxh2 Dxb7',
    gana: true,
    valor: '+4,4',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1v2LH de la base abierta de Lichess (CC0), rating 1551. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+4,4) y la segunda queda en -3,5.',
  },
  {
    n: 38,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_0uIwA',
    tema: 'demolicion',
    lichess: '0uIwA',
    rating: 1615,
    elo: 835,
    juegan: 'b',
    fen: '4rrk1/ppp3bp/3p2p1/2PPp3/1P3n1q/4BB1P/P2Q1PP1/3R1R1K b - - 0 19',
    ultima: 'c5',
    marca: ['c4', 'c5'],
    solucion: { from: 'f4', to: 'h3' },
    primera: 'Cxh3',
    linea: '19…Cxh3 20.g3 Cxf2+ 21.Rg2 Dh3+',
    gana: true,
    valor: '+5,6',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 0uIwA de la base abierta de Lichess (CC0), rating 1615. Stockfish 16 a profundidad 18: Cxh3 es la mejor (+5,6) y la segunda queda en +0,5.',
  },
  {
    n: 39,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2W0uC',
    tema: 'demolicion',
    lichess: '2W0uC',
    rating: 1693,
    elo: 913,
    juegan: 'w',
    fen: 'r7/p2qr3/1p1p2kp/2p2pp1/8/2QPR1P1/PPP2PP1/1K5R w - - 6 27',
    ultima: 'Rg6',
    marca: ['f7', 'g6'],
    solucion: { from: 'h1', to: 'h6' },
    primera: 'Txh6+',
    linea: '27.Txh6+ Rxh6 28.Df6+',
    gana: true,
    valor: '+6,2',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2W0uC de la base abierta de Lichess (CC0), rating 1693. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+6,2) y la segunda queda en -0,0.',
  },
  {
    n: 40,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2347F',
    tema: 'h7',
    lichess: '2347F',
    rating: 1907,
    elo: 1127,
    juegan: 'w',
    fen: 'r1bq1rk1/pp2Bppp/2n1p3/3p4/3P4/2NB4/PPP2nPP/R2QK2R w KQ - 0 11',
    ultima: 'Cxf2',
    marca: ['g4', 'f2'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '11.Axh7+ Rxh7 12.Dh5+ Rg8 13.Axd8',
    gana: true,
    valor: '+4,5',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2347F de la base abierta de Lichess (CC0), rating 1907. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+4,5) y la segunda queda en -1,4.',
  },
  {
    n: 41,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2kQXT',
    tema: 'concentracion',
    lichess: '2kQXT',
    rating: 1918,
    elo: 1138,
    juegan: 'w',
    fen: '2r3k1/3qprbp/p2p2p1/1p1n4/1P1B2P1/P2B1P2/2P4Q/2R1K2R w K - 0 22',
    ultima: 'Cxd5',
    marca: ['f6', 'd5'],
    solucion: { from: 'h2', to: 'h7' },
    primera: 'Dxh7+',
    linea: '22.Dxh7+ Rf8 23.Dh8+ Axh8 24.Txh8#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 2kQXT de la base abierta de Lichess (CC0), rating 1918. Stockfish 16 a profundidad 18: Dxh7+ es la mejor (mate en 3) y la segunda queda en -1,8.',
  },
  {
    n: 42,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2rUgy',
    tema: 'h7',
    lichess: '2rUgy',
    rating: 2188,
    elo: 1408,
    juegan: 'b',
    fen: 'r1bqk3/ppp2pp1/2nb4/8/2P3nP/2N5/PP2PPBP/R1BQ1RK1 b q - 0 11',
    ultima: 'gxh4',
    marca: ['g3', 'h4'],
    solucion: { from: 'd6', to: 'h2' },
    primera: 'Axh2+',
    linea: '11…Axh2+ 12.Rh1 Dxh4 13.Ag5 Dxg5',
    gana: true,
    valor: '+5,8',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2rUgy de la base abierta de Lichess (CC0), rating 2188. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+5,8) y la segunda queda en -0,3.',
  },
  {
    n: 43,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_1XH1f',
    tema: 'concentracion',
    lichess: '1XH1f',
    rating: 2294,
    elo: 1514,
    juegan: 'w',
    fen: '6k1/p4pp1/2p4p/3p1bn1/2pP4/2P2PqP/PPQ3P1/4R1K1 w - - 0 27',
    ultima: 'Axf5',
    marca: ['d7', 'f5'],
    solucion: { from: 'e1', to: 'e8' },
    primera: 'Te8+',
    linea: '27.Te8+ Rh7 28.Dxf5+ g6 29.Dg4',
    gana: true,
    valor: '+3,2',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 1XH1f de la base abierta de Lichess (CC0), rating 2294. Stockfish 16 a profundidad 18: Te8+ es la mejor (+3,2) y la segunda queda en -4,9.',
  },
  {
    n: 44,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_35eKV',
    tema: 'desarrollo',
    lichess: '35eKV',
    rating: 1299,
    elo: 519,
    juegan: 'b',
    fen: 'rnb1k2r/pp1p1ppp/2p2q2/8/2PbP3/2N5/PP2QPPP/R1B1KB1R b KQkq - 1 9',
    ultima: 'De2',
    marca: ['g4', 'e2'],
    solucion: { from: 'd4', to: 'c3' },
    primera: 'Axc3+',
    linea: '9…Axc3+ 10.bxc3 Dxc3+ 11.Dd2 Dxa1',
    gana: true,
    valor: '+3,9',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 35eKV de la base abierta de Lichess (CC0), rating 1299. Stockfish 16 a profundidad 18: Axc3+ es la mejor (+3,9) y la segunda queda en +0,1.',
  },
  {
    n: 45,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2RjqT',
    tema: 'f7',
    lichess: '2RjqT',
    rating: 1604,
    elo: 824,
    juegan: 'b',
    fen: '8/2pk3p/p1b2Br1/P1Rp4/8/4P1P1/r4R1P/4K3 b - - 2 46',
    ultima: 'Re1',
    marca: ['d2', 'e1'],
    solucion: { from: 'a2', to: 'f2' },
    primera: 'Txf2',
    linea: '46…Txf2 47.Rxf2 Txf6+',
    gana: true,
    valor: '+5,1',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2RjqT de la base abierta de Lichess (CC0), rating 1604. Stockfish 16 a profundidad 18: Txf2 es la mejor (+5,1) y la segunda queda en -0,1.',
  },
  {
    n: 46,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_29Jkd',
    tema: 'reycentro',
    lichess: '29Jkd',
    rating: 1606,
    elo: 826,
    juegan: 'w',
    fen: 'rn1qk2r/pp4pp/3bp3/2p1n3/5B2/8/PP3PPP/RN1QK1NR w KQkq - 0 12',
    ultima: 'fxe6',
    marca: ['f7', 'e6'],
    solucion: { from: 'f4', to: 'e5' },
    primera: 'Axe5',
    linea: '12.Axe5 Axe5 13.Dh5+ g6 14.Dxe5',
    gana: true,
    valor: '+4,1',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 29Jkd de la base abierta de Lichess (CC0), rating 1606. Stockfish 16 a profundidad 18: Axe5 es la mejor (+4,1) y la segunda queda en -0,8.',
  },
  {
    n: 47,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_3KZue',
    tema: 'desarrollo',
    lichess: '3KZue',
    rating: 1759,
    elo: 979,
    juegan: 'w',
    fen: 'r1bqr1k1/pppn1ppp/2np4/3P4/4P3/4bN2/PP1NBPPP/R2Q1RK1 w - - 0 12',
    ultima: 'Axe3',
    marca: ['b6', 'e3'],
    solucion: { from: 'd5', to: 'c6' },
    primera: 'dxc6',
    linea: '12.dxc6 Ab6 13.cxd7',
    gana: true,
    valor: '+3,6',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3KZue de la base abierta de Lichess (CC0), rating 1759. Stockfish 16 a profundidad 18: dxc6 es la mejor (+3,6) y la segunda queda en -0,0.',
  },
  {
    n: 48,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2F3P4',
    tema: 'f7',
    lichess: '2F3P4',
    rating: 1833,
    elo: 1053,
    juegan: 'w',
    fen: 'r1b1kbnr/2q2pp1/p1pp3p/4p1N1/2Q1P3/2N5/PPP2PPP/R1B1K2R w KQkq - 0 10',
    ultima: 'h6',
    marca: ['h7', 'h6'],
    solucion: { from: 'g5', to: 'f7' },
    primera: 'Cxf7',
    linea: '10.Cxf7 Dxf7 11.Dxc6+ Dd7 12.Dxa8',
    gana: true,
    valor: '+3,8',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2F3P4 de la base abierta de Lichess (CC0), rating 1833. Stockfish 16 a profundidad 18: Cxf7 es la mejor (+3,8) y la segunda queda en -1,1.',
  },
  {
    n: 49,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2BKlU',
    tema: 'reycentro',
    lichess: '2BKlU',
    rating: 1914,
    elo: 1134,
    juegan: 'w',
    fen: '2bq1k2/1r4b1/pr4P1/2p1nP2/2PpP3/P6Q/3B1P2/R2BK2R w KQ - 5 30',
    ultima: 'Rf8',
    marca: ['g8', 'f8'],
    solucion: { from: 'h3', to: 'h8' },
    primera: 'Dh8+',
    linea: '30.Dh8+ Axh8 31.Txh8+ Rg7 32.Txd8',
    gana: true,
    valor: '+3,1',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 2BKlU de la base abierta de Lichess (CC0), rating 1914. Stockfish 16 a profundidad 18: Dh8+ es la mejor (+3,1) y la segunda queda en +0,2.',
  },
  {
    n: 50,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_01UsT',
    tema: 'f7',
    lichess: '01UsT',
    rating: 2093,
    elo: 1313,
    juegan: 'b',
    fen: 'r3r1k1/pp2qp1p/3b2p1/3p4/3P2n1/1PN4P/PBP1BPP1/R2QK2R b KQ - 0 15',
    ultima: 'h3',
    marca: ['h2', 'h3'],
    solucion: { from: 'g4', to: 'f2' },
    primera: 'Cxf2',
    linea: '15…Cxf2 16.Rxf2 De3+ 17.Rf1 Ag3',
    gana: true,
    valor: '+3,0',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 01UsT de la base abierta de Lichess (CC0), rating 2093. Stockfish 16 a profundidad 18: Cxf2 es la mejor (+3,0) y la segunda queda en -3,4.',
  },
  {
    n: 51,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_0LmCW',
    tema: 'reycentro',
    lichess: '0LmCW',
    rating: 2164,
    elo: 1384,
    juegan: 'b',
    fen: '2kr1b1R/p5p1/1pp1Qqp1/3n4/5NP1/5P2/PPP5/2R1K3 b - - 1 22',
    ultima: 'De6+',
    marca: ['e4', 'e6'],
    solucion: { from: 'f6', to: 'e6' },
    primera: 'Dxe6+',
    linea: '22…Dxe6+ 23.Cxe6 Ab4+ 24.c3 Txh8',
    gana: true,
    valor: '+4,6',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 0LmCW de la base abierta de Lichess (CC0), rating 2164. Stockfish 16 a profundidad 18: Dxe6+ es la mejor (+4,6) y la segunda queda en -4,9.',
  },
  {
    n: 52,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_2L0cj',
    tema: 'caballo',
    lichess: '2L0cj',
    rating: 1331,
    elo: 551,
    juegan: 'w',
    fen: '5n1k/1p2q1p1/2p1B2r/p3PQNp/PbpP4/4P3/1P4PP/6K1 w - - 9 31',
    ultima: 'Cf8',
    marca: ['d7', 'f8'],
    solucion: { from: 'g5', to: 'f7' },
    primera: 'Cf7+',
    linea: '31.Cf7+ Rg8 32.Cxh6+ Rh8 33.Cf7+',
    gana: true,
    valor: '+5,0',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 2L0cj de la base abierta de Lichess (CC0), rating 1331. Stockfish 16 a profundidad 18: Cf7+ es la mejor (+5,0) y la segunda queda en -1,0.',
  },
  {
    n: 53,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_106yW',
    tema: 'alfil',
    lichess: '106yW',
    rating: 1399,
    elo: 619,
    juegan: 'w',
    fen: '1k1r3r/pp1n2pp/2pqBnb1/6B1/2QP4/8/PPP3PP/R4RK1 w - - 0 16',
    ultima: 'Dxd6',
    marca: ['e7', 'd6'],
    solucion: { from: 'g5', to: 'f4' },
    primera: 'Af4',
    linea: '16.Af4 Dxf4 17.Txf4',
    gana: true,
    valor: '+4,3',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 106yW de la base abierta de Lichess (CC0), rating 1399. Stockfish 16 a profundidad 18: Af4 es la mejor (+4,3) y la segunda queda en -3,0.',
  },
  {
    n: 54,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1LK8D',
    tema: 'septima',
    lichess: '1LK8D',
    rating: 1639,
    elo: 859,
    juegan: 'b',
    fen: 'r6r/pp3pk1/2b1pNp1/2q1n1Q1/5P2/1B6/PP4PP/3R1R1K b - - 4 25',
    ultima: 'Rh1',
    marca: ['g1', 'h1'],
    solucion: { from: 'h8', to: 'h2' },
    primera: 'Txh2+',
    linea: '25…Txh2+ 26.Rxh2 Th8+ 27.Ch5+ Txh5+ 28.Dxh5 gxh5',
    gana: true,
    valor: '+4,9',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1LK8D de la base abierta de Lichess (CC0), rating 1639. Stockfish 16 a profundidad 18: Txh2+ es la mejor (+4,9) y la segunda queda en -1,4.',
  },
  {
    n: 55,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_0B136',
    tema: 'alfil',
    lichess: '0B136',
    rating: 1737,
    elo: 957,
    juegan: 'w',
    fen: 'r3r1k1/pp1n1ppp/2pb4/3p1q2/3Pn3/P4B1P/1PPBNPP1/R2Q1RK1 w - - 4 15',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'f3', to: 'g4' },
    primera: 'Ag4',
    linea: '15.Ag4 Dg6 16.Axd7 Te7 17.Ag4',
    gana: true,
    valor: '+3,4',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 0B136 de la base abierta de Lichess (CC0), rating 1737. Stockfish 16 a profundidad 18: Ag4 es la mejor (+3,4) y la segunda queda en -0,3.',
  },
  {
    n: 56,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1ag85',
    tema: 'caballo',
    lichess: '1ag85',
    rating: 1924,
    elo: 1144,
    juegan: 'w',
    fen: 'r3kb1r/pppqp1pp/4Nn2/3n1p2/4p3/2N5/PPP2PPP/R1BQK2R w KQkq - 0 10',
    ultima: 'Cbxd5',
    marca: ['b4', 'd5'],
    solucion: { from: 'c3', to: 'd5' },
    primera: 'Cxd5',
    linea: '10.Cxd5 Cxd5 11.Dxd5 Dxd5 12.Cxc7+ Rf7 13.Cxd5',
    gana: true,
    valor: '+3,2',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1ag85 de la base abierta de Lichess (CC0), rating 1924. Stockfish 16 a profundidad 18: Cxd5 es la mejor (+3,2) y la segunda queda en -3,5.',
  },
  {
    n: 57,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_2w52V',
    tema: 'septima',
    lichess: '2w52V',
    rating: 2017,
    elo: 1237,
    juegan: 'w',
    fen: 'r6r/p1k3pp/3b1n2/N1p2p2/3n1B2/2NB4/PP3PPP/3KR3 w - - 4 18',
    ultima: 'Ad6',
    marca: ['f8', 'd6'],
    solucion: { from: 'e1', to: 'e7' },
    primera: 'Te7+',
    linea: '18.Te7+ Rd8 19.Axd6',
    gana: true,
    valor: '+5,4',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 2w52V de la base abierta de Lichess (CC0), rating 2017. Stockfish 16 a profundidad 18: Te7+ es la mejor (+5,4) y la segunda queda en -1,3.',
  },
  {
    n: 58,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1eP7U',
    tema: 'septima',
    lichess: '1eP7U',
    rating: 2083,
    elo: 1303,
    juegan: 'w',
    fen: '5rk1/pq3r1p/1pN3p1/2Pnp3/8/8/P3Q1PP/3R1RK1 w - - 0 28',
    ultima: 'Cxd5',
    marca: ['f6', 'd5'],
    solucion: { from: 'f1', to: 'f7' },
    primera: 'Txf7',
    linea: '28.Txf7 Dxf7 29.Txd5',
    gana: true,
    valor: '+3,8',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 1eP7U de la base abierta de Lichess (CC0), rating 2083. Stockfish 16 a profundidad 18: Txf7 es la mejor (+3,8) y la segunda queda en -0,3.',
  },
  {
    n: 59,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1WNxd',
    tema: 'caballo',
    lichess: '1WNxd',
    rating: 2532,
    elo: 1752,
    juegan: 'b',
    fen: '1kr5/5R2/p3p3/2qpP3/4n1P1/1Pp2Q1P/P1P1B3/3K4 b - - 2 36',
    ultima: 'Rd1',
    marca: ['c1', 'd1'],
    solucion: { from: 'e4', to: 'g5' },
    primera: 'Cg5',
    linea: '36…Cg5 37.Df2 Cxf7 38.Dxc5 Txc5',
    gana: true,
    valor: '+4,5',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1WNxd de la base abierta de Lichess (CC0), rating 2532. Stockfish 16 a profundidad 18: Cg5 es la mejor (+4,5) y la segunda queda en -0,9.',
  },
  {
    n: 60,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2S2mo',
    tema: 'pasado',
    lichess: '2S2mo',
    rating: 1532,
    elo: 752,
    juegan: 'b',
    fen: '8/1p2rk2/p4p2/7P/1P1R1K2/2P3p1/1P3P2/8 b - - 1 55',
    ultima: 'Rf4',
    marca: ['f5', 'f4'],
    solucion: { from: 'g3', to: 'f2' },
    primera: 'gxf2',
    linea: '55…gxf2 56.Td1 Te1',
    gana: true,
    valor: '+5,8',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2S2mo de la base abierta de Lichess (CC0), rating 1532. Stockfish 16 a profundidad 18: gxf2 es la mejor (+5,8) y la segunda queda en -0,7.',
  },
  {
    n: 61,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_1U30e',
    tema: 'ruptura',
    lichess: '1U30e',
    rating: 1588,
    elo: 808,
    juegan: 'b',
    fen: '1r3r2/p2b2kp/2p3p1/5p2/2PqpP2/1P6/P2NBQPP/R1R3K1 b - - 1 21',
    ultima: 'Df2',
    marca: ['g3', 'f2'],
    solucion: { from: 'e4', to: 'e3' },
    primera: 'e3',
    linea: '21…e3 22.Dg3 exd2+',
    gana: true,
    valor: '+4,7',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1U30e de la base abierta de Lichess (CC0), rating 1588. Stockfish 16 a profundidad 18: e3 es la mejor (+4,7) y la segunda queda en -4,3.',
  },
  {
    n: 62,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_3BzAn',
    tema: 'coronar',
    lichess: '3BzAn',
    rating: 1639,
    elo: 859,
    juegan: 'w',
    fen: '3K4/3P4/1k6/8/8/8/p3r3/2R5 w - - 15 71',
    ultima: 'Rb6',
    marca: ['b7', 'b6'],
    solucion: { from: 'd8', to: 'c8' },
    primera: 'Rc8',
    linea: '71.Rc8 Td2 72.d8=D+ Txd8+ 73.Rxd8 Rb5 74.Ta1 Rb4 75.Txa2',
    gana: true,
    valor: '+5,1',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 3BzAn de la base abierta de Lichess (CC0), rating 1639. Stockfish 16 a profundidad 18: Rc8 es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 63,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2ch3I',
    tema: 'coronar',
    lichess: '2ch3I',
    rating: 1687,
    elo: 907,
    juegan: 'w',
    fen: '6k1/1PK5/8/7R/6p1/8/1r5p/8 w - - 0 45',
    ultima: 'h2',
    marca: ['h3', 'h2'],
    solucion: { from: 'h5', to: 'h2' },
    primera: 'Txh2',
    linea: '45.Txh2 Txh2 46.b8=D+',
    gana: true,
    valor: '+3,0',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2ch3I de la base abierta de Lichess (CC0), rating 1687. Stockfish 16 a profundidad 18: Txh2 es la mejor (+3,0) y la segunda queda en -2,8.',
  },
  {
    n: 64,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2hGL0',
    tema: 'pasado',
    lichess: '2hGL0',
    rating: 1729,
    elo: 949,
    juegan: 'w',
    fen: '7k/5p1p/4pP1B/3PP2p/2p1p3/p1r5/P6P/6K1 w - - 0 38',
    ultima: 'Txc3',
    marca: ['c2', 'c3'],
    solucion: { from: 'd5', to: 'e6' },
    primera: 'dxe6',
    linea: '38.dxe6 fxe6 39.f7',
    gana: true,
    valor: '+4,7',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2hGL0 de la base abierta de Lichess (CC0), rating 1729. Stockfish 16 a profundidad 18: dxe6 es la mejor (+4,7) y la segunda queda en -5,0.',
  },
  {
    n: 65,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_24X3L',
    tema: 'ruptura',
    lichess: '24X3L',
    rating: 1768,
    elo: 988,
    juegan: 'b',
    fen: '5rk1/3qbrpp/p2p4/2p1Q1B1/8/2P2P1P/P1P3P1/R2R2K1 b - - 0 21',
    ultima: 'Dxe5',
    marca: ['e2', 'e5'],
    solucion: { from: 'd6', to: 'e5' },
    primera: 'dxe5',
    linea: '21…dxe5 22.Txd7 Axg5',
    gana: true,
    valor: '+4,5',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 24X3L de la base abierta de Lichess (CC0), rating 1768. Stockfish 16 a profundidad 18: dxe5 es la mejor (+4,5) y la segunda queda en -0,2.',
  },
  {
    n: 66,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2qLf9',
    tema: 'coronar',
    lichess: '2qLf9',
    rating: 2068,
    elo: 1288,
    juegan: 'b',
    fen: '6k1/5p1p/2RP2p1/4P3/8/1p3P1P/r4P2/6K1 b - - 0 28',
    ultima: 'd6',
    marca: ['d5', 'd6'],
    solucion: { from: 'b3', to: 'b2' },
    primera: 'b2',
    linea: '28…b2 29.d7 b1=D+ 30.Rg2 Td2 31.Tc8+ Rg7 32.d8=D Txd8',
    gana: true,
    valor: '+3,7',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2qLf9 de la base abierta de Lichess (CC0), rating 2068. Stockfish 16 a profundidad 18: b2 es la mejor (+3,7) y la segunda queda en 0,0.',
  },
  {
    n: 67,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2EgIj',
    tema: 'pasado',
    lichess: '2EgIj',
    rating: 2208,
    elo: 1428,
    juegan: 'w',
    fen: '8/p7/1p6/3PN3/2P2k1p/4n3/PP4p1/6K1 w - - 0 42',
    ultima: 'h4',
    marca: ['h5', 'h4'],
    solucion: { from: 'd5', to: 'd6' },
    primera: 'd6',
    linea: '42.d6 Rg3 43.d7 h3 44.Cf3 Rxf3 45.d8=D',
    gana: true,
    valor: '+4,2',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2EgIj de la base abierta de Lichess (CC0), rating 2208. Stockfish 16 a profundidad 18: d6 es la mejor (+4,2) y la segunda queda en 0,0.',
  },
  {
    n: 68,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_0XVJf',
    tema: 'interferencia',
    lichess: '0XVJf',
    rating: 1482,
    elo: 702,
    juegan: 'w',
    fen: 'r4k1r/ppp2ppp/2pb4/8/3q2b1/3B2P1/PPPP1P1P/R1B1RQK1 w - - 1 14',
    ultima: 'Dd4',
    marca: ['f4', 'd4'],
    solucion: { from: 'e1', to: 'e4' },
    primera: 'Te4',
    linea: '14.Te4 Df6 15.Txg4',
    gana: true,
    valor: '+3,5',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 0XVJf de la base abierta de Lichess (CC0), rating 1482. Stockfish 16 a profundidad 18: Te4 es la mejor (+3,5) y la segunda queda en +0,6.',
  },
  {
    n: 69,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2TEGK',
    tema: 'defensor',
    lichess: '2TEGK',
    rating: 1510,
    elo: 730,
    juegan: 'b',
    fen: '2r1b3/2r5/1n1k1p1p/pP1P1Pp1/P3B1P1/2NP3P/1K6/2R1R3 b - - 2 34',
    ultima: 'The1',
    marca: ['h1', 'e1'],
    solucion: { from: 'c7', to: 'c3' },
    primera: 'Txc3',
    linea: '34…Txc3 35.Txc3 Cxa4+ 36.Rb3 Cxc3',
    gana: true,
    valor: '+3,8',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2TEGK de la base abierta de Lichess (CC0), rating 1510. Stockfish 16 a profundidad 18: Txc3 es la mejor (+3,8) y la segunda queda en -2,6.',
  },
  {
    n: 70,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_3NYtV',
    tema: 'desviacion',
    lichess: '3NYtV',
    rating: 1619,
    elo: 839,
    juegan: 'b',
    fen: '1r4k1/6P1/5R2/p2P4/1bPP2p1/3B2q1/PPQ5/2K5 b - - 0 34',
    ultima: 'Txf6',
    marca: ['f1', 'f6'],
    solucion: { from: 'g3', to: 'e1' },
    primera: 'De1+',
    linea: '34…De1+ 35.Dd1 Ad2+ 36.Rc2 Txb2+ 37.Rxb2 Dxd1',
    gana: true,
    valor: '+6,1',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 3NYtV de la base abierta de Lichess (CC0), rating 1619. Stockfish 16 a profundidad 18: De1+ es la mejor (+6,1) y la segunda queda en -2,5.',
  },
  {
    n: 71,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_20CdR',
    tema: 'interferencia',
    lichess: '20CdR',
    rating: 1811,
    elo: 1031,
    juegan: 'w',
    fen: '7k/p1p3q1/1p1pQ3/3PbP2/P1P1B1r1/8/4R3/5K2 w - - 3 45',
    ultima: 'Rh8',
    marca: ['g8', 'h8'],
    solucion: { from: 'e6', to: 'e8' },
    primera: 'De8+',
    linea: '45.De8+ Dg8 46.Dh5+ Rg7 47.Dxg4+',
    gana: true,
    valor: '+5,3',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 20CdR de la base abierta de Lichess (CC0), rating 1811. Stockfish 16 a profundidad 18: De8+ es la mejor (+5,3) y la segunda queda en 0,0.',
  },
  {
    n: 72,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2LGyi',
    tema: 'defensor',
    lichess: '2LGyi',
    rating: 1928,
    elo: 1148,
    juegan: 'w',
    fen: 'r4rk1/pp2q3/2p2p1Q/4pb2/1bn1P1n1/2N3R1/PPP2PPP/5RK1 w - - 0 17',
    ultima: 'Axf5',
    marca: ['c8', 'f5'],
    solucion: { from: 'e4', to: 'f5' },
    primera: 'exf5',
    linea: '17.exf5 Dh7 18.Txg4+ Rh8 19.Dxh7+',
    gana: true,
    valor: '+3,2',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2LGyi de la base abierta de Lichess (CC0), rating 1928. Stockfish 16 a profundidad 18: exf5 es la mejor (+3,2) y la segunda queda en -3,9.',
  },
  {
    n: 73,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_0FQU8',
    tema: 'desviacion',
    lichess: '0FQU8',
    rating: 2041,
    elo: 1261,
    juegan: 'w',
    fen: '8/8/pp3k2/3p4/3PpK2/P7/1PP5/8 w - - 0 37',
    ultima: 'a6',
    marca: ['a7', 'a6'],
    solucion: { from: 'c2', to: 'c4' },
    primera: 'c4',
    linea: '37.c4 dxc4 38.Rxe4 Re6 39.d5+',
    gana: true,
    valor: '+3,8',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0FQU8 de la base abierta de Lichess (CC0), rating 2041. Stockfish 16 a profundidad 18: c4 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 74,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2ufXl',
    tema: 'desviacion',
    lichess: '2ufXl',
    rating: 2149,
    elo: 1369,
    juegan: 'b',
    fen: '5rk1/p5pp/4p3/2P1P3/2qp4/1Rn5/PQ1B2PP/4R1K1 b - - 2 28',
    ultima: 'Ad2',
    marca: ['f4', 'd2'],
    solucion: { from: 'c4', to: 'f1' },
    primera: 'Df1+',
    linea: '28…Df1+ 29.Txf1 Ce2+ 30.Rh1 Txf1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 2ufXl de la base abierta de Lichess (CC0), rating 2149. Stockfish 16 a profundidad 18: Df1+ es la mejor (mate en 3) y la segunda queda en -4,7.',
  },
  {
    n: 75,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2ngFz',
    tema: 'defensor',
    lichess: '2ngFz',
    rating: 2526,
    elo: 1746,
    juegan: 'w',
    fen: '5r2/pb2rp2/7R/6R1/2Bk1p2/P3p3/1PP4P/2K5 w - - 4 31',
    ultima: 'Rd4',
    marca: ['e5', 'd4'],
    solucion: { from: 'h6', to: 'd6' },
    primera: 'Td6+',
    linea: '31.Td6+ Re4 32.Ad3+ Rf3 33.Tf6 Te4 34.Tg3+ Rf2 35.Axe4 Axe4 36.Txf4+ Re2 37.Txe4',
    gana: true,
    valor: '+4,6',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2ngFz de la base abierta de Lichess (CC0), rating 2526. Stockfish 16 a profundidad 18: Td6+ es la mejor (+4,6) y la segunda queda en -4,2.',
  },
  {
    n: 76,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_2YJBp',
    tema: 'torres',
    lichess: '2YJBp',
    rating: 1252,
    elo: 472,
    juegan: 'b',
    fen: '6k1/6p1/1r5p/8/8/pR4P1/P2K3P/8 b - - 11 53',
    ultima: 'Rd2',
    marca: ['e2', 'd2'],
    solucion: { from: 'b6', to: 'b3' },
    primera: 'Txb3',
    linea: '53…Txb3 54.axb3 a2',
    gana: true,
    valor: '+5,7',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2YJBp de la base abierta de Lichess (CC0), rating 1252. Stockfish 16 a profundidad 18: Txb3 es la mejor (+5,7) y la segunda queda en 0,0.',
  },
  {
    n: 77,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_2Pubi',
    tema: 'alfilcaballo',
    lichess: '2Pubi',
    rating: 1277,
    elo: 497,
    juegan: 'w',
    fen: '8/5N2/5K2/6Pk/6bp/8/8/8 w - - 1 63',
    ultima: 'Ag4',
    marca: ['h3', 'g4'],
    solucion: { from: 'g5', to: 'g6' },
    primera: 'g6',
    linea: '63.g6 Ae6 64.g7 Axf7 65.Rxf7',
    gana: true,
    valor: '+7,3',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2Pubi de la base abierta de Lichess (CC0), rating 1277. Stockfish 16 a profundidad 18: g6 es la mejor (+7,3) y la segunda queda en 0,0.',
  },
  {
    n: 78,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_20YMB',
    tema: 'alfiles',
    lichess: '20YMB',
    rating: 1543,
    elo: 763,
    juegan: 'b',
    fen: '8/5k2/4p1p1/p3P1Pp/1p1P3P/1P3B1b/5K2/8 b - - 0 45',
    ultima: 'Axf3',
    marca: ['c6', 'f3'],
    solucion: { from: 'a5', to: 'a4' },
    primera: 'a4',
    linea: '45…a4 46.bxa4 b3 47.a5 b2',
    gana: true,
    valor: '+4,4',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 20YMB de la base abierta de Lichess (CC0), rating 1543. Stockfish 16 a profundidad 18: a4 es la mejor (+4,4) y la segunda queda en -0,1.',
  },
  {
    n: 79,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1RLkb',
    tema: 'alfiles',
    lichess: '1RLkb',
    rating: 1672,
    elo: 892,
    juegan: 'b',
    fen: '8/8/8/1P1K1p2/4Pk1p/3B1b2/7P/8 b - - 0 38',
    ultima: 'b5',
    marca: ['b4', 'b5'],
    solucion: { from: 'f5', to: 'e4' },
    primera: 'fxe4',
    linea: '38…fxe4 39.Af1 e3+ 40.Rc5 e2 41.Axe2 Axe2',
    gana: true,
    valor: '+4,7',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1RLkb de la base abierta de Lichess (CC0), rating 1672. Stockfish 16 a profundidad 18: fxe4 es la mejor (+4,7) y la segunda queda en 0,0.',
  },
  {
    n: 80,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1y3KM',
    tema: 'alfilcaballo',
    lichess: '1y3KM',
    rating: 1753,
    elo: 973,
    juegan: 'w',
    fen: '8/2n3pp/pB2kp2/P7/4PP2/2p3KP/5P2/8 w - - 1 33',
    ultima: 'Cc7',
    marca: ['d5', 'c7'],
    solucion: { from: 'b6', to: 'c7' },
    primera: 'Axc7',
    linea: '33.Axc7 c2 34.f5+ Re7 35.Af4',
    gana: true,
    valor: '+3,8',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 1y3KM de la base abierta de Lichess (CC0), rating 1753. Stockfish 16 a profundidad 18: Axc7 es la mejor (+3,8) y la segunda queda en -1,8.',
  },
  {
    n: 81,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_2THDK',
    tema: 'torres',
    lichess: '2THDK',
    rating: 1934,
    elo: 1154,
    juegan: 'w',
    fen: '8/8/6K1/5p1p/5PkP/2R3r1/8/8 w - - 0 55',
    ultima: 'Txg3',
    marca: ['g2', 'g3'],
    solucion: { from: 'c3', to: 'g3' },
    primera: 'Txg3+',
    linea: '55.Txg3+ Rxg3 56.Rg5 Rf3 57.Rxf5',
    gana: true,
    valor: '+8,2',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2THDK de la base abierta de Lichess (CC0), rating 1934. Stockfish 16 a profundidad 18: Txg3+ es la mejor (+8,2) y la segunda queda en -0,1.',
  },
  {
    n: 82,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_0ENcl',
    tema: 'alfiles',
    lichess: '0ENcl',
    rating: 2292,
    elo: 1512,
    juegan: 'b',
    fen: '8/7p/8/3k1bPP/8/2pBK3/8/8 b - - 2 53',
    ultima: 'Ad3',
    marca: ['e2', 'd3'],
    solucion: { from: 'c3', to: 'c2' },
    primera: 'c2',
    linea: '53…c2 54.Axc2 Axc2 55.g6 h6',
    gana: true,
    valor: '+4,4',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'Hay un rayo X: la pieza actúa a través de otra que está en medio.',
    comprobado: 'Ejercicio 0ENcl de la base abierta de Lichess (CC0), rating 2292. Stockfish 16 a profundidad 18: c2 es la mejor (+4,4) y la segunda queda en +0,0.',
  },
  {
    n: 83,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1zhwS',
    tema: 'torres',
    lichess: '1zhwS',
    rating: 2306,
    elo: 1526,
    juegan: 'w',
    fen: '8/1r2k3/5p1p/4pP2/p3K2P/1p4R1/8/8 w - - 0 52',
    ultima: 'b3',
    marca: ['b4', 'b3'],
    solucion: { from: 'g3', to: 'g7' },
    primera: 'Tg7+',
    linea: '52.Tg7+ Rd6 53.Txb7 Rc6 54.Tb8',
    gana: true,
    valor: '+4,7',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 1zhwS de la base abierta de Lichess (CC0), rating 2306. Stockfish 16 a profundidad 18: Tg7+ es la mejor (+4,7) y la segunda queda en -7,0.',
  },
  {
    n: 84,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2U4qv',
    tema: 'mayores',
    lichess: '2U4qv',
    rating: 1274,
    elo: 494,
    juegan: 'w',
    fen: '5rk1/p4rp1/1pp4p/3p4/3Pq3/2P3QP/PP3RP1/5RK1 w - - 0 27',
    ultima: 'Dxe4',
    marca: ['e6', 'e4'],
    solucion: { from: 'f2', to: 'f7' },
    primera: 'Txf7',
    linea: '27.Txf7 Txf7 28.Db8+ Rh7 29.Txf7',
    gana: true,
    valor: '+6,0',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2U4qv de la base abierta de Lichess (CC0), rating 1274. Stockfish 16 a profundidad 18: Txf7 es la mejor (+6,0) y la segunda queda en 0,0.',
  },
  {
    n: 85,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2XnWW',
    tema: 'f7',
    lichess: '2XnWW',
    rating: 1304,
    elo: 524,
    juegan: 'b',
    fen: '8/pp6/5p2/1P2p3/4Pk2/1R3P2/2r2N1p/3BK3 b - - 5 71',
    ultima: 'Ad1',
    marca: ['e2', 'd1'],
    solucion: { from: 'c2', to: 'f2' },
    primera: 'Txf2',
    linea: '71…Txf2 72.Rxf2 h1=D',
    gana: true,
    valor: '+3,0',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2XnWW de la base abierta de Lichess (CC0), rating 1304. Stockfish 16 a profundidad 18: Txf2 es la mejor (+3,0) y la segunda queda en -1,1.',
  },
  {
    n: 86,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_0YQva',
    tema: 'h7',
    lichess: '0YQva',
    rating: 1319,
    elo: 539,
    juegan: 'w',
    fen: '1r3rk1/1p3ppp/p3pn2/8/2P5/2qB1R2/5QPP/R5K1 w - - 0 19',
    ultima: 'Dxc3',
    marca: ['d4', 'c3'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '19.Axh7+ Cxh7 20.Txc3',
    gana: true,
    valor: '+5,1',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 0YQva de la base abierta de Lichess (CC0), rating 1319. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+5,1) y la segunda queda en -3,6.',
  },
  {
    n: 87,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2vIkr',
    tema: 'patrones',
    lichess: '2vIkr',
    rating: 1327,
    elo: 547,
    juegan: 'b',
    fen: '6k1/1pp3rp/p2p1r2/3PpP2/5np1/2P1QB2/PP3P1K/R5R1 b - - 0 30',
    ultima: 'Rxh2',
    marca: ['h1', 'h2'],
    solucion: { from: 'f6', to: 'h6' },
    primera: 'Th6+',
    linea: '30…Th6+ 31.Rg3 Th3#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es mate en dos: la primera jugada no deja defensa.',
    comprobado: 'Ejercicio 2vIkr de la base abierta de Lichess (CC0), rating 1327. Stockfish 16 a profundidad 18: Th6+ es la mejor (mate en 2) y la segunda queda en -3,4.',
  },
  {
    n: 88,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_0WOvq',
    tema: 'reycentro',
    lichess: '0WOvq',
    rating: 1347,
    elo: 567,
    juegan: 'w',
    fen: '3rk3/p1p1nr2/1p3p2/4p2Q/1P6/PqPR4/5PPP/4R1K1 w - - 4 31',
    ultima: 'Td8',
    marca: ['b8', 'd8'],
    solucion: { from: 'h5', to: 'h8' },
    primera: 'Dh8+',
    linea: '31.Dh8+ Tf8 32.Txd8+ Rxd8 33.Dxf8+',
    gana: true,
    valor: '+5,7',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 0WOvq de la base abierta de Lichess (CC0), rating 1347. Stockfish 16 a profundidad 18: Dh8+ es la mejor (+5,7) y la segunda queda en -2,6.',
  },
  {
    n: 89,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2Llf8',
    tema: 'concentracion',
    lichess: '2Llf8',
    rating: 1558,
    elo: 778,
    juegan: 'b',
    fen: '1r2r2k/1p4p1/3b1q2/2pB4/PpQ5/1P3N2/4RPPP/R5K1 b - - 0 28',
    ultima: 'Txe2',
    marca: ['e1', 'e2'],
    solucion: { from: 'f6', to: 'a1' },
    primera: 'Dxa1+',
    linea: '28…Dxa1+ 29.Ce1 Dxe1+ 30.Txe1 Txe1+',
    gana: true,
    valor: '+5,9',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un rayo X: la pieza actúa a través de otra que está en medio.',
    comprobado: 'Ejercicio 2Llf8 de la base abierta de Lichess (CC0), rating 1558. Stockfish 16 a profundidad 18: Dxa1+ es la mejor (+5,9) y la segunda queda en -0,7.',
  },
  {
    n: 90,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1JwhQ',
    tema: 'demolicion',
    lichess: '1JwhQ',
    rating: 1572,
    elo: 792,
    juegan: 'b',
    fen: '2k3rr/pp3p1p/5p2/PB1pq3/1P3P2/2P4b/3Q2PP/R4RK1 b - f3 0 22',
    ultima: 'f4',
    marca: ['f2', 'f4'],
    solucion: { from: 'g8', to: 'g2' },
    primera: 'Txg2+',
    linea: '22…Txg2+ 23.Dxg2 De3+ 24.Tf2 Axg2',
    gana: true,
    valor: '+5,8',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1JwhQ de la base abierta de Lichess (CC0), rating 1572. Stockfish 16 a profundidad 18: Txg2+ es la mejor (+5,8) y la segunda queda en -2,1.',
  },
  {
    n: 91,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_29Ejv',
    tema: 'octava',
    lichess: '29Ejv',
    rating: 1600,
    elo: 820,
    juegan: 'w',
    fen: '5rk1/p2R1ppp/Bp6/4p3/4P3/1Q2KP1q/P5r1/8 w - - 0 32',
    ultima: 'e5',
    marca: ['e6', 'e5'],
    solucion: { from: 'b3', to: 'f7' },
    primera: 'Dxf7+',
    linea: '32.Dxf7+ Txf7 33.Td8+ Tf8 34.Ac4+ De6 35.Axe6+ Rh8 36.Txf8#',
    gana: true,
    valor: 'mate en 5',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 29Ejv de la base abierta de Lichess (CC0), rating 1600. Stockfish 16 a profundidad 18: Dxf7+ es la mejor (mate en 5) y la segunda queda en -7,4.',
  },
  {
    n: 92,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2ipr0',
    tema: 'demolicion',
    lichess: '2ipr0',
    rating: 1664,
    elo: 884,
    juegan: 'b',
    fen: '4r1k1/p4p1p/1p4p1/2pP4/2PN1q2/1P2r2P/P2Q1pP1/2R2R1K b - - 0 30',
    ultima: 'Cxd4',
    marca: ['b5', 'd4'],
    solucion: { from: 'e3', to: 'h3' },
    primera: 'Txh3+',
    linea: '30…Txh3+ 31.gxh3 Dxd2',
    gana: true,
    valor: '+5,4',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2ipr0 de la base abierta de Lichess (CC0), rating 1664. Stockfish 16 a profundidad 18: Txh3+ es la mejor (+5,4) y la segunda queda en +0,1.',
  },
  {
    n: 93,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_3GTJE',
    tema: 'mayores',
    lichess: '3GTJE',
    rating: 1680,
    elo: 900,
    juegan: 'b',
    fen: '3r4/4kp2/p1p1p2p/4Pp2/5r1q/2N4Q/PPP3P1/R3R1K1 b - - 1 25',
    ultima: 'Dh3',
    marca: ['f3', 'h3'],
    solucion: { from: 'h4', to: 'f2' },
    primera: 'Df2+',
    linea: '25…Df2+ 26.Rh1 Th4 27.Dxh4+ Dxh4+',
    gana: true,
    valor: '+5,4',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 3GTJE de la base abierta de Lichess (CC0), rating 1680. Stockfish 16 a profundidad 18: Df2+ es la mejor (+5,4) y la segunda queda en -0,9.',
  },
  {
    n: 94,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_372v3',
    tema: 'h7',
    lichess: '372v3',
    rating: 1685,
    elo: 905,
    juegan: 'b',
    fen: 'r1bq1rk1/pp3ppp/3b1n2/8/2BQp3/4P3/PP3PPP/RNBR2K1 b - - 2 12',
    ultima: 'Td1',
    marca: ['f1', 'd1'],
    solucion: { from: 'd6', to: 'h2' },
    primera: 'Axh2+',
    linea: '12…Axh2+ 13.Rxh2 Cg4+ 14.Rg1 Dh4',
    gana: true,
    valor: '+3,7',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 372v3 de la base abierta de Lichess (CC0), rating 1685. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+3,7) y la segunda queda en +0,4.',
  },
  {
    n: 95,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1VToK',
    tema: 'concentracion',
    lichess: '1VToK',
    rating: 1699,
    elo: 919,
    juegan: 'w',
    fen: '2r2rk1/ppqnbp1p/4p1p1/2pp2P1/1P2nP2/P2BPR1Q/1BPP3P/R5K1 w - - 1 18',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'h3', to: 'h7' },
    primera: 'Dxh7+',
    linea: '18.Dxh7+ Rxh7 19.Th3+ Rg8 20.Th8#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1VToK de la base abierta de Lichess (CC0), rating 1699. Stockfish 16 a profundidad 18: Dxh7+ es la mejor (mate en 3) y la segunda queda en +0,0.',
  },
  {
    n: 96,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2ciHU',
    tema: 'patrones',
    lichess: '2ciHU',
    rating: 1699,
    elo: 919,
    juegan: 'w',
    fen: 'r2q1bnr/ppp1k1pp/8/4p3/8/1B3b2/PPPP2PP/RNB1Q1K1 w - - 0 12',
    ultima: 'Axf3',
    marca: ['g4', 'f3'],
    solucion: { from: 'e1', to: 'e5' },
    primera: 'Dxe5+',
    linea: '12.Dxe5+ Rd7 13.De6#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es mate en dos: la primera jugada no deja defensa.',
    comprobado: 'Ejercicio 2ciHU de la base abierta de Lichess (CC0), rating 1699. Stockfish 16 a profundidad 18: Dxe5+ es la mejor (mate en 2) y la segunda queda en -0,9.',
  },
  {
    n: 97,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1tIu5',
    tema: 'reycentro',
    lichess: '1tIu5',
    rating: 1798,
    elo: 1018,
    juegan: 'w',
    fen: '4rk2/p1p3b1/3p2Qp/5q2/P2PNpb1/2P5/3B2PP/4R1K1 w - - 1 27',
    ultima: 'Df5',
    marca: ['d7', 'f5'],
    solucion: { from: 'g6', to: 'e8' },
    primera: 'Dxe8+',
    linea: '27.Dxe8+ Rxe8 28.Cxd6+ Rd7 29.Cxf5',
    gana: true,
    valor: '+5,5',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 1tIu5 de la base abierta de Lichess (CC0), rating 1798. Stockfish 16 a profundidad 18: Dxe8+ es la mejor (+5,5) y la segunda queda en -0,5.',
  },
  {
    n: 98,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2QOON',
    tema: 'octava',
    lichess: '2QOON',
    rating: 1839,
    elo: 1059,
    juegan: 'w',
    fen: '5rk1/ppR2ppp/7r/BP6/3Pp1n1/P3PbPq/Q4P2/4RBK1 w - - 0 26',
    ultima: 'Dxh3',
    marca: ['h5', 'h3'],
    solucion: { from: 'a2', to: 'f7' },
    primera: 'Dxf7+',
    linea: '26.Dxf7+ Txf7 27.Tc8+ Tf8 28.Ac4+ Te6 29.Axe6+ Rh8 30.Txf8#',
    gana: true,
    valor: 'mate en 5',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 2QOON de la base abierta de Lichess (CC0), rating 1839. Stockfish 16 a profundidad 18: Dxf7+ es la mejor (mate en 5) y la segunda queda en recibe mate en 6.',
  },
  {
    n: 99,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2frXU',
    tema: 'f7',
    lichess: '2frXU',
    rating: 2007,
    elo: 1227,
    juegan: 'w',
    fen: 'r3kb1r/pp3p1p/2n1Bnp1/3Q4/2pP1B2/2PqP3/P4PPP/5RK1 w kq - 1 18',
    ultima: 'Cf6',
    marca: ['e4', 'f6'],
    solucion: { from: 'e6', to: 'f7' },
    primera: 'Axf7+',
    linea: '18.Axf7+ Re7 19.De6+ Rd8 20.Dxf6+',
    gana: true,
    valor: '+7,4',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2frXU de la base abierta de Lichess (CC0), rating 2007. Stockfish 16 a profundidad 18: Axf7+ es la mejor (+7,4) y la segunda queda en -5,7.',
  },
  {
    n: 100,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2mbuQ',
    tema: 'octava',
    lichess: '2mbuQ',
    rating: 2051,
    elo: 1271,
    juegan: 'b',
    fen: '2r2rk1/pb1n1q2/1p2p2Q/3p2N1/3P4/4P3/PP3PPP/2R2RK1 b - - 4 20',
    ultima: 'Cg5',
    marca: ['f3', 'g5'],
    solucion: { from: 'f7', to: 'f2' },
    primera: 'Dxf2+',
    linea: '20…Dxf2+ 21.Rh1 Dxf1+ 22.Txf1 Txf1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 2mbuQ de la base abierta de Lichess (CC0), rating 2051. Stockfish 16 a profundidad 18: Dxf2+ es la mejor (mate en 3) y la segunda queda en -2,0.',
  },
  {
    n: 101,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2wKNb',
    tema: 'demolicion',
    lichess: '2wKNb',
    rating: 2059,
    elo: 1279,
    juegan: 'w',
    fen: '5r1k/2p1qpp1/1p1p1b1p/p6R/2P1B1Q1/1P2P1P1/P4PP1/6K1 w - - 7 40',
    ultima: 'Tf8',
    marca: ['d8', 'f8'],
    solucion: { from: 'h5', to: 'h6' },
    primera: 'Txh6+',
    linea: '40.Txh6+ gxh6 41.Df5 Dxe4 42.Dxe4',
    gana: true,
    valor: '+4,5',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 2wKNb de la base abierta de Lichess (CC0), rating 2059. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+4,5) y la segunda queda en +0,1.',
  },
  {
    n: 102,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_0uwtt',
    tema: 'f7',
    lichess: '0uwtt',
    rating: 2066,
    elo: 1286,
    juegan: 'w',
    fen: '3rkb1r/ppq2ppb/2n1p2p/2ppP2B/5PQn/2PP4/PP1N2PP/R1B2R1K w k - 0 16',
    ultima: 'Cxh4',
    marca: ['f5', 'h4'],
    solucion: { from: 'g4', to: 'e6' },
    primera: 'Dxe6+',
    linea: '16.Dxe6+ Ae7 17.Dxf7+ Rd7 18.Ag4+ Af5 19.Axf5+',
    gana: true,
    valor: '+5,1',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 0uwtt de la base abierta de Lichess (CC0), rating 2066. Stockfish 16 a profundidad 18: Dxe6+ es la mejor (+5,1) y la segunda queda en -1,7.',
  },
  {
    n: 103,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_25yIx',
    tema: 'h7',
    lichess: '25yIx',
    rating: 2068,
    elo: 1288,
    juegan: 'w',
    fen: 'r2q1rk1/1bp1Bppp/p3p3/1p2P3/8/2nBP3/PP3PPP/R2Q1RK1 w - - 0 14',
    ultima: 'Cxc3',
    marca: ['d5', 'c3'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '14.Axh7+ Rxh7 15.Dh5+',
    gana: true,
    valor: '+5,2',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 25yIx de la base abierta de Lichess (CC0), rating 2068. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+5,2) y la segunda queda en +0,1.',
  },
  {
    n: 104,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_303H6',
    tema: 'patrones',
    lichess: '303H6',
    rating: 2088,
    elo: 1308,
    juegan: 'w',
    fen: '8/2P2p2/q3bkp1/2Q4p/4B2P/6P1/7K/8 w - - 1 54',
    ultima: 'Da6',
    marca: ['c8', 'a6'],
    solucion: { from: 'c5', to: 'd4' },
    primera: 'Dd4+',
    linea: '54.Dd4+ Re7 55.Dd8#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es mate en dos: la primera jugada no deja defensa.',
    comprobado: 'Ejercicio 303H6 de la base abierta de Lichess (CC0), rating 2088. Stockfish 16 a profundidad 18: Dd4+ es la mejor (mate en 2) y la segunda queda en +0,5.',
  },
  {
    n: 105,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1vmbL',
    tema: 'mayores',
    lichess: '1vmbL',
    rating: 2107,
    elo: 1327,
    juegan: 'b',
    fen: '5rk1/2p3p1/p2b2p1/1p1p2rp/1P1P3q/P3PN1P/1BR1QPP1/5RK1 b - - 4 28',
    ultima: 'Cf3',
    marca: ['h2', 'f3'],
    solucion: { from: 'h4', to: 'h3' },
    primera: 'Dxh3',
    linea: '28…Dxh3 29.g3 Axg3 30.fxg3 Txg3+',
    gana: true,
    valor: '+5,6',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 1vmbL de la base abierta de Lichess (CC0), rating 2107. Stockfish 16 a profundidad 18: Dxh3 es la mejor (+5,6) y la segunda queda en -1,5.',
  },
  {
    n: 106,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_0rtaZ',
    tema: 'reycentro',
    lichess: '0rtaZ',
    rating: 2134,
    elo: 1354,
    juegan: 'b',
    fen: 'r4b1r/1p4pp/p1p3k1/4p3/2QnP3/3P2P1/PPP5/R1B1K3 b Q - 0 18',
    ultima: 'd3',
    marca: ['d2', 'd3'],
    solucion: { from: 'b7', to: 'b5' },
    primera: 'b5',
    linea: '18…b5 19.Dc3 Ab4 20.Dxb4 Cxc2+ 21.Rd2 Cxb4',
    gana: true,
    valor: '+5,6',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0rtaZ de la base abierta de Lichess (CC0), rating 2134. Stockfish 16 a profundidad 18: b5 es la mejor (+5,6) y la segunda queda en -1,4.',
  },
  {
    n: 107,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2i7ZP',
    tema: 'concentracion',
    lichess: '2i7ZP',
    rating: 2386,
    elo: 1606,
    juegan: 'w',
    fen: 'r1bq1rk1/pp4pp/2pb2n1/4N3/3Pn3/1P6/PBQ1N1PP/2R2RK1 w - - 0 19',
    ultima: 'Cxe4',
    marca: ['g5', 'e4'],
    solucion: { from: 'c2', to: 'c4' },
    primera: 'Dc4+',
    linea: '19.Dc4+ Rh8 20.Txf8+ Dxf8 21.Cf7+',
    gana: true,
    valor: '+4,3',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2i7ZP de la base abierta de Lichess (CC0), rating 2386. Stockfish 16 a profundidad 18: Dc4+ es la mejor (+4,3) y la segunda queda en -0,2.',
  },
];
