/* ===== Las posiciones de «Ideas que ganan partidas», de Oscar Angulo Cubero =====
 *
 * GENERADO por herramientas/ideas-que-ganan-partidas-generar.js — no se edita a mano.
 *
 * 107 posiciones de la base abierta de Lichess (CC0), comprobadas con
 * Stockfish: 35 ejemplos (uno por lección, los mismos del curso),
 * 48 ejercicios por capítulo y 24 mixtos. Lo usa el libro
 * (herramientas/ideas-que-ganan-partidas-pdf.js). Vive detrás del candado de
 * material/: trae las respuestas.
 */
window.IDEAS_QUE_GANAN = {
  TITULO: 'Ideas que ganan partidas',
  AUTOR: 'Oscar Angulo Cubero',
  POR_CAPITULO: 8,
  MIXTOS: 24,
  CAPITULOS: [{ n: 1, titulo: 'El ataque al rey enrocado', ideas: ['concentracion', 'h7', 'demolicion', 'mayores', 'octava', 'patrones'] }, { n: 2, titulo: 'El rey en el centro y los enroques opuestos', ideas: ['reycentro', 'f7', 'desarrollo', 'extraccion', 'opuestos', 'defensa'] }, { n: 3, titulo: 'Las piezas en su sitio', ideas: ['septima', 'caballo', 'alfil', 'dama', 'atrapada', 'calidad'] }, { n: 4, titulo: 'Los peones deciden', ideas: ['pasado', 'coronar', 'ruptura', 'peonsac', 'peones', 'detener'] }, { n: 5, titulo: 'La táctica que sostiene el plan', ideas: ['desviacion', 'defensor', 'interferencia', 'clavada', 'despeje', 'rayosx'] }, { n: 6, titulo: 'Los finales que hay que saber', ideas: ['torres', 'alfiles', 'alfilcaballo', 'damas', 'zugzwang'] }],
};
window.IDEAS_QUE_GANAN_ITEMS = [
  {
    n: 1,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 1,
    id: 'ig_18gps',
    tema: 'concentracion',
    lichess: '18gps',
    rating: 1571,
    elo: 791,
    juegan: 'b',
    fen: '5rk1/p1p3pp/2N1pq2/2Q5/4p3/4P3/P1Rr1PPP/5RK1 b - - 7 22',
    ultima: 'Tc2',
    marca: ['c1', 'c2'],
    solucion: { from: 'f6', to: 'f2' },
    primera: 'Dxf2+',
    linea: '22…Dxf2+ 23.Txf2 Td1+ 24.Tf1 Tdxf1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 18gps de la base abierta de Lichess (CC0), rating 1571. Stockfish 16 a profundidad 18: Dxf2+ es la mejor (mate en 3) y la segunda queda en -5,0.',
  },
  {
    n: 2,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 2,
    id: 'ig_1tJp9',
    tema: 'h7',
    lichess: '1tJp9',
    rating: 1585,
    elo: 805,
    juegan: 'w',
    fen: 'r1bq1rk1/pp2nppp/1bn1p3/3pP3/3P4/2PB1N2/P4PPP/RNBQK2R w KQ - 1 9',
    ultima: 'Cbc6',
    marca: ['b8', 'c6'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '9.Axh7+ Rxh7 10.Cg5+',
    gana: true,
    valor: '+5,1',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1tJp9 de la base abierta de Lichess (CC0), rating 1585. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+5,1) y la segunda queda en +0,6.',
  },
  {
    n: 3,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 3,
    id: 'ig_0yjuV',
    tema: 'demolicion',
    lichess: '0yjuV',
    rating: 1355,
    elo: 575,
    juegan: 'w',
    fen: '1b5k/1p3qp1/p1npR2p/P1pQp3/2P5/8/5PPP/6K1 w - - 7 39',
    ultima: 'Df7',
    marca: ['e7', 'f7'],
    solucion: { from: 'e6', to: 'h6' },
    primera: 'Txh6+',
    linea: '39.Txh6+ Rg8 40.Th8+ Rxh8 41.Dxf7',
    gana: true,
    valor: '+5,5',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0yjuV de la base abierta de Lichess (CC0), rating 1355. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+5,5) y la segunda queda en -3,0.',
  },
  {
    n: 4,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 4,
    id: 'ig_0eUUp',
    tema: 'mayores',
    lichess: '0eUUp',
    rating: 1312,
    elo: 532,
    juegan: 'w',
    fen: 'r2b2k1/ppp2rpp/3pR3/3P4/2P2B2/8/PP4PP/5RK1 w - - 2 21',
    ultima: 'Tf7',
    marca: ['f5', 'f7'],
    solucion: { from: 'e6', to: 'e8' },
    primera: 'Te8+',
    linea: '21.Te8+ Tf8 22.Txf8+ Rxf8 23.Axd6+',
    gana: true,
    valor: '+4,0',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 0eUUp de la base abierta de Lichess (CC0), rating 1312. Stockfish 16 a profundidad 18: Te8+ es la mejor (+4,0) y la segunda queda en +0,2.',
  },
  {
    n: 5,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 5,
    id: 'ig_12rIE',
    tema: 'octava',
    lichess: '12rIE',
    rating: 1388,
    elo: 608,
    juegan: 'b',
    fen: '4rk2/pQ6/7R/4q1p1/2p5/2Pb4/PP4PP/R5K1 b - - 0 31',
    ultima: 'Dxb7',
    marca: ['d5', 'b7'],
    solucion: { from: 'e5', to: 'e3' },
    primera: 'De3+',
    linea: '31…De3+ 32.Rh1 De1+ 33.Txe1 Txe1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 12rIE de la base abierta de Lichess (CC0), rating 1388. Stockfish 16 a profundidad 18: De3+ es la mejor (mate en 3) y la segunda queda en -4,0.',
  },
  {
    n: 6,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 6,
    id: 'ig_35JUo',
    tema: 'patrones',
    lichess: '35JUo',
    rating: 1484,
    elo: 704,
    juegan: 'b',
    fen: '1k4r1/1pp5/8/p1qQp3/2Pn4/P7/5RP1/5RK1 b - - 2 38',
    ultima: 'Dd5',
    marca: ['f3', 'd5'],
    solucion: { from: 'd4', to: 'e2' },
    primera: 'Ce2+',
    linea: '38…Ce2+ 39.Rh2 Th8#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 35JUo de la base abierta de Lichess (CC0), rating 1484. Stockfish 16 a profundidad 18: Ce2+ es la mejor (mate en 2) y la segunda queda en -1,2.',
  },
  {
    n: 7,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 7,
    id: 'ig_1KdZW',
    tema: 'reycentro',
    lichess: '1KdZW',
    rating: 1623,
    elo: 843,
    juegan: 'w',
    fen: 'r3k2r/1pR1nn2/p2p1Q2/3Pp1q1/4P3/1P6/P4PPP/5RK1 w kq - 1 20',
    ultima: 'Dg5',
    marca: ['d2', 'g5'],
    solucion: { from: 'c7', to: 'e7' },
    primera: 'Txe7+',
    linea: '20.Txe7+ Rd8 21.Txf7+ Dxf6 22.Txf6',
    gana: true,
    valor: '+5,3',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1KdZW de la base abierta de Lichess (CC0), rating 1623. Stockfish 16 a profundidad 18: Txe7+ es la mejor (+5,3) y la segunda queda en -3,8.',
  },
  {
    n: 8,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 8,
    id: 'ig_1yuqX',
    tema: 'f7',
    lichess: '1yuqX',
    rating: 1479,
    elo: 699,
    juegan: 'b',
    fen: 'r1bqk2r/ppp1Pppp/2n5/2b5/5B2/2P5/PP2PPPP/RN1QKBNR b KQkq - 0 6',
    ultima: 'dxe7',
    marca: ['d6', 'e7'],
    solucion: { from: 'c5', to: 'f2' },
    primera: 'Axf2+',
    linea: '6…Axf2+ 7.Rxf2 Dxd1',
    gana: true,
    valor: '+4,3',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1yuqX de la base abierta de Lichess (CC0), rating 1479. Stockfish 16 a profundidad 18: Axf2+ es la mejor (+4,3) y la segunda queda en -4,1.',
  },
  {
    n: 9,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 9,
    id: 'ig_1ghMX',
    tema: 'desarrollo',
    lichess: '1ghMX',
    rating: 1373,
    elo: 593,
    juegan: 'w',
    fen: 'rnbqkb1r/ppp2ppp/4pn2/4N3/8/3Q4/PPP2PPP/RNB1KB1R w KQkq - 1 6',
    ultima: 'Cf6',
    marca: ['g8', 'f6'],
    solucion: { from: 'd3', to: 'd8' },
    primera: 'Dxd8+',
    linea: '6.Dxd8+ Rxd8 7.Cxf7+ Re8 8.Cxh8',
    gana: true,
    valor: '+3,7',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1ghMX de la base abierta de Lichess (CC0), rating 1373. Stockfish 16 a profundidad 18: Dxd8+ es la mejor (+3,7) y la segunda queda en -0,8.',
  },
  {
    n: 10,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 10,
    id: 'ig_2fvjC',
    tema: 'extraccion',
    lichess: '2fvjC',
    rating: 1332,
    elo: 552,
    juegan: 'b',
    fen: 'R3n1k1/5pp1/7p/1b6/1B6/P5PP/5rB1/6K1 b - - 1 33',
    ultima: 'Rg1',
    marca: ['h2', 'g1'],
    solucion: { from: 'f2', to: 'g2' },
    primera: 'Txg2+',
    linea: '33…Txg2+ 34.Rxg2 Ac6+ 35.Rf2 Axa8',
    gana: true,
    valor: '+4,3',
    pista: 'Un jaque con sacrificio puede sacar al rey de su casa. Afuera está solo.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2fvjC de la base abierta de Lichess (CC0), rating 1332. Stockfish 16 a profundidad 18: Txg2+ es la mejor (+4,3) y la segunda queda en -0,7.',
  },
  {
    n: 11,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 11,
    id: 'ig_2jpNp',
    tema: 'opuestos',
    lichess: '2jpNp',
    rating: 1615,
    elo: 835,
    juegan: 'b',
    fen: '3r2k1/pppb1p1p/6p1/q4P2/2P1P3/1KQ5/P2N3P/R5R1 b - - 2 28',
    ultima: 'Dc3',
    marca: ['e3', 'c3'],
    solucion: { from: 'd7', to: 'a4' },
    primera: 'Aa4+',
    linea: '28…Aa4+ 29.Rb2 Txd2+ 30.Dxd2 Dxd2+',
    gana: true,
    valor: '+6,3',
    pista: 'Con los reyes en flancos distintos, gana quien llegue primero.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2jpNp de la base abierta de Lichess (CC0), rating 1615. Stockfish 16 a profundidad 18: Aa4+ es la mejor (+6,3) y la segunda queda en -3,8.',
  },
  {
    n: 12,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 12,
    id: 'ig_0MP31',
    tema: 'defensa',
    lichess: '0MP31',
    rating: 1393,
    elo: 613,
    juegan: 'b',
    fen: 'r4b2/1pqb1k1Q/p1pp1pp1/4p1p1/4P3/P1NP4/1PP2PPP/R3K2R b KQ - 1 17',
    ultima: 'Dh7+',
    marca: ['h8', 'h7'],
    solucion: { from: 'f8', to: 'g7' },
    primera: 'Ag7',
    linea: '17…Ag7 18.h4 Th8 19.Dxh8 Axh8',
    gana: true,
    valor: '+3,3',
    pista: 'Juega por el rival primero: ¿qué amenaza? Solo una jugada lo para.',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 0MP31 de la base abierta de Lichess (CC0), rating 1393. Stockfish 16 a profundidad 18: Ag7 es la mejor (+3,3) y la segunda queda en -5,0.',
  },
  {
    n: 13,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 13,
    id: 'ig_1haNF',
    tema: 'septima',
    lichess: '1haNF',
    rating: 1486,
    elo: 706,
    juegan: 'b',
    fen: '4rrk1/1p4pp/1N6/2p5/3n4/5N2/PP1B1KPP/1R6 b - - 0 22',
    ultima: 'Cxb6',
    marca: ['d5', 'b6'],
    solucion: { from: 'e8', to: 'e2' },
    primera: 'Te2+',
    linea: '22…Te2+ 23.Rg3 Cxf3 24.gxf3 Txd2',
    gana: true,
    valor: '+4,5',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 1haNF de la base abierta de Lichess (CC0), rating 1486. Stockfish 16 a profundidad 18: Te2+ es la mejor (+4,5) y la segunda queda en +0,4.',
  },
  {
    n: 14,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 14,
    id: 'ig_0orK6',
    tema: 'caballo',
    lichess: '0orK6',
    rating: 1292,
    elo: 512,
    juegan: 'b',
    fen: '2kr1bnr/ppp1pNpp/8/8/2Pn4/8/PP2NPPP/R1B1K2R b KQ - 0 11',
    ultima: 'Cxf7',
    marca: ['g5', 'f7'],
    solucion: { from: 'd4', to: 'c2' },
    primera: 'Cc2+',
    linea: '11…Cc2+ 12.Rf1 Td1#',
    gana: true,
    valor: 'mate en 2',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 0orK6 de la base abierta de Lichess (CC0), rating 1292. Stockfish 16 a profundidad 18: Cc2+ es la mejor (mate en 2) y la segunda queda en -3,3.',
  },
  {
    n: 15,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 15,
    id: 'ig_2tT48',
    tema: 'alfil',
    lichess: '2tT48',
    rating: 1590,
    elo: 810,
    juegan: 'w',
    fen: 'r3q1kr/2pbB1p1/p1N2bQp/1p2p3/7P/1P3PP1/1PP5/3RK2R w K - 6 24',
    ultima: 'De8',
    marca: ['c8', 'e8'],
    solucion: { from: 'e7', to: 'f6' },
    primera: 'Axf6',
    linea: '24.Axf6 Dxg6 25.Ce7+ Rh7 26.Cxg6',
    gana: true,
    valor: '+3,4',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2tT48 de la base abierta de Lichess (CC0), rating 1590. Stockfish 16 a profundidad 18: Axf6 es la mejor (+3,4) y la segunda queda en -3,7.',
  },
  {
    n: 16,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 16,
    id: 'ig_0DvcD',
    tema: 'dama',
    lichess: '0DvcD',
    rating: 1616,
    elo: 836,
    juegan: 'b',
    fen: 'r4rk1/pp3ppp/2b1p3/2Q5/4pP2/2P1B1Pq/PP5P/RN2K2R b KQ - 2 17',
    ultima: 'Ae3',
    marca: ['c1', 'e3'],
    solucion: { from: 'h3', to: 'g2' },
    primera: 'Dg2',
    linea: '17…Dg2 18.Tg1 Dxb2 19.Da3 Dxa1',
    gana: true,
    valor: '+4,2',
    pista: 'No hay jaque ni captura que sirva: la dama gana con una jugada tranquila.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 0DvcD de la base abierta de Lichess (CC0), rating 1616. Stockfish 16 a profundidad 18: Dg2 es la mejor (+4,2) y la segunda queda en +0,4.',
  },
  {
    n: 17,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 17,
    id: 'ig_0I4Ga',
    tema: 'atrapada',
    lichess: '0I4Ga',
    rating: 1591,
    elo: 811,
    juegan: 'b',
    fen: 'r1bq1rk1/5ppp/3p1n2/ppp1b3/3PP3/1BP1BQ2/PP3PPP/RN2R1K1 b - - 0 15',
    ultima: 'd4',
    marca: ['d3', 'd4'],
    solucion: { from: 'c8', to: 'g4' },
    primera: 'Ag4',
    linea: '15…Ag4 16.dxe5 Axf3',
    gana: true,
    valor: '+3,0',
    pista: 'Una pieza rival se quedó sin casillas. ¿Cómo la atacas?',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 0I4Ga de la base abierta de Lichess (CC0), rating 1591. Stockfish 16 a profundidad 18: Ag4 es la mejor (+3,0) y la segunda queda en -1,0.',
  },
  {
    n: 18,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 18,
    id: 'ig_0TD5k',
    tema: 'calidad',
    lichess: '0TD5k',
    rating: 1607,
    elo: 827,
    juegan: 'w',
    fen: '2kr1r2/1p4p1/p2b3p/2p1Rb2/P1Bp1P2/2P4P/1P1B1KP1/R7 w - - 1 21',
    ultima: 'Ad6',
    marca: ['e7', 'd6'],
    solucion: { from: 'e5', to: 'f5' },
    primera: 'Txf5',
    linea: '21.Txf5 Txf5 22.Ae6+ Rc7 23.Axf5',
    gana: true,
    valor: '+4,3',
    pista: 'Entregar la torre por una pieza menor está bien si lo que queda vale más.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0TD5k de la base abierta de Lichess (CC0), rating 1607. Stockfish 16 a profundidad 18: Txf5 es la mejor (+4,3) y la segunda queda en -0,6.',
  },
  {
    n: 19,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 19,
    id: 'ig_0eJwd',
    tema: 'pasado',
    lichess: '0eJwd',
    rating: 1572,
    elo: 792,
    juegan: 'b',
    fen: '8/8/8/3k1BKP/2p5/1p6/8/8 b - - 0 46',
    ultima: 'h5',
    marca: ['h4', 'h5'],
    solucion: { from: 'c4', to: 'c3' },
    primera: 'c3',
    linea: '46…c3 47.h6 c2 48.Rg6 c1=D',
    gana: true,
    valor: '+5,1',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0eJwd de la base abierta de Lichess (CC0), rating 1572. Stockfish 16 a profundidad 18: c3 es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 20,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 20,
    id: 'ig_26Lkb',
    tema: 'coronar',
    lichess: '26Lkb',
    rating: 1295,
    elo: 515,
    juegan: 'b',
    fen: '7Q/8/4bpk1/8/4PK2/P7/6pp/1R6 b - - 1 50',
    ultima: 'Dh8',
    marca: ['b8', 'h8'],
    solucion: { from: 'g2', to: 'g1', promotion: 'q' },
    primera: 'g1=D',
    linea: '50…g1=D 51.Txg1+ hxg1=D 52.De8+ Af7',
    gana: true,
    valor: '+3,5',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 26Lkb de la base abierta de Lichess (CC0), rating 1295. Stockfish 16 a profundidad 18: g1=D es la mejor (+3,5) y la segunda queda en -6,6.',
  },
  {
    n: 21,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 21,
    id: 'ig_3RUBS',
    tema: 'ruptura',
    lichess: '3RUBS',
    rating: 1371,
    elo: 591,
    juegan: 'w',
    fen: 'r7/p3kppp/1q6/4PP2/B2rQ3/2b5/P5PP/5R1K w - - 1 24',
    ultima: 'Td4',
    marca: ['d8', 'd4'],
    solucion: { from: 'f5', to: 'f6' },
    primera: 'f6+',
    linea: '24.f6+ gxf6 25.exf6+',
    gana: true,
    valor: '+5,0',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 3RUBS de la base abierta de Lichess (CC0), rating 1371. Stockfish 16 a profundidad 18: f6+ es la mejor (+5,0) y la segunda queda en 0,0.',
  },
  {
    n: 22,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 22,
    id: 'ig_2kztb',
    tema: 'peonsac',
    lichess: '2kztb',
    rating: 1486,
    elo: 706,
    juegan: 'b',
    fen: '2B5/7k/pP1p3p/P1p2p2/2P5/3P1pQP/4q3/7K b - - 3 46',
    ultima: 'Rh1',
    marca: ['h2', 'h1'],
    solucion: { from: 'f3', to: 'f2' },
    primera: 'f2',
    linea: '46…f2 47.Dxf2 Dxf2',
    gana: true,
    valor: '+4,1',
    pista: 'El peón se entrega a propósito: lo que importa es lo que abre.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2kztb de la base abierta de Lichess (CC0), rating 1486. Stockfish 16 a profundidad 18: f2 es la mejor (+4,1) y la segunda queda en 0,0.',
  },
  {
    n: 23,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 23,
    id: 'ig_1fInU',
    tema: 'peones',
    lichess: '1fInU',
    rating: 1586,
    elo: 806,
    juegan: 'w',
    fen: '8/8/8/1kp3P1/8/p1p2K2/P2p4/8 w - - 0 44',
    ultima: 'bxc3',
    marca: ['b4', 'c3'],
    solucion: { from: 'f3', to: 'e2' },
    primera: 'Re2',
    linea: '44.Re2 Rc4 45.g6 Rd4 46.g7',
    gana: true,
    valor: '+4,4',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1fInU de la base abierta de Lichess (CC0), rating 1586. Stockfish 16 a profundidad 18: Re2 es la mejor (+4,4) y la segunda queda en recibe mate en 8.',
  },
  {
    n: 24,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 24,
    id: 'ig_0gq92',
    tema: 'detener',
    lichess: '0gq92',
    rating: 1568,
    elo: 788,
    juegan: 'w',
    fen: '3R4/p6p/P5p1/KP6/1r6/2kp4/8/8 w - - 2 56',
    ultima: 'Tb4',
    marca: ['g4', 'b4'],
    solucion: { from: 'd8', to: 'd3' },
    primera: 'Txd3+',
    linea: '56.Txd3+ Rc4 57.Td4+ Rxd4 58.Rxb4 g5 59.b6',
    gana: true,
    valor: '+5,0',
    pista: 'El peón rival está muy avanzado. Lo primero es frenarlo.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0gq92 de la base abierta de Lichess (CC0), rating 1568. Stockfish 16 a profundidad 18: Txd3+ es la mejor (+5,0) y la segunda queda en -6,2.',
  },
  {
    n: 25,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 25,
    id: 'ig_0RHWa',
    tema: 'desviacion',
    lichess: '0RHWa',
    rating: 1472,
    elo: 692,
    juegan: 'b',
    fen: '5rk1/pb1Q3p/1p6/2ppN3/4nr1q/2P5/PP2B1PP/R4RK1 b - - 1 27',
    ultima: 'Dd7',
    marca: ['b5', 'd7'],
    solucion: { from: 'f4', to: 'f1' },
    primera: 'Txf1+',
    linea: '27…Txf1+ 28.Axf1 Df2+ 29.Rh1 Dxf1+ 30.Txf1 Txf1#',
    gana: true,
    valor: 'mate en 4',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 0RHWa de la base abierta de Lichess (CC0), rating 1472. Stockfish 16 a profundidad 18: Txf1+ es la mejor (mate en 4) y la segunda queda en -0,2.',
  },
  {
    n: 26,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 26,
    id: 'ig_2Eueb',
    tema: 'defensor',
    lichess: '2Eueb',
    rating: 1337,
    elo: 557,
    juegan: 'b',
    fen: '6k1/4nppp/B2qp3/2Np4/1P1Pn3/1Q2P3/5PPP/6K1 b - - 0 22',
    ultima: 'Axa6',
    marca: ['e2', 'a6'],
    solucion: { from: 'e4', to: 'c5' },
    primera: 'Cxc5',
    linea: '22…Cxc5 23.bxc5 Dxa6',
    gana: true,
    valor: '+3,2',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2Eueb de la base abierta de Lichess (CC0), rating 1337. Stockfish 16 a profundidad 18: Cxc5 es la mejor (+3,2) y la segunda queda en -2,1.',
  },
  {
    n: 27,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 27,
    id: 'ig_32oY9',
    tema: 'interferencia',
    lichess: '32oY9',
    rating: 1493,
    elo: 713,
    juegan: 'w',
    fen: 'r6r/p2q1kbp/3p2p1/1p6/3Q4/2N2PP1/PPP4P/4R1K1 w - - 4 25',
    ultima: 'Ag7',
    marca: ['f8', 'g7'],
    solucion: { from: 'd4', to: 'd5' },
    primera: 'Dd5+',
    linea: '25.Dd5+ Rf8 26.Dxa8+',
    gana: true,
    valor: '+5,1',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 32oY9 de la base abierta de Lichess (CC0), rating 1493. Stockfish 16 a profundidad 18: Dd5+ es la mejor (+5,1) y la segunda queda en -4,4.',
  },
  {
    n: 28,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 28,
    id: 'ig_16rjh',
    tema: 'clavada',
    lichess: '16rjh',
    rating: 1309,
    elo: 529,
    juegan: 'w',
    fen: 'r3kb1r/1p1qpp1p/p4np1/1N1P4/Q7/8/P4PPP/R1B1K2R w KQkq - 0 15',
    ultima: 'Dxd7',
    marca: ['d8', 'd7'],
    solucion: { from: 'b5', to: 'c7' },
    primera: 'Cc7+',
    linea: '15.Cc7+ Rd8 16.Dxd7+ Rxd7 17.Cxa8',
    gana: true,
    valor: '+4,6',
    pista: 'Una pieza rival no se puede mover sin dejar algo peor detrás.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 16rjh de la base abierta de Lichess (CC0), rating 1309. Stockfish 16 a profundidad 18: Cc7+ es la mejor (+4,6) y la segunda queda en -2,7.',
  },
  {
    n: 29,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 29,
    id: 'ig_34QQ2',
    tema: 'despeje',
    lichess: '34QQ2',
    rating: 1437,
    elo: 657,
    juegan: 'w',
    fen: 'r1b1k2r/pp4pp/1qn1p3/2bpn3/3N4/P1PB1N2/1P4PP/R1BQK2R w KQkq - 0 13',
    ultima: 'Cdxe5',
    marca: ['d7', 'e5'],
    solucion: { from: 'f3', to: 'e5' },
    primera: 'Cxe5',
    linea: '13.Cxe5 Cxe5 14.Dh5+',
    gana: true,
    valor: '+3,9',
    pista: 'Una pieza tuya estorba a otra. ¿Cómo la sacas de ahí con ganancia de tiempo?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 34QQ2 de la base abierta de Lichess (CC0), rating 1437. Stockfish 16 a profundidad 18: Cxe5 es la mejor (+3,9) y la segunda queda en -1,2.',
  },
  {
    n: 30,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 30,
    id: 'ig_00coU',
    tema: 'rayosx',
    lichess: '00coU',
    rating: 1472,
    elo: 692,
    juegan: 'b',
    fen: '6k1/R3K3/8/1r6/5r2/p4N2/8/5R2 b - - 4 50',
    ultima: 'Re7',
    marca: ['f6', 'e7'],
    solucion: { from: 'f4', to: 'f7' },
    primera: 'Tf7+',
    linea: '50…Tf7+ 51.Rd6 Txa7',
    gana: true,
    valor: '+4,7',
    pista: 'Dos piezas rivales en la misma línea: ataca la de adelante.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 00coU de la base abierta de Lichess (CC0), rating 1472. Stockfish 16 a profundidad 18: Tf7+ es la mejor (+4,7) y la segunda queda en +0,2.',
  },
  {
    n: 31,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 31,
    id: 'ig_2msgm',
    tema: 'torres',
    lichess: '2msgm',
    rating: 1620,
    elo: 840,
    juegan: 'w',
    fen: '5k2/R5p1/p2P1p1p/1p6/8/4P1PP/5P1K/r7 w - - 1 40',
    ultima: 'Rf8',
    marca: ['g8', 'f8'],
    solucion: { from: 'a7', to: 'a8' },
    primera: 'Ta8+',
    linea: '40.Ta8+ Rf7 41.d7',
    gana: true,
    valor: '+4,7',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2msgm de la base abierta de Lichess (CC0), rating 1620. Stockfish 16 a profundidad 18: Ta8+ es la mejor (+4,7) y la segunda queda en +0,3.',
  },
  {
    n: 32,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 32,
    id: 'ig_14y0L',
    tema: 'alfiles',
    lichess: '14y0L',
    rating: 1486,
    elo: 706,
    juegan: 'b',
    fen: '8/p3b2p/1k4p1/1p1p4/P2P4/1P1K1PB1/5P1P/8 b - - 0 45',
    ultima: 'a4',
    marca: ['a3', 'a4'],
    solucion: { from: 'b5', to: 'a4' },
    primera: 'bxa4',
    linea: '45…bxa4 46.bxa4 Ra5 47.Ab8 a6 48.Rc3 Rxa4',
    gana: true,
    valor: '+3,9',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 14y0L de la base abierta de Lichess (CC0), rating 1486. Stockfish 16 a profundidad 18: bxa4 es la mejor (+3,9) y la segunda queda en +0,2.',
  },
  {
    n: 33,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 33,
    id: 'ig_1UCwA',
    tema: 'alfilcaballo',
    lichess: '1UCwA',
    rating: 1441,
    elo: 661,
    juegan: 'w',
    fen: '8/8/3k3B/8/3pp1p1/n5P1/2P1K3/8 w - - 0 54',
    ultima: 'd4',
    marca: ['d5', 'd4'],
    solucion: { from: 'h6', to: 'f8' },
    primera: 'Af8+',
    linea: '54.Af8+ Rd5 55.Axa3',
    gana: true,
    valor: '+4,9',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 1UCwA de la base abierta de Lichess (CC0), rating 1441. Stockfish 16 a profundidad 18: Af8+ es la mejor (+4,9) y la segunda queda en -4,9.',
  },
  {
    n: 34,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 34,
    id: 'ig_1cP0o',
    tema: 'damas',
    lichess: '1cP0o',
    rating: 1443,
    elo: 663,
    juegan: 'w',
    fen: '8/8/2Q5/2p5/3P4/3k2K1/8/1q6 w - - 1 46',
    ultima: 'Rd3',
    marca: ['e4', 'd3'],
    solucion: { from: 'c6', to: 'g6' },
    primera: 'Dg6+',
    linea: '46.Dg6+ Re3 47.Dxb1',
    gana: true,
    valor: '+35,1',
    pista: 'Con damas, cada jaque cuenta: busca el que gana algo o corona.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 1cP0o de la base abierta de Lichess (CC0), rating 1443. Stockfish 16 a profundidad 18: Dg6+ es la mejor (+35,1) y la segunda queda en 0,0.',
  },
  {
    n: 35,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 35,
    id: 'ig_0LETl',
    tema: 'zugzwang',
    lichess: '0LETl',
    rating: 1642,
    elo: 862,
    juegan: 'w',
    fen: '8/2p5/p1p1k2p/6p1/PP1K2P1/7P/8/8 w - - 3 42',
    ultima: 'Re6',
    marca: ['d6', 'e6'],
    solucion: { from: 'd4', to: 'c5' },
    primera: 'Rc5',
    linea: '42.Rc5 Rd7 43.a5 Re8 44.Rxc6',
    gana: true,
    valor: '+3,8',
    pista: 'A veces lo mejor es dejar que el rival se ahogue: ¿qué jugada le quita las buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0LETl de la base abierta de Lichess (CC0), rating 1642. Stockfish 16 a profundidad 18: Rc5 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 36,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_09WMe',
    tema: 'concentracion',
    lichess: '09WMe',
    rating: 1426,
    elo: 646,
    juegan: 'w',
    fen: 'r4rk1/pbq2ppp/1pp2n2/8/8/2NB3R/PPP2PPP/R2Q2K1 w - - 5 16',
    ultima: 'Dc7',
    marca: ['d8', 'c7'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '16.Axh7+ Cxh7 17.Dh5 f6 18.Dxh7+',
    gana: true,
    valor: '+5,1',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 09WMe de la base abierta de Lichess (CC0), rating 1426. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+5,1) y la segunda queda en +0,1.',
  },
  {
    n: 37,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_0HqyL',
    tema: 'h7',
    lichess: '0HqyL',
    rating: 1528,
    elo: 748,
    juegan: 'b',
    fen: 'r4rk1/2q1p2p/1p4pB/3pbb2/p3n2N/2PN4/PP2B1PP/2RQ1RK1 b - - 0 21',
    ultima: 'Axh6',
    marca: ['e3', 'h6'],
    solucion: { from: 'e5', to: 'h2' },
    primera: 'Axh2+',
    linea: '21…Axh2+ 22.Rh1 Cg3+ 23.Rxh2 Cxf1+',
    gana: true,
    valor: '+5,3',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 0HqyL de la base abierta de Lichess (CC0), rating 1528. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+5,3) y la segunda queda en -2,6.',
  },
  {
    n: 38,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_0uIwA',
    tema: 'demolicion',
    lichess: '0uIwA',
    rating: 1615,
    elo: 835,
    juegan: 'b',
    fen: '4rrk1/ppp3bp/3p2p1/2PPp3/1P3n1q/4BB1P/P2Q1PP1/3R1R1K b - - 0 19',
    ultima: 'c5',
    marca: ['c4', 'c5'],
    solucion: { from: 'f4', to: 'h3' },
    primera: 'Cxh3',
    linea: '19…Cxh3 20.g3 Cxf2+ 21.Rg2 Dh3+',
    gana: true,
    valor: '+5,6',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 0uIwA de la base abierta de Lichess (CC0), rating 1615. Stockfish 16 a profundidad 18: Cxh3 es la mejor (+5,6) y la segunda queda en +0,5.',
  },
  {
    n: 39,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2W0uC',
    tema: 'demolicion',
    lichess: '2W0uC',
    rating: 1693,
    elo: 913,
    juegan: 'w',
    fen: 'r7/p2qr3/1p1p2kp/2p2pp1/8/2QPR1P1/PPP2PP1/1K5R w - - 6 27',
    ultima: 'Rg6',
    marca: ['f7', 'g6'],
    solucion: { from: 'h1', to: 'h6' },
    primera: 'Txh6+',
    linea: '27.Txh6+ Rxh6 28.Df6+',
    gana: true,
    valor: '+6,2',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2W0uC de la base abierta de Lichess (CC0), rating 1693. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+6,2) y la segunda queda en -0,0.',
  },
  {
    n: 40,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_1ssxa',
    tema: 'h7',
    lichess: '1ssxa',
    rating: 1831,
    elo: 1051,
    juegan: 'w',
    fen: 'r1b2rk1/pp1pbppp/2n1p3/q2nP3/1p1P3P/P2B1N2/2PB1PP1/RN1QK2R w KQ - 1 10',
    ultima: 'Cd5',
    marca: ['f6', 'd5'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '10.Axh7+ Rxh7 11.Cg5+ Rg8 12.Dh5 Cf6 13.exf6',
    gana: true,
    valor: '+4,0',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1ssxa de la base abierta de Lichess (CC0), rating 1831. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+4,0) y la segunda queda en -0,0.',
  },
  {
    n: 41,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_2kQXT',
    tema: 'concentracion',
    lichess: '2kQXT',
    rating: 1918,
    elo: 1138,
    juegan: 'w',
    fen: '2r3k1/3qprbp/p2p2p1/1p1n4/1P1B2P1/P2B1P2/2P4Q/2R1K2R w K - 0 22',
    ultima: 'Cxd5',
    marca: ['f6', 'd5'],
    solucion: { from: 'h2', to: 'h7' },
    primera: 'Dxh7+',
    linea: '22.Dxh7+ Rf8 23.Dh8+ Axh8 24.Txh8#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 2kQXT de la base abierta de Lichess (CC0), rating 1918. Stockfish 16 a profundidad 18: Dxh7+ es la mejor (mate en 3) y la segunda queda en -1,8.',
  },
  {
    n: 42,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_0blRs',
    tema: 'h7',
    lichess: '0blRs',
    rating: 2053,
    elo: 1273,
    juegan: 'b',
    fen: '2r3k1/1bq4p/4p1p1/1p2b3/1PR5/P3Q3/1B4PP/5RK1 b - - 0 27',
    ultima: 'Txc4',
    marca: ['c1', 'c4'],
    solucion: { from: 'e5', to: 'h2' },
    primera: 'Axh2+',
    linea: '27…Axh2+ 28.Rh1 Dxc4',
    gana: true,
    valor: '+4,1',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 0blRs de la base abierta de Lichess (CC0), rating 2053. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+4,1) y la segunda queda en -1,1.',
  },
  {
    n: 43,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'ig_1XH1f',
    tema: 'concentracion',
    lichess: '1XH1f',
    rating: 2294,
    elo: 1514,
    juegan: 'w',
    fen: '6k1/p4pp1/2p4p/3p1bn1/2pP4/2P2PqP/PPQ3P1/4R1K1 w - - 0 27',
    ultima: 'Axf5',
    marca: ['d7', 'f5'],
    solucion: { from: 'e1', to: 'e8' },
    primera: 'Te8+',
    linea: '27.Te8+ Rh7 28.Dxf5+ g6 29.Dg4',
    gana: true,
    valor: '+3,2',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 1XH1f de la base abierta de Lichess (CC0), rating 2294. Stockfish 16 a profundidad 18: Te8+ es la mejor (+3,2) y la segunda queda en -4,9.',
  },
  {
    n: 44,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_1r5Zh',
    tema: 'desarrollo',
    lichess: '1r5Zh',
    rating: 1431,
    elo: 651,
    juegan: 'w',
    fen: 'r3kb1r/pp3ppp/2npp1b1/2p5/4N1Pq/3P3P/PPP2PB1/R1BQK2R w KQkq - 0 11',
    ultima: 'Dxh4',
    marca: ['d8', 'h4'],
    solucion: { from: 'c1', to: 'g5' },
    primera: 'Ag5',
    linea: '11.Ag5 Axe4 12.Axh4',
    gana: true,
    valor: '+4,2',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 1r5Zh de la base abierta de Lichess (CC0), rating 1431. Stockfish 16 a profundidad 18: Ag5 es la mejor (+4,2) y la segunda queda en -1,2.',
  },
  {
    n: 45,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2XhlY',
    tema: 'reycentro',
    lichess: '2XhlY',
    rating: 1609,
    elo: 829,
    juegan: 'w',
    fen: '2Qqk2r/1p4pp/5p2/1p1pbp2/5r2/8/PP3P1P/2R1R1K1 w k - 2 24',
    ultima: 'Dd8',
    marca: ['d7', 'd8'],
    solucion: { from: 'c8', to: 'e6' },
    primera: 'De6+',
    linea: '24.De6+ Rf8 25.Tc8 Dxc8 26.Dxc8+ Rf7 27.Dxh8',
    gana: true,
    valor: '+5,0',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 2XhlY de la base abierta de Lichess (CC0), rating 1609. Stockfish 16 a profundidad 18: De6+ es la mejor (+5,0) y la segunda queda en 0,0.',
  },
  {
    n: 46,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_1zyBZ',
    tema: 'f7',
    lichess: '1zyBZ',
    rating: 1611,
    elo: 831,
    juegan: 'b',
    fen: 'r4rk1/pppq2p1/3ppn1p/n1b1p3/1P2P2N/2PP2NP/P4PP1/R1BQK2R b KQ b3 0 13',
    ultima: 'b4',
    marca: ['b2', 'b4'],
    solucion: { from: 'c5', to: 'f2' },
    primera: 'Axf2+',
    linea: '13…Axf2+ 14.Rxf2 Cxe4+ 15.Rg1 Cxg3',
    gana: true,
    valor: '+4,0',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 1zyBZ de la base abierta de Lichess (CC0), rating 1611. Stockfish 16 a profundidad 18: Axf2+ es la mejor (+4,0) y la segunda queda en -0,3.',
  },
  {
    n: 47,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_3KZue',
    tema: 'desarrollo',
    lichess: '3KZue',
    rating: 1759,
    elo: 979,
    juegan: 'w',
    fen: 'r1bqr1k1/pppn1ppp/2np4/3P4/4P3/4bN2/PP1NBPPP/R2Q1RK1 w - - 0 12',
    ultima: 'Axe3',
    marca: ['b6', 'e3'],
    solucion: { from: 'd5', to: 'c6' },
    primera: 'dxc6',
    linea: '12.dxc6 Ab6 13.cxd7',
    gana: true,
    valor: '+3,6',
    pista: 'Tienes más piezas en juego que el rival. Ese tiempo hay que usarlo ahora.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3KZue de la base abierta de Lichess (CC0), rating 1759. Stockfish 16 a profundidad 18: dxc6 es la mejor (+3,6) y la segunda queda en -0,0.',
  },
  {
    n: 48,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2BKlU',
    tema: 'reycentro',
    lichess: '2BKlU',
    rating: 1914,
    elo: 1134,
    juegan: 'w',
    fen: '2bq1k2/1r4b1/pr4P1/2p1nP2/2PpP3/P6Q/3B1P2/R2BK2R w KQ - 5 30',
    ultima: 'Rf8',
    marca: ['g8', 'f8'],
    solucion: { from: 'h3', to: 'h8' },
    primera: 'Dh8+',
    linea: '30.Dh8+ Axh8 31.Txh8+ Rg7 32.Txd8',
    gana: true,
    valor: '+3,1',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 2BKlU de la base abierta de Lichess (CC0), rating 1914. Stockfish 16 a profundidad 18: Dh8+ es la mejor (+3,1) y la segunda queda en +0,2.',
  },
  {
    n: 49,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_1h24f',
    tema: 'f7',
    lichess: '1h24f',
    rating: 1926,
    elo: 1146,
    juegan: 'w',
    fen: 'r1bqk2r/p2pbp1p/2n2p1B/2p5/2B5/8/Pp2QPPP/3RK1NR w Kkq - 2 13',
    ultima: 'Cc6',
    marca: ['b8', 'c6'],
    solucion: { from: 'c4', to: 'f7' },
    primera: 'Axf7+',
    linea: '13.Axf7+ Rxf7 14.Dh5+ Re6 15.Dd5#',
    gana: true,
    valor: 'mate en 3',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1h24f de la base abierta de Lichess (CC0), rating 1926. Stockfish 16 a profundidad 18: Axf7+ es la mejor (mate en 3) y la segunda queda en -0,8.',
  },
  {
    n: 50,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_01UsT',
    tema: 'f7',
    lichess: '01UsT',
    rating: 2093,
    elo: 1313,
    juegan: 'b',
    fen: 'r3r1k1/pp2qp1p/3b2p1/3p4/3P2n1/1PN4P/PBP1BPP1/R2QK2R b KQ - 0 15',
    ultima: 'h3',
    marca: ['h2', 'h3'],
    solucion: { from: 'g4', to: 'f2' },
    primera: 'Cxf2',
    linea: '15…Cxf2 16.Rxf2 De3+ 17.Rf1 Ag3',
    gana: true,
    valor: '+3,0',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 01UsT de la base abierta de Lichess (CC0), rating 2093. Stockfish 16 a profundidad 18: Cxf2 es la mejor (+3,0) y la segunda queda en -3,4.',
  },
  {
    n: 51,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'ig_2eZAI',
    tema: 'reycentro',
    lichess: '2eZAI',
    rating: 2370,
    elo: 1590,
    juegan: 'w',
    fen: '1r3k2/p1pbq1bR/1p3pQ1/2Np4/8/2P1P1P1/PP3PP1/2K5 w - - 0 23',
    ultima: 'b6',
    marca: ['b7', 'b6'],
    solucion: { from: 'g6', to: 'g7' },
    primera: 'Dxg7+',
    linea: '23.Dxg7+ Dxg7 24.Cxd7+ Dxd7 25.Txd7',
    gana: true,
    valor: '+5,2',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2eZAI de la base abierta de Lichess (CC0), rating 2370. Stockfish 16 a profundidad 18: Dxg7+ es la mejor (+5,2) y la segunda queda en -0,4.',
  },
  {
    n: 52,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_106yW',
    tema: 'alfil',
    lichess: '106yW',
    rating: 1399,
    elo: 619,
    juegan: 'w',
    fen: '1k1r3r/pp1n2pp/2pqBnb1/6B1/2QP4/8/PPP3PP/R4RK1 w - - 0 16',
    ultima: 'Dxd6',
    marca: ['e7', 'd6'],
    solucion: { from: 'g5', to: 'f4' },
    primera: 'Af4',
    linea: '16.Af4 Dxf4 17.Txf4',
    gana: true,
    valor: '+4,3',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 106yW de la base abierta de Lichess (CC0), rating 1399. Stockfish 16 a profundidad 18: Af4 es la mejor (+4,3) y la segunda queda en -3,0.',
  },
  {
    n: 53,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_0UgJJ',
    tema: 'septima',
    lichess: '0UgJJ',
    rating: 1575,
    elo: 795,
    juegan: 'b',
    fen: '2r2rk1/p3pp1p/6p1/3P4/1P2PP1P/3QR1P1/1q6/5R1K b - - 0 28',
    ultima: 'cxb4',
    marca: ['c3', 'b4'],
    solucion: { from: 'c8', to: 'c2' },
    primera: 'Tc2',
    linea: '28…Tc2 29.Dxc2 Dxc2',
    gana: true,
    valor: '+5,0',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0UgJJ de la base abierta de Lichess (CC0), rating 1575. Stockfish 16 a profundidad 18: Tc2 es la mejor (+5,0) y la segunda queda en +0,1.',
  },
  {
    n: 54,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_25UOh',
    tema: 'caballo',
    lichess: '25UOh',
    rating: 1645,
    elo: 865,
    juegan: 'w',
    fen: '2qr2k1/p4p1p/1b3Pp1/5N2/2P5/7P/P4rQ1/3RR1K1 w - - 0 26',
    ultima: 'Txf2',
    marca: ['b2', 'f2'],
    solucion: { from: 'f5', to: 'e7' },
    primera: 'Ce7+',
    linea: '26.Ce7+ Rf8 27.Cxc8 Txg2+ 28.Rxg2',
    gana: true,
    valor: '+4,5',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 25UOh de la base abierta de Lichess (CC0), rating 1645. Stockfish 16 a profundidad 18: Ce7+ es la mejor (+4,5) y la segunda queda en -4,8.',
  },
  {
    n: 55,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_0Jcdq',
    tema: 'caballo',
    lichess: '0Jcdq',
    rating: 1680,
    elo: 900,
    juegan: 'w',
    fen: 'r3r1k1/2p1q2p/3p1pp1/p7/4NP2/3P4/PQ4PP/4R1K1 w - - 0 21',
    ultima: 'f6',
    marca: ['f7', 'f6'],
    solucion: { from: 'e4', to: 'f6' },
    primera: 'Cxf6+',
    linea: '21.Cxf6+ Dxf6 22.Txe8+ Txe8 23.Dxf6',
    gana: true,
    valor: '+5,0',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 0Jcdq de la base abierta de Lichess (CC0), rating 1680. Stockfish 16 a profundidad 18: Cxf6+ es la mejor (+5,0) y la segunda queda en -1,9.',
  },
  {
    n: 56,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_0B136',
    tema: 'alfil',
    lichess: '0B136',
    rating: 1737,
    elo: 957,
    juegan: 'w',
    fen: 'r3r1k1/pp1n1ppp/2pb4/3p1q2/3Pn3/P4B1P/1PPBNPP1/R2Q1RK1 w - - 4 15',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'f3', to: 'g4' },
    primera: 'Ag4',
    linea: '15.Ag4 Dg6 16.Axd7 Te7 17.Ag4',
    gana: true,
    valor: '+3,4',
    pista: 'El alfil trabaja de lejos: mira la diagonal entera, hasta el final.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 0B136 de la base abierta de Lichess (CC0), rating 1737. Stockfish 16 a profundidad 18: Ag4 es la mejor (+3,4) y la segunda queda en -0,3.',
  },
  {
    n: 57,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1RAhc',
    tema: 'septima',
    lichess: '1RAhc',
    rating: 1936,
    elo: 1156,
    juegan: 'b',
    fen: '5r2/2R2pkp/1p3qp1/6Nr/1p3R2/1Q3P2/1P3P1P/7K b - - 0 33',
    ultima: 'Txf4',
    marca: ['g4', 'f4'],
    solucion: { from: 'h5', to: 'h2' },
    primera: 'Txh2+',
    linea: '33…Txh2+ 34.Rxh2 Dxf4+',
    gana: true,
    valor: '+4,5',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1RAhc de la base abierta de Lichess (CC0), rating 1936. Stockfish 16 a profundidad 18: Txh2+ es la mejor (+4,5) y la segunda queda en -5,3.',
  },
  {
    n: 58,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1eP7U',
    tema: 'septima',
    lichess: '1eP7U',
    rating: 2083,
    elo: 1303,
    juegan: 'w',
    fen: '5rk1/pq3r1p/1pN3p1/2Pnp3/8/8/P3Q1PP/3R1RK1 w - - 0 28',
    ultima: 'Cxd5',
    marca: ['f6', 'd5'],
    solucion: { from: 'f1', to: 'f7' },
    primera: 'Txf7',
    linea: '28.Txf7 Dxf7 29.Txd5',
    gana: true,
    valor: '+3,8',
    pista: 'Una torre en la séptima ataca peones y encierra al rey.',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 1eP7U de la base abierta de Lichess (CC0), rating 2083. Stockfish 16 a profundidad 18: Txf7 es la mejor (+3,8) y la segunda queda en -0,3.',
  },
  {
    n: 59,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'ig_1WNxd',
    tema: 'caballo',
    lichess: '1WNxd',
    rating: 2532,
    elo: 1752,
    juegan: 'b',
    fen: '1kr5/5R2/p3p3/2qpP3/4n1P1/1Pp2Q1P/P1P1B3/3K4 b - - 2 36',
    ultima: 'Rd1',
    marca: ['c1', 'd1'],
    solucion: { from: 'e4', to: 'g5' },
    primera: 'Cg5',
    linea: '36…Cg5 37.Df2 Cxf7 38.Dxc5 Txc5',
    gana: true,
    valor: '+4,5',
    pista: 'El caballo ataca dos cosas a la vez: busca la casilla.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1WNxd de la base abierta de Lichess (CC0), rating 2532. Stockfish 16 a profundidad 18: Cg5 es la mejor (+4,5) y la segunda queda en -0,9.',
  },
  {
    n: 60,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2S2mo',
    tema: 'pasado',
    lichess: '2S2mo',
    rating: 1532,
    elo: 752,
    juegan: 'b',
    fen: '8/1p2rk2/p4p2/7P/1P1R1K2/2P3p1/1P3P2/8 b - - 1 55',
    ultima: 'Rf4',
    marca: ['f5', 'f4'],
    solucion: { from: 'g3', to: 'f2' },
    primera: 'gxf2',
    linea: '55…gxf2 56.Td1 Te1',
    gana: true,
    valor: '+5,8',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2S2mo de la base abierta de Lichess (CC0), rating 1532. Stockfish 16 a profundidad 18: gxf2 es la mejor (+5,8) y la segunda queda en -0,7.',
  },
  {
    n: 61,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_1U30e',
    tema: 'ruptura',
    lichess: '1U30e',
    rating: 1588,
    elo: 808,
    juegan: 'b',
    fen: '1r3r2/p2b2kp/2p3p1/5p2/2PqpP2/1P6/P2NBQPP/R1R3K1 b - - 1 21',
    ultima: 'Df2',
    marca: ['g3', 'f2'],
    solucion: { from: 'e4', to: 'e3' },
    primera: 'e3',
    linea: '21…e3 22.Dg3 exd2+',
    gana: true,
    valor: '+4,7',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1U30e de la base abierta de Lichess (CC0), rating 1588. Stockfish 16 a profundidad 18: e3 es la mejor (+4,7) y la segunda queda en -4,3.',
  },
  {
    n: 62,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_3BzAn',
    tema: 'coronar',
    lichess: '3BzAn',
    rating: 1639,
    elo: 859,
    juegan: 'w',
    fen: '3K4/3P4/1k6/8/8/8/p3r3/2R5 w - - 15 71',
    ultima: 'Rb6',
    marca: ['b7', 'b6'],
    solucion: { from: 'd8', to: 'c8' },
    primera: 'Rc8',
    linea: '71.Rc8 Td2 72.d8=D+ Txd8+ 73.Rxd8 Rb5 74.Ta1 Rb4 75.Txa2',
    gana: true,
    valor: '+5,1',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 3BzAn de la base abierta de Lichess (CC0), rating 1639. Stockfish 16 a profundidad 18: Rc8 es la mejor (+5,1) y la segunda queda en 0,0.',
  },
  {
    n: 63,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2ch3I',
    tema: 'coronar',
    lichess: '2ch3I',
    rating: 1687,
    elo: 907,
    juegan: 'w',
    fen: '6k1/1PK5/8/7R/6p1/8/1r5p/8 w - - 0 45',
    ultima: 'h2',
    marca: ['h3', 'h2'],
    solucion: { from: 'h5', to: 'h2' },
    primera: 'Txh2',
    linea: '45.Txh2 Txh2 46.b8=D+',
    gana: true,
    valor: '+3,0',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2ch3I de la base abierta de Lichess (CC0), rating 1687. Stockfish 16 a profundidad 18: Txh2 es la mejor (+3,0) y la segunda queda en -2,8.',
  },
  {
    n: 64,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_24X3L',
    tema: 'ruptura',
    lichess: '24X3L',
    rating: 1768,
    elo: 988,
    juegan: 'b',
    fen: '5rk1/3qbrpp/p2p4/2p1Q1B1/8/2P2P1P/P1P3P1/R2R2K1 b - - 0 21',
    ultima: 'Dxe5',
    marca: ['e2', 'e5'],
    solucion: { from: 'd6', to: 'e5' },
    primera: 'dxe5',
    linea: '21…dxe5 22.Txd7 Axg5',
    gana: true,
    valor: '+4,5',
    pista: 'Un golpe de peón abre las líneas que tus piezas necesitan.',
    explica: 'Se captura al defensor y lo que defendía queda colgado.',
    comprobado: 'Ejercicio 24X3L de la base abierta de Lichess (CC0), rating 1768. Stockfish 16 a profundidad 18: dxe5 es la mejor (+4,5) y la segunda queda en -0,2.',
  },
  {
    n: 65,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_04bMQ',
    tema: 'pasado',
    lichess: '04bMQ',
    rating: 1818,
    elo: 1038,
    juegan: 'b',
    fen: '8/8/p2R2r1/2P3p1/P7/1K2pk1P/8/8 b - - 1 39',
    ultima: 'Td6',
    marca: ['d8', 'd6'],
    solucion: { from: 'e3', to: 'e2' },
    primera: 'e2',
    linea: '39…e2 40.Txg6 e1=D',
    gana: true,
    valor: '+4,0',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 04bMQ de la base abierta de Lichess (CC0), rating 1818. Stockfish 16 a profundidad 18: e2 es la mejor (+4,0) y la segunda queda en +0,4.',
  },
  {
    n: 66,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_0Q6VW',
    tema: 'pasado',
    lichess: '0Q6VW',
    rating: 2161,
    elo: 1381,
    juegan: 'w',
    fen: '2r5/6p1/1P1P4/2Pk2p1/1K6/5P1P/6P1/8 w - - 1 51',
    ultima: 'Tc8',
    marca: ['d8', 'c8'],
    solucion: { from: 'd6', to: 'd7' },
    primera: 'd7',
    linea: '51.d7 Td8 52.Rb5 Txd7 53.c6',
    gana: true,
    valor: '+4,8',
    pista: 'Un peón pasado avanzado vale casi una pieza: empújalo.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0Q6VW de la base abierta de Lichess (CC0), rating 2161. Stockfish 16 a profundidad 18: d7 es la mejor (+4,8) y la segunda queda en -3,3.',
  },
  {
    n: 67,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'ig_2EgIj',
    tema: 'coronar',
    lichess: '2EgIj',
    rating: 2208,
    elo: 1428,
    juegan: 'w',
    fen: '8/p7/1p6/3PN3/2P2k1p/4n3/PP4p1/6K1 w - - 0 42',
    ultima: 'h4',
    marca: ['h5', 'h4'],
    solucion: { from: 'd5', to: 'd6' },
    primera: 'd6',
    linea: '42.d6 Rg3 43.d7 h3 44.Cf3 Rxf3 45.d8=D',
    gana: true,
    valor: '+4,2',
    pista: 'El peón está cerca de la última fila. ¿Qué hay que quitar del camino?',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2EgIj de la base abierta de Lichess (CC0), rating 2208. Stockfish 16 a profundidad 18: d6 es la mejor (+4,2) y la segunda queda en 0,0.',
  },
  {
    n: 68,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2TEGK',
    tema: 'defensor',
    lichess: '2TEGK',
    rating: 1510,
    elo: 730,
    juegan: 'b',
    fen: '2r1b3/2r5/1n1k1p1p/pP1P1Pp1/P3B1P1/2NP3P/1K6/2R1R3 b - - 2 34',
    ultima: 'The1',
    marca: ['h1', 'e1'],
    solucion: { from: 'c7', to: 'c3' },
    primera: 'Txc3',
    linea: '34…Txc3 35.Txc3 Cxa4+ 36.Rb3 Cxc3',
    gana: true,
    valor: '+3,8',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2TEGK de la base abierta de Lichess (CC0), rating 1510. Stockfish 16 a profundidad 18: Txc3 es la mejor (+3,8) y la segunda queda en -2,6.',
  },
  {
    n: 69,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2uDwr',
    tema: 'interferencia',
    lichess: '2uDwr',
    rating: 1634,
    elo: 854,
    juegan: 'b',
    fen: 'r1Nk3r/pp3ppp/4p3/3pn3/3N3q/8/PPP1K1PP/R2Q1B1R b - - 2 14',
    ultima: 'Re2',
    marca: ['e1', 'e2'],
    solucion: { from: 'h4', to: 'e4' },
    primera: 'De4+',
    linea: '14…De4+ 15.Rd2 Dxd4+',
    gana: true,
    valor: '+4,3',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 2uDwr de la base abierta de Lichess (CC0), rating 1634. Stockfish 16 a profundidad 18: De4+ es la mejor (+4,3) y la segunda queda en -1,5.',
  },
  {
    n: 70,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_1srCZ',
    tema: 'desviacion',
    lichess: '1srCZ',
    rating: 1637,
    elo: 857,
    juegan: 'w',
    fen: '4r3/p4pk1/2p3p1/8/7Q/2P2q2/PP3P1R/5nK1 w - - 2 31',
    ultima: 'Rg7',
    marca: ['f6', 'g7'],
    solucion: { from: 'h4', to: 'd4' },
    primera: 'Dd4+',
    linea: '31.Dd4+ Df6 32.Th7+ Rxh7 33.Dxf6',
    gana: true,
    valor: '+4,6',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1srCZ de la base abierta de Lichess (CC0), rating 1637. Stockfish 16 a profundidad 18: Dd4+ es la mejor (+4,6) y la segunda queda en 0,0.',
  },
  {
    n: 71,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_20CdR',
    tema: 'interferencia',
    lichess: '20CdR',
    rating: 1811,
    elo: 1031,
    juegan: 'w',
    fen: '7k/p1p3q1/1p1pQ3/3PbP2/P1P1B1r1/8/4R3/5K2 w - - 3 45',
    ultima: 'Rh8',
    marca: ['g8', 'h8'],
    solucion: { from: 'e6', to: 'e8' },
    primera: 'De8+',
    linea: '45.De8+ Dg8 46.Dh5+ Rg7 47.Dxg4+',
    gana: true,
    valor: '+5,3',
    pista: 'Pon una pieza entre dos piezas rivales que se defienden.',
    explica: 'Es una interferencia: una pieza se mete entre la defensora y lo que defiende.',
    comprobado: 'Ejercicio 20CdR de la base abierta de Lichess (CC0), rating 1811. Stockfish 16 a profundidad 18: De8+ es la mejor (+5,3) y la segunda queda en 0,0.',
  },
  {
    n: 72,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_1TkYZ',
    tema: 'defensor',
    lichess: '1TkYZ',
    rating: 1847,
    elo: 1067,
    juegan: 'b',
    fen: '5r2/Q1n1q1pk/4P2p/3P4/5P2/2P1P2B/Pr5P/R3K1R1 b Q f3 0 22',
    ultima: 'f4',
    marca: ['f2', 'f4'],
    solucion: { from: 'e7', to: 'h4' },
    primera: 'Dh4+',
    linea: '22…Dh4+ 23.Tg3 Txh2 24.O-O-O Dxg3',
    gana: true,
    valor: '+4,6',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1TkYZ de la base abierta de Lichess (CC0), rating 1847. Stockfish 16 a profundidad 18: Dh4+ es la mejor (+4,6) y la segunda queda en -2,5.',
  },
  {
    n: 73,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_0FQU8',
    tema: 'desviacion',
    lichess: '0FQU8',
    rating: 2041,
    elo: 1261,
    juegan: 'w',
    fen: '8/8/pp3k2/3p4/3PpK2/P7/1PP5/8 w - - 0 37',
    ultima: 'a6',
    marca: ['a7', 'a6'],
    solucion: { from: 'c2', to: 'c4' },
    primera: 'c4',
    linea: '37.c4 dxc4 38.Rxe4 Re6 39.d5+',
    gana: true,
    valor: '+3,8',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0FQU8 de la base abierta de Lichess (CC0), rating 2041. Stockfish 16 a profundidad 18: c4 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 74,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_1xHRG',
    tema: 'desviacion',
    lichess: '1xHRG',
    rating: 2465,
    elo: 1685,
    juegan: 'w',
    fen: '4r2k/2q1r1p1/1p1p1p1p/p1pB3Q/2P2P2/3n2P1/PB4KP/4R3 w - - 1 32',
    ultima: 'Cd3',
    marca: ['e5', 'd3'],
    solucion: { from: 'h5', to: 'e8' },
    primera: 'Dxe8+',
    linea: '32.Dxe8+ Txe8 33.Txe8+ Rh7 34.Ae4+ g6 35.Axf6',
    gana: true,
    valor: '+6,9',
    pista: 'Una pieza rival sostiene todo. ¿Puedes obligarla a irse?',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1xHRG de la base abierta de Lichess (CC0), rating 2465. Stockfish 16 a profundidad 18: Dxe8+ es la mejor (+6,9) y la segunda queda en -4,4.',
  },
  {
    n: 75,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'ig_2ngFz',
    tema: 'defensor',
    lichess: '2ngFz',
    rating: 2526,
    elo: 1746,
    juegan: 'w',
    fen: '5r2/pb2rp2/7R/6R1/2Bk1p2/P3p3/1PP4P/2K5 w - - 4 31',
    ultima: 'Rd4',
    marca: ['e5', 'd4'],
    solucion: { from: 'h6', to: 'd6' },
    primera: 'Td6+',
    linea: '31.Td6+ Re4 32.Ad3+ Rf3 33.Tf6 Te4 34.Tg3+ Rf2 35.Axe4 Axe4 36.Txf4+ Re2 37.Txe4',
    gana: true,
    valor: '+4,6',
    pista: 'Toma la pieza que defiende, y lo que defendía queda colgando.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 2ngFz de la base abierta de Lichess (CC0), rating 2526. Stockfish 16 a profundidad 18: Td6+ es la mejor (+4,6) y la segunda queda en -4,2.',
  },
  {
    n: 76,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_2YJBp',
    tema: 'torres',
    lichess: '2YJBp',
    rating: 1252,
    elo: 472,
    juegan: 'b',
    fen: '6k1/6p1/1r5p/8/8/pR4P1/P2K3P/8 b - - 11 53',
    ultima: 'Rd2',
    marca: ['e2', 'd2'],
    solucion: { from: 'b6', to: 'b3' },
    primera: 'Txb3',
    linea: '53…Txb3 54.axb3 a2',
    gana: true,
    valor: '+5,7',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2YJBp de la base abierta de Lichess (CC0), rating 1252. Stockfish 16 a profundidad 18: Txb3 es la mejor (+5,7) y la segunda queda en 0,0.',
  },
  {
    n: 77,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1ABiI',
    tema: 'alfilcaballo',
    lichess: '1ABiI',
    rating: 1528,
    elo: 748,
    juegan: 'w',
    fen: '8/8/4pkp1/p1P1N3/P3K2b/8/8/8 w - - 0 47',
    ultima: 'Axh4',
    marca: ['e1', 'h4'],
    solucion: { from: 'c5', to: 'c6' },
    primera: 'c6',
    linea: '47.c6 Ag3 48.c7 Axe5 49.c8=D',
    gana: true,
    valor: '+5,5',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1ABiI de la base abierta de Lichess (CC0), rating 1528. Stockfish 16 a profundidad 18: c6 es la mejor (+5,5) y la segunda queda en 0,0.',
  },
  {
    n: 78,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_20YMB',
    tema: 'alfiles',
    lichess: '20YMB',
    rating: 1543,
    elo: 763,
    juegan: 'b',
    fen: '8/5k2/4p1p1/p3P1Pp/1p1P3P/1P3B1b/5K2/8 b - - 0 45',
    ultima: 'Axf3',
    marca: ['c6', 'f3'],
    solucion: { from: 'a5', to: 'a4' },
    primera: 'a4',
    linea: '45…a4 46.bxa4 b3 47.a5 b2',
    gana: true,
    valor: '+4,4',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 20YMB de la base abierta de Lichess (CC0), rating 1543. Stockfish 16 a profundidad 18: a4 es la mejor (+4,4) y la segunda queda en -0,1.',
  },
  {
    n: 79,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1RLkb',
    tema: 'alfiles',
    lichess: '1RLkb',
    rating: 1672,
    elo: 892,
    juegan: 'b',
    fen: '8/8/8/1P1K1p2/4Pk1p/3B1b2/7P/8 b - - 0 38',
    ultima: 'b5',
    marca: ['b4', 'b5'],
    solucion: { from: 'f5', to: 'e4' },
    primera: 'fxe4',
    linea: '38…fxe4 39.Af1 e3+ 40.Rc5 e2 41.Axe2 Axe2',
    gana: true,
    valor: '+4,7',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1RLkb de la base abierta de Lichess (CC0), rating 1672. Stockfish 16 a profundidad 18: fxe4 es la mejor (+4,7) y la segunda queda en 0,0.',
  },
  {
    n: 80,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_1y3KM',
    tema: 'alfilcaballo',
    lichess: '1y3KM',
    rating: 1753,
    elo: 973,
    juegan: 'w',
    fen: '8/2n3pp/pB2kp2/P7/4PP2/2p3KP/5P2/8 w - - 1 33',
    ultima: 'Cc7',
    marca: ['d5', 'c7'],
    solucion: { from: 'b6', to: 'c7' },
    primera: 'Axc7',
    linea: '33.Axc7 c2 34.f5+ Re7 35.Af4',
    gana: true,
    valor: '+3,8',
    pista: 'Alfil contra caballo: decide quién tiene peones en los dos flancos.',
    explica: 'Es un despeje: la pieza se aparta para abrirle la línea o la casilla a otra.',
    comprobado: 'Ejercicio 1y3KM de la base abierta de Lichess (CC0), rating 1753. Stockfish 16 a profundidad 18: Axc7 es la mejor (+3,8) y la segunda queda en -1,8.',
  },
  {
    n: 81,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_0Lmp0',
    tema: 'torres',
    lichess: '0Lmp0',
    rating: 1795,
    elo: 1015,
    juegan: 'b',
    fen: '3r2k1/7p/4K3/3P4/1p3P1P/3R4/1r6/4R3 b - - 3 40',
    ultima: 'Re6',
    marca: ['e5', 'e6'],
    solucion: { from: 'd8', to: 'e8' },
    primera: 'Te8+',
    linea: '40…Te8+ 41.Rf6 Txe1 42.d6 Te8 43.Tg3+ Rf8',
    gana: true,
    valor: '+4,4',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 0Lmp0 de la base abierta de Lichess (CC0), rating 1795. Stockfish 16 a profundidad 18: Te8+ es la mejor (+4,4) y la segunda queda en -1,6.',
  },
  {
    n: 82,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_0hFtR',
    tema: 'alfiles',
    lichess: '0hFtR',
    rating: 2278,
    elo: 1498,
    juegan: 'w',
    fen: '8/8/4pp1k/3p3P/3PbP2/5BK1/8/8 w - - 3 51',
    ultima: 'Ae4',
    marca: ['f5', 'e4'],
    solucion: { from: 'f3', to: 'e4' },
    primera: 'Axe4',
    linea: '51.Axe4 dxe4 52.f5 Rxh5 53.fxe6 Rg6 54.d5 f5 55.d6',
    gana: true,
    valor: '+4,5',
    pista: 'En los finales de alfiles, las casillas del color de tu alfil son tuyas.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0hFtR de la base abierta de Lichess (CC0), rating 2278. Stockfish 16 a profundidad 18: Axe4 es la mejor (+4,5) y la segunda queda en 0,0.',
  },
  {
    n: 83,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'ig_13B14',
    tema: 'torres',
    lichess: '13B14',
    rating: 2309,
    elo: 1529,
    juegan: 'b',
    fen: '8/8/7p/4k1p1/6P1/p2K2P1/P1R4r/8 b - - 0 46',
    ultima: 'Txc2',
    marca: ['c7', 'c2'],
    solucion: { from: 'h2', to: 'c2' },
    primera: 'Txc2',
    linea: '46…Txc2 47.Rxc2 Re4 48.Rb3 Rf3 49.Rxa3 Rxg4 50.Rb3 h5 51.a4 h4 52.gxh4 gxh4 53.a5 h3',
    gana: true,
    valor: '+4,3',
    pista: 'En los finales de torre manda la actividad: torre y rey activos.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 13B14 de la base abierta de Lichess (CC0), rating 2309. Stockfish 16 a profundidad 18: Txc2 es la mejor (+4,3) y la segunda queda en +0,2.',
  },
  {
    n: 84,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2vIkr',
    tema: 'patrones',
    lichess: '2vIkr',
    rating: 1327,
    elo: 547,
    juegan: 'b',
    fen: '6k1/1pp3rp/p2p1r2/3PpP2/5np1/2P1QB2/PP3P1K/R5R1 b - - 0 30',
    ultima: 'Rxh2',
    marca: ['h1', 'h2'],
    solucion: { from: 'f6', to: 'h6' },
    primera: 'Th6+',
    linea: '30…Th6+ 31.Rg3 Th3#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es mate en dos: la primera jugada no deja defensa.',
    comprobado: 'Ejercicio 2vIkr de la base abierta de Lichess (CC0), rating 1327. Stockfish 16 a profundidad 18: Th6+ es la mejor (mate en 2) y la segunda queda en -3,4.',
  },
  {
    n: 85,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_13M4a',
    tema: 'mayores',
    lichess: '13M4a',
    rating: 1450,
    elo: 670,
    juegan: 'w',
    fen: '2rq1rk1/5p2/2n1p2Q/pp1p4/3Pn3/2P2NPP/PP4P1/R3R1K1 w - - 1 19',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'e1', to: 'e4' },
    primera: 'Txe4',
    linea: '19.Txe4 dxe4 20.Cg5 Dxg5 21.Dxg5+',
    gana: true,
    valor: '+5,9',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 13M4a de la base abierta de Lichess (CC0), rating 1450. Stockfish 16 a profundidad 18: Txe4 es la mejor (+5,9) y la segunda queda en -0,8.',
  },
  {
    n: 86,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2vk7U',
    tema: 'concentracion',
    lichess: '2vk7U',
    rating: 1493,
    elo: 713,
    juegan: 'w',
    fen: '3r1rk1/pp3pp1/1n2q2p/2p1P3/7P/5N2/PP1Q1PP1/1K1R3R w - - 2 19',
    ultima: 'Tad8',
    marca: ['a8', 'd8'],
    solucion: { from: 'd2', to: 'd8' },
    primera: 'Dxd8',
    linea: '19.Dxd8 Txd8 20.Txd8+ Rh7 21.Cg5+ hxg5 22.hxg5+ Rg6 23.Td6',
    gana: true,
    valor: '+4,8',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2vk7U de la base abierta de Lichess (CC0), rating 1493. Stockfish 16 a profundidad 18: Dxd8 es la mejor (+4,8) y la segunda queda en -1,1.',
  },
  {
    n: 87,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1v2LH',
    tema: 'h7',
    lichess: '1v2LH',
    rating: 1551,
    elo: 771,
    juegan: 'b',
    fen: 'r4rk1/1Qb1qpp1/p3p2p/8/1n6/1PN2N2/PB1P1PPP/2R1R1K1 b - - 0 20',
    ultima: 'Dxb7',
    marca: ['e4', 'b7'],
    solucion: { from: 'c7', to: 'h2' },
    primera: 'Axh2+',
    linea: '20…Axh2+ 21.Rxh2 Dxb7',
    gana: true,
    valor: '+4,4',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 1v2LH de la base abierta de Lichess (CC0), rating 1551. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+4,4) y la segunda queda en -3,5.',
  },
  {
    n: 88,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1JwhQ',
    tema: 'demolicion',
    lichess: '1JwhQ',
    rating: 1572,
    elo: 792,
    juegan: 'b',
    fen: '2k3rr/pp3p1p/5p2/PB1pq3/1P3P2/2P4b/3Q2PP/R4RK1 b - f3 0 22',
    ultima: 'f4',
    marca: ['f2', 'f4'],
    solucion: { from: 'g8', to: 'g2' },
    primera: 'Txg2+',
    linea: '22…Txg2+ 23.Dxg2 De3+ 24.Tf2 Axg2',
    gana: true,
    valor: '+5,8',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1JwhQ de la base abierta de Lichess (CC0), rating 1572. Stockfish 16 a profundidad 18: Txg2+ es la mejor (+5,8) y la segunda queda en -2,1.',
  },
  {
    n: 89,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_29Ejv',
    tema: 'octava',
    lichess: '29Ejv',
    rating: 1600,
    elo: 820,
    juegan: 'w',
    fen: '5rk1/p2R1ppp/Bp6/4p3/4P3/1Q2KP1q/P5r1/8 w - - 0 32',
    ultima: 'e5',
    marca: ['e6', 'e5'],
    solucion: { from: 'b3', to: 'f7' },
    primera: 'Dxf7+',
    linea: '32.Dxf7+ Txf7 33.Td8+ Tf8 34.Ac4+ De6 35.Axe6+ Rh8 36.Txf8#',
    gana: true,
    valor: 'mate en 5',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 29Ejv de la base abierta de Lichess (CC0), rating 1600. Stockfish 16 a profundidad 18: Dxf7+ es la mejor (mate en 5) y la segunda queda en -7,4.',
  },
  {
    n: 90,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_29Jkd',
    tema: 'reycentro',
    lichess: '29Jkd',
    rating: 1606,
    elo: 826,
    juegan: 'w',
    fen: 'rn1qk2r/pp4pp/3bp3/2p1n3/5B2/8/PP3PPP/RN1QK1NR w KQkq - 0 12',
    ultima: 'fxe6',
    marca: ['f7', 'e6'],
    solucion: { from: 'f4', to: 'e5' },
    primera: 'Axe5',
    linea: '12.Axe5 Axe5 13.Dh5+ g6 14.Dxe5',
    gana: true,
    valor: '+4,1',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 29Jkd de la base abierta de Lichess (CC0), rating 1606. Stockfish 16 a profundidad 18: Axe5 es la mejor (+4,1) y la segunda queda en -0,8.',
  },
  {
    n: 91,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1XhVl',
    tema: 'f7',
    lichess: '1XhVl',
    rating: 1635,
    elo: 855,
    juegan: 'w',
    fen: '4k1BQ/pbq2p2/4p3/3pP3/1b3P2/4P1P1/PP6/1K6 w - - 5 31',
    ultima: 'Re8',
    marca: ['f8', 'e8'],
    solucion: { from: 'g8', to: 'f7' },
    primera: 'Axf7+',
    linea: '31.Axf7+ Rxf7 32.Dh7+ Rf8 33.Dxc7',
    gana: true,
    valor: '+5,9',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es un jaque doble: el rey tiene que moverse y no alcanza a tapar nada.',
    comprobado: 'Ejercicio 1XhVl de la base abierta de Lichess (CC0), rating 1635. Stockfish 16 a profundidad 18: Axf7+ es la mejor (+5,9) y la segunda queda en -1,5.',
  },
  {
    n: 92,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1Sebl',
    tema: 'concentracion',
    lichess: '1Sebl',
    rating: 1653,
    elo: 873,
    juegan: 'w',
    fen: 'r2q1rk1/1p2bppp/p1np2b1/4p3/4n1PN/1BN1B2P/PP2QP2/R2R2K1 w - - 0 17',
    ultima: 'Cxe4',
    marca: ['f6', 'e4'],
    solucion: { from: 'h4', to: 'g6' },
    primera: 'Cxg6',
    linea: '17.Cxg6 Cxc3 18.Cxe7+ Cxe7 19.bxc3',
    gana: true,
    valor: '+4,1',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 1Sebl de la base abierta de Lichess (CC0), rating 1653. Stockfish 16 a profundidad 18: Cxg6 es la mejor (+4,1) y la segunda queda en -1,2.',
  },
  {
    n: 93,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1i7Lv',
    tema: 'reycentro',
    lichess: '1i7Lv',
    rating: 1674,
    elo: 894,
    juegan: 'w',
    fen: '4rk2/pb4q1/1p5Q/2b5/8/4N3/PP3PPP/3R2K1 w - - 1 26',
    ultima: 'Dg7',
    marca: ['e5', 'g7'],
    solucion: { from: 'h6', to: 'g7' },
    primera: 'Dxg7+',
    linea: '26.Dxg7+ Rxg7 27.Td7+ Rf8 28.Txb7',
    gana: true,
    valor: '+3,8',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1i7Lv de la base abierta de Lichess (CC0), rating 1674. Stockfish 16 a profundidad 18: Dxg7+ es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 94,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1VToK',
    tema: 'mayores',
    lichess: '1VToK',
    rating: 1699,
    elo: 919,
    juegan: 'w',
    fen: '2r2rk1/ppqnbp1p/4p1p1/2pp2P1/1P2nP2/P2BPR1Q/1BPP3P/R5K1 w - - 1 18',
    ultima: 'Ce4',
    marca: ['f6', 'e4'],
    solucion: { from: 'h3', to: 'h7' },
    primera: 'Dxh7+',
    linea: '18.Dxh7+ Rxh7 19.Th3+ Rg8 20.Th8#',
    gana: true,
    valor: 'mate en 3',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 1VToK de la base abierta de Lichess (CC0), rating 1699. Stockfish 16 a profundidad 18: Dxh7+ es la mejor (mate en 3) y la segunda queda en +0,0.',
  },
  {
    n: 95,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2ciHU',
    tema: 'patrones',
    lichess: '2ciHU',
    rating: 1699,
    elo: 919,
    juegan: 'w',
    fen: 'r2q1bnr/ppp1k1pp/8/4p3/8/1B3b2/PPPP2PP/RNB1Q1K1 w - - 0 12',
    ultima: 'Axf3',
    marca: ['g4', 'f3'],
    solucion: { from: 'e1', to: 'e5' },
    primera: 'Dxe5+',
    linea: '12.Dxe5+ Rd7 13.De6#',
    gana: true,
    valor: 'mate en 2',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es mate en dos: la primera jugada no deja defensa.',
    comprobado: 'Ejercicio 2ciHU de la base abierta de Lichess (CC0), rating 1699. Stockfish 16 a profundidad 18: Dxe5+ es la mejor (mate en 2) y la segunda queda en -0,9.',
  },
  {
    n: 96,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2QOON',
    tema: 'octava',
    lichess: '2QOON',
    rating: 1839,
    elo: 1059,
    juegan: 'w',
    fen: '5rk1/ppR2ppp/7r/BP6/3Pp1n1/P3PbPq/Q4P2/4RBK1 w - - 0 26',
    ultima: 'Dxh3',
    marca: ['h5', 'h3'],
    solucion: { from: 'a2', to: 'f7' },
    primera: 'Dxf7+',
    linea: '26.Dxf7+ Txf7 27.Tc8+ Tf8 28.Ac4+ Te6 29.Axe6+ Rh8 30.Txf8#',
    gana: true,
    valor: 'mate en 5',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 2QOON de la base abierta de Lichess (CC0), rating 1839. Stockfish 16 a profundidad 18: Dxf7+ es la mejor (mate en 5) y la segunda queda en recibe mate en 6.',
  },
  {
    n: 97,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2347F',
    tema: 'h7',
    lichess: '2347F',
    rating: 1907,
    elo: 1127,
    juegan: 'w',
    fen: 'r1bq1rk1/pp2Bppp/2n1p3/3p4/3P4/2NB4/PPP2nPP/R2QK2R w KQ - 0 11',
    ultima: 'Cxf2',
    marca: ['g4', 'f2'],
    solucion: { from: 'd3', to: 'h7' },
    primera: 'Axh7+',
    linea: '11.Axh7+ Rxh7 12.Dh5+ Rg8 13.Axd8',
    gana: true,
    valor: '+4,5',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2347F de la base abierta de Lichess (CC0), rating 1907. Stockfish 16 a profundidad 18: Axh7+ es la mejor (+4,5) y la segunda queda en -1,4.',
  },
  {
    n: 98,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_0NVfF',
    tema: 'demolicion',
    lichess: '0NVfF',
    rating: 1951,
    elo: 1171,
    juegan: 'w',
    fen: '2r5/6pk/5p1p/2pQpP1P/1qPpP3/6RK/6P1/8 w - - 6 46',
    ultima: 'Tc8',
    marca: ['g8', 'c8'],
    solucion: { from: 'g3', to: 'g7' },
    primera: 'Txg7+',
    linea: '46.Txg7+ Rxg7 47.Dd7+ Rf8 48.Dxc8+',
    gana: true,
    valor: '+3,9',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 0NVfF de la base abierta de Lichess (CC0), rating 1951. Stockfish 16 a profundidad 18: Txg7+ es la mejor (+3,9) y la segunda queda en -3,0.',
  },
  {
    n: 99,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1EwzF',
    tema: 'f7',
    lichess: '1EwzF',
    rating: 1994,
    elo: 1214,
    juegan: 'w',
    fen: 'r3kr2/p4p2/1p2pR2/3bP1Q1/3Pq3/2P5/P5PP/5RK1 w q - 1 29',
    ultima: 'Ad5',
    marca: ['b7', 'd5'],
    solucion: { from: 'f6', to: 'f7' },
    primera: 'Txf7',
    linea: '29.Txf7 Txf7 30.Dg8+ Rd7 31.Txf7+ Rc6 32.Dxa8+',
    gana: true,
    valor: '+3,5',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 1EwzF de la base abierta de Lichess (CC0), rating 1994. Stockfish 16 a profundidad 18: Txf7 es la mejor (+3,5) y la segunda queda en -2,6.',
  },
  {
    n: 100,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2wKNb',
    tema: 'demolicion',
    lichess: '2wKNb',
    rating: 2059,
    elo: 1279,
    juegan: 'w',
    fen: '5r1k/2p1qpp1/1p1p1b1p/p6R/2P1B1Q1/1P2P1P1/P4PP1/6K1 w - - 7 40',
    ultima: 'Tf8',
    marca: ['d8', 'f8'],
    solucion: { from: 'h5', to: 'h6' },
    primera: 'Txh6+',
    linea: '40.Txh6+ gxh6 41.Df5 Dxe4 42.Dxe4',
    gana: true,
    valor: '+4,5',
    pista: 'Los peones del enroque son el techo del rey. Romper uno puede valer una pieza.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 2wKNb de la base abierta de Lichess (CC0), rating 2059. Stockfish 16 a profundidad 18: Txh6+ es la mejor (+4,5) y la segunda queda en +0,1.',
  },
  {
    n: 101,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1Sw6a',
    tema: 'f7',
    lichess: '1Sw6a',
    rating: 2069,
    elo: 1289,
    juegan: 'w',
    fen: 'rnbqk1nr/1p3p2/p1pbp1pp/6N1/2pPP2Q/6P1/PP3PBP/RNB2RK1 w kq - 2 11',
    ultima: 'Cg8',
    marca: ['e7', 'g8'],
    solucion: { from: 'g5', to: 'f7' },
    primera: 'Cxf7',
    linea: '11.Cxf7 Dxh4 12.Cxd6+ Rd7 13.gxh4',
    gana: true,
    valor: '+3,7',
    pista: 'La casilla f7 (f2) solo la defiende el rey. Es el punto más débil al empezar.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1Sw6a de la base abierta de Lichess (CC0), rating 2069. Stockfish 16 a profundidad 18: Cxf7 es la mejor (+3,7) y la segunda queda en -0,1.',
  },
  {
    n: 102,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2ufXl',
    tema: 'octava',
    lichess: '2ufXl',
    rating: 2149,
    elo: 1369,
    juegan: 'b',
    fen: '5rk1/p5pp/4p3/2P1P3/2qp4/1Rn5/PQ1B2PP/4R1K1 b - - 2 28',
    ultima: 'Ad2',
    marca: ['f4', 'd2'],
    solucion: { from: 'c4', to: 'f1' },
    primera: 'Df1+',
    linea: '28…Df1+ 29.Txf1 Ce2+ 30.Rh1 Txf1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'El rey no tiene casillas de escape: mira su última fila.',
    explica: 'El golpe va a la última fila, donde el rey no tiene salida.',
    comprobado: 'Ejercicio 2ufXl de la base abierta de Lichess (CC0), rating 2149. Stockfish 16 a profundidad 18: Df1+ es la mejor (mate en 3) y la segunda queda en -4,7.',
  },
  {
    n: 103,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2rUgy',
    tema: 'h7',
    lichess: '2rUgy',
    rating: 2188,
    elo: 1408,
    juegan: 'b',
    fen: 'r1bqk3/ppp2pp1/2nb4/8/2P3nP/2N5/PP2PPBP/R1BQ1RK1 b q - 0 11',
    ultima: 'gxh4',
    marca: ['g3', 'h4'],
    solucion: { from: 'd6', to: 'h2' },
    primera: 'Axh2+',
    linea: '11…Axh2+ 12.Rh1 Dxh4 13.Ag5 Dxg5',
    gana: true,
    valor: '+5,8',
    pista: 'El peón de h7 (h2) es el único defensor de esa casilla. ¿Qué pasa si se lo quitas con jaque?',
    explica: 'Hay una jugada intermedia: antes de lo obvio, algo más fuerte.',
    comprobado: 'Ejercicio 2rUgy de la base abierta de Lichess (CC0), rating 2188. Stockfish 16 a profundidad 18: Axh2+ es la mejor (+5,8) y la segunda queda en -0,3.',
  },
  {
    n: 104,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_00dt1',
    tema: 'patrones',
    lichess: '00dt1',
    rating: 2234,
    elo: 1454,
    juegan: 'b',
    fen: 'Q7/8/3B4/2p5/1rkn4/K7/8/8 b - - 2 54',
    ultima: 'Ra3',
    marca: ['a4', 'a3'],
    solucion: { from: 'd4', to: 'b5' },
    primera: 'Cb5+',
    linea: '54…Cb5+ 55.Ra2 Cc3+ 56.Ra1 Tb1#',
    gana: true,
    valor: 'mate en 3',
    pista: 'Hay un mate de dibujo conocido. Busca el jaque que lo deja armado.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 00dt1 de la base abierta de Lichess (CC0), rating 2234. Stockfish 16 a profundidad 18: Cb5+ es la mejor (mate en 3) y la segunda queda en -2,5.',
  },
  {
    n: 105,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2e0q2',
    tema: 'mayores',
    lichess: '2e0q2',
    rating: 2312,
    elo: 1532,
    juegan: 'b',
    fen: 'r4k2/pp4p1/3p4/4p1q1/3nB1pr/P2P4/1PP2PP1/R1BQ1RK1 b - - 0 18',
    ultima: 'd3',
    marca: ['d2', 'd3'],
    solucion: { from: 'g5', to: 'h5' },
    primera: 'Dh5',
    linea: '18…Dh5 19.f4 Th1+ 20.Rf2 g3+ 21.Re3 Dxd1 22.Txd1 Txd1',
    gana: true,
    valor: '+4,4',
    pista: 'La dama y las torres son las que dan el mate: ¿por dónde entran?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2e0q2 de la base abierta de Lichess (CC0), rating 2312. Stockfish 16 a profundidad 18: Dh5 es la mejor (+4,4) y la segunda queda en -4,2.',
  },
  {
    n: 106,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_1kjIx',
    tema: 'reycentro',
    lichess: '1kjIx',
    rating: 2317,
    elo: 1537,
    juegan: 'w',
    fen: '2r4r/2Qbk1p1/p5qp/1p1PB3/8/8/PP4PP/5R1K w - - 1 24',
    ultima: 'Tac8',
    marca: ['a8', 'c8'],
    solucion: { from: 'e5', to: 'd6' },
    primera: 'Ad6+',
    linea: '24.Ad6+ Dxd6 25.Te1+ De6 26.Txe6+',
    gana: true,
    valor: '+4,9',
    pista: 'El rey rival sigue en el centro: abre líneas antes de que se esconda.',
    explica: 'Todo gira en torno a una clavada: la pieza clavada no puede defender.',
    comprobado: 'Ejercicio 1kjIx de la base abierta de Lichess (CC0), rating 2317. Stockfish 16 a profundidad 18: Ad6+ es la mejor (+4,9) y la segunda queda en -3,2.',
  },
  {
    n: 107,
    uso: 'mixto',
    capitulo: 0,
    id: 'ig_2vQn5',
    tema: 'concentracion',
    lichess: '2vQn5',
    rating: 2342,
    elo: 1562,
    juegan: 'b',
    fen: 'r7/p4pk1/3p1qp1/2pP4/4Pn1r/P5Q1/4NPP1/1R1BR1K1 b - - 4 31',
    ultima: 'Dg3',
    marca: ['g4', 'g3'],
    solucion: { from: 'a8', to: 'h8' },
    primera: 'Tah8',
    linea: '31…Tah8 32.Rf1 Cxe2 33.Rxe2 Txe4+',
    gana: true,
    valor: '+5,4',
    pista: 'Cuenta atacantes y defensores alrededor del rey: si sobran los tuyos, hay algo.',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 2vQn5 de la base abierta de Lichess (CC0), rating 2342. Stockfish 16 a profundidad 18: Tah8 es la mejor (+5,4) y la segunda queda en 0,0.',
  },
];
