/* ===== Las posiciones de «Ganar con poco», de Oscar Angulo Cubero =====
 *
 * GENERADO por herramientas/ganar-con-poco-generar.js — no se edita a mano.
 *
 * 97 posiciones de la base abierta de Lichess (CC0), comprobadas con
 * Stockfish: 25 ejemplos (uno por lección, los mismos del curso),
 * 48 ejercicios por capítulo y 24 mixtos. Lo usa el libro
 * (herramientas/ganar-con-poco-pdf.js). Vive detrás del candado de
 * material/: trae las respuestas.
 */
window.GANAR_CON_POCO = {
  TITULO: 'Ganar con poco',
  AUTOR: 'Oscar Angulo Cubero',
  POR_CAPITULO: 8,
  MIXTOS: 24,
  CAPITULOS: [{ n: 1, titulo: 'Ver lo que no se ve', temas: ['quietMove', 'trappedPiece', 'defensiveMove'] }, { n: 2, titulo: 'Piezas buenas y piezas malas', temas: ['trappedPiece', 'bishopEndgame', 'knightEndgame', 'rookEndgame'] }, { n: 3, titulo: 'Los peones deciden', temas: ['advancedPawn', 'promotion', 'pawnEndgame'] }, { n: 4, titulo: 'Cambiar para ganar', temas: ['pawnEndgame', 'zugzwang', 'rookEndgame'] }, { n: 5, titulo: 'La técnica en el final', temas: ['rookEndgame', 'bishopEndgame', 'knightEndgame', 'queenEndgame'] }, { n: 6, titulo: 'Paciencia y defensa', temas: ['quietMove', 'defensiveMove', 'zugzwang'] }, { n: 7, titulo: 'Las partidas del libro', temas: [] }, { n: 8, titulo: 'Tu propio método', temas: [] }],
};
window.GANAR_CON_POCO_ITEMS = [
  {
    n: 1,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 1,
    id: 'gp_17uHj',
    tema: 'quietMove',
    lichess: '17uHj',
    rating: 1345,
    elo: 565,
    juegan: 'b',
    fen: '4r3/1ppR4/p5pk/7p/3P4/6QP/PPP3PK/5q2 b - - 6 32',
    ultima: 'Dg3',
    marca: ['b3', 'g3'],
    solucion: { from: 'e8', to: 'e1' },
    primera: 'Te1',
    linea: '32…Te1 33.Dxe1 Dxe1',
    gana: true,
    valor: '+4,4',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 17uHj de la base abierta de Lichess (CC0), rating 1345. Stockfish 16 a profundidad 18: Te1 es la mejor (+4,4) y la segunda queda en -1,9.',
  },
  {
    n: 2,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 2,
    id: 'gp_2mRC9',
    tema: 'trappedPiece',
    lichess: '2mRC9',
    rating: 1448,
    elo: 668,
    juegan: 'w',
    fen: 'r3k2r/ppbn1ppp/2p1p3/5b2/4N2q/3P1B1P/PPP1QPP1/R1B2RK1 w kq - 2 15',
    ultima: 'Ac7',
    marca: ['d6', 'c7'],
    solucion: { from: 'c1', to: 'g5' },
    primera: 'Ag5',
    linea: '15.Ag5 Axe4 16.Axh4',
    gana: true,
    valor: '+5,5',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 2mRC9 de la base abierta de Lichess (CC0), rating 1448. Stockfish 16 a profundidad 18: Ag5 es la mejor (+5,5) y la segunda queda en +0,4.',
  },
  {
    n: 3,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 3,
    id: 'gp_07wdS',
    tema: 'quietMove',
    lichess: '07wdS',
    rating: 1613,
    elo: 833,
    juegan: 'b',
    fen: '5r1k/1p3pp1/p3b3/Q7/4q3/P2pB2P/1P1R1PP1/6K1 b - - 0 25',
    ultima: 'Txd2',
    marca: ['d1', 'd2'],
    solucion: { from: 'e6', to: 'd5' },
    primera: 'Ad5',
    linea: '25…Ad5 26.f3 Dxe3+',
    gana: true,
    valor: '+5,7',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 07wdS de la base abierta de Lichess (CC0), rating 1613. Stockfish 16 a profundidad 18: Ad5 es la mejor (+5,7) y la segunda queda en +0,1.',
  },
  {
    n: 4,
    uso: 'ejemplo',
    capitulo: 1,
    leccion: 4,
    id: 'gp_0HbWu',
    tema: 'defensiveMove',
    lichess: '0HbWu',
    rating: 1563,
    elo: 783,
    juegan: 'w',
    fen: '8/8/4nkp1/1N1R4/p5K1/r3p1P1/7P/8 w - - 0 49',
    ultima: 'e3',
    marca: ['e4', 'e3'],
    solucion: { from: 'b5', to: 'a3' },
    primera: 'Cxa3',
    linea: '49.Cxa3 e2 50.Cc2',
    gana: true,
    valor: '+5,1',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 0HbWu de la base abierta de Lichess (CC0), rating 1563. Stockfish 16 a profundidad 18: Cxa3 es la mejor (+5,1) y la segunda queda en -3,8.',
  },
  {
    n: 5,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 5,
    id: 'gp_2jElr',
    tema: 'trappedPiece',
    lichess: '2jElr',
    rating: 1602,
    elo: 822,
    juegan: 'b',
    fen: '3r3k/5rp1/7p/1pB2p2/1Pp1pR2/P4P2/6PP/4R1K1 b - - 0 39',
    ultima: 'f3',
    marca: ['f2', 'f3'],
    solucion: { from: 'g7', to: 'g5' },
    primera: 'g5',
    linea: '39…g5 40.Txf5 Txf5',
    gana: true,
    valor: '+3,2',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 2jElr de la base abierta de Lichess (CC0), rating 1602. Stockfish 16 a profundidad 18: g5 es la mejor (+3,2) y la segunda queda en -3,0.',
  },
  {
    n: 6,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 6,
    id: 'gp_1kH80',
    tema: 'bishopEndgame',
    lichess: '1kH80',
    rating: 1614,
    elo: 834,
    juegan: 'b',
    fen: '4b1B1/4k3/6p1/p3KpP1/p7/2P5/2P2P2/8 b - - 5 40',
    ultima: 'Re5',
    marca: ['f4', 'e5'],
    solucion: { from: 'e8', to: 'f7' },
    primera: 'Af7',
    linea: '40…Af7 41.Axf7 Rxf7',
    gana: true,
    valor: '+4,7',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 1kH80 de la base abierta de Lichess (CC0), rating 1614. Stockfish 16 a profundidad 18: Af7 es la mejor (+4,7) y la segunda queda en +0,1.',
  },
  {
    n: 7,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 7,
    id: 'gp_274PM',
    tema: 'knightEndgame',
    lichess: '274PM',
    rating: 1572,
    elo: 792,
    juegan: 'w',
    fen: '8/2N5/2n3k1/P5pp/8/1P6/8/6K1 w - - 1 51',
    ultima: 'Cc6',
    marca: ['b4', 'c6'],
    solucion: { from: 'a5', to: 'a6' },
    primera: 'a6',
    linea: '51.a6 Rf5 52.b4 Cxb4 53.a7',
    gana: true,
    valor: '+4,4',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 274PM de la base abierta de Lichess (CC0), rating 1572. Stockfish 16 a profundidad 18: a6 es la mejor (+4,4) y la segunda queda en -0,1.',
  },
  {
    n: 8,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 8,
    id: 'gp_2V4SF',
    tema: 'rookEndgame',
    lichess: '2V4SF',
    rating: 1509,
    elo: 729,
    juegan: 'w',
    fen: '8/7p/K1k1p1p1/P1r1R3/8/8/8/8 w - - 0 42',
    ultima: 'Txc5',
    marca: ['c2', 'c5'],
    solucion: { from: 'e5', to: 'c5' },
    primera: 'Txc5+',
    linea: '42.Txc5+ Rxc5 43.Rb7 e5 44.a6 e4 45.a7 e3 46.a8=D',
    gana: true,
    valor: '+4,7',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2V4SF de la base abierta de Lichess (CC0), rating 1509. Stockfish 16 a profundidad 18: Txc5+ es la mejor (+4,7) y la segunda queda en 0,0.',
  },
  {
    n: 9,
    uso: 'ejemplo',
    capitulo: 2,
    leccion: 9,
    id: 'gp_38yIr',
    tema: 'pawnEndgame',
    lichess: '38yIr',
    rating: 1451,
    elo: 671,
    juegan: 'b',
    fen: '8/8/p1p3p1/P4p2/1P3P1K/2k5/6PP/8 b - - 1 49',
    ultima: 'Rh4',
    marca: ['g3', 'h4'],
    solucion: { from: 'c3', to: 'b4' },
    primera: 'Rxb4',
    linea: '49…Rxb4 50.Rg5 c5 51.g4 c4',
    gana: true,
    valor: '+4,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 38yIr de la base abierta de Lichess (CC0), rating 1451. Stockfish 16 a profundidad 18: Rxb4 es la mejor (+4,0) y la segunda queda en -3,0.',
  },
  {
    n: 10,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 10,
    id: 'gp_0r1nZ',
    tema: 'advancedPawn',
    lichess: '0r1nZ',
    rating: 1488,
    elo: 708,
    juegan: 'b',
    fen: '8/8/6p1/PK1N4/6bP/1p6/k7/8 b - - 0 57',
    ultima: 'a5',
    marca: ['a4', 'a5'],
    solucion: { from: 'b3', to: 'b2' },
    primera: 'b2',
    linea: '57…b2 58.Cc3+ Rb3',
    gana: true,
    valor: '+4,8',
    pista: 'Un peón pasado es una ventaja que crece sola: ¿cómo lo empujas o lo aprovechas?',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0r1nZ de la base abierta de Lichess (CC0), rating 1488. Stockfish 16 a profundidad 18: b2 es la mejor (+4,8) y la segunda queda en +1,3.',
  },
  {
    n: 11,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 11,
    id: 'gp_32LjT',
    tema: 'promotion',
    lichess: '32LjT',
    rating: 1498,
    elo: 718,
    juegan: 'w',
    fen: 'r2k1r2/1pp2Ppp/p1n5/3p4/3P4/2P4P/P1P3P1/4RRK1 w - - 1 19',
    ultima: 'Tf8',
    marca: ['h8', 'f8'],
    solucion: { from: 'e1', to: 'e8' },
    primera: 'Te8+',
    linea: '19.Te8+ Txe8 20.f8=D Txf8 21.Txf8+ Rd7 22.Txa8',
    gana: true,
    valor: '+3,3',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'Es una enfilada: la pieza de adelante se va y cae la de atrás.',
    comprobado: 'Ejercicio 32LjT de la base abierta de Lichess (CC0), rating 1498. Stockfish 16 a profundidad 18: Te8+ es la mejor (+3,3) y la segunda queda en -3,3.',
  },
  {
    n: 12,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 12,
    id: 'gp_14nEZ',
    tema: 'pawnEndgame',
    lichess: '14nEZ',
    rating: 1520,
    elo: 740,
    juegan: 'w',
    fen: '8/p7/2k3pp/2P2p2/P2K3P/8/6P1/8 w - - 0 34',
    ultima: 'h6',
    marca: ['h7', 'h6'],
    solucion: { from: 'd4', to: 'e5' },
    primera: 'Re5',
    linea: '34.Re5 Rxc5 35.Rf6',
    gana: true,
    valor: '+5,5',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: '',
    comprobado: 'Ejercicio 14nEZ de la base abierta de Lichess (CC0), rating 1520. Stockfish 16 a profundidad 18: Re5 es la mejor (+5,5) y la segunda queda en +0,0.',
  },
  {
    n: 13,
    uso: 'ejemplo',
    capitulo: 3,
    leccion: 13,
    id: 'gp_2cBgW',
    tema: 'quietMove',
    lichess: '2cBgW',
    rating: 1311,
    elo: 531,
    juegan: 'b',
    fen: '6k1/pp3pqp/8/3p2pP/PP2p1P1/4Pn2/4QP2/2R4K b - - 1 36',
    ultima: 'Tc1',
    marca: ['f1', 'c1'],
    solucion: { from: 'g7', to: 'e5' },
    primera: 'De5',
    linea: '36…De5 37.Dxf3 exf3 38.Tc8+ Rg7',
    gana: true,
    valor: '+6,3',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2cBgW de la base abierta de Lichess (CC0), rating 1311. Stockfish 16 a profundidad 18: De5 es la mejor (+6,3) y la segunda queda en 0,0.',
  },
  {
    n: 14,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 14,
    id: 'gp_2QgVs',
    tema: 'pawnEndgame',
    lichess: '2QgVs',
    rating: 1549,
    elo: 769,
    juegan: 'w',
    fen: '8/2k1p3/1p2P3/1Pp5/2P2PK1/7p/8/8 w - - 0 51',
    ultima: 'h3',
    marca: ['h4', 'h3'],
    solucion: { from: 'g4', to: 'h3' },
    primera: 'Rxh3',
    linea: '51.Rxh3 Rd6 52.f5 Re5 53.Rg4',
    gana: true,
    valor: '+4,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2QgVs de la base abierta de Lichess (CC0), rating 1549. Stockfish 16 a profundidad 18: Rxh3 es la mejor (+4,8) y la segunda queda en -0,2.',
  },
  {
    n: 15,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 15,
    id: 'gp_1qUzo',
    tema: 'pawnEndgame',
    lichess: '1qUzo',
    rating: 1578,
    elo: 798,
    juegan: 'b',
    fen: '8/8/8/p5p1/2Pk2P1/P7/2K5/8 b - - 2 53',
    ultima: 'Rc2',
    marca: ['d2', 'c2'],
    solucion: { from: 'd4', to: 'c4' },
    primera: 'Rxc4',
    linea: '53…Rxc4 54.Rb2 a4 55.Rc2 Rd4',
    gana: true,
    valor: '+5,5',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1qUzo de la base abierta de Lichess (CC0), rating 1578. Stockfish 16 a profundidad 18: Rxc4 es la mejor (+5,5) y la segunda queda en -0,0.',
  },
  {
    n: 16,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 16,
    id: 'gp_0oi5E',
    tema: 'rookEndgame',
    lichess: '0oi5E',
    rating: 1454,
    elo: 674,
    juegan: 'b',
    fen: '8/1pR2pr1/k6p/P2pK3/1P1P4/5P2/8/8 b - - 5 37',
    ultima: 'Re5',
    marca: ['f4', 'e5'],
    solucion: { from: 'f7', to: 'f6' },
    primera: 'f6+',
    linea: '37…f6+ 38.Rxf6 Txc7',
    gana: true,
    valor: '+4,0',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'Es un ataque a la descubierta: al moverse una pieza, se destapa otra.',
    comprobado: 'Ejercicio 0oi5E de la base abierta de Lichess (CC0), rating 1454. Stockfish 16 a profundidad 18: f6+ es la mejor (+4,0) y la segunda queda en -0,8.',
  },
  {
    n: 17,
    uso: 'ejemplo',
    capitulo: 4,
    leccion: 17,
    id: 'gp_0v3Rb',
    tema: 'zugzwang',
    lichess: '0v3Rb',
    rating: 1307,
    elo: 527,
    juegan: 'w',
    fen: '8/1p6/p1pk4/P4p1p/1P1P1P1P/2K5/8/8 w - - 3 37',
    ultima: 'Rd6',
    marca: ['e6', 'd6'],
    solucion: { from: 'c3', to: 'c4' },
    primera: 'Rc4',
    linea: '37.Rc4 Rd7 38.Rc5 Re6 39.Rb6 Rd6 40.Rxb7',
    gana: true,
    valor: '+4,0',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0v3Rb de la base abierta de Lichess (CC0), rating 1307. Stockfish 16 a profundidad 18: Rc4 es la mejor (+4,0) y la segunda queda en 0,0.',
  },
  {
    n: 18,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 18,
    id: 'gp_3HeX2',
    tema: 'rookEndgame',
    lichess: '3HeX2',
    rating: 1340,
    elo: 560,
    juegan: 'w',
    fen: 'R7/8/8/2p4p/2Pk3P/P4p2/3r1p2/5K2 w - - 2 36',
    ultima: 'Rd4',
    marca: ['e5', 'd4'],
    solucion: { from: 'a8', to: 'd8' },
    primera: 'Td8+',
    linea: '36.Td8+ Rc3 37.Txd2 Rxd2 38.a4 Rd3 39.a5 Rxc4 40.a6',
    gana: true,
    valor: '+4,1',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3HeX2 de la base abierta de Lichess (CC0), rating 1340. Stockfish 16 a profundidad 18: Td8+ es la mejor (+4,1) y la segunda queda en -2,6.',
  },
  {
    n: 19,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 19,
    id: 'gp_1dAvV',
    tema: 'bishopEndgame',
    lichess: '1dAvV',
    rating: 1298,
    elo: 518,
    juegan: 'w',
    fen: '8/3k1p2/5Pp1/5P2/p2K2bB/P7/8/8 w - - 0 49',
    ultima: 'Axg4',
    marca: ['d1', 'g4'],
    solucion: { from: 'f5', to: 'g6' },
    primera: 'fxg6',
    linea: '49.fxg6 fxg6 50.f7',
    gana: true,
    valor: '+5,9',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1dAvV de la base abierta de Lichess (CC0), rating 1298. Stockfish 16 a profundidad 18: fxg6 es la mejor (+5,9) y la segunda queda en -0,0.',
  },
  {
    n: 20,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 20,
    id: 'gp_1oIpG',
    tema: 'knightEndgame',
    lichess: '1oIpG',
    rating: 1447,
    elo: 667,
    juegan: 'w',
    fen: '8/4Pkp1/p2K4/1p1p4/4n3/2P3Np/PP6/8 w - - 2 42',
    ultima: 'Ce4+',
    marca: ['f6', 'e4'],
    solucion: { from: 'g3', to: 'e4' },
    primera: 'Cxe4',
    linea: '42.Cxe4 dxe4 43.Rd7',
    gana: true,
    valor: '+4,7',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1oIpG de la base abierta de Lichess (CC0), rating 1447. Stockfish 16 a profundidad 18: Cxe4 es la mejor (+4,7) y la segunda queda en -2,9.',
  },
  {
    n: 21,
    uso: 'ejemplo',
    capitulo: 5,
    leccion: 21,
    id: 'gp_2HuZV',
    tema: 'queenEndgame',
    lichess: '2HuZV',
    rating: 1332,
    elo: 552,
    juegan: 'b',
    fen: '8/6p1/2p3k1/1p1p4/3Q4/P1Pq3P/6PK/8 b - - 0 52',
    ultima: 'Dxd4',
    marca: ['h4', 'd4'],
    solucion: { from: 'd3', to: 'd4' },
    primera: 'Dxd4',
    linea: '52…Dxd4 53.cxd4 Rf5',
    gana: true,
    valor: '+4,1',
    pista: 'Con damas, primero el rey propio a salvo de jaques; después, el peón.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2HuZV de la base abierta de Lichess (CC0), rating 1332. Stockfish 16 a profundidad 18: Dxd4 es la mejor (+4,1) y la segunda queda en 0,0.',
  },
  {
    n: 22,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 22,
    id: 'gp_1c4Rd',
    tema: 'quietMove',
    lichess: '1c4Rd',
    rating: 1544,
    elo: 764,
    juegan: 'w',
    fen: '1n2k1nr/3p1ppp/1qbQp3/4P3/8/1p6/1PPB1PPP/4KBNR w Kk - 2 14',
    ultima: 'Db6',
    marca: ['a5', 'b6'],
    solucion: { from: 'd2', to: 'b4' },
    primera: 'Ab4',
    linea: '14.Ab4 Dxb4+ 15.Dxb4',
    gana: true,
    valor: '+6,0',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1c4Rd de la base abierta de Lichess (CC0), rating 1544. Stockfish 16 a profundidad 18: Ab4 es la mejor (+6,0) y la segunda queda en +0,7.',
  },
  {
    n: 23,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 23,
    id: 'gp_1pIxY',
    tema: 'defensiveMove',
    lichess: '1pIxY',
    rating: 1638,
    elo: 858,
    juegan: 'w',
    fen: '7k/2q3p1/6Q1/5N2/5P2/7P/4r1PK/8 w - - 3 58',
    ultima: 'Dc7',
    marca: ['b7', 'c7'],
    solucion: { from: 'g6', to: 'h5' },
    primera: 'Dh5+',
    linea: '58.Dh5+ Rg8 59.Dxe2 Dxf4+ 60.Cg3',
    gana: true,
    valor: '+5,0',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Es una horquilla: una pieza ataca dos objetivos a la vez.',
    comprobado: 'Ejercicio 1pIxY de la base abierta de Lichess (CC0), rating 1638. Stockfish 16 a profundidad 18: Dh5+ es la mejor (+5,0) y la segunda queda en +0,2.',
  },
  {
    n: 24,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 24,
    id: 'gp_0blu0',
    tema: 'defensiveMove',
    lichess: '0blu0',
    rating: 1452,
    elo: 672,
    juegan: 'w',
    fen: 'r1k1r3/pbpn1Q2/1p2p3/7R/3q1B2/P4P1P/2P3P1/4R1K1 w - - 0 28',
    ultima: 'Dxd4+',
    marca: ['c3', 'd4'],
    solucion: { from: 'f4', to: 'e3' },
    primera: 'Ae3',
    linea: '28.Ae3 Tf8 29.Dxf8+ Cxf8 30.Axd4',
    gana: true,
    valor: '+5,8',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0blu0 de la base abierta de Lichess (CC0), rating 1452. Stockfish 16 a profundidad 18: Ae3 es la mejor (+5,8) y la segunda queda en -2,7.',
  },
  {
    n: 25,
    uso: 'ejemplo',
    capitulo: 6,
    leccion: 25,
    id: 'gp_02kQm',
    tema: 'zugzwang',
    lichess: '02kQm',
    rating: 1573,
    elo: 793,
    juegan: 'b',
    fen: '8/8/8/pp6/4k1p1/P1P3P1/1P2K3/8 b - - 3 53',
    ultima: 'Re2',
    marca: ['f2', 'e2'],
    solucion: { from: 'a5', to: 'a4' },
    primera: 'a4',
    linea: '53…a4 54.b3 axb3',
    gana: true,
    valor: '+5,8',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 02kQm de la base abierta de Lichess (CC0), rating 1573. Stockfish 16 a profundidad 18: a4 es la mejor (+5,8) y la segunda queda en -5,6.',
  },
  {
    n: 26,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_1Mbi5',
    tema: 'trappedPiece',
    lichess: '1Mbi5',
    rating: 1320,
    elo: 540,
    juegan: 'b',
    fen: '5r1k/pq4pp/4Qn2/3r1p2/8/3P1N1P/P3PP2/4RKR1 b - - 8 24',
    ultima: 'Tg1',
    marca: ['h1', 'g1'],
    solucion: { from: 'f8', to: 'e8' },
    primera: 'Te8',
    linea: '24…Te8 25.Dxe8+ Cxe8',
    gana: true,
    valor: '+4,8',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 1Mbi5 de la base abierta de Lichess (CC0), rating 1320. Stockfish 16 a profundidad 18: Te8 es la mejor (+4,8) y la segunda queda en -0,4.',
  },
  {
    n: 27,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_0E1wO',
    tema: 'defensiveMove',
    lichess: '0E1wO',
    rating: 1561,
    elo: 781,
    juegan: 'b',
    fen: '8/8/8/8/4Rp2/5k1K/8/8 b - - 0 45',
    ultima: 'Txe4',
    marca: ['e7', 'e4'],
    solucion: { from: 'f3', to: 'e4' },
    primera: 'Rxe4',
    linea: '45…Rxe4 46.Rg2 Re3 47.Rf1 Rf3',
    gana: true,
    valor: '+35,4',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0E1wO de la base abierta de Lichess (CC0), rating 1561. Stockfish 16 a profundidad 18: Rxe4 es la mejor (+35,4) y la segunda queda en -4,9.',
  },
  {
    n: 28,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_1rUn9',
    tema: 'quietMove',
    lichess: '1rUn9',
    rating: 1582,
    elo: 802,
    juegan: 'b',
    fen: '8/4kpp1/4p2p/PB1p4/3Pb3/1r2P3/5PPP/R5K1 b - - 0 27',
    ultima: 'a5',
    marca: ['a4', 'a5'],
    solucion: { from: 'b3', to: 'b5' },
    primera: 'Txb5',
    linea: '27…Txb5 28.a6 Tb8 29.a7 Ta8',
    gana: true,
    valor: '+3,2',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 1rUn9 de la base abierta de Lichess (CC0), rating 1582. Stockfish 16 a profundidad 18: Txb5 es la mejor (+3,2) y la segunda queda en -4,8.',
  },
  {
    n: 29,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_2fzFk',
    tema: 'trappedPiece',
    lichess: '2fzFk',
    rating: 1809,
    elo: 1029,
    juegan: 'w',
    fen: '4r1k1/pp3p2/5bpp/2pP4/2P1NPBq/1P5P/P2Q2P1/5K2 w - - 3 29',
    ultima: 'Te8',
    marca: ['d8', 'e8'],
    solucion: { from: 'g2', to: 'g3' },
    primera: 'g3',
    linea: '29.g3 Txe4 30.gxh4',
    gana: true,
    valor: '+4,6',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 2fzFk de la base abierta de Lichess (CC0), rating 1809. Stockfish 16 a profundidad 18: g3 es la mejor (+4,6) y la segunda queda en 0,0.',
  },
  {
    n: 30,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_3FWKw',
    tema: 'quietMove',
    lichess: '3FWKw',
    rating: 1847,
    elo: 1067,
    juegan: 'w',
    fen: '8/8/3p3p/p1kPp1pP/P3P3/1K2bP2/4N3/8 w - - 0 41',
    ultima: 'a5',
    marca: ['a6', 'a5'],
    solucion: { from: 'e2', to: 'g3' },
    primera: 'Cg3',
    linea: '41.Cg3 g4 42.fxg4 Rd4 43.Cf5+',
    gana: true,
    valor: '+4,0',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3FWKw de la base abierta de Lichess (CC0), rating 1847. Stockfish 16 a profundidad 18: Cg3 es la mejor (+4,0) y la segunda queda en +0,3.',
  },
  {
    n: 31,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_3674E',
    tema: 'defensiveMove',
    lichess: '3674E',
    rating: 1986,
    elo: 1206,
    juegan: 'b',
    fen: '8/1pp1k1pp/4b3/2P5/8/4K3/p5PP/3R4 b - - 1 33',
    ultima: 'Td1',
    marca: ['d4', 'd1'],
    solucion: { from: 'e6', to: 'f5' },
    primera: 'Af5',
    linea: '33…Af5 34.Ta1 Ab1',
    gana: true,
    valor: '+3,6',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3674E de la base abierta de Lichess (CC0), rating 1986. Stockfish 16 a profundidad 18: Af5 es la mejor (+3,6) y la segunda queda en +0,0.',
  },
  {
    n: 32,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_1gXf6',
    tema: 'trappedPiece',
    lichess: '1gXf6',
    rating: 2111,
    elo: 1331,
    juegan: 'b',
    fen: 'r1bq1r1k/pp3ppB/5b2/4n1NQ/7P/8/PP3PP1/R1B1K2R b KQ - 2 14',
    ultima: 'Dh5',
    marca: ['d1', 'h5'],
    solucion: { from: 'c8', to: 'g4' },
    primera: 'Ag4',
    linea: '14…Ag4 15.Ag6+ Axh5',
    gana: true,
    valor: '+6,2',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 1gXf6 de la base abierta de Lichess (CC0), rating 2111. Stockfish 16 a profundidad 18: Ag4 es la mejor (+6,2) y la segunda queda en +0,1.',
  },
  {
    n: 33,
    uso: 'ejercicio',
    capitulo: 1,
    id: 'gp_0scR3',
    tema: 'quietMove',
    lichess: '0scR3',
    rating: 2153,
    elo: 1373,
    juegan: 'b',
    fen: '8/1p2k3/3p1n1p/p1pP2p1/P1P3P1/2P1KP2/7B/8 b - - 1 36',
    ultima: 'Ah2',
    marca: ['g3', 'h2'],
    solucion: { from: 'f6', to: 'd7' },
    primera: 'Cd7',
    linea: '36…Cd7 37.Rd3 Cb6',
    gana: true,
    valor: '+3,3',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0scR3 de la base abierta de Lichess (CC0), rating 2153. Stockfish 16 a profundidad 18: Cd7 es la mejor (+3,3) y la segunda queda en 0,0.',
  },
  {
    n: 34,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_1ka9P',
    tema: 'bishopEndgame',
    lichess: '1ka9P',
    rating: 1514,
    elo: 734,
    juegan: 'w',
    fen: '8/4K3/2kP4/8/1pB5/7b/8/8 w - - 7 54',
    ultima: 'Ah3',
    marca: ['d7', 'h3'],
    solucion: { from: 'c4', to: 'e6' },
    primera: 'Ae6',
    linea: '54.Ae6 Axe6 55.Rxe6 b3 56.d7 Rc7 57.Re7 b2 58.d8=D+',
    gana: true,
    valor: '+6,5',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1ka9P de la base abierta de Lichess (CC0), rating 1514. Stockfish 16 a profundidad 18: Ae6 es la mejor (+6,5) y la segunda queda en 0,0.',
  },
  {
    n: 35,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_1Qsh9',
    tema: 'knightEndgame',
    lichess: '1Qsh9',
    rating: 1634,
    elo: 854,
    juegan: 'b',
    fen: '8/8/3N4/2k1p3/2P1Kn2/8/8/8 b - - 0 46',
    ultima: 'Cxd6',
    marca: ['f5', 'd6'],
    solucion: { from: 'c5', to: 'd6' },
    primera: 'Rxd6',
    linea: '46…Rxd6 47.c5+ Re6',
    gana: true,
    valor: '+6,7',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 1Qsh9 de la base abierta de Lichess (CC0), rating 1634. Stockfish 16 a profundidad 18: Rxd6 es la mejor (+6,7) y la segunda queda en 0,0.',
  },
  {
    n: 36,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_0g3m0',
    tema: 'trappedPiece',
    lichess: '0g3m0',
    rating: 1649,
    elo: 869,
    juegan: 'w',
    fen: 'r4rk1/pp1nbppp/2p1p3/8/2PP2b1/P1N1PN2/1q2B1PP/R2Q1RK1 w - - 3 16',
    ultima: 'Db2',
    marca: ['b6', 'b2'],
    solucion: { from: 'c3', to: 'a4' },
    primera: 'Ca4',
    linea: '16.Ca4 Dxa1 17.Dxa1',
    gana: true,
    valor: '+4,5',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 0g3m0 de la base abierta de Lichess (CC0), rating 1649. Stockfish 16 a profundidad 18: Ca4 es la mejor (+4,5) y la segunda queda en -1,3.',
  },
  {
    n: 37,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_2e0oU',
    tema: 'trappedPiece',
    lichess: '2e0oU',
    rating: 1750,
    elo: 970,
    juegan: 'b',
    fen: 'r3kr2/1pp5/p1p1bqp1/8/4P1pP/3P2P1/PPPQ1P2/RN2K2R b KQq - 2 18',
    ultima: 'Dd2',
    marca: ['h6', 'd2'],
    solucion: { from: 'f6', to: 'b2' },
    primera: 'Dxb2',
    linea: '18…Dxb2 19.O-O Dxa1 20.Cc3 Db2 21.Tb1 Da3',
    gana: true,
    valor: '+3,5',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 2e0oU de la base abierta de Lichess (CC0), rating 1750. Stockfish 16 a profundidad 18: Dxb2 es la mejor (+3,5) y la segunda queda en -1,8.',
  },
  {
    n: 38,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_0FkJE',
    tema: 'bishopEndgame',
    lichess: '0FkJE',
    rating: 1892,
    elo: 1112,
    juegan: 'w',
    fen: '7b/2k2K2/pp4p1/2p1P3/7p/P1B5/1P3P2/8 w - - 2 51',
    ultima: 'Ah8',
    marca: ['g7', 'h8'],
    solucion: { from: 'e5', to: 'e6' },
    primera: 'e6',
    linea: '51.e6 Axc3 52.e7',
    gana: true,
    valor: '+4,3',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0FkJE de la base abierta de Lichess (CC0), rating 1892. Stockfish 16 a profundidad 18: e6 es la mejor (+4,3) y la segunda queda en 0,0.',
  },
  {
    n: 39,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_3PUYi',
    tema: 'knightEndgame',
    lichess: '3PUYi',
    rating: 1906,
    elo: 1126,
    juegan: 'b',
    fen: '5k2/5p2/pp5N/2p1P2p/P1Pn1P2/1P4P1/8/5K2 b - f3 0 37',
    ultima: 'f4',
    marca: ['f2', 'f4'],
    solucion: { from: 'f8', to: 'g7' },
    primera: 'Rg7',
    linea: '37…Rg7 38.Cxf7 Rxf7',
    gana: true,
    valor: '+4,1',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 3PUYi de la base abierta de Lichess (CC0), rating 1906. Stockfish 16 a profundidad 18: Rg7 es la mejor (+4,1) y la segunda queda en +0,6.',
  },
  {
    n: 40,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_0tLC5',
    tema: 'trappedPiece',
    lichess: '0tLC5',
    rating: 2246,
    elo: 1466,
    juegan: 'b',
    fen: 'r1brq1k1/2p2pbp/5np1/p1B1p3/2Q1P3/1NP2N1P/PP3PP1/R2R2K1 b - - 3 17',
    ultima: 'Tfd1',
    marca: ['f1', 'd1'],
    solucion: { from: 'd8', to: 'd1' },
    primera: 'Txd1+',
    linea: '17…Txd1+ 18.Txd1 Aa6 19.Dxa6 Txa6',
    gana: true,
    valor: '+5,3',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 0tLC5 de la base abierta de Lichess (CC0), rating 2246. Stockfish 16 a profundidad 18: Txd1+ es la mejor (+5,3) y la segunda queda en -0,2.',
  },
  {
    n: 41,
    uso: 'ejercicio',
    capitulo: 2,
    id: 'gp_2zdw5',
    tema: 'bishopEndgame',
    lichess: '2zdw5',
    rating: 2313,
    elo: 1533,
    juegan: 'w',
    fen: '3kB3/8/p3p3/1p1pKb2/1P1P4/2P5/P7/8 w - - 13 53',
    ultima: 'Rd8',
    marca: ['c7', 'd8'],
    solucion: { from: 'e8', to: 'c6' },
    primera: 'Ac6',
    linea: '53.Ac6 Re7 54.Axd5',
    gana: true,
    valor: '+5,0',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 2zdw5 de la base abierta de Lichess (CC0), rating 2313. Stockfish 16 a profundidad 18: Ac6 es la mejor (+5,0) y la segunda queda en +0,1.',
  },
  {
    n: 42,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_0gLCV',
    tema: 'pawnEndgame',
    lichess: '0gLCV',
    rating: 1371,
    elo: 591,
    juegan: 'w',
    fen: '4k3/5p2/p4P1p/3Pp3/5p2/3K4/PP3P2/8 w - - 1 45',
    ultima: 'Re8',
    marca: ['f8', 'e8'],
    solucion: { from: 'd3', to: 'e4' },
    primera: 'Re4',
    linea: '45.Re4 Rd7 46.Rxe5',
    gana: true,
    valor: '+3,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: '',
    comprobado: 'Ejercicio 0gLCV de la base abierta de Lichess (CC0), rating 1371. Stockfish 16 a profundidad 18: Re4 es la mejor (+3,8) y la segunda queda en -3,6.',
  },
  {
    n: 43,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_1b61f',
    tema: 'advancedPawn',
    lichess: '1b61f',
    rating: 1533,
    elo: 753,
    juegan: 'w',
    fen: '8/5pk1/1PN3p1/8/2P5/5n1p/K3R3/3r4 w - - 0 43',
    ultima: 'Cxf3',
    marca: ['g5', 'f3'],
    solucion: { from: 'b6', to: 'b7' },
    primera: 'b7',
    linea: '43.b7 h2 44.Txh2',
    gana: true,
    valor: '+4,4',
    pista: 'Un peón pasado es una ventaja que crece sola: ¿cómo lo empujas o lo aprovechas?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1b61f de la base abierta de Lichess (CC0), rating 1533. Stockfish 16 a profundidad 18: b7 es la mejor (+4,4) y la segunda queda en -0,1.',
  },
  {
    n: 44,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_3Rq5W',
    tema: 'promotion',
    lichess: '3Rq5W',
    rating: 1648,
    elo: 868,
    juegan: 'b',
    fen: '8/p7/1p3k2/4p3/R3Kpp1/7p/PPP5/5B2 b - - 1 33',
    ultima: 'Af1',
    marca: ['g2', 'f1'],
    solucion: { from: 'h3', to: 'h2' },
    primera: 'h2',
    linea: '33…h2 34.Ag2 f3 35.Axf3 gxf3 36.Rxf3 h1=D+',
    gana: true,
    valor: '+5,3',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 3Rq5W de la base abierta de Lichess (CC0), rating 1648. Stockfish 16 a profundidad 18: h2 es la mejor (+5,3) y la segunda queda en -5,4.',
  },
  {
    n: 45,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_1TWEd',
    tema: 'pawnEndgame',
    lichess: '1TWEd',
    rating: 1654,
    elo: 874,
    juegan: 'w',
    fen: '8/5ppp/1p6/p1p2PPP/8/1P1k4/4p3/4K3 w - - 0 47',
    ultima: 'e2',
    marca: ['e3', 'e2'],
    solucion: { from: 'g5', to: 'g6' },
    primera: 'g6',
    linea: '47.g6 hxg6 48.f6 gxf6 49.h6',
    gana: true,
    valor: '+4,2',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Hay un sacrificio: se entrega material para ganar más.',
    comprobado: 'Ejercicio 1TWEd de la base abierta de Lichess (CC0), rating 1654. Stockfish 16 a profundidad 18: g6 es la mejor (+4,2) y la segunda queda en -8,0.',
  },
  {
    n: 46,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_2b3hk',
    tema: 'advancedPawn',
    lichess: '2b3hk',
    rating: 1719,
    elo: 939,
    juegan: 'b',
    fen: '8/4k1p1/4Q2p/3Pq3/8/2p3PP/6BK/8 b - - 11 52',
    ultima: 'De6+',
    marca: ['c6', 'e6'],
    solucion: { from: 'e5', to: 'e6' },
    primera: 'Dxe6',
    linea: '52…Dxe6 53.dxe6 c2',
    gana: true,
    valor: '+5,1',
    pista: 'Un peón pasado es una ventaja que crece sola: ¿cómo lo empujas o lo aprovechas?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2b3hk de la base abierta de Lichess (CC0), rating 1719. Stockfish 16 a profundidad 18: Dxe6 es la mejor (+5,1) y la segunda queda en recibe mate en 7.',
  },
  {
    n: 47,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_3P8sF',
    tema: 'promotion',
    lichess: '3P8sF',
    rating: 1856,
    elo: 1076,
    juegan: 'b',
    fen: '4K3/3P4/8/4k1p1/6P1/8/1p6/8 b - - 1 56',
    ultima: 'Re8',
    marca: ['d8', 'e8'],
    solucion: { from: 'b2', to: 'b1', promotion: 'q' },
    primera: 'b1=D',
    linea: '56…b1=D 57.d8=D Dg6+ 58.Rf8 Df6+ 59.Dxf6+ Rxf6 60.Rg8 Re5 61.Rf7 Rf4',
    gana: true,
    valor: '+8,2',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 3P8sF de la base abierta de Lichess (CC0), rating 1856. Stockfish 16 a profundidad 18: b1=D es la mejor (+8,2) y la segunda queda en +0,0.',
  },
  {
    n: 48,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_2Y4ZP',
    tema: 'advancedPawn',
    lichess: '2Y4ZP',
    rating: 2108,
    elo: 1328,
    juegan: 'w',
    fen: '1r2nk2/3q4/3p1PQp/2pPp3/2P2b2/1PB4P/6P1/5R1K w - - 3 31',
    ultima: 'Ce8',
    marca: ['c7', 'e8'],
    solucion: { from: 'f1', to: 'f4' },
    primera: 'Txf4',
    linea: '31.Txf4 exf4 32.Dxh6+ Rg8 33.f7+ Rxf7 34.Dh7+',
    gana: true,
    valor: '+5,3',
    pista: 'Un peón pasado es una ventaja que crece sola: ¿cómo lo empujas o lo aprovechas?',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2Y4ZP de la base abierta de Lichess (CC0), rating 2108. Stockfish 16 a profundidad 18: Txf4 es la mejor (+5,3) y la segunda queda en -1,8.',
  },
  {
    n: 49,
    uso: 'ejercicio',
    capitulo: 3,
    id: 'gp_1sbdm',
    tema: 'promotion',
    lichess: '1sbdm',
    rating: 2285,
    elo: 1505,
    juegan: 'b',
    fen: '4r3/1pp2k2/p1p5/6pp/5p2/2BP1P2/PPP5/2K1R3 b - - 2 27',
    ultima: 'Te1',
    marca: ['d1', 'e1'],
    solucion: { from: 'e8', to: 'e1' },
    primera: 'Txe1+',
    linea: '27…Txe1+ 28.Axe1 h4 29.Af2 h3 30.Ag1 g4 31.fxg4 f3 32.Rd2 f2 33.Axf2 h2 34.Ag3 h1=D',
    gana: true,
    valor: '+4,7',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1sbdm de la base abierta de Lichess (CC0), rating 2285. Stockfish 16 a profundidad 18: Txe1+ es la mejor (+4,7) y la segunda queda en -1,9.',
  },
  {
    n: 50,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_1MXkM',
    tema: 'pawnEndgame',
    lichess: '1MXkM',
    rating: 1277,
    elo: 497,
    juegan: 'w',
    fen: '8/5k1p/3p1pp1/3p4/1pK1P3/6PP/5P2/8 w - - 0 43',
    ultima: 'exd5+',
    marca: ['e6', 'd5'],
    solucion: { from: 'e4', to: 'd5' },
    primera: 'exd5',
    linea: '43.exd5 g5 44.Rxb4',
    gana: true,
    valor: '+3,0',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: '',
    comprobado: 'Ejercicio 1MXkM de la base abierta de Lichess (CC0), rating 1277. Stockfish 16 a profundidad 18: exd5 es la mejor (+3,0) y la segunda queda en -5,0.',
  },
  {
    n: 51,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_0f0uh',
    tema: 'zugzwang',
    lichess: '0f0uh',
    rating: 1602,
    elo: 822,
    juegan: 'w',
    fen: '8/8/5k2/4p1pK/4r2p/5P1P/8/8 w - - 0 47',
    ultima: 'Txe4',
    marca: ['b4', 'e4'],
    solucion: { from: 'f3', to: 'e4' },
    primera: 'fxe4',
    linea: '47.fxe4 g4 48.Rxg4',
    gana: true,
    valor: '+7,8',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 0f0uh de la base abierta de Lichess (CC0), rating 1602. Stockfish 16 a profundidad 18: fxe4 es la mejor (+7,8) y la segunda queda en recibe mate en 10.',
  },
  {
    n: 52,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_0JmII',
    tema: 'rookEndgame',
    lichess: '0JmII',
    rating: 1649,
    elo: 869,
    juegan: 'b',
    fen: '8/4k3/4P3/6p1/2K3P1/1R4r1/8/8 b - - 0 52',
    ultima: 'Txb3',
    marca: ['a3', 'b3'],
    solucion: { from: 'g3', to: 'b3' },
    primera: 'Txb3',
    linea: '52…Txb3 53.Rxb3 Rxe6',
    gana: true,
    valor: '+8,3',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: '',
    comprobado: 'Ejercicio 0JmII de la base abierta de Lichess (CC0), rating 1649. Stockfish 16 a profundidad 18: Txb3 es la mejor (+8,3) y la segunda queda en 0,0.',
  },
  {
    n: 53,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_1EAz3',
    tema: 'rookEndgame',
    lichess: '1EAz3',
    rating: 1709,
    elo: 929,
    juegan: 'b',
    fen: '8/P4pk1/2R5/6P1/3p1P2/8/1Kp5/r7 b - - 3 50',
    ultima: 'Rb2',
    marca: ['b3', 'b2'],
    solucion: { from: 'd4', to: 'd3' },
    primera: 'd3',
    linea: '50…d3 51.Rxa1 d2 52.Rb2 d1=D',
    gana: true,
    valor: '+3,8',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1EAz3 de la base abierta de Lichess (CC0), rating 1709. Stockfish 16 a profundidad 18: d3 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 54,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_0Y7XB',
    tema: 'zugzwang',
    lichess: '0Y7XB',
    rating: 1907,
    elo: 1127,
    juegan: 'w',
    fen: '8/8/pp6/2p1k3/P1P1P3/3K4/8/8 w - - 0 46',
    ultima: 'dxc5',
    marca: ['d6', 'c5'],
    solucion: { from: 'd3', to: 'e3' },
    primera: 'Re3',
    linea: '46.Re3 a5 47.Rf3 Rd4 48.Rf4 Rxc4 49.e5 Rb3 50.e6 c4 51.e7 c3 52.e8=D',
    gana: true,
    valor: '+3,3',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0Y7XB de la base abierta de Lichess (CC0), rating 1907. Stockfish 16 a profundidad 18: Re3 es la mejor (+3,3) y la segunda queda en -6,9.',
  },
  {
    n: 55,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_04MWF',
    tema: 'pawnEndgame',
    lichess: '04MWF',
    rating: 2012,
    elo: 1232,
    juegan: 'b',
    fen: '8/1Pk5/6p1/3K3p/pP3p2/2P5/P5P1/8 b - - 1 47',
    ultima: 'Rd5',
    marca: ['c5', 'd5'],
    solucion: { from: 'f4', to: 'f3' },
    primera: 'f3',
    linea: '47…f3 48.b8=D+ Rxb8 49.gxf3 h4',
    gana: true,
    valor: '+4,4',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 04MWF de la base abierta de Lichess (CC0), rating 2012. Stockfish 16 a profundidad 18: f3 es la mejor (+4,4) y la segunda queda en 0,0.',
  },
  {
    n: 56,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_2okMZ',
    tema: 'pawnEndgame',
    lichess: '2okMZ',
    rating: 2155,
    elo: 1375,
    juegan: 'w',
    fen: '8/8/pp6/2pK1kp1/2P3p1/PP4P1/8/8 w - - 0 46',
    ultima: 'a6',
    marca: ['a7', 'a6'],
    solucion: { from: 'b3', to: 'b4' },
    primera: 'b4',
    linea: '46.b4 cxb4 47.axb4',
    gana: true,
    valor: '+3,8',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: '',
    comprobado: 'Ejercicio 2okMZ de la base abierta de Lichess (CC0), rating 2155. Stockfish 16 a profundidad 18: b4 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 57,
    uso: 'ejercicio',
    capitulo: 4,
    id: 'gp_25Mg3',
    tema: 'zugzwang',
    lichess: '25Mg3',
    rating: 2374,
    elo: 1594,
    juegan: 'b',
    fen: '8/6p1/p6p/1ppk4/2P3P1/1P1K3P/P7/8 b - - 0 34',
    ultima: 'c4+',
    marca: ['c3', 'c4'],
    solucion: { from: 'b5', to: 'c4' },
    primera: 'bxc4+',
    linea: '34…bxc4+ 35.bxc4+ Re5 36.Re3 a5',
    gana: true,
    valor: '+3,3',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 25Mg3 de la base abierta de Lichess (CC0), rating 2374. Stockfish 16 a profundidad 18: bxc4+ es la mejor (+3,3) y la segunda queda en 0,0.',
  },
  {
    n: 58,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_2TgpJ',
    tema: 'bishopEndgame',
    lichess: '2TgpJ',
    rating: 1268,
    elo: 488,
    juegan: 'b',
    fen: '8/8/p6p/1p1kb1p1/6P1/1P2K3/P2B1P2/8 b - - 4 37',
    ultima: 'Re3',
    marca: ['f3', 'e3'],
    solucion: { from: 'e5', to: 'f4' },
    primera: 'Af4+',
    linea: '37…Af4+ 38.Re2 Axd2 39.Rxd2 Re4',
    gana: true,
    valor: '+4,6',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2TgpJ de la base abierta de Lichess (CC0), rating 1268. Stockfish 16 a profundidad 18: Af4+ es la mejor (+4,6) y la segunda queda en -0,3.',
  },
  {
    n: 59,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_20ayL',
    tema: 'knightEndgame',
    lichess: '20ayL',
    rating: 1567,
    elo: 787,
    juegan: 'b',
    fen: '8/8/p3k3/P1np1N2/3K1P2/2P5/8/8 b - - 4 40',
    ultima: 'Rd4',
    marca: ['e3', 'd4'],
    solucion: { from: 'c5', to: 'b3' },
    primera: 'Cb3+',
    linea: '40…Cb3+ 41.Re3 Rxf5',
    gana: true,
    valor: '+5,5',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: '',
    comprobado: 'Ejercicio 20ayL de la base abierta de Lichess (CC0), rating 1567. Stockfish 16 a profundidad 18: Cb3+ es la mejor (+5,5) y la segunda queda en -0,1.',
  },
  {
    n: 60,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_1PYvj',
    tema: 'rookEndgame',
    lichess: '1PYvj',
    rating: 1647,
    elo: 867,
    juegan: 'w',
    fen: '8/8/8/4pk2/7p/2P1R1rP/4K3/8 w - - 4 50',
    ultima: 'Rf5',
    marca: ['e6', 'f5'],
    solucion: { from: 'e3', to: 'g3' },
    primera: 'Txg3',
    linea: '50.Txg3 hxg3 51.Rf3 g2 52.Rxg2',
    gana: true,
    valor: '+6,3',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: '',
    comprobado: 'Ejercicio 1PYvj de la base abierta de Lichess (CC0), rating 1647. Stockfish 16 a profundidad 18: Txg3 es la mejor (+6,3) y la segunda queda en 0,0.',
  },
  {
    n: 61,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_0iFp2',
    tema: 'knightEndgame',
    lichess: '0iFp2',
    rating: 1825,
    elo: 1045,
    juegan: 'b',
    fen: '2n5/1k6/2N3p1/PK5p/8/8/5P2/8 b - - 12 53',
    ultima: 'Rb5',
    marca: ['c5', 'b5'],
    solucion: { from: 'c8', to: 'a7' },
    primera: 'Ca7+',
    linea: '53…Ca7+ 54.Rc5 Cxc6',
    gana: true,
    valor: '+5,3',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: '',
    comprobado: 'Ejercicio 0iFp2 de la base abierta de Lichess (CC0), rating 1825. Stockfish 16 a profundidad 18: Ca7+ es la mejor (+5,3) y la segunda queda en +0,2.',
  },
  {
    n: 62,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_2B1tw',
    tema: 'rookEndgame',
    lichess: '2B1tw',
    rating: 1828,
    elo: 1048,
    juegan: 'w',
    fen: '6R1/6P1/8/1P2p3/K2p4/4k1r1/8/8 w - - 1 54',
    ultima: 'Re3',
    marca: ['e4', 'e3'],
    solucion: { from: 'b5', to: 'b6' },
    primera: 'b6',
    linea: '54.b6 d3 55.b7 d2 56.Td8',
    gana: true,
    valor: '+5,3',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2B1tw de la base abierta de Lichess (CC0), rating 1828. Stockfish 16 a profundidad 18: b6 es la mejor (+5,3) y la segunda queda en +0,1.',
  },
  {
    n: 63,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_1GUxH',
    tema: 'bishopEndgame',
    lichess: '1GUxH',
    rating: 1854,
    elo: 1074,
    juegan: 'w',
    fen: '8/8/2k3p1/p1p2p1p/2p1bP1P/P1P1K1P1/8/3B4 w - - 1 42',
    ultima: 'Rc6',
    marca: ['d6', 'c6'],
    solucion: { from: 'd1', to: 'a4' },
    primera: 'Aa4+',
    linea: '42.Aa4+ Rd6 43.Ae8 Re7 44.Axg6',
    gana: true,
    valor: '+3,7',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 1GUxH de la base abierta de Lichess (CC0), rating 1854. Stockfish 16 a profundidad 18: Aa4+ es la mejor (+3,7) y la segunda queda en 0,0.',
  },
  {
    n: 64,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_2gysJ',
    tema: 'bishopEndgame',
    lichess: '2gysJ',
    rating: 2121,
    elo: 1341,
    juegan: 'w',
    fen: '8/1pB5/4pk2/1P2p3/4KbP1/8/6P1/8 w - - 2 46',
    ultima: 'Rf6',
    marca: ['f7', 'f6'],
    solucion: { from: 'c7', to: 'e5' },
    primera: 'Axe5+',
    linea: '46.Axe5+ Axe5 47.g5+ Rxg5 48.Rxe5',
    gana: true,
    valor: '+7,2',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 2gysJ de la base abierta de Lichess (CC0), rating 2121. Stockfish 16 a profundidad 18: Axe5+ es la mejor (+7,2) y la segunda queda en +1,2.',
  },
  {
    n: 65,
    uso: 'ejercicio',
    capitulo: 5,
    id: 'gp_1gwYW',
    tema: 'rookEndgame',
    lichess: '1gwYW',
    rating: 2176,
    elo: 1396,
    juegan: 'w',
    fen: '8/2p3R1/8/p6P/1pp5/2P1k1KP/Pr6/8 w - - 0 38',
    ultima: 'b4',
    marca: ['b5', 'b4'],
    solucion: { from: 'h5', to: 'h6' },
    primera: 'h6',
    linea: '38.h6 bxc3 39.h7 Tb8 40.Tg8',
    gana: true,
    valor: '+3,9',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 1gwYW de la base abierta de Lichess (CC0), rating 2176. Stockfish 16 a profundidad 18: h6 es la mejor (+3,9) y la segunda queda en 0,0.',
  },
  {
    n: 66,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_2bppg',
    tema: 'quietMove',
    lichess: '2bppg',
    rating: 1583,
    elo: 803,
    juegan: 'b',
    fen: '3br1k1/2p2pp1/p2p4/1p1P3p/5P1q/2P2Q1P/PP1B2PK/4R3 b - - 1 22',
    ultima: 'Te1',
    marca: ['a1', 'e1'],
    solucion: { from: 'e8', to: 'e1' },
    primera: 'Txe1',
    linea: '22…Txe1 23.g3 De7 24.Axe1 Dxe1',
    gana: true,
    valor: '+4,9',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2bppg de la base abierta de Lichess (CC0), rating 1583. Stockfish 16 a profundidad 18: Txe1 es la mejor (+4,9) y la segunda queda en -0,3.',
  },
  {
    n: 67,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_2l9qX',
    tema: 'zugzwang',
    lichess: '2l9qX',
    rating: 1583,
    elo: 803,
    juegan: 'w',
    fen: '8/2B2p2/p2n2p1/1p1k2P1/1P5P/P2K4/8/8 w - - 6 49',
    ultima: 'Cd6',
    marca: ['e4', 'd6'],
    solucion: { from: 'c7', to: 'd6' },
    primera: 'Axd6',
    linea: '49.Axd6 Rxd6 50.Rd4 Re6 51.Rc5 f5 52.gxf6',
    gana: true,
    valor: '+3,8',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 2l9qX de la base abierta de Lichess (CC0), rating 1583. Stockfish 16 a profundidad 18: Axd6 es la mejor (+3,8) y la segunda queda en -2,4.',
  },
  {
    n: 68,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_2epmE',
    tema: 'defensiveMove',
    lichess: '2epmE',
    rating: 1617,
    elo: 837,
    juegan: 'b',
    fen: '7Q/6p1/4p3/4q1k1/4b1PP/1P1p1B2/6K1/8 b - - 0 53',
    ultima: 'h4+',
    marca: ['h3', 'h4'],
    solucion: { from: 'g5', to: 'f4' },
    primera: 'Rf4',
    linea: '53…Rf4 54.Df8+ Re3',
    gana: true,
    valor: '+5,5',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 2epmE de la base abierta de Lichess (CC0), rating 1617. Stockfish 16 a profundidad 18: Rf4 es la mejor (+5,5) y la segunda queda en 0,0.',
  },
  {
    n: 69,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_0UEf6',
    tema: 'defensiveMove',
    lichess: '0UEf6',
    rating: 1668,
    elo: 888,
    juegan: 'b',
    fen: '8/8/2p5/8/8/4Q2p/P3k3/7K b - - 0 55',
    ultima: 'Dxe3+',
    marca: ['f4', 'e3'],
    solucion: { from: 'e2', to: 'e3' },
    primera: 'Rxe3',
    linea: '55…Rxe3 56.a4 Rd4',
    gana: true,
    valor: '+7,5',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 0UEf6 de la base abierta de Lichess (CC0), rating 1668. Stockfish 16 a profundidad 18: Rxe3 es la mejor (+7,5) y la segunda queda en -42,9.',
  },
  {
    n: 70,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_218OF',
    tema: 'zugzwang',
    lichess: '218OF',
    rating: 1680,
    elo: 900,
    juegan: 'w',
    fen: '8/p1p3p1/1p1p1k2/1P1P2p1/P1P1K2P/7P/8/8 w - - 0 40',
    ultima: 'g5',
    marca: ['g6', 'g5'],
    solucion: { from: 'h4', to: 'h5' },
    primera: 'h5',
    linea: '40.h5 Rf7 41.Rf5',
    gana: true,
    valor: '+3,8',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 218OF de la base abierta de Lichess (CC0), rating 1680. Stockfish 16 a profundidad 18: h5 es la mejor (+3,8) y la segunda queda en -1,4.',
  },
  {
    n: 71,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_06Nwf',
    tema: 'quietMove',
    lichess: '06Nwf',
    rating: 1796,
    elo: 1016,
    juegan: 'w',
    fen: 'r4rk1/pp3p1p/4p1p1/3pP1B1/1q6/5Q2/P4PPP/5RK1 w - - 0 23',
    ultima: 'Dxb4',
    marca: ['b6', 'b4'],
    solucion: { from: 'f3', to: 'f6' },
    primera: 'Df6',
    linea: '23.Df6 Tfe8 24.Ah6 Df8 25.Axf8',
    gana: true,
    valor: '+4,3',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 06Nwf de la base abierta de Lichess (CC0), rating 1796. Stockfish 16 a profundidad 18: Df6 es la mejor (+4,3) y la segunda queda en -3,1.',
  },
  {
    n: 72,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_1OdEw',
    tema: 'defensiveMove',
    lichess: '1OdEw',
    rating: 2239,
    elo: 1459,
    juegan: 'w',
    fen: '2kr2nr/2p3p1/R2p1p2/1Q5p/3P2PB/P1P2q1P/5P2/1b4K1 w - - 0 24',
    ultima: 'Axb1',
    marca: ['g6', 'b1'],
    solucion: { from: 'd4', to: 'd5' },
    primera: 'd5',
    linea: '24.d5 Dd1+ 25.Rh2 Dxd5 26.Dxd5',
    gana: true,
    valor: '+4,8',
    pista: 'Antes de apretar, mira qué amenaza el rival: solo una jugada conserva lo que tienes.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 1OdEw de la base abierta de Lichess (CC0), rating 2239. Stockfish 16 a profundidad 18: d5 es la mejor (+4,8) y la segunda queda en -8,4.',
  },
  {
    n: 73,
    uso: 'ejercicio',
    capitulo: 6,
    id: 'gp_0d9wh',
    tema: 'quietMove',
    lichess: '0d9wh',
    rating: 2269,
    elo: 1489,
    juegan: 'w',
    fen: 'r3r1k1/1b3p1p/pb4p1/1ppqP1B1/2pP4/2P1QN2/P4PPP/R4RK1 w - - 2 21',
    ultima: 'Dd5',
    marca: ['d8', 'd5'],
    solucion: { from: 'g5', to: 'f6' },
    primera: 'Af6',
    linea: '21.Af6 Dd6 22.exd6',
    gana: true,
    valor: '+5,8',
    pista: 'No hay un jaque que gane: busca la jugada silenciosa que mejora lo tuyo y deja al rival sin respuesta.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0d9wh de la base abierta de Lichess (CC0), rating 2269. Stockfish 16 a profundidad 18: Af6 es la mejor (+5,8) y la segunda queda en -0,8.',
  },
  {
    n: 74,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0Cuxd',
    tema: 'bishopEndgame',
    lichess: '0Cuxd',
    rating: 1360,
    elo: 580,
    juegan: 'b',
    fen: '4b3/6k1/8/7p/pP5P/3BK1P1/2P5/8 b - - 0 41',
    ultima: 'axb4',
    marca: ['a3', 'b4'],
    solucion: { from: 'a4', to: 'a3' },
    primera: 'a3',
    linea: '41…a3 42.Ac4 Af7 43.Axf7 Rxf7',
    gana: true,
    valor: '+4,3',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 0Cuxd de la base abierta de Lichess (CC0), rating 1360. Stockfish 16 a profundidad 18: a3 es la mejor (+4,3) y la segunda queda en -4,7.',
  },
  {
    n: 75,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2D1Jf',
    tema: 'trappedPiece',
    lichess: '2D1Jf',
    rating: 1394,
    elo: 614,
    juegan: 'w',
    fen: 'r1b1kb1r/pp2ppp1/n1p2n1p/3p4/3P1B2/P1N1P3/1qP2PPP/R2QKBNR w KQkq - 0 8',
    ultima: 'Dxb2',
    marca: ['b6', 'b2'],
    solucion: { from: 'c3', to: 'a4' },
    primera: 'Ca4',
    linea: '8.Ca4 Dxa1 9.Dxa1',
    gana: true,
    valor: '+4,9',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 2D1Jf de la base abierta de Lichess (CC0), rating 1394. Stockfish 16 a profundidad 18: Ca4 es la mejor (+4,9) y la segunda queda en -0,9.',
  },
  {
    n: 76,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0pBWw',
    tema: 'zugzwang',
    lichess: '0pBWw',
    rating: 1424,
    elo: 644,
    juegan: 'w',
    fen: '8/8/8/6k1/5p2/5pPK/5P2/8 w - - 0 81',
    ultima: 'f4',
    marca: ['f5', 'f4'],
    solucion: { from: 'g3', to: 'g4' },
    primera: 'g4',
    linea: '81.g4 Rf6 82.Rh4 Rg6 83.g5',
    gana: true,
    valor: '+6,4',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0pBWw de la base abierta de Lichess (CC0), rating 1424. Stockfish 16 a profundidad 18: g4 es la mejor (+6,4) y la segunda queda en +0,1.',
  },
  {
    n: 77,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0T4KD',
    tema: 'pawnEndgame',
    lichess: '0T4KD',
    rating: 1514,
    elo: 734,
    juegan: 'b',
    fen: '8/4K3/p7/7k/1p6/4P2P/P7/8 b - - 0 39',
    ultima: 'Rxe7',
    marca: ['e6', 'e7'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'a5',
    linea: '39…a5 40.e4 a4 41.e5 b3',
    gana: true,
    valor: '+3,4',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 0T4KD de la base abierta de Lichess (CC0), rating 1514. Stockfish 16 a profundidad 18: a5 es la mejor (+3,4) y la segunda queda en -6,0.',
  },
  {
    n: 78,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0rJ06',
    tema: 'knightEndgame',
    lichess: '0rJ06',
    rating: 1604,
    elo: 824,
    juegan: 'b',
    fen: '8/8/5n2/p3k1p1/4p1P1/2N1K2P/P7/8 b - - 2 37',
    ultima: 'Cc3',
    marca: ['e2', 'c3'],
    solucion: { from: 'f6', to: 'd5' },
    primera: 'Cd5+',
    linea: '37…Cd5+ 38.Cxd5 Rxd5 39.a4 Re5',
    gana: true,
    valor: '+5,4',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 0rJ06 de la base abierta de Lichess (CC0), rating 1604. Stockfish 16 a profundidad 18: Cd5+ es la mejor (+5,4) y la segunda queda en 0,0.',
  },
  {
    n: 79,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_03CzP',
    tema: 'queenEndgame',
    lichess: '03CzP',
    rating: 1605,
    elo: 825,
    juegan: 'w',
    fen: '3K4/3Q4/7k/1Pq3p1/8/8/8/8 w - - 0 56',
    ultima: 'g5',
    marca: ['g6', 'g5'],
    solucion: { from: 'd7', to: 'c6' },
    primera: 'Dc6+',
    linea: '56.Dc6+ Dxc6 57.bxc6',
    gana: true,
    valor: '+35,5',
    pista: 'Con damas, primero el rey propio a salvo de jaques; después, el peón.',
    explica: '',
    comprobado: 'Ejercicio 03CzP de la base abierta de Lichess (CC0), rating 1605. Stockfish 16 a profundidad 18: Dc6+ es la mejor (+35,5) y la segunda queda en +0,5.',
  },
  {
    n: 80,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2tuIf',
    tema: 'rookEndgame',
    lichess: '2tuIf',
    rating: 1611,
    elo: 831,
    juegan: 'w',
    fen: '4r3/p1R1Pp1p/1p3k2/5p2/r7/7P/P2R4/6K1 w - - 1 34',
    ultima: 'Te8',
    marca: ['f8', 'e8'],
    solucion: { from: 'd2', to: 'd6' },
    primera: 'Td6+',
    linea: '34.Td6+ Rg5 35.Td8 Txe7 36.Txe7',
    gana: true,
    valor: '+4,0',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: '',
    comprobado: 'Ejercicio 2tuIf de la base abierta de Lichess (CC0), rating 1611. Stockfish 16 a profundidad 18: Td6+ es la mejor (+4,0) y la segunda queda en -1,3.',
  },
  {
    n: 81,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0GPcj',
    tema: 'promotion',
    lichess: '0GPcj',
    rating: 1646,
    elo: 866,
    juegan: 'w',
    fen: '2b5/2P1Nk1p/8/1p6/2p5/7P/6PK/3r4 w - - 5 50',
    ultima: 'Rf7',
    marca: ['g8', 'f7'],
    solucion: { from: 'e7', to: 'c8' },
    primera: 'Cxc8',
    linea: '50.Cxc8 Td5 51.Cd6+ Re6 52.c8=D+',
    gana: true,
    valor: '+3,0',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'Hay algo sin defender, y hay que verlo antes que el rival.',
    comprobado: 'Ejercicio 0GPcj de la base abierta de Lichess (CC0), rating 1646. Stockfish 16 a profundidad 18: Cxc8 es la mejor (+3,0) y la segunda queda en -5,8.',
  },
  {
    n: 82,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0szr7',
    tema: 'promotion',
    lichess: '0szr7',
    rating: 1681,
    elo: 901,
    juegan: 'w',
    fen: '8/pp6/4Pk2/3p1P1p/4n3/1P3N1P/5r2/4R1K1 w - - 5 48',
    ultima: 'Tf2',
    marca: ['d2', 'f2'],
    solucion: { from: 'e1', to: 'e4' },
    primera: 'Txe4',
    linea: '48.Txe4 Txf3 49.e7 dxe4 50.e8=D',
    gana: true,
    valor: '+3,9',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 0szr7 de la base abierta de Lichess (CC0), rating 1681. Stockfish 16 a profundidad 18: Txe4 es la mejor (+3,9) y la segunda queda en -0,2.',
  },
  {
    n: 83,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0CIIu',
    tema: 'knightEndgame',
    lichess: '0CIIu',
    rating: 1700,
    elo: 920,
    juegan: 'b',
    fen: '8/k1K2pp1/P7/1P2NP2/2n4p/8/8/8 b - - 1 43',
    ultima: 'Ce5',
    marca: ['d7', 'e5'],
    solucion: { from: 'c4', to: 'e5' },
    primera: 'Cxe5',
    linea: '43…Cxe5 44.b6+ Rxa6 45.b7 Cd7 46.Rxd7 Rxb7',
    gana: true,
    valor: '+6,2',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Es una desviación: se aleja al defensor de lo que defendía.',
    comprobado: 'Ejercicio 0CIIu de la base abierta de Lichess (CC0), rating 1700. Stockfish 16 a profundidad 18: Cxe5 es la mejor (+6,2) y la segunda queda en -0,0.',
  },
  {
    n: 84,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_1f1SN',
    tema: 'trappedPiece',
    lichess: '1f1SN',
    rating: 1702,
    elo: 922,
    juegan: 'b',
    fen: 'r4rk1/p2n1p1p/2pb2p1/qp4PP/3PB3/3QBN2/bPP2P2/2KR3R b - - 0 17',
    ultima: 'h5',
    marca: ['h4', 'h5'],
    solucion: { from: 'a2', to: 'c4' },
    primera: 'Ac4',
    linea: '17…Ac4 18.Dc3 Ab4 19.Dxb4 Dxb4',
    gana: true,
    valor: '+3,8',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 1f1SN de la base abierta de Lichess (CC0), rating 1702. Stockfish 16 a profundidad 18: Ac4 es la mejor (+3,8) y la segunda queda en 0,0.',
  },
  {
    n: 85,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2Jjxp',
    tema: 'rookEndgame',
    lichess: '2Jjxp',
    rating: 1715,
    elo: 935,
    juegan: 'w',
    fen: '8/2k3p1/3r4/8/4p1P1/4P1K1/3R4/8 w - - 5 58',
    ultima: 'Td6',
    marca: ['c6', 'd6'],
    solucion: { from: 'd2', to: 'd6' },
    primera: 'Txd6',
    linea: '58.Txd6 Rxd6 59.Rf4 Rd5 60.Rf5',
    gana: true,
    valor: '+3,8',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: '',
    comprobado: 'Ejercicio 2Jjxp de la base abierta de Lichess (CC0), rating 1715. Stockfish 16 a profundidad 18: Txd6 es la mejor (+3,8) y la segunda queda en +0,1.',
  },
  {
    n: 86,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_3EaHh',
    tema: 'pawnEndgame',
    lichess: '3EaHh',
    rating: 1716,
    elo: 936,
    juegan: 'b',
    fen: '8/8/1p1k4/p7/P4PK1/6P1/8/8 b - - 0 45',
    ultima: 'Rxg4',
    marca: ['f5', 'g4'],
    solucion: { from: 'b6', to: 'b5' },
    primera: 'b5',
    linea: '45…b5 46.axb5 a4 47.b6 a3 48.b7 Rc7',
    gana: true,
    valor: '+3,2',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 3EaHh de la base abierta de Lichess (CC0), rating 1716. Stockfish 16 a profundidad 18: b5 es la mejor (+3,2) y la segunda queda en -2,1.',
  },
  {
    n: 87,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_1Sqxc',
    tema: 'queenEndgame',
    lichess: '1Sqxc',
    rating: 1758,
    elo: 978,
    juegan: 'b',
    fen: '4q1k1/8/5p2/1p1p1Ppp/3P4/2PQ1PKP/8/8 b - - 1 35',
    ultima: 'Rg3',
    marca: ['h2', 'g3'],
    solucion: { from: 'e8', to: 'e1' },
    primera: 'De1+',
    linea: '35…De1+ 36.Rg2 h4',
    gana: true,
    valor: '+3,0',
    pista: 'Con damas, primero el rey propio a salvo de jaques; después, el peón.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 1Sqxc de la base abierta de Lichess (CC0), rating 1758. Stockfish 16 a profundidad 18: De1+ es la mejor (+3,0) y la segunda queda en +0,2.',
  },
  {
    n: 88,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0R69Q',
    tema: 'bishopEndgame',
    lichess: '0R69Q',
    rating: 1826,
    elo: 1046,
    juegan: 'w',
    fen: 'k7/8/PP6/3b1p2/1K2p3/3pB3/8/8 w - - 1 61',
    ultima: 'Ra8',
    marca: ['b8', 'a8'],
    solucion: { from: 'b4', to: 'c5' },
    primera: 'Rc5',
    linea: '61.Rc5 d2 62.Axd2 e3 63.Axe3',
    gana: true,
    valor: '+7,0',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 0R69Q de la base abierta de Lichess (CC0), rating 1826. Stockfish 16 a profundidad 18: Rc5 es la mejor (+7,0) y la segunda queda en +0,1.',
  },
  {
    n: 89,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0VNbA',
    tema: 'zugzwang',
    lichess: '0VNbA',
    rating: 2009,
    elo: 1229,
    juegan: 'b',
    fen: '8/1p6/p4k2/6pp/P3K3/1P3P1P/8/8 b - a3 0 37',
    ultima: 'a4',
    marca: ['a2', 'a4'],
    solucion: { from: 'a6', to: 'a5' },
    primera: 'a5',
    linea: '37…a5 38.f4 g4',
    gana: true,
    valor: '+4,3',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0VNbA de la base abierta de Lichess (CC0), rating 2009. Stockfish 16 a profundidad 18: a5 es la mejor (+4,3) y la segunda queda en 0,0.',
  },
  {
    n: 90,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0nhHm',
    tema: 'pawnEndgame',
    lichess: '0nhHm',
    rating: 2070,
    elo: 1290,
    juegan: 'w',
    fen: '8/p1p5/1p1pk1p1/1P3p2/P1PP3P/5pP1/6K1/8 w - - 0 32',
    ultima: 'gxf3+',
    marca: ['g4', 'f3'],
    solucion: { from: 'g2', to: 'f3' },
    primera: 'Rxf3',
    linea: '32.Rxf3 d5 33.cxd5+ Rxd5 34.Rf4',
    gana: true,
    valor: '+3,3',
    pista: 'Cuenta tiempos antes de mover: en un final de peones una sola jugada decide.',
    explica: '',
    comprobado: 'Ejercicio 0nhHm de la base abierta de Lichess (CC0), rating 2070. Stockfish 16 a profundidad 18: Rxf3 es la mejor (+3,3) y la segunda queda en +0,1.',
  },
  {
    n: 91,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2ok8E',
    tema: 'rookEndgame',
    lichess: '2ok8E',
    rating: 2109,
    elo: 1329,
    juegan: 'w',
    fen: '7R/8/3kp2P/3p4/3Kp3/4P3/8/7r w - - 1 46',
    ultima: 'Th1',
    marca: ['a1', 'h1'],
    solucion: { from: 'h6', to: 'h7' },
    primera: 'h7',
    linea: '46.h7 Rc7 47.Ta8 Txh7 48.Ta7+',
    gana: true,
    valor: '+4,3',
    pista: 'En un final de torres gana la torre activa: ¿dónde molesta más la tuya?',
    explica: 'La clave es una jugada tranquila: sin jaque ni captura, pero sin defensa.',
    comprobado: 'Ejercicio 2ok8E de la base abierta de Lichess (CC0), rating 2109. Stockfish 16 a profundidad 18: h7 es la mejor (+4,3) y la segunda queda en -0,1.',
  },
  {
    n: 92,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_081MG',
    tema: 'knightEndgame',
    lichess: '081MG',
    rating: 2112,
    elo: 1332,
    juegan: 'b',
    fen: '8/8/4p1kp/3pP1P1/3P3K/1n6/4N3/8 b - - 0 64',
    ultima: 'g5',
    marca: ['g4', 'g5'],
    solucion: { from: 'h6', to: 'g5' },
    primera: 'hxg5+',
    linea: '64…hxg5+ 65.Rg4 Rh6',
    gana: true,
    valor: '+3,4',
    pista: 'El caballo es lento: cuenta cuántos saltos necesita cada uno para llegar.',
    explica: 'Es una jugada defensiva precisa: la única que sostiene la posición.',
    comprobado: 'Ejercicio 081MG de la base abierta de Lichess (CC0), rating 2112. Stockfish 16 a profundidad 18: hxg5+ es la mejor (+3,4) y la segunda queda en 0,0.',
  },
  {
    n: 93,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2NV3W',
    tema: 'queenEndgame',
    lichess: '2NV3W',
    rating: 2115,
    elo: 1335,
    juegan: 'b',
    fen: '8/4k3/4P1Qp/3P4/6PP/1p6/1P2q3/6K1 b - - 4 57',
    ultima: 'Rg1',
    marca: ['g2', 'g1'],
    solucion: { from: 'e2', to: 'd1' },
    primera: 'Dd1+',
    linea: '57…Dd1+ 58.Rf2 Dc2+ 59.Dxc2 bxc2',
    gana: true,
    valor: '+4,6',
    pista: 'Con damas, primero el rey propio a salvo de jaques; después, el peón.',
    explica: 'El peón avanzado decide: hay que empujarlo o aprovecharlo a tiempo.',
    comprobado: 'Ejercicio 2NV3W de la base abierta de Lichess (CC0), rating 2115. Stockfish 16 a profundidad 18: Dd1+ es la mejor (+4,6) y la segunda queda en 0,0.',
  },
  {
    n: 94,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_1ZyjF',
    tema: 'bishopEndgame',
    lichess: '1ZyjF',
    rating: 2169,
    elo: 1389,
    juegan: 'w',
    fen: '8/8/2pb2K1/7P/3k4/1p4P1/8/2B5 w - - 1 58',
    ultima: 'Ad6',
    marca: ['e7', 'd6'],
    solucion: { from: 'c1', to: 'b2' },
    primera: 'Ab2+',
    linea: '58.Ab2+ Rd3 59.h6',
    gana: true,
    valor: '+3,3',
    pista: 'En un final de alfiles mandan los colores: ¿qué casillas controla tu alfil y cuáles no?',
    explica: '',
    comprobado: 'Ejercicio 1ZyjF de la base abierta de Lichess (CC0), rating 2169. Stockfish 16 a profundidad 18: Ab2+ es la mejor (+3,3) y la segunda queda en +0,0.',
  },
  {
    n: 95,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_2dWze',
    tema: 'promotion',
    lichess: '2dWze',
    rating: 2292,
    elo: 1512,
    juegan: 'b',
    fen: '1knr2r1/p6p/Pp1b4/3Q4/7P/4B3/1P3Pp1/R4RK1 b - - 1 29',
    ultima: 'Rg1',
    marca: ['h1', 'g1'],
    solucion: { from: 'd6', to: 'h2' },
    primera: 'Ah2+',
    linea: '29…Ah2+ 30.Rxh2 gxf1=C+ 31.Txf1 Txd5',
    gana: true,
    valor: '+5,1',
    pista: 'Cuenta cuántas jugadas faltan para coronar y quién llega primero.',
    explica: 'Es una atracción: se arrastra a una pieza (a menudo el rey) a una casilla fatal.',
    comprobado: 'Ejercicio 2dWze de la base abierta de Lichess (CC0), rating 2292. Stockfish 16 a profundidad 18: Ah2+ es la mejor (+5,1) y la segunda queda en -5,1.',
  },
  {
    n: 96,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_33C6I',
    tema: 'trappedPiece',
    lichess: '33C6I',
    rating: 2313,
    elo: 1533,
    juegan: 'w',
    fen: '5r1k/1p4p1/p2p3p/4p2r/2P2P1q/1P6/P3Q1PP/3R1RK1 w - - 1 27',
    ultima: 'Dh4',
    marca: ['f6', 'h4'],
    solucion: { from: 'g2', to: 'g4' },
    primera: 'g4',
    linea: '27.g4 exf4 28.gxh5',
    gana: true,
    valor: '+4,7',
    pista: 'Mira las casillas de cada pieza rival: una se quedó sin salida.',
    explica: 'Una pieza rival queda atrapada, sin casilla adonde ir.',
    comprobado: 'Ejercicio 33C6I de la base abierta de Lichess (CC0), rating 2313. Stockfish 16 a profundidad 18: g4 es la mejor (+4,7) y la segunda queda en +0,6.',
  },
  {
    n: 97,
    uso: 'mixto',
    capitulo: 0,
    id: 'gp_0yUTj',
    tema: 'zugzwang',
    lichess: '0yUTj',
    rating: 2393,
    elo: 1613,
    juegan: 'b',
    fen: '8/8/3p4/2b1p3/1RK1P3/3P4/8/2k5 b - - 0 85',
    ultima: 'Txb4',
    marca: ['b2', 'b4'],
    solucion: { from: 'c5', to: 'b4' },
    primera: 'Axb4',
    linea: '85…Axb4 86.Rxb4 Rc2 87.Rc4 Rd2 88.d4 Re3 89.dxe5 dxe5 90.Rd5 Rf4',
    gana: true,
    valor: '+7,1',
    pista: 'A veces lo mejor es pasar el turno: ¿qué jugada deja al rival sin jugadas buenas?',
    explica: 'Es un zugzwang: al rival le toca mover y cualquier jugada lo empeora.',
    comprobado: 'Ejercicio 0yUTj de la base abierta de Lichess (CC0), rating 2393. Stockfish 16 a profundidad 18: Axb4 es la mejor (+7,1) y la segunda queda en -5,0.',
  },
];
