/* ===== Las partidas del libro, en «Ganar con poco» =====
 *
 * GENERADO por herramientas/ganar-con-poco-partidas.js — no se edita a mano.
 * Las jugadas, del PGN comprobado con chess.js; los comentarios, propios; los
 * momentos clave, confirmados con Stockfish. Lo usa el libro
 * (herramientas/ganar-con-poco-pdf.js).
 */
window.GANAR_CON_POCO_PARTIDAS = [
 {
  "n": 1,
  "id": "gp-p1",
  "titulo": "Andersson – Potkin: la pieza activa manda",
  "tema": "Piezas activas contra piezas pasivas",
  "blancas": "Ulf Andersson",
  "negras": "Vladimir Potkin",
  "evento": "Estambul, 2003",
  "resultado": "1-0",
  "apertura": "Apertura Catalana",
  "resumen": "Una Catalana tranquila, con el material igualado durante casi toda la partida. Ulf Andersson no busca ningún golpe: cambia lo que le conviene, deja a su caballo en la casilla d3, desde donde cuida y ataca a la vez, y gana un peón del flanco de dama que queda pasado. Después viene la parte más instructiva: un final largo de torre y caballo en el que las blancas mejoran de a poco, repiten jugadas para ganar tiempo en el reloj y empujan el peón pasado cuando el rival ya no puede hacer nada.",
  "ideas": [
   "Con el material igual, la diferencia la hace qué piezas trabajan y cuáles solo defienden.",
   "Un peón pasado en el flanco de dama, lejos de los reyes, vale cada vez más a medida que se cambian piezas.",
   "En un final ganado no hay apuro: se puede repetir jugadas para ordenar las ideas antes del paso decisivo."
  ],
  "lecciones": [
   "Antes de cambiar piezas, pregúntate cuál queda activa y cuál pasiva después del cambio.",
   "Cuando tengas un peón pasado lejos de los reyes, lleva tu torre a apoyarlo y tu rey al centro."
  ],
  "jugadas": [
   "Nf3",
   "d5",
   "d4",
   "Nf6",
   "c4",
   "e6",
   "g3",
   "dxc4",
   "Qa4+",
   "c6",
   "Qxc4",
   "b5",
   "Qd3",
   "Bb7",
   "Bg2",
   "Nbd7",
   "O-O",
   "a6",
   "Be3",
   "c5",
   "dxc5",
   "Bxc5",
   "Nbd2",
   "Qb6",
   "Bxc5",
   "Nxc5",
   "Qe3",
   "O-O",
   "Nb3",
   "Rfc8",
   "Ne5",
   "Bxg2",
   "Kxg2",
   "Nd5",
   "Qf3",
   "Qc7",
   "Nxc5",
   "Qxe5",
   "Nd3",
   "Qd6",
   "Rac1",
   "h6",
   "Rfd1",
   "Qe7",
   "a3",
   "a5",
   "Qe4",
   "Rab8",
   "Qd4",
   "Qb7",
   "Kg1",
   "b4",
   "a4",
   "Rc6",
   "Rc5",
   "Rxc5",
   "Qxc5",
   "Rc8",
   "Qxa5",
   "Ra8",
   "Qb5",
   "Qxb5",
   "axb5",
   "Rb8",
   "Rc1",
   "Rxb5",
   "Rc8+",
   "Kh7",
   "e4",
   "Nf6",
   "f3",
   "g5",
   "g4",
   "Rb7",
   "Kf2",
   "h5",
   "h3",
   "hxg4",
   "hxg4",
   "b3",
   "Nc5",
   "Ra7",
   "Ke3",
   "Kg7",
   "Rb8",
   "Rc7",
   "Nd3",
   "Nd7",
   "Rxb3",
   "Kf6",
   "Rc3",
   "Rb7",
   "Kd4",
   "Ra7",
   "Ra3",
   "Rc7",
   "Rc3",
   "Ra7",
   "Ra3",
   "Rc7",
   "b4",
   "Rc2",
   "Ra7",
   "Nb6",
   "Ra6",
   "Nd7",
   "Ra7",
   "Nb6",
   "Ra6",
   "Nd7",
   "b5",
   "Rd2",
   "Kc3",
   "Rd1",
   "Ra7",
   "Nb6",
   "Ra6",
   "Nd7",
   "Ra7",
   "Nb6",
   "Rb7",
   "Na4+",
   "Kb4",
   "Rxd3",
   "Kxa4",
   "Rxf3",
   "Rc7",
   "Rf1",
   "b6",
   "Ke5",
   "Rc4",
   "Rb1",
   "Rb4",
   "Ra1+",
   "Kb5",
   "Ra8",
   "b7",
   "Rb8",
   "Kc6",
   "Kf4",
   "Kc7",
   "Rg8",
   "Rd4",
   "f6",
   "b8=Q",
   "Rxb8",
   "Kxb8",
   "Kxg4",
   "Kc7",
   "e5",
   "Ra4",
   "Kf4",
   "Kd6",
   "g4",
   "Kd5",
   "g3",
   "Ra8",
   "f5",
   "Rf8",
   "g2",
   "Rxf5+"
  ],
  "comentarios": {
   "39": "El caballo encuentra su casilla: d3.",
   "59": "Las blancas ganan un peón y queda un peón pasado en la columna a."
  },
  "claves": [
   {
    "ply": 39,
    "fen": "r1r3k1/5ppp/p3p3/1pNnq3/8/5QP1/PP2PPKP/R4R2 w - - 0 20",
    "juegan": "w",
    "jugada": "20.Cd3",
    "pregunta": "El caballo blanco de c5 está bien puesto, pero puede estar mejor. ¿Adónde lo llevarías?",
    "explicacion": "20.Cd3 ataca la dama de e5 y deja al caballo en una casilla central desde la que vigila b4, c5, e5 y f4. Esta casilla será su base durante casi toda la partida. Stockfish 16 a profundidad 16: Cd3 es la mejor (+0,2) y la segunda queda 1,6 peor."
   },
   {
    "ply": 59,
    "fen": "2r3k1/1q3pp1/4p2p/p1Qn4/Pp6/3N2P1/1P2PP1P/3R2K1 w - - 1 30",
    "juegan": "w",
    "jugada": "30.Dxa5",
    "pregunta": "¿Cómo aprovechan las blancas la presión que tienen en el flanco de dama?",
    "explicacion": "30.Dxa5 gana un peón, y además el peón blanco de a4 queda pasado: ningún peón negro puede frenarlo. Stockfish 16 a profundidad 16: Dxa5 es la mejor (+0,6) y la segunda queda 0,9 peor."
   },
   {
    "ply": 127,
    "fen": "8/1R3p2/4pk2/1P4p1/K3P1P1/5r2/8/8 w - - 0 64",
    "juegan": "w",
    "jugada": "64.Tc7",
    "pregunta": "Final de torres con un peón de más. ¿Dónde pondrías la torre?",
    "explicacion": "64.Tc7 le deja libre la columna b al peón, que ahora puede avanzar, y la torre sigue en la séptima fila atacando el peón de f7. Stockfish 16 a profundidad 16: Tc7 es la mejor (+3,0) y la segunda queda 0,8 peor."
   }
  ]
 },
 {
  "n": 2,
  "id": "gp-p2",
  "titulo": "Petrosian – Botvinnik: el peón débil de e6",
  "tema": "Una debilidad y el rey en el centro",
  "blancas": "Tigran Petrosian",
  "negras": "Mijaíl Botvinnik",
  "evento": "Match por el campeonato del mundo, Moscú 1963 (5.ª partida)",
  "resultado": "1-0",
  "apertura": "Defensa Grunfeld",
  "resumen": "Petrosian cambia las damas temprano: pierde el enroque, pero a cambio deja a las negras con un peón débil en e6. Sin damas, el rey ya no corre peligro y se convierte en una pieza más. Las blancas fijan los peones del flanco de dama, centralizan el rey y, cuando la posición lo pide, devuelven material para mantener sus piezas activas. Es una de las partidas más citadas para mostrar cómo una sola debilidad, bien explotada, alcanza para ganar.",
  "ideas": [
   "Un peón aislado o retrasado obliga al rival a defenderlo con piezas, que dejan de hacer otra cosa.",
   "Sin damas, el rey es una pieza de ataque: el que lo lleva antes al centro suele mandar.",
   "Es mejor tener las piezas activas con el material igual que un peón de más con las piezas pasivas."
  ],
  "lecciones": [
   "Cuando cambies damas, piensa enseguida adónde va tu rey.",
   "Fija los peones del rival antes de atacarlos: un peón fijo no puede escaparse ni cambiarse."
  ],
  "jugadas": [
   "c4",
   "g6",
   "d4",
   "Nf6",
   "Nc3",
   "d5",
   "Nf3",
   "Bg7",
   "e3",
   "O-O",
   "Be2",
   "dxc4",
   "Bxc4",
   "c5",
   "d5",
   "e6",
   "dxe6",
   "Qxd1+",
   "Kxd1",
   "Bxe6",
   "Bxe6",
   "fxe6",
   "Ke2",
   "Nc6",
   "Rd1",
   "Rad8",
   "Rxd8",
   "Rxd8",
   "Ng5",
   "Re8",
   "Nge4",
   "Nxe4",
   "Nxe4",
   "b6",
   "Rb1",
   "Nb4",
   "Bd2",
   "Nd5",
   "a4",
   "Rc8",
   "b3",
   "Bf8",
   "Rc1",
   "Be7",
   "b4",
   "c4",
   "b5",
   "Kf7",
   "Bc3",
   "Ba3",
   "Rc2",
   "Nxc3+",
   "Rxc3",
   "Bb4",
   "Rc2",
   "Ke7",
   "Nd2",
   "c3",
   "Ne4",
   "Ba5",
   "Kd3",
   "Rd8+",
   "Kc4",
   "Rd1",
   "Nxc3",
   "Rh1",
   "Ne4",
   "Rxh2",
   "Kd4",
   "Kd7",
   "g3",
   "Bb4",
   "Ke5",
   "Rh5+",
   "Kf6",
   "Be7+",
   "Kg7",
   "e5",
   "Rc6",
   "Rh1",
   "Kf7",
   "Ra1",
   "Re6",
   "Bd8",
   "Rd6+",
   "Kc8",
   "Ke8",
   "Bc7",
   "Rc6",
   "Rd1",
   "Ng5",
   "Rd8+",
   "Kf7",
   "Rd7+",
   "Kg8"
  ],
  "comentarios": {
   "47": "Los peones del flanco de dama quedan fijos.",
   "69": "El rey blanco entra en juego."
  },
  "claves": [
   {
    "ply": 47,
    "fen": "2r3k1/p3b2p/1p2p1p1/3n4/PPp1N3/4P3/3BKPPP/2R5 w - - 0 24",
    "juegan": "w",
    "jugada": "24.b5",
    "pregunta": "¿Cómo mejoran las blancas su flanco de dama?",
    "explicacion": "24.b5 deja fijos los peones negros del flanco de dama y le quita la casilla c6 a las piezas negras. Stockfish 16 a profundidad 16: b5 es la mejor (+0,3) y la segunda queda 0,7 peor."
   },
   {
    "ply": 69,
    "fen": "8/p3k2p/1p2p1p1/bP6/P1K1N3/4P3/2R2PPr/8 w - - 0 35",
    "juegan": "w",
    "jugada": "35.Rd4",
    "pregunta": "¿Qué pieza blanca todavía puede mejorar?",
    "explicacion": "35.Rd4 lleva el rey al centro, junto a las casillas d5 y e5, donde apoya al caballo y presiona los peones negros. Stockfish 16 a profundidad 16: Rd4 es la mejor (+2,2) y la segunda queda 1,0 peor."
   }
  ]
 },
 {
  "n": 3,
  "id": "gp-p3",
  "titulo": "Matulović – Botvinnik: las casillas que deja un peón",
  "tema": "Una red de casillas débiles",
  "blancas": "Milan Matulović",
  "negras": "Mijaíl Botvinnik",
  "evento": "Belgrado, 1969",
  "resultado": "0-1",
  "apertura": "Defensa Pirc",
  "resumen": "Un avance de peón de la apertura, hecho para cuidar una sola casilla, deja débiles varias casillas del mismo color. Botvinnik las ocupa una por una con sus piezas, cambia la pieza blanca más activa cuando puede y lleva la partida a un final donde su caballo y su rey entran por las casillas que ningún peón blanco puede cuidar.",
  "ideas": [
   "Cada avance de peón deja casillas que ya no podrá defender: hay que saber cuáles.",
   "Un caballo apoyado por un peón, en una casilla que ningún peón rival puede atacar, vale más que una torre pasiva.",
   "Cambiar la pieza más activa del rival suele ser un buen negocio."
  ],
  "lecciones": [
   "Antes de avanzar un peón, di qué casillas deja de cuidar.",
   "Busca en la posición del rival una casilla que ningún peón suyo pueda atacar, y lleva ahí un caballo."
  ],
  "jugadas": [
   "e4",
   "g6",
   "d4",
   "Bg7",
   "Nf3",
   "d6",
   "Nc3",
   "Nf6",
   "Be2",
   "O-O",
   "O-O",
   "Nc6",
   "h3",
   "e5",
   "dxe5",
   "dxe5",
   "Qxd8",
   "Rxd8",
   "Bg5",
   "Be6",
   "Rfd1",
   "h6",
   "Be3",
   "Ne8",
   "Ne1",
   "Nd4",
   "Bf1",
   "Rd7",
   "Ne2",
   "Rad8",
   "Bxd4",
   "exd4",
   "Nf4",
   "Re7",
   "Nxe6",
   "Rxe6",
   "f3",
   "Nd6",
   "Nd3",
   "Re7",
   "Re1",
   "h5",
   "g4",
   "hxg4",
   "hxg4",
   "g5",
   "b3",
   "Nb5",
   "Re2",
   "Be5",
   "a4",
   "Nc3",
   "Rd2",
   "Bd6",
   "Bg2",
   "c6",
   "a5",
   "a6",
   "Kf2",
   "Kg7",
   "Rh1",
   "f6",
   "Rh5",
   "Rh8",
   "Rxh8",
   "Kxh8",
   "Kf1",
   "Kg7",
   "Nb2",
   "Be5",
   "Nc4",
   "Kf8",
   "Kg1",
   "Rh7",
   "Bf1",
   "Ke7",
   "Nxe5",
   "fxe5",
   "Bc4",
   "Kd6",
   "Kg2",
   "Rh6",
   "Bf7",
   "Kc5",
   "Be8",
   "Kb4",
   "Bd7",
   "Nb1",
   "Rd3",
   "Na3",
   "f4",
   "Nxc2",
   "Kg1",
   "gxf4",
   "Bf5",
   "Ne3",
   "g5",
   "Rh5",
   "g6",
   "Nxf5",
   "exf5",
   "Rxf5"
  ],
  "comentarios": {
   "52": "El caballo negro llega a c3 y ya no se va."
  },
  "claves": [
   {
    "ply": 52,
    "fen": "3r2k1/ppp1rp2/8/1n2b1p1/P2pP1P1/1P1N1P2/2P1R3/R4BK1 b - a3 0 26",
    "juegan": "b",
    "jugada": "26…Cc3",
    "pregunta": "Las casillas negras del campo blanco están débiles. ¿Dónde se instala el caballo de b5?",
    "explicacion": "26…Cc3 instala el caballo en una casilla apoyada por el peón de d4, de la que ningún peón blanco puede echarlo, y ataca la torre de e2 y los peones de a4 y e4. Stockfish 16 a profundidad 16: Cc3 es la mejor (-0,6) y la segunda queda 0,8 peor."
   },
   {
    "ply": 90,
    "fen": "8/1p1B4/p1p4r/P3p1p1/1k1pP1P1/1P1R1P2/2P3K1/1n6 b - - 11 45",
    "juegan": "b",
    "jugada": "45…Ca3",
    "pregunta": "El caballo negro está lejos, en b1. ¿Cómo vuelve al juego con ganancia de tiempo?",
    "explicacion": "45…Ca3 devuelve el caballo al juego atacando el peón de c2, que ninguna pieza blanca defiende. Stockfish 16 a profundidad 16: Ca3 es la mejor (-4,4) y la segunda queda 1,0 peor."
   }
  ]
 },
 {
  "n": 4,
  "id": "gp-p4",
  "titulo": "Kárpov – Krámnik: torre y caballo contra torre y alfil",
  "tema": "Cuando el caballo vale más que el alfil",
  "blancas": "Anatoli Kárpov",
  "negras": "Vladímir Krámnik",
  "evento": "Viena, 1996",
  "resultado": "1-0",
  "apertura": "Defensa Eslava",
  "resumen": "Se suele decir que torre y alfil son mejores que torre y caballo. Kárpov muestra la excepción: con el centro abierto, su caballo encuentra casillas, su rey se mete entre los peones negros y la ventaja pequeña de la apertura se convierte, de a poco, en un final ganado. La jugada 12 no viene escrita en el libro (va en un diagrama): 12.Axe4 h6 es la única pareja de jugadas que deja legal el resto de la partida.",
  "ideas": [
   "Las reglas sobre el valor de las piezas son promedios: la posición concreta manda.",
   "Con el rey activo y el caballo bien apoyado, la torre y el caballo pueden más que la torre y el alfil.",
   "La ventaja pequeña del medio juego se cobra en el final, con el rey."
  ],
  "lecciones": [
   "Cuando cambies piezas menores, piensa en qué final queda: caballo o alfil, ¿cuál tendrá más casillas?",
   "En el final de torres y piezas menores, lleva el rey hacia los peones del rival."
  ],
  "jugadas": [
   "d4",
   "d5",
   "c4",
   "c6",
   "Nc3",
   "Nf6",
   "Nf3",
   "e6",
   "e3",
   "Nbd7",
   "Qc2",
   "Bd6",
   "Bd3",
   "O-O",
   "O-O",
   "e5",
   "cxd5",
   "cxd5",
   "e4",
   "dxe4",
   "Nxe4",
   "Nxe4",
   "Bxe4",
   "h6",
   "Be3",
   "exd4",
   "Bh7+",
   "Kh8",
   "Bxd4",
   "Nf6",
   "Bf5",
   "Bxf5",
   "Qxf5",
   "Qc8",
   "Qb5",
   "a6",
   "Qb6",
   "Qc7",
   "Qxc7",
   "Bxc7",
   "Bxf6",
   "gxf6",
   "Rfe1",
   "Rfe8",
   "Rad1",
   "Rxe1+",
   "Rxe1",
   "Rd8",
   "g3",
   "Rd7",
   "Re2",
   "Kg7",
   "Nh4",
   "Rd5",
   "Re7",
   "Rc5",
   "Rd7",
   "b5",
   "b4",
   "Rc2",
   "Nf5+",
   "Kg6",
   "Ne3",
   "Rc1+",
   "Kg2",
   "Be5",
   "Ra7",
   "Rc6",
   "Nd5",
   "Bd6",
   "a3",
   "Kf5",
   "Ne3+",
   "Kg6",
   "Kf3",
   "Be5",
   "Nd5",
   "Kg7",
   "Ne7",
   "Rc3+",
   "Kg4",
   "Rxa3",
   "f4",
   "Bc3",
   "Kh5",
   "Bxb4",
   "Nf5+",
   "Kg8",
   "Ra8+",
   "Kh7",
   "Ra7",
   "Kg8",
   "Nxh6+",
   "Kf8",
   "Rxf7+",
   "Ke8",
   "Kg6",
   "Bc3",
   "Nf5",
   "b4",
   "Rb7",
   "Ra2",
   "h4",
   "a5",
   "h5",
   "a4",
   "h6",
   "Rh2",
   "h7",
   "Kd8",
   "Nh4",
   "f5",
   "Rxb4",
   "Rh3",
   "Rxa4",
   "Rxg3+",
   "Kxf5"
  ],
  "comentarios": {
   "65": "Sin damas, el rey se pone en marcha."
  },
  "claves": [
   {
    "ply": 29,
    "fen": "r1bq1r1k/pp1n1ppB/3b3p/8/3p4/4BN2/PPQ2PPP/R4RK1 w - - 2 15",
    "juegan": "w",
    "jugada": "15.Axd4",
    "pregunta": "Hay dos formas de recuperar el peón de d4. ¿Cuál conserva la ventaja?",
    "explicacion": "15.Axd4 recupera el peón con el alfil: el caballo se queda en f3 y el alfil queda centralizado en d4, apuntando al peón de g7. Stockfish 16 a profundidad 16: Axd4 es la mejor (+0,4) y la segunda queda 0,8 peor."
   },
   {
    "ply": 65,
    "fen": "8/2bR1p2/p4pkp/1p6/1P6/4N1P1/P4P1P/2r3K1 w - - 5 33",
    "juegan": "w",
    "jugada": "33.Rg2",
    "pregunta": "Ya se cambiaron las damas. ¿Qué hace el rey blanco?",
    "explicacion": "33.Rg2 saca el rey de la primera fila, donde la torre negra lo molesta, y lo acerca al centro. Stockfish 16 a profundidad 16: Rg2 es la mejor (+0,6) y la segunda queda 0,6 peor."
   },
   {
    "ply": 81,
    "fen": "8/R3Npk1/p4p1p/1p2b3/1P6/P1r2KP1/5P1P/8 w - - 9 41",
    "juegan": "w",
    "jugada": "41.Rg4",
    "pregunta": "El rey blanco puede ser la pieza decisiva. ¿Hacia dónde va?",
    "explicacion": "41.Rg4 mete el rey en el flanco de rey, rumbo a f5 y h5, para atacar los peones negros de cerca. Stockfish 16 a profundidad 16: Rg4 es la mejor (+1,3) y la segunda queda 0,9 peor."
   }
  ]
 },
 {
  "n": 5,
  "id": "gp-p5",
  "titulo": "Sálov – Short: las casillas negras",
  "tema": "Debilidades de un color",
  "blancas": "Valeri Sálov",
  "negras": "Nigel Short",
  "evento": "Barcelona, 1989",
  "resultado": "1-0",
  "apertura": "Defensa Holandesa",
  "resumen": "En una Holandesa con la estructura «stonewall», las blancas cambian los alfiles de casillas negras y las casillas de ese color quedan débiles en el campo negro. Sálov pone sus caballos ahí, aprieta el peón de e6 con las torres y, como pasa siempre, las negras crean nuevas debilidades al tapar las que ya tenían. La partida termina con un final técnico de dama contra torre, que las blancas ganan sin apuro.",
  "ideas": [
   "Cuando se cambia el alfil que cuidaba un color, todas las casillas de ese color se vuelven débiles.",
   "Limitar las piezas del rival vale tanto como darles libertad a las propias.",
   "Al defender una debilidad suelen aparecer otras: el que defiende siempre llega tarde."
  ],
  "lecciones": [
   "Si tu rival cambia su alfil bueno, busca las casillas de ese color para tus caballos.",
   "Aprende la técnica de dama contra torre: aparece más de lo que parece."
  ],
  "jugadas": [
   "d4",
   "e6",
   "c4",
   "f5",
   "g3",
   "Nf6",
   "Bg2",
   "Be7",
   "Nf3",
   "O-O",
   "O-O",
   "d5",
   "b3",
   "c6",
   "Ba3",
   "Bd7",
   "Qc1",
   "Be8",
   "Bxe7",
   "Qxe7",
   "Qa3",
   "Qxa3",
   "Nxa3",
   "a5",
   "Ne5",
   "Nbd7",
   "Nd3",
   "Bh5",
   "Rfe1",
   "g5",
   "Rac1",
   "Ne4",
   "f3",
   "Nd6",
   "c5",
   "Nf7",
   "f4",
   "Rfe8",
   "Bf3",
   "Nf6",
   "Rc2",
   "Re7",
   "Nb1",
   "Bxf3",
   "exf3",
   "g4",
   "fxg4",
   "fxg4",
   "Rce2",
   "Rae8",
   "Na3",
   "Nh6",
   "Nc2",
   "Nf5",
   "Nf2",
   "h5",
   "Kg2",
   "Kf7",
   "Rd1",
   "Nh7",
   "Ne3",
   "Kf6",
   "h3",
   "gxh3+",
   "Kxh3",
   "Nf8",
   "Kg2",
   "Ng6",
   "Nh3",
   "Kg7",
   "Kf3",
   "Rf8",
   "Nxf5+",
   "Rxf5",
   "Rde1",
   "Kf6",
   "a3",
   "Re8",
   "Re3",
   "Re7",
   "b4",
   "axb4",
   "axb4",
   "Re8",
   "R1e2",
   "Re7",
   "Re1",
   "Re8",
   "b5",
   "cxb5",
   "R1e2",
   "b4",
   "Re1",
   "Re7",
   "Rb3",
   "e5",
   "Rxb4",
   "exf4",
   "Rb6+",
   "Kf7",
   "Rxe7+",
   "Nxe7",
   "Nxf4",
   "Nc6",
   "Rxb7+",
   "Ke8",
   "Ke3",
   "Rg5",
   "Ne2",
   "Rg4",
   "Rh7",
   "Re4+",
   "Kd3",
   "Nb4+",
   "Kd2",
   "Nc6",
   "Kd3",
   "Nb4+",
   "Kc3",
   "Nc6",
   "Rh6",
   "Ne7",
   "Nf4",
   "Re3+",
   "Kb4",
   "Rxg3",
   "c6",
   "Rg4",
   "Rh8+",
   "Kf7",
   "Rh7+",
   "Ke8",
   "c7",
   "Rxf4",
   "Rxe7+",
   "Kxe7",
   "c8=Q",
   "Rxd4+",
   "Kb5",
   "Re4",
   "Qf5",
   "Re6",
   "Qxh5",
   "d4",
   "Qh4+",
   "Kf7",
   "Kc5",
   "d3",
   "Qh7+",
   "Kf6",
   "Qxd3",
   "Ke7",
   "Qg3",
   "Rf6",
   "Qg4",
   "Re6",
   "Qg7+",
   "Ke8",
   "Kd5",
   "Rb6",
   "Qc7",
   "Rg6",
   "Ke5",
   "Kf8",
   "Kf5",
   "Rg7",
   "Qd8+",
   "Kf7",
   "Qh8",
   "Rg2",
   "Qf6+",
   "Kg8",
   "Qc6",
   "Rg1",
   "Kf6",
   "Rg7",
   "Qa8+",
   "Kh7",
   "Qe8",
   "Ra7",
   "Qh5+",
   "Kg8",
   "Qg4+",
   "Kh7",
   "Qh3+",
   "Kg8",
   "Qg3+",
   "Kh7",
   "Qh2+",
   "Kg8",
   "Qb8+",
   "Kh7",
   "Qxa7+",
   "Kh8",
   "Qg7#"
  ],
  "comentarios": {
   "75": "Las dos torres contra el peón de e6."
  },
  "claves": [
   {
    "ply": 75,
    "fen": "8/1p2r1k1/2p1p1n1/p1Pp1r1p/3P1P2/1P3KPN/P3R3/3R4 w - - 0 38",
    "juegan": "w",
    "jugada": "38.Tde1",
    "pregunta": "El peón de e6 está débil. ¿Cómo aumentan la presión las blancas?",
    "explicacion": "38.Tde1 dobla las torres en la columna e, contra el peón débil de e6. Stockfish 16 a profundidad 16: Tde1 es la mejor (+1,1) y la segunda queda 0,6 peor."
   },
   {
    "ply": 107,
    "fen": "4k3/1R6/2n5/2Pp1r1p/3P1N2/5KP1/8/8 w - - 1 54",
    "juegan": "w",
    "jugada": "54.Re3",
    "pregunta": "Final de torre y caballo. ¿Qué hace el rey blanco?",
    "explicacion": "54.Re3 lleva el rey hacia el centro: sigue defendiendo el caballo de f4 y se acerca a d3, junto a los peones del flanco de dama. Stockfish 16 a profundidad 16: Re3 es la mejor (+1,4) y la segunda queda 0,7 peor."
   }
  ]
 },
 {
  "n": 6,
  "id": "gp-p6",
  "titulo": "Kamsky – Lautier: la mejor estructura de peones",
  "tema": "Peones sanos contra peones débiles",
  "blancas": "Gata Kamsky",
  "negras": "Joël Lautier",
  "evento": "Las Palmas, 1994",
  "resultado": "1-0",
  "apertura": "Apertura Española",
  "resumen": "Una Española en la que las negras quedan con peones doblados. No hay nada que ganar de inmediato: Kamsky mantiene la tensión, lleva los caballos a casillas donde molestan y espera. La peor estructura de las negras obliga a sus piezas a defender, y cuando la posición se abre, la diferencia de actividad decide.",
  "ideas": [
   "Una estructura de peones peor obliga a las piezas a defender, y una pieza que defiende no ataca.",
   "No hace falta cambiar en el centro si la tensión molesta más al rival que a ti.",
   "Un caballo centralizado puede abrirle una fila o columna a una torre."
  ],
  "lecciones": [
   "Mira tus peones doblados o aislados: ¿qué pieza tuya está atada a defenderlos?",
   "Antes de cambiar en el centro, pregúntate a quién alivia el cambio."
  ],
  "jugadas": [
   "e4",
   "e5",
   "Nf3",
   "Nc6",
   "Bb5",
   "a6",
   "Ba4",
   "d6",
   "O-O",
   "Bg4",
   "c3",
   "Qf6",
   "Bxc6+",
   "bxc6",
   "d4",
   "Ne7",
   "Nbd2",
   "g5",
   "Re1",
   "Ng6",
   "Qa4",
   "Bd7",
   "dxe5",
   "dxe5",
   "Nc4",
   "g4",
   "Bg5",
   "Qe6",
   "Nfd2",
   "h5",
   "Qb3",
   "Bc5",
   "Na5",
   "Qxb3",
   "Ndxb3",
   "Bb6",
   "Rad1",
   "f6",
   "Be3",
   "O-O-O",
   "Nc4",
   "Bxe3",
   "fxe3",
   "Be6",
   "Nca5",
   "Bxb3",
   "axb3",
   "Ne7",
   "b4",
   "f5",
   "Rxd8+",
   "Rxd8",
   "exf5",
   "Nxf5",
   "e4",
   "Ne7",
   "Nc4",
   "Ng6",
   "Rf1",
   "h4",
   "g3",
   "h3",
   "Kf2",
   "Nf8",
   "Ke2",
   "Nd7",
   "Rf7",
   "c5",
   "Ne3",
   "cxb4",
   "cxb4",
   "Nb6",
   "Nf5",
   "Na4",
   "Ne7+",
   "Kb7",
   "Nd5",
   "Rc8",
   "Rg7",
   "Nb6",
   "Ne3",
   "Rd8",
   "Rxg4",
   "Na4",
   "Nd5",
   "Nb6",
   "Rh4",
   "Nxd5",
   "exd5",
   "Rxd5",
   "Rxh3",
   "Rd4",
   "Rh4",
   "e4",
   "Ke3",
   "Rxb4",
   "Rxe4",
   "Rxb2",
   "h4",
   "Rh2",
   "Kf4",
   "Kb6",
   "Kg5",
   "Rh3",
   "g4",
   "Kb5",
   "h5",
   "c5",
   "Re1",
   "c4",
   "Kh6",
   "c3",
   "g5"
  ],
  "comentarios": {
   "77": "Caballo y torre contra c7."
  },
  "claves": [
   {
    "ply": 17,
    "fen": "r3kb1r/2p1nppp/p1pp1q2/4p3/3PP1b1/2P2N2/PP3PPP/RNBQ1RK1 w kq - 1 9",
    "juegan": "w",
    "jugada": "9.Cbd2",
    "pregunta": "¿Cambiar en e5 o seguir desarrollando?",
    "explicacion": "9.Cbd2 desarrolla la última pieza menor y mantiene la tensión: cambiar en e5 habría aliviado a las negras. Stockfish 16 a profundidad 16: Cbd2 es la mejor (+0,8) y la segunda queda 0,5 peor."
   },
   {
    "ply": 41,
    "fen": "2kr3r/2pb4/pbp2pn1/N3p2p/4P1p1/1NP1B3/PP3PPP/3RR1K1 w - - 2 21",
    "juegan": "w",
    "jugada": "21.Cc4",
    "pregunta": "¿Adónde va el caballo de b3?",
    "explicacion": "21.Cc4 ataca el alfil de b6 y el peón de e5. Stockfish 16 a profundidad 16: Cc4 es la mejor (+0,8) y la segunda queda 0,6 peor."
   },
   {
    "ply": 77,
    "fen": "3r4/1kp1NR2/p7/4p3/nP2P1p1/6Pp/1P2K2P/8 w - - 5 39",
    "juegan": "w",
    "jugada": "39.Cd5",
    "pregunta": "¿Cómo aumentan las blancas la presión sobre el peón de c7?",
    "explicacion": "39.Cd5 centraliza el caballo, que ataca c7, y le abre la séptima a la torre de f7: el peón de c7 queda atacado dos veces y solo lo defiende el rey. Stockfish 16 a profundidad 16: Cd5 es la mejor (+0,8) y la segunda queda 1,3 peor."
   }
  ]
 },
 {
  "n": 7,
  "id": "gp-p7",
  "titulo": "Portisch – Beliavsky: la mayoría del flanco de dama",
  "tema": "Mayoría de peones y columna abierta",
  "blancas": "Lajos Portisch",
  "negras": "Alexander Beliavsky",
  "evento": "Tilburg, 1981",
  "resultado": "1-0",
  "apertura": "Defensa Eslava",
  "resumen": "En una Eslava, Portisch consigue una mayoría de peones en el flanco de dama, una torre en la columna c y una dama centralizada. Es una ventaja pequeña, pero sin contrajuego para las negras: las blancas la empujan hasta tener un peón pasado y, con el cambio de damas a la vista, la partida se decide.",
  "ideas": [
   "Una mayoría de peones es un peón pasado que todavía no nació.",
   "Un caballo en una casilla que ningún peón puede atacar es una espina en el campo rival.",
   "Con un peón pasado, cambiar damas suele favorecer al que lo tiene."
  ],
  "lecciones": [
   "Cuenta los peones de cada flanco al salir de la apertura: ¿dónde tienes la mayoría?",
   "Si tienes un peón pasado, busca cambiar las piezas que pueden frenarlo."
  ],
  "jugadas": [
   "d4",
   "d5",
   "c4",
   "c6",
   "Nc3",
   "Nf6",
   "cxd5",
   "cxd5",
   "Bf4",
   "Nc6",
   "e3",
   "Bf5",
   "Nf3",
   "e6",
   "Ne5",
   "Nd7",
   "Nxc6",
   "bxc6",
   "Be2",
   "Be7",
   "O-O",
   "O-O",
   "Rc1",
   "c5",
   "Nb5",
   "a6",
   "Nd6",
   "Bg6",
   "dxc5",
   "Nxc5",
   "Rxc5",
   "Bxd6",
   "Bxd6",
   "Qxd6",
   "Qd4",
   "Rac8",
   "b4",
   "Rxc5",
   "bxc5",
   "Qc6",
   "Rc1",
   "Rb8",
   "Qf4",
   "Rc8",
   "Qb4",
   "f6",
   "a4",
   "Rc7",
   "Qa5",
   "Be8",
   "h3",
   "Kf8",
   "Bd1",
   "Rc8",
   "Qc3",
   "h6",
   "a5",
   "Qb7",
   "Bg4",
   "Rc6",
   "Qd3",
   "Qc7",
   "Qa3",
   "Qb8",
   "Be2",
   "Kg8",
   "Bd3",
   "Qb7",
   "e4",
   "Qd7",
   "exd5",
   "exd5",
   "Be2",
   "Qe7",
   "Bf3",
   "Bf7",
   "Qb4",
   "Qc7",
   "Bd1",
   "Re6",
   "Bb3",
   "Re4",
   "Qb6",
   "Qf4",
   "Rb1",
   "Re2",
   "Rf1",
   "Kh7",
   "c6",
   "Be6",
   "Qxa6",
   "Rb2",
   "Qd3+",
   "Qf5",
   "Qd1",
   "Qg5",
   "Kh1",
   "Rd2",
   "Qe1",
   "Bc8",
   "c7",
   "Rb2",
   "Qc3",
   "Qd2",
   "Qxd2",
   "Rxd2",
   "Ra1",
   "Ba6",
   "Rc1",
   "Bc8",
   "Kg1",
   "Rb2",
   "Bc2+",
   "f5"
  ],
  "comentarios": {
   "27": "El caballo se instala en d6."
  },
  "claves": [
   {
    "ply": 27,
    "fen": "r2q1rk1/3nbppp/p3p3/1Npp1b2/3P1B2/4P3/PP2BPPP/2RQ1RK1 w - - 0 14",
    "juegan": "w",
    "jugada": "14.Cd6",
    "pregunta": "¿Dónde estaría mejor el caballo de b5?",
    "explicacion": "14.Cd6 instala el caballo en una casilla a la que ningún peón negro llega, y ataca el alfil de f5. Stockfish 16 a profundidad 16: Cd6 es la mejor (+0,6) y la segunda queda 0,5 peor."
   },
   {
    "ply": 83,
    "fen": "6k1/2q2bp1/p4p1p/P1Pp4/1Q2r3/1B5P/5PP1/2R3K1 w - - 10 42",
    "juegan": "w",
    "jugada": "42.Db6",
    "pregunta": "¿Cómo convierte Portisch su peón pasado de c5?",
    "explicacion": "42.Db6 ataca la dama de c7 y ofrece el cambio: con las damas fuera, el peón pasado de c5 es imparable. Stockfish 16 a profundidad 16: Db6 es la mejor (+2,1) y la segunda queda 0,7 peor."
   }
  ]
 },
 {
  "n": 8,
  "id": "gp-p8",
  "titulo": "Spassky – Petrosian: los peones de d5 y e5",
  "tema": "Presión constante sobre peones fijos",
  "blancas": "Boris Spassky",
  "negras": "Tigran Petrosian",
  "evento": "Match por el campeonato del mundo, Moscú 1966 (19.ª partida)",
  "resultado": "1-0",
  "apertura": "Defensa Francesa",
  "resumen": "Petrosian propone cambiar las damas, y Spassky lo aprovecha: sin damas, empieza una presión lenta y constante sobre los peones negros del centro. Cada cambio de piezas deja a las negras un poco más pasivas, hasta que la defensa no alcanza.",
  "ideas": [
   "Un cambio de piezas mal elegido puede dejar las piezas propias pasivas para el resto de la partida.",
   "Un peón fijo en el centro es un blanco que no se puede mover.",
   "En el final, la presión sostenida pesa más que un golpe."
  ],
  "lecciones": [
   "Antes de proponer un cambio de damas, imagina qué piezas quedan y cuáles serán pasivas.",
   "Cuando ataques un peón fijo, suma atacantes uno por uno, sin apuro."
  ],
  "jugadas": [
   "e4",
   "e6",
   "d4",
   "d5",
   "Nc3",
   "Nf6",
   "e5",
   "Nfd7",
   "Nf3",
   "c5",
   "dxc5",
   "Nc6",
   "Bf4",
   "Bxc5",
   "Bd3",
   "f6",
   "exf6",
   "Nxf6",
   "O-O",
   "O-O",
   "Ne5",
   "Bd7",
   "Nxc6",
   "Bxc6",
   "Qe2",
   "Qe7",
   "Rae1",
   "Rae8",
   "Bg3",
   "a6",
   "a3",
   "Qf7",
   "b4",
   "Bd4",
   "Be5",
   "Bxe5",
   "Qxe5",
   "Nd7",
   "Qg3",
   "e5",
   "f3",
   "Qf4",
   "Qxf4",
   "Rxf4",
   "Rf2",
   "g6",
   "Rd2",
   "Nb6",
   "Rde2",
   "Nd7",
   "Nd1",
   "b5",
   "c3",
   "Rf7",
   "Bc2",
   "Kg7",
   "Bb3",
   "h5",
   "Ne3",
   "Nb6",
   "Nc2",
   "Nd7",
   "Re3",
   "h4",
   "h3",
   "Rf6",
   "Nd4",
   "Bb7",
   "a4",
   "Rd8",
   "Ne2",
   "bxa4",
   "Bxa4",
   "Nb6",
   "Bb3",
   "e4",
   "Nd4",
   "Kh6",
   "Rd1",
   "Rc8",
   "fxe4",
   "dxe4",
   "Ne6",
   "Nc4",
   "Bxc4",
   "Rxc4",
   "Nc5",
   "Rf7",
   "Ra1",
   "Kg5",
   "Ra5",
   "Kf4",
   "Kf2",
   "Bd5",
   "Nb3",
   "Ke5+",
   "Ke2",
   "Rc6",
   "Nd2",
   "Ke6",
   "Nxe4",
   "Bc4+",
   "Kd2",
   "Rd7+",
   "Kc2",
   "Kf7",
   "Re5",
   "Kg7",
   "Nd2",
   "Bb5",
   "Nf3",
   "Ba4+",
   "Kb2",
   "Rd1",
   "R5e4",
   "Rf1",
   "Re1",
   "Rxe1",
   "Rxe1",
   "Rf6",
   "Re4",
   "g5",
   "Nxg5",
   "Rf2+",
   "Ka3",
   "Bc6",
   "Rxh4",
   "Bxg2",
   "Ne4",
   "Re2",
   "Nc5",
   "Bf1",
   "Rf4",
   "Re1",
   "h4",
   "Be2",
   "Re4"
  ],
  "comentarios": {
   "99": "Un atacante más contra e4."
  },
  "claves": [
   {
    "ply": 85,
    "fen": "2r5/1b6/p3Nrpk/8/1Pn1p2p/1BP1R2P/6P1/3R2K1 w - - 2 43",
    "juegan": "w",
    "jugada": "43.Axc4",
    "pregunta": "¿Con qué pieza capturan las blancas en c4?",
    "explicacion": "43.Axc4 se lleva el caballo de c4 con el alfil. Stockfish 16 a profundidad 16: Axc4 es la mejor (+0,6) y la segunda queda 1,8 peor."
   },
   {
    "ply": 99,
    "fen": "8/5r2/p1r3p1/R2bk3/1P2p2p/1NP1R2P/4K1P1/8 w - - 12 50",
    "juegan": "w",
    "jugada": "50.Cd2",
    "pregunta": "¿Cómo se suma un atacante más contra el peón de e4?",
    "explicacion": "50.Cd2 lleva el caballo a atacar el peón de e4. Stockfish 16 a profundidad 16: Cd2 es la mejor (+1,0) y la segunda queda 0,8 peor."
   }
  ]
 },
 {
  "n": 9,
  "id": "gp-p9",
  "titulo": "Fischer – Portisch: de una ventaja ligera a una decisiva",
  "tema": "Ir sumando ventajas",
  "blancas": "Robert Fischer",
  "negras": "Lajos Portisch",
  "evento": "Estocolmo, 1962",
  "resultado": "1-0",
  "apertura": "Defensa Caro Kan",
  "resumen": "Fischer muestra aquí una de sus virtudes: tomar una ventaja ligera, convertirla en clara y después en decisiva, sin saltarse ningún paso. Los cambios llevan a un final de torres en el que el rey blanco es más activo, y desde ahí todo es técnica.",
  "ideas": [
   "Una ventaja ligera no se cobra de golpe: se convierte, paso a paso, en una ventaja mayor.",
   "En el final de torres, el rey activo vale casi un peón.",
   "La torre que ataca peones desde el costado obliga al rival a defenderse con todo."
  ],
  "lecciones": [
   "Después de una partida ganada, marca en qué jugadas tu ventaja creció: ¿qué hiciste en cada una?",
   "En tus finales de torres, ¿tu rey estuvo más activo que el del rival?"
  ],
  "jugadas": [
   "e4",
   "c6",
   "Nc3",
   "d5",
   "Nf3",
   "dxe4",
   "Nxe4",
   "Nd7",
   "Bc4",
   "Ngf6",
   "Neg5",
   "Nd5",
   "d4",
   "h6",
   "Ne4",
   "N7b6",
   "Bb3",
   "Bf5",
   "Ng3",
   "Bh7",
   "O-O",
   "e6",
   "Ne5",
   "Nd7",
   "c4",
   "N5f6",
   "Bf4",
   "Nxe5",
   "Bxe5",
   "Bd6",
   "Qe2",
   "O-O",
   "Rad1",
   "Qe7",
   "Bxd6",
   "Qxd6",
   "f4",
   "c5",
   "Qe5",
   "Qxe5",
   "dxe5",
   "Ne4",
   "Rd7",
   "Nxg3",
   "hxg3",
   "Be4",
   "Ba4",
   "Rad8",
   "Rfd1",
   "Rxd7",
   "Rxd7",
   "g5",
   "Bd1",
   "Bc6",
   "Rd6",
   "Rc8",
   "Kf2",
   "Kf8",
   "Bf3",
   "Bxf3",
   "gxf3",
   "gxf4",
   "gxf4",
   "Ke7",
   "f5",
   "exf5",
   "Rxh6",
   "Rd8",
   "Ke2",
   "Rg8",
   "Kf2",
   "Rd8",
   "Ke3",
   "Rd1",
   "b3",
   "Re1+",
   "Kf4",
   "Re2",
   "Kxf5",
   "Rxa2",
   "f4",
   "Re2",
   "Rh3",
   "Re1",
   "Rd3",
   "Rb1",
   "Re3",
   "Rb2",
   "e6",
   "a6",
   "exf7+",
   "Kxf7",
   "Ke5",
   "Rd2",
   "Rc3",
   "b6",
   "f5",
   "Rd1",
   "Rh3",
   "b5",
   "Rh7+",
   "Kg8",
   "Rb7",
   "bxc4",
   "bxc4",
   "Rd4",
   "Ke6",
   "Re4+",
   "Kd5",
   "Rf4",
   "Kxc5",
   "Rxf5+",
   "Kd6",
   "Rf6+",
   "Ke5",
   "Rf7",
   "Rb6",
   "Rc7",
   "Kd5",
   "Kf7",
   "Rxa6",
   "Ke7",
   "Re6+",
   "Kd8",
   "Rd6+",
   "Ke7",
   "c5",
   "Rc8",
   "c6",
   "Rc7",
   "Rh6",
   "Kd8",
   "Rh8+",
   "Ke7",
   "Ra8"
  ],
  "comentarios": {
   "77": "El rey blanco entra en acción."
  },
  "claves": [
   {
    "ply": 15,
    "fen": "r1bqkb1r/pp1nppp1/2p4p/3n2N1/2BP4/5N2/PPP2PPP/R1BQK2R w KQkq - 0 8",
    "juegan": "w",
    "jugada": "8.Ce4",
    "pregunta": "El caballo de g5 está atacado. ¿Adónde va?",
    "explicacion": "8.Ce4 pone el caballo en el centro, desde donde controla d6 y f6. Stockfish 16 a profundidad 16: Ce4 es la mejor (+0,6) y la segunda queda 0,5 peor."
   },
   {
    "ply": 77,
    "fen": "8/pp2kp2/7R/2p1Pp2/2P5/1P2KP2/P7/4r3 w - - 1 39",
    "juegan": "w",
    "jugada": "39.Rf4",
    "pregunta": "Final de torres. ¿Qué hace el rey blanco?",
    "explicacion": "39.Rf4 lanza el rey sobre el peón de f5, que ninguna pieza negra defiende. Stockfish 16 a profundidad 16: Rf4 es la mejor (+1,5) y la segunda queda 1,7 peor."
   },
   {
    "ply": 103,
    "fen": "6k1/7R/p7/1pp1KP2/2P5/1P6/8/3r4 w - - 2 52",
    "juegan": "w",
    "jugada": "52.Tb7",
    "pregunta": "¿Adónde apunta la torre blanca ahora?",
    "explicacion": "52.Tb7 pasa a atacar el peón de b5. Stockfish 16 a profundidad 16: Tb7 es la mejor (+1,8) y la segunda queda 0,8 peor."
   }
  ]
 },
 {
  "n": 10,
  "id": "gp-p10",
  "titulo": "Krámnik – Deep Fritz: técnica contra la máquina",
  "tema": "La técnica impecable",
  "blancas": "Vladímir Krámnik",
  "negras": "Deep Fritz",
  "evento": "Brains in Bahrain, Manama 2002",
  "resultado": "1-0",
  "apertura": "Gambito de dama rehusado",
  "resumen": "Krámnik juega contra uno de los programas más fuertes de su época como contra un ser humano: posiciones sencillas, pocas complicaciones y una ventaja pequeña que no se escapa. Le quita casillas a las piezas negras, ataca lo que no se puede defender bien y lleva la partida a un final donde su rey es más activo.",
  "ideas": [
   "Contra un rival que calcula muy bien, conviene que la posición no dependa del cálculo.",
   "Una jugada de peón que le quita casillas a las piezas rivales también es una ventaja.",
   "Atacar dos veces lo que está defendido dos veces mantiene al rival atado."
  ],
  "lecciones": [
   "Si tu rival es muy táctico, busca posiciones sencillas y sin golpes.",
   "Antes de atacar, mira qué casillas puedes quitarle al rival."
  ],
  "jugadas": [
   "d4",
   "d5",
   "c4",
   "dxc4",
   "Nf3",
   "Nf6",
   "e3",
   "e6",
   "Bxc4",
   "c5",
   "O-O",
   "a6",
   "dxc5",
   "Qxd1",
   "Rxd1",
   "Bxc5",
   "Kf1",
   "b5",
   "Be2",
   "Bb7",
   "Nbd2",
   "Nbd7",
   "Nb3",
   "Bf8",
   "a4",
   "b4",
   "Nfd2",
   "Bd5",
   "f3",
   "Bd6",
   "g3",
   "e5",
   "e4",
   "Be6",
   "Nc4",
   "Bc7",
   "Be3",
   "a5",
   "Nc5",
   "Nxc5",
   "Bxc5",
   "Nd7",
   "Nd6+",
   "Kf8",
   "Bf2",
   "Bxd6",
   "Rxd6",
   "Ke7",
   "Rad1",
   "Rhc8",
   "Bb5",
   "Nc5",
   "Bc6",
   "Bc4+",
   "Ke1",
   "Nd3+",
   "R1xd3",
   "Bxd3",
   "Bc5",
   "Bc4",
   "Rd4+",
   "Kf6",
   "Rxc4",
   "Rxc6",
   "Be7+",
   "Kxe7",
   "Rxc6",
   "Kd7",
   "Rc5",
   "f6",
   "Kd2",
   "Kd6",
   "Rd5+",
   "Kc6",
   "Kd3",
   "g6",
   "Kc4",
   "g5",
   "h3",
   "h6",
   "h4",
   "gxh4",
   "gxh4",
   "Ra7",
   "h5",
   "Ra8",
   "Rc5+",
   "Kb6",
   "Rb5+",
   "Kc6",
   "Rd5",
   "Kc7",
   "Kb5",
   "b3",
   "Rd3",
   "Ra7",
   "Rxb3",
   "Rb7+",
   "Kc4",
   "Ra7",
   "Rb5",
   "Ra8",
   "Kd5",
   "Ra6",
   "Rc5+",
   "Kd7",
   "b3",
   "Rd6+",
   "Kc4",
   "Rd4+",
   "Kc3",
   "Rd1",
   "Rd5+"
  ],
  "comentarios": {
   "93": "El rey blanco va por los peones."
  },
  "claves": [
   {
    "ply": 29,
    "fen": "r3kb1r/3n1ppp/p3pn2/3b4/Pp6/1N2P3/1P1NBPPP/R1BR1K2 w kq - 2 15",
    "juegan": "w",
    "jugada": "15.f3",
    "pregunta": "¿Qué casilla central les conviene quitar a las piezas negras?",
    "explicacion": "15.f3 le quita la casilla e4 al caballo de f6 y al alfil de d5. Stockfish 16 a profundidad 16: f3 es la mejor (+1,6) y la segunda queda 0,5 peor."
   },
   {
    "ply": 51,
    "fen": "r1r5/3nkppp/3Rb3/p3p3/Pp2P3/5PP1/1P2BB1P/3R1K2 w - - 3 26",
    "juegan": "w",
    "jugada": "26.Ab5",
    "pregunta": "¿Cómo se aumenta la presión sobre el caballo de d7?",
    "explicacion": "26.Ab5 ataca el caballo de d7 por segunda vez: las negras tienen que dedicar dos piezas a defenderlo. Stockfish 16 a profundidad 16: Ab5 es la mejor (+0,9) y la segunda queda 0,8 peor."
   },
   {
    "ply": 93,
    "fen": "r7/2k5/5p1p/p2Rp2P/PpK1P3/5P2/1P6/8 w - - 7 47",
    "juegan": "w",
    "jugada": "47.Rb5",
    "pregunta": "Final de torres. ¿Hacia dónde va el rey blanco?",
    "explicacion": "47.Rb5 lleva el rey junto a los peones negros de a5 y b4. Stockfish 16 a profundidad 16: Rb5 es la mejor (+3,2) y la segunda queda 1,4 peor."
   }
  ]
 },
 {
  "n": 11,
  "id": "gp-p11",
  "titulo": "Yusúpov – Rozentalis: el alfil y el rey activo",
  "tema": "Alfil contra caballo en el final",
  "blancas": "Artur Yusúpov",
  "negras": "Eduardas Rozentalis",
  "evento": "Alemania, 1995",
  "resultado": "1-0",
  "apertura": "Defensa Nimzoindia",
  "resumen": "En una Nimzoindia, la partida llega a un final de torre y alfil contra torre y caballo. Yusúpov tiene el rey más activo y un alfil que, con peones en los dos flancos, llega más rápido que el caballo. La ventaja crece de a poco hasta que los peones negros empiezan a caer.",
  "ideas": [
   "Con peones en los dos flancos, el alfil suele ser mejor que el caballo.",
   "Una pieza que tapa a otra más valiosa queda atada.",
   "El rey activo decide los finales de piezas."
  ],
  "lecciones": [
   "En tus finales de alfil contra caballo, mira si hay peones en los dos flancos.",
   "Busca piezas rivales que estén tapando a otras más valiosas: son un blanco."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "c4",
   "e6",
   "Nc3",
   "Bb4",
   "e3",
   "O-O",
   "Bd3",
   "c5",
   "Nf3",
   "d5",
   "O-O",
   "dxc4",
   "Bxc4",
   "b6",
   "a3",
   "cxd4",
   "axb4",
   "dxc3",
   "Qxd8",
   "Rxd8",
   "bxc3",
   "a5",
   "Bb2",
   "Bb7",
   "Be2",
   "Nbd7",
   "Rfd1",
   "Rdc8",
   "Kf1",
   "Bd5",
   "Nd2",
   "Ne5",
   "f3",
   "Ne8",
   "e4",
   "Bc4",
   "Nxc4",
   "Nxc4",
   "Bxc4",
   "Rxc4",
   "Rd7",
   "Rc7",
   "Rad1",
   "f6",
   "Rxc7",
   "Nxc7",
   "Rd6",
   "Rb8",
   "Ke2",
   "e5",
   "g3",
   "Kf8",
   "Rd7",
   "Ne6",
   "Ke3",
   "axb4",
   "cxb4",
   "Rc8",
   "Kd3",
   "Rc6",
   "h4",
   "h5",
   "Bc3",
   "Ke8",
   "Rb7",
   "Kd8",
   "Rb8+",
   "Ke7",
   "b5",
   "Rd6+",
   "Kc4",
   "Nc5",
   "Bb4",
   "Rd4+",
   "Kc3",
   "Rd3+",
   "Kc2",
   "Rd4",
   "Rb7+",
   "Ke8",
   "Bxc5",
   "bxc5",
   "Rxg7",
   "Rb4",
   "Rb7",
   "Kf8",
   "Kc3",
   "Kg8",
   "b6",
   "Kf8",
   "g4",
   "hxg4",
   "fxg4",
   "Kg8",
   "h5",
   "Kh8",
   "h6"
  ],
  "comentarios": {
   "75": "El alfil apunta al caballo y a la torre."
  },
  "claves": [
   {
    "ply": 75,
    "fen": "1R6/4k1p1/1p1r1p2/1Pn1p2p/2K1P2P/2B2PP1/8/8 w - - 3 38",
    "juegan": "w",
    "jugada": "38.Ab4",
    "pregunta": "¿Cómo molestan las blancas al caballo de c5?",
    "explicacion": "38.Ab4 ataca el caballo de c5, que tapa a la torre de d6. Stockfish 16 a profundidad 16: Ab4 es la mejor (+1,7) y la segunda queda 1,3 peor."
   }
  ]
 },
 {
  "n": 12,
  "id": "gp-p12",
  "titulo": "Kaspárov – X3D Fritz: espacio y una casilla débil",
  "tema": "Ganar espacio y crear una casilla débil",
  "blancas": "Garri Kaspárov",
  "negras": "X3D Fritz",
  "evento": "Match hombre contra máquina, 2003",
  "resultado": "1-0",
  "apertura": "Defensa Eslava",
  "resumen": "Kaspárov, conocido por su ajedrez de ataque, juega aquí una partida de pura estrategia. Cierra el centro temprano, gana espacio en el flanco de dama con sus peones y después entrega un peón para conseguir una casilla débil en el campo negro y debilitar el peón de c6. La máquina no encuentra nada que hacer y la ventaja crece sin un solo golpe táctico.",
  "ideas": [
   "El espacio ganado con peones encierra a las piezas rivales.",
   "A veces se entrega un peón para conseguir una casilla débil permanente.",
   "Contra un rival que calcula muy bien, conviene cerrar la posición."
  ],
  "lecciones": [
   "Si tienes más espacio en un flanco, no cambies piezas: deja que las del rival se estorben.",
   "Busca casillas en el campo rival que ningún peón pueda defender."
  ],
  "jugadas": [
   "Nf3",
   "Nf6",
   "c4",
   "e6",
   "Nc3",
   "d5",
   "d4",
   "c6",
   "e3",
   "a6",
   "c5",
   "Nbd7",
   "b4",
   "a5",
   "b5",
   "e5",
   "Qa4",
   "Qc7",
   "Ba3",
   "e4",
   "Nd2",
   "Be7",
   "b6",
   "Qd8",
   "h3",
   "O-O",
   "Nb3",
   "Bd6",
   "Rb1",
   "Be7",
   "Nxa5",
   "Nb8",
   "Bb4",
   "Qd7",
   "Rb2",
   "Qe6",
   "Qd1",
   "Nfd7",
   "a3",
   "Qh6",
   "Nb3",
   "Bh4",
   "Qd2",
   "Nf6",
   "Kd1",
   "Be6",
   "Kc1",
   "Rd8",
   "Rc2",
   "Nbd7",
   "Kb2",
   "Nf8",
   "a4",
   "Ng6",
   "a5",
   "Ne7",
   "a6",
   "bxa6",
   "Na5",
   "Rdb8",
   "g3",
   "Bg5",
   "Bg2",
   "Qg6",
   "Ka1",
   "Kh8",
   "Na2",
   "Bd7",
   "Bc3",
   "Ne8",
   "Nb4",
   "Kg8",
   "Rb1",
   "Bc8",
   "Ra2",
   "Bh6",
   "Bf1",
   "Qe6",
   "Qd1",
   "Nf6",
   "Qa4",
   "Bb7",
   "Nxb7",
   "Rxb7",
   "Nxa6",
   "Qd7",
   "Qc2",
   "Kh8",
   "Rb3"
  ],
  "comentarios": {
   "15": "Con 8.b5 las blancas siguen ganando espacio en el flanco de dama."
  },
  "claves": []
 },
 {
  "n": 13,
  "id": "gp-p13",
  "titulo": "Palavandishvili – Keres: las torres por la sexta fila",
  "tema": "Torres activas sin columnas abiertas",
  "blancas": "Palavandishvili",
  "negras": "Paul Keres",
  "evento": "Tiflis, 1946",
  "resultado": "0-1",
  "apertura": "Defensa Nimzoindia",
  "resumen": "En la posición no hay columnas abiertas, y las torres parecen no tener nada que hacer. Keres encuentra otra vía: lleva sus torres a la sexta fila y desde ahí pasan de un flanco al otro. Es una ventaja pequeña, pero dura: mientras las torres negras se mueven libres, las blancas tienen que defender.",
  "ideas": [
   "Sin columnas abiertas, una torre puede activarse por una fila.",
   "Cambiar el único alfil del rival puede dejar sus peones sin defensa.",
   "Una ventaja de actividad, si el rival no la iguala, crece sola."
  ],
  "lecciones": [
   "Cuando tus torres no tengan columnas, busca una fila libre.",
   "Antes de cambiar un alfil, mira qué peones quedan en su color."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "c4",
   "e6",
   "Nc3",
   "Bb4",
   "Qc2",
   "O-O",
   "e4",
   "d6",
   "Nf3",
   "e5",
   "d5",
   "a5",
   "h3",
   "Na6",
   "Be3",
   "Nh5",
   "g4",
   "Nf4",
   "a3",
   "Bc5",
   "Na4",
   "Qe7",
   "Nxc5",
   "Nxc5",
   "Bxc5",
   "dxc5",
   "Qc3",
   "Re8",
   "Ng1",
   "Ra6",
   "O-O-O",
   "a4",
   "Qe3",
   "Rb6",
   "Bd3",
   "Bd7",
   "Ne2",
   "Qd6",
   "Bc2",
   "Nxe2+",
   "Qxe2",
   "Qh6+",
   "Qd2",
   "Qxd2+",
   "Rxd2",
   "Rf6",
   "Bd1",
   "Ra8",
   "f3",
   "Raa6",
   "Kc2",
   "Rf4",
   "Be2",
   "h5",
   "Bd1",
   "Rh6",
   "g5",
   "Rg6",
   "h4",
   "f6",
   "Rg2",
   "f5",
   "Kd3",
   "Rb6",
   "Ke3",
   "fxe4",
   "fxe4",
   "Bg4",
   "Rd2",
   "Bxd1",
   "Rdxd1",
   "Rxb2",
   "Rd3",
   "Rbf2",
   "Rh3",
   "Rc2",
   "Rh1",
   "Rxc4",
   "d6",
   "cxd6"
  ],
  "comentarios": {
   "70": "Las negras buscan cambiar el alfil blanco."
  },
  "claves": [
   {
    "ply": 70,
    "fen": "6k1/1ppb2p1/1r6/2pPp1Pp/p1P1Pr1P/P3K3/1P4R1/3B3R b - - 0 35",
    "juegan": "b",
    "jugada": "35…Ag4",
    "pregunta": "¿Qué pieza blanca conviene cambiar?",
    "explicacion": "35…Ag4 ofrece el cambio del único alfil blanco, que es el que defiende las casillas claras. Stockfish 16 a profundidad 16: Ag4 es la mejor (-2,0) y la segunda queda 0,6 peor."
   }
  ]
 },
 {
  "n": 14,
  "id": "gp-p14",
  "titulo": "Rubinstein – Grünfeld: paciencia en el final",
  "tema": "El arte del final",
  "blancas": "Akiba Rubinstein",
  "negras": "Ernst Grünfeld",
  "evento": "Karlsbad, 1929",
  "resultado": "1-0",
  "apertura": "Defensa India de Dama",
  "resumen": "Rubinstein, uno de los mejores jugadores de finales de la historia, convierte una ventaja pequeña en un final de damas y alfiles de distinto color, y después en uno de alfiles con peones en los dos flancos. Cada fase se juega sin apuro: primero se fijan los peones del rival, después se activa el rey y al final se empuja el peón pasado.",
  "ideas": [
   "Con damas en el tablero, los alfiles de distinto color favorecen al que ataca.",
   "Un peón que fija a otro le quita casillas al rey y a las piezas rivales.",
   "En el final de alfiles, el que frena el peón pasado del rival y empuja el propio gana."
  ],
  "lecciones": [
   "Juega finales contra la computadora y anota en cuántas jugadas activaste tu rey.",
   "En tus finales de alfiles, mira de qué color son las casillas de los peones pasados."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "Nf3",
   "e6",
   "e3",
   "b6",
   "Nbd2",
   "Bb7",
   "Bd3",
   "c5",
   "O-O",
   "Be7",
   "e4",
   "cxd4",
   "Nxd4",
   "Nc6",
   "Nxc6",
   "dxc6",
   "Qe2",
   "Qc7",
   "f4",
   "Nd7",
   "c3",
   "e5",
   "Nc4",
   "Bf6",
   "f5",
   "Nc5",
   "Bc2",
   "Ba6",
   "Be3",
   "O-O",
   "Bxc5",
   "bxc5",
   "Bd3",
   "Bxc4",
   "Bxc4",
   "Rfd8",
   "Rad1",
   "Rxd1",
   "Rxd1",
   "Rd8",
   "Rxd8+",
   "Qxd8",
   "Kf1",
   "g6",
   "fxg6",
   "hxg6",
   "g3",
   "Kg7",
   "h4",
   "Qd7",
   "Kg2",
   "Qd6",
   "Bb3",
   "Qd7",
   "Qc4",
   "Qd2+",
   "Kf3",
   "Kh6",
   "Qxc5",
   "Qxb2",
   "Qe3+",
   "Kg7",
   "Qxa7",
   "Qxc3+",
   "Kg4",
   "Qd3",
   "Qxf7+",
   "Kh6",
   "Qc4",
   "Qd2",
   "Qf1",
   "Kg7",
   "Qd1",
   "Qg2",
   "Qf3",
   "Qd2",
   "Kh3",
   "Qd8",
   "Qc3",
   "Qd6",
   "g4",
   "Bd8",
   "g5",
   "Bb6",
   "Qf3",
   "Qf8",
   "Qxf8+",
   "Kxf8",
   "Kg4",
   "Be3",
   "Ba4",
   "c5",
   "Bb3",
   "Bd2",
   "Bc4",
   "Kg7",
   "a4",
   "Kf8",
   "Kf3",
   "Ke7",
   "Ke2",
   "Ba5",
   "Kd1",
   "Bb4",
   "Be2",
   "Kd6",
   "h5",
   "gxh5",
   "Bxh5",
   "Ke7",
   "Kc2",
   "c4",
   "Be2",
   "c3",
   "Kb3",
   "Kf7",
   "Bd3",
   "Ba5",
   "Kc4",
   "Kg6",
   "Kb5",
   "Bd8",
   "a5",
   "Bxg5",
   "a6",
   "Be3",
   "Kc6",
   "Kg5",
   "Kb7",
   "Kf4",
   "Bb1",
   "Bd4",
   "a7",
   "Bxa7",
   "Kxa7",
   "Ke3",
   "Kb6"
  ],
  "comentarios": {
   "85": "Los peones negros quedan fijos."
  },
  "claves": [
   {
    "ply": 85,
    "fen": "3b4/6k1/2pq2p1/4p3/4P1PP/1BQ4K/P7/8 w - - 1 43",
    "juegan": "w",
    "jugada": "43.g5",
    "pregunta": "¿Cómo aumentan las blancas su ventaja en el flanco de rey?",
    "explicacion": "43.g5 fija el peón de g6 y les quita las casillas f6 y h6 al rey y a la dama negros. Stockfish 16 a profundidad 16: g5 es la mejor (+2,5) y la segunda queda 1,0 peor."
   },
   {
    "ply": 119,
    "fen": "8/5k2/8/4p1P1/Pb2P3/1Kp5/4B3/8 w - - 2 60",
    "juegan": "w",
    "jugada": "60.Ad3",
    "pregunta": "Final de alfiles. ¿Cómo se frena el peón negro de c3?",
    "explicacion": "60.Ad3 vigila la casilla c2, por donde tiene que pasar el peón de c3, y defiende el peón de e4. Stockfish 16 a profundidad 16: Ad3 es la mejor (+1,3) y la segunda queda 0,7 peor."
   }
  ]
 },
 {
  "n": 15,
  "id": "gp-p15",
  "titulo": "Capablanca – Yates: los caballos de Capablanca",
  "tema": "Simplificar y tomar la iniciativa",
  "blancas": "José Raúl Capablanca",
  "negras": "Frederick Yates",
  "evento": "Nueva York, 1924",
  "resultado": "1-0",
  "apertura": "Defensa India del Rey",
  "resumen": "Capablanca hace lo que lo hizo famoso: simplifica la posición, toma la iniciativa y juega con una claridad que parece fácil. Sus caballos buscan los peones débiles del flanco de dama y, con cada cambio, la ventaja crece hasta ser decisiva.",
  "ideas": [
   "Simplificar no es ir a tablas: es quedarse con las piezas que trabajan.",
   "Dos caballos bien coordinados atacan muchas casillas a la vez.",
   "Un ataque doble con un caballo sale de tenerlo cerca de las piezas rivales."
  ],
  "lecciones": [
   "En tus partidas, antes de cada cambio, di qué pieza buena te queda después.",
   "Busca casillas desde las que un caballo ataque dos piezas a la vez."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "Nf3",
   "g6",
   "Nc3",
   "d5",
   "Bf4",
   "Bg7",
   "e3",
   "O-O",
   "h3",
   "c5",
   "dxc5",
   "Qa5",
   "Nd2",
   "Qxc5",
   "Nb3",
   "Qb6",
   "Be5",
   "e6",
   "Nb5",
   "Ne8",
   "Bxg7",
   "Nxg7",
   "h4",
   "a6",
   "Nc3",
   "Nc6",
   "Bd3",
   "f5",
   "Qd2",
   "Ne5",
   "Be2",
   "Nc4",
   "Bxc4",
   "dxc4",
   "Qd4",
   "Qc7",
   "Qc5",
   "Qxc5",
   "Nxc5",
   "b6",
   "N5a4",
   "Rb8",
   "O-O-O",
   "b5",
   "Nc5",
   "Rb6",
   "a4",
   "Nh5",
   "b3",
   "cxb3",
   "cxb3",
   "bxa4",
   "N3xa4",
   "Rc6",
   "Kb2",
   "Nf6",
   "Rd2",
   "a5",
   "Rhd1",
   "Nd5",
   "g3",
   "Rf7",
   "Nd3",
   "Rb7",
   "Ne5",
   "Rcc7",
   "Rd4",
   "Kg7",
   "e4",
   "fxe4",
   "Rxe4",
   "Rb5",
   "Rc4",
   "Rxc4",
   "Nxc4",
   "Bd7",
   "Nc3",
   "Rc5",
   "Ne4",
   "Rb5",
   "Ned6",
   "Rc5",
   "Nb7",
   "Rc7",
   "Nbxa5",
   "Bb5",
   "Nd6",
   "Bd7",
   "Nac4",
   "Ra7",
   "Ne4",
   "h6",
   "f4",
   "Be8",
   "Ne5",
   "Ra8",
   "Rc1",
   "Bf7",
   "Rc6",
   "Bg8",
   "Nc5",
   "Re8",
   "Ra6",
   "Re7",
   "Ka3",
   "Bf7",
   "b4",
   "Nc7",
   "Rc6",
   "Nb5+",
   "Kb2",
   "Nd4",
   "Ra6",
   "Be8",
   "g4",
   "Kf6",
   "Ne4+",
   "Kg7",
   "Nd6",
   "Bb5",
   "Ra5",
   "Bf1",
   "Ra8",
   "g5",
   "fxg5",
   "hxg5",
   "hxg5",
   "Bg2",
   "Re8",
   "Rc7",
   "Rd8",
   "Nc6",
   "Ne8+",
   "Kf8",
   "Nxc7+",
   "Nxd8",
   "Kc3",
   "Bb7",
   "Kd4",
   "Bc8",
   "g6",
   "Nb7",
   "Ne8",
   "Nd8",
   "b5",
   "Kg8",
   "g5",
   "Kf8",
   "g7+",
   "Kg8",
   "g6"
  ],
  "comentarios": {
   "79": "Un caballo ataca dos piezas."
  },
  "claves": [
   {
    "ply": 43,
    "fen": "r1b2rk1/6np/pp2p1p1/2N2p2/2p4P/2N1P3/PPP2PP1/R3K2R w KQ - 0 22",
    "juegan": "w",
    "jugada": "22.C5a4",
    "pregunta": "¿Adónde va el caballo de c5?",
    "explicacion": "22.C5a4 ataca el peón de b6. Stockfish 16 a profundidad 16: C5a4 es la mejor (+0,2) y la segunda queda 3,0 peor."
   },
   {
    "ply": 79,
    "fen": "8/3b2kp/4p1p1/pr1n4/N1N4P/1P4P1/1K3P2/3R4 w - - 1 40",
    "juegan": "w",
    "jugada": "40.Cc3",
    "pregunta": "¿Cómo atacan las blancas dos piezas a la vez?",
    "explicacion": "40.Cc3 ataca a la vez la torre de b5 y el caballo de d5. Stockfish 16 a profundidad 16: Cc3 es la mejor (+1,4) y la segunda queda 0,6 peor."
   },
   {
    "ply": 135,
    "fen": "3R4/2r3k1/2nNp3/4N1P1/1P4P1/8/1K4b1/8 w - - 5 68",
    "juegan": "w",
    "jugada": "68.Ce8+",
    "pregunta": "¿Cómo sigue el ataque blanco?",
    "explicacion": "68.Ce8+ da jaque y le deja libre la columna d a la torre. Stockfish 16 a profundidad 16: Ce8+ es la mejor (+4,0) y la segunda queda 1,8 peor."
   }
  ]
 },
 {
  "n": 16,
  "id": "gp-p16",
  "titulo": "Nóvikov – García: recoger la cuerda de a poco",
  "tema": "Mejorar poco a poco desde la defensa",
  "blancas": "Igor Nóvikov",
  "negras": "Guillermo García",
  "evento": "Camagüey, 1987",
  "resultado": "0-1",
  "apertura": "Defensa Bogoindia",
  "resumen": "Guillermo García, uno de los grandes talentos del ajedrez cubano, conduce las negras. Durante muchas jugadas defiende las amenazas del rival y, en cada pausa, mejora un poco su posición. La ventaja llega sola: un caballo metido en el campo blanco, el cambio de damas en el momento justo y un rey que avanza en el final.",
  "ideas": [
   "Defenderse bien también es acumular ventajas: cada ataque fallido le cuesta algo al atacante.",
   "Un caballo en el campo rival ata a las piezas que lo vigilan.",
   "El cambio de damas conviene al que tiene las piezas mejor puestas."
  ],
  "lecciones": [
   "Revisa una partida en la que defendiste mucho tiempo: ¿mejoraste tus piezas en las pausas?",
   "Cuando ofrezcas el cambio de damas, mira qué piezas quedan y quién las tiene mejor."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "c4",
   "e6",
   "Nf3",
   "Bb4+",
   "Nbd2",
   "O-O",
   "a3",
   "Bxd2+",
   "Qxd2",
   "Ne4",
   "Qc2",
   "f5",
   "e3",
   "b6",
   "Bd3",
   "Bb7",
   "O-O",
   "d6",
   "b4",
   "Nd7",
   "Bb2",
   "Ng5",
   "Nxg5",
   "Qxg5",
   "f4",
   "Qg6",
   "d5",
   "exd5",
   "cxd5",
   "Bxd5",
   "Bc4",
   "Bxc4",
   "Qxc4+",
   "Rf7",
   "Qxc7",
   "Qe6",
   "Qc3",
   "Nf6",
   "Qd4",
   "Re8",
   "Rfe1",
   "Qb3",
   "Rad1",
   "Ne4",
   "Rc1",
   "h6",
   "Red1",
   "Ree7",
   "Rd3",
   "Qa2",
   "Rc8+",
   "Kh7",
   "Rd1",
   "Nf6",
   "h3",
   "Rc7",
   "Rc1",
   "Rxc8",
   "Rxc8",
   "Qe6",
   "Rc6",
   "Nd5",
   "Kf2",
   "Re7",
   "Bc1",
   "Nf6",
   "Kg1",
   "Ne4",
   "Bb2",
   "Qb3",
   "Kh2",
   "h5",
   "Rc8",
   "h4",
   "Re8",
   "Qf7",
   "Rxe7",
   "Qxe7",
   "Bc3",
   "Ng3",
   "Bd2",
   "b5",
   "Qd3",
   "Qe4",
   "Qc3",
   "a6",
   "Bc1",
   "Qb1",
   "Qc6",
   "Qd3",
   "Bb2",
   "Qf1",
   "Qc1",
   "Kg6",
   "Qxf1",
   "Nxf1+",
   "Kg1",
   "Nxe3",
   "Bd4",
   "Nc4",
   "Kf2",
   "Nxa3",
   "Ke2",
   "Nc4",
   "Bf2",
   "Kh5",
   "Be1",
   "Nb6",
   "Kd3",
   "Nd5",
   "Bd2",
   "Kg6",
   "Kd4",
   "Nc7",
   "Be3",
   "Kf7",
   "Bf2",
   "Ke6",
   "Bxh4",
   "Nd5",
   "Be1",
   "Nxf4",
   "g4",
   "fxg4",
   "hxg4",
   "Ng6",
   "Bc3",
   "Ne5",
   "g5",
   "Nf3+"
  ],
  "comentarios": {
   "86": "La dama negra se centraliza."
  },
  "claves": [
   {
    "ply": 86,
    "fen": "8/p3q1pk/3p4/1p3p2/1P3P1p/P2QP1nP/3B2PK/8 b - - 1 43",
    "juegan": "b",
    "jugada": "43…De4",
    "pregunta": "¿Cómo aprovechan las negras que su caballo esté metido en el campo blanco?",
    "explicacion": "43…De4 centraliza la dama y ofrece el cambio: con menos piezas, el caballo de g3 pesa más. Stockfish 16 a profundidad 16: De4 es la mejor (-1,7) y la segunda queda 1,0 peor."
   },
   {
    "ply": 108,
    "fen": "8/6p1/p2p2k1/1p3p2/1Pn2P1p/7P/4KBP1/8 b - - 3 54",
    "juegan": "b",
    "jugada": "54…Rh5",
    "pregunta": "Final de caballo contra alfil. ¿Qué hace el rey negro?",
    "explicacion": "54…Rh5 lleva el rey hacia g4, junto a los peones blancos. Stockfish 16 a profundidad 16: Rh5 es la mejor (-2,2) y la segunda queda 1,1 peor."
   }
  ]
 },
 {
  "n": 17,
  "id": "gp-p17",
  "titulo": "Nikolić – Van der Wiel: el peón débil de f4",
  "tema": "Atacar una debilidad con el rey",
  "blancas": "Predrag Nikolić",
  "negras": "John van der Wiel",
  "evento": "Olimpiada de Novi Sad, 1990",
  "resultado": "1-0",
  "apertura": "Defensa India de Dama",
  "resumen": "Predrag Nikolić, conocido por su juego posicional, gana un peón en el medio juego y lleva la partida a un final de torres y alfiles. Ahí su rey se acerca a los peones negros, la torre se activa y el peón de f4 de las negras termina cayendo.",
  "ideas": [
   "El rey es la mejor pieza para atacar peones en el final.",
   "Con más actividad, un peón de ventaja crece hasta ser decisivo.",
   "Las torres activas obligan a las del rival a defender."
  ],
  "lecciones": [
   "En tus finales, marca qué peones rivales puede atacar tu rey.",
   "Antes de cambiar torres, mira cuál de las dos está más activa."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "c4",
   "e6",
   "Nf3",
   "b6",
   "g3",
   "Bb7",
   "Bg2",
   "Be7",
   "O-O",
   "O-O",
   "Bf4",
   "d6",
   "Nc3",
   "Ne4",
   "Rc1",
   "f5",
   "Nxe4",
   "Bxe4",
   "Ne1",
   "Bxg2",
   "Nxg2",
   "Nd7",
   "Qb3",
   "Rf7",
   "Rfd1",
   "Qe8",
   "c5",
   "bxc5",
   "Qxe6",
   "Bf6",
   "Qxe8+",
   "Rxe8",
   "dxc5",
   "Nxc5",
   "Rc2",
   "Ne6",
   "Kf1",
   "g5",
   "Bc1",
   "Be5",
   "Rc4",
   "f4",
   "gxf4",
   "Nxf4",
   "Nxf4",
   "gxf4",
   "Kg2",
   "Re6",
   "h4",
   "Rg6+",
   "Kf3",
   "h5",
   "b4",
   "Rg4",
   "Rh1",
   "Kh7",
   "b5",
   "Rg8",
   "Bd2",
   "Rb8",
   "Rhc1",
   "Rxb5",
   "Rxc7",
   "Kg6",
   "Rxf7",
   "Kxf7",
   "Rc7+",
   "Kf6",
   "Rxa7",
   "Rb2",
   "Be1",
   "Kf5",
   "Ra4",
   "Rb1",
   "Bd2",
   "Rh1",
   "Bxf4",
   "Rxh4",
   "e4+",
   "Ke6",
   "Be3",
   "Rg4",
   "Ra7",
   "Rg1",
   "Rh7",
   "Ra1",
   "Bg5",
   "d5",
   "Rh6+",
   "Kd7",
   "exd5",
   "Rxa2",
   "Ke4",
   "Bd6",
   "Rh7+",
   "Kc8",
   "Be3",
   "Ra4+",
   "Kf5",
   "h4",
   "Bg5",
   "Ra5",
   "Ke6",
   "Ra6",
   "Rh8+",
   "Kc7",
   "Bd8+",
   "Kb7",
   "Bxh4",
   "Bc7+",
   "Kf7",
   "Ra5",
   "Rh5",
   "Kc8",
   "Bg3",
   "Ra3",
   "Bxc7",
   "Kxc7",
   "Ke6"
  ],
  "comentarios": {
   "53": "El rey va por el peón de f4."
  },
  "claves": [
   {
    "ply": 31,
    "fen": "r3q1k1/p1pnbrpp/3pp3/2p2p2/3P1B2/1Q4P1/PP2PPNP/2RR2K1 w - - 0 16",
    "juegan": "w",
    "jugada": "16.Dxe6",
    "pregunta": "¿Cómo aprovechan las blancas la debilidad de e6?",
    "explicacion": "16.Dxe6 captura el peón de e6. Stockfish 16 a profundidad 16: Dxe6 es la mejor (+0,4) y la segunda queda 1,3 peor."
   },
   {
    "ply": 53,
    "fen": "6k1/p1p2r1p/3p2r1/4b3/2R2p1P/8/PP2PPK1/2BR4 w - - 1 27",
    "juegan": "w",
    "jugada": "27.Rf3",
    "pregunta": "Final de torres y alfiles. ¿Qué hace el rey blanco?",
    "explicacion": "27.Rf3 lleva el rey a atacar el peón de f4. Stockfish 16 a profundidad 16: Rf3 es la mejor (+0,7) y la segunda queda 1,2 peor."
   }
  ]
 },
 {
  "n": 18,
  "id": "gp-p18",
  "titulo": "Leyva – Pineda: el peón pasado de c",
  "tema": "Un peón pasado y el alfil",
  "blancas": "Héctor Leyva",
  "negras": "B. Pineda",
  "evento": "San Salvador, 2000",
  "resultado": "1-0",
  "apertura": "Defensa Eslava",
  "resumen": "La partida del propio Héctor Leyva, autor del libro de donde salen estas partidas. Las blancas tienen más espacio en el flanco de dama y un peón pasado en la columna c; su alfil acompaña el avance y la torre entra a la séptima. Cuando el peón llega, la ventaja es decisiva.",
  "ideas": [
   "Un peón pasado apoyado por una torre en la séptima fila es muy difícil de frenar.",
   "Un alfil que ataca a la pieza que frena el peón le abre el camino.",
   "En la técnica, cada jugada prepara la siguiente."
  ],
  "lecciones": [
   "Cuando tengas un peón pasado, mira qué pieza rival lo frena y cómo puedes atacarla.",
   "Pon tu torre detrás o al costado del peón pasado, no delante."
  ],
  "jugadas": [
   "d4",
   "Nf6",
   "Nf3",
   "d5",
   "c4",
   "c6",
   "Nc3",
   "g6",
   "e3",
   "Bg7",
   "Bd3",
   "O-O",
   "O-O",
   "Nbd7",
   "cxd5",
   "cxd5",
   "Qb3",
   "e6",
   "Bd2",
   "a6",
   "a4",
   "Rb8",
   "Rfc1",
   "Re8",
   "a5",
   "e5",
   "Bf1",
   "e4",
   "Ne1",
   "Nf8",
   "Na4",
   "h5",
   "Qb6",
   "N8h7",
   "Qxd8",
   "Rxd8",
   "Bb4",
   "Bf8",
   "Bxf8",
   "Nxf8",
   "Nc2",
   "Be6",
   "Nb4",
   "Rdc8",
   "Rxc8",
   "Rxc8",
   "Nc5",
   "Rc7",
   "Na2",
   "N8d7",
   "b4",
   "Nxc5",
   "bxc5",
   "Nd7",
   "Nb4",
   "Nb8",
   "Rb1",
   "Kg7",
   "Rb2",
   "g5",
   "Be2",
   "h4",
   "Bd1",
   "f5",
   "Bb3",
   "Rd7",
   "Kf1",
   "f4",
   "Ke2",
   "Kf6",
   "Kd2",
   "Kf5",
   "Ke2",
   "Rd8",
   "Rc2",
   "h3",
   "g3",
   "Kg4",
   "Rb2",
   "Rd7",
   "Bd1",
   "Kh5",
   "Ke1+",
   "Bg4",
   "Ba4",
   "Rd8",
   "Nxd5",
   "Rxd5",
   "Rxb7",
   "Rd8",
   "c6",
   "Rc8",
   "Rb6",
   "fxg3",
   "fxg3",
   "Rf8",
   "c7",
   "Nd7",
   "Rd6",
   "Nf6",
   "Rd8",
   "Rf7",
   "Bd7",
   "Bxd7",
   "Rxd7",
   "Rxd7",
   "c8=Q",
   "Kg6",
   "Qxa6",
   "Rc7",
   "Kd2"
  ],
  "comentarios": {
   "91": "El peón pasado avanza."
  },
  "claves": [
   {
    "ply": 85,
    "fen": "1n6/1p1r4/p7/P1Pp2pk/1N1Pppb1/4P1Pp/1R3P1P/3BK3 w - - 7 43",
    "juegan": "w",
    "jugada": "43.Aa4",
    "pregunta": "¿Cómo molestan las blancas a la torre de d7?",
    "explicacion": "43.Aa4 ataca la torre de d7. Stockfish 16 a profundidad 16: Aa4 es la mejor (+1,6) y la segunda queda 0,6 peor."
   },
   {
    "ply": 91,
    "fen": "1n1r4/1R6/p7/P1P3pk/B2Pppb1/4P1Pp/5P1P/4K3 w - - 1 46",
    "juegan": "w",
    "jugada": "46.c6",
    "pregunta": "¿Cuándo avanza el peón pasado de c5?",
    "explicacion": "46.c6 empuja el peón pasado, con la torre de b7 cuidando la casilla c7. Stockfish 16 a profundidad 16: c6 es la mejor (+2,2) y la segunda queda 1,2 peor."
   }
  ]
 }
];
